-- *****************************************************************************
-- Comment: EQM1001_R03 개정 이력 파라미터 등록
-- Create:  2026-10-06  한성수  REV 조회·저장 및 승인·반려 이관에 따른 R03 파라미터 추가
-- *****************************************************************************
-- 아래 백업은 R03 프로시저 교체 전에 실행합니다.
CREATE TABLE IF NOT EXISTS MES_SNS2.SYSTEM_PARAMETERS_BAK_EQM1001_R03_20261006 AS
SELECT * FROM MES_SNS2.SYSTEM_PARAMETERS
WHERE SPECIFIC_SCHEMA = 'MES_SNS2'
  AND SPECIFIC_NAME = 'EQM1001_R03';

-- R03 프로시저 교체 후 아래 삭제·재등록을 같은 트랜잭션으로 실행합니다.
START TRANSACTION;
DELETE FROM MES_SNS2.SYSTEM_PARAMETERS
WHERE SPECIFIC_SCHEMA = 'MES_SNS2'
  AND SPECIFIC_NAME = 'EQM1001_R03';

INSERT INTO MES_SNS2.SYSTEM_PARAMETERS
SELECT * FROM information_schema.PARAMETERS
WHERE SPECIFIC_SCHEMA = 'MES_SNS2'
  AND SPECIFIC_NAME = 'EQM1001_R03';
COMMIT;

-- 30건: 23~26번 PLANTP·PLANCD·REVNUM·REMARK, 27~28번 APRVSTT·REJREASON, 29~30번 CALLTYPE·KEYWORD
SELECT ORDINAL_POSITION, PARAMETER_NAME, DATA_TYPE
FROM MES_SNS2.SYSTEM_PARAMETERS
WHERE SPECIFIC_SCHEMA = 'MES_SNS2'
  AND SPECIFIC_NAME = 'EQM1001_R03'
ORDER BY ORDINAL_POSITION;
