-- *****************************************************************************
-- Comment: 설비점검계획 리비전 기존 계획 이관 (REV.0 제정)
-- Create:  2026-09-30  한성수  현재 승인 상태를 설비그룹·설비 REV.0으로 등록하고 승인본 스냅샷 생성
-- *****************************************************************************
-- MES_SNS2_EQM1001_PLAN_REV.sql 반영 후, 프로시저 반영 전에 실행합니다.
-- 이미 등록된 리비전은 건너뛰므로 다시 실행해도 중복 등록되지 않습니다.

-- 설비 REV.0 : 승인·반려는 현재 승인 상태를 옮기고, 승인 이력이 없으면 대기
INSERT INTO `MES_SNS2`.`MSTEQMREV_HEADER` (
  PLANTP, PLANCD, REVNUM, APRVSTT, REMARK,
  REQTIME, REQEMP, REQPRG,
  APRVTIME, APRVEMP, APRVPRG, REJREASON,
  RTIME, REMP, RPRG
)
SELECT
  'E', MSTEQM.FANO, 0,
  CASE WHEN EQM_APRV.APRVSTT IN ('A', 'R') THEN EQM_APRV.APRVSTT ELSE '' END,
  '제정',
  COALESCE(EQM_APRV.REQTIME, ''), COALESCE(EQM_APRV.REQEMP, ''), COALESCE(EQM_APRV.REQPRG, ''),
  COALESCE(EQM_APRV.APRVTIME, ''), COALESCE(EQM_APRV.APRVEMP, ''), COALESCE(EQM_APRV.APRVPRG, ''), COALESCE(EQM_APRV.REJREASON, ''),
  DATE_FORMAT(NOW(), '%Y-%m-%d %H:%i:%s'), 'SYSTEM', 'EQM1001_PLAN_REV_INIT'
FROM `MES_SNS2`.`MSTEQM`
INNER JOIN (
  SELECT CHKPLANEQM.EQMCD AS FANO
  FROM `MES_SNS2`.`CHKPLANEQM`
  WHERE CHKPLANEQM.CHKTP = '02'
  UNION
  SELECT CHKPLANEQM_APRV.PLANCD
  FROM `MES_SNS2`.`CHKPLANEQM_APRV`
  WHERE CHKPLANEQM_APRV.PLANTP = 'E'
) EQM_PLAN
  ON EQM_PLAN.FANO = MSTEQM.FANO
LEFT JOIN `MES_SNS2`.`CHKPLANEQM_APRV` EQM_APRV
  ON EQM_APRV.PLANTP = 'E'
 AND EQM_APRV.PLANCD = MSTEQM.FANO
LEFT JOIN `MES_SNS2`.`MSTEQMREV_HEADER` EXIST_REV
  ON EXIST_REV.PLANTP = 'E'
 AND EXIST_REV.PLANCD = MSTEQM.FANO
WHERE MSTEQM.USEYN = 'Y'
  AND EXIST_REV.PLANCD IS NULL;

-- 설비그룹 REV.0
INSERT INTO `MES_SNS2`.`MSTEQMREV_HEADER` (
  PLANTP, PLANCD, REVNUM, APRVSTT, REMARK,
  REQTIME, REQEMP, REQPRG,
  APRVTIME, APRVEMP, APRVPRG, REJREASON,
  RTIME, REMP, RPRG
)
SELECT
  'G', GRP_PLAN.EQMGUBUN, 0,
  CASE WHEN GRP_APRV.APRVSTT IN ('A', 'R') THEN GRP_APRV.APRVSTT ELSE '' END,
  '제정',
  COALESCE(GRP_APRV.REQTIME, ''), COALESCE(GRP_APRV.REQEMP, ''), COALESCE(GRP_APRV.REQPRG, ''),
  COALESCE(GRP_APRV.APRVTIME, ''), COALESCE(GRP_APRV.APRVEMP, ''), COALESCE(GRP_APRV.APRVPRG, ''), COALESCE(GRP_APRV.REJREASON, ''),
  DATE_FORMAT(NOW(), '%Y-%m-%d %H:%i:%s'), 'SYSTEM', 'EQM1001_PLAN_REV_INIT'
FROM (
  SELECT MSTEQM.EQMGUBUN
  FROM `MES_SNS2`.`MSTEQM`
  INNER JOIN `MES_SNS2`.`CHKPLANEQM`
    ON CHKPLANEQM.EQMCD = MSTEQM.FANO
   AND CHKPLANEQM.CHKTP = '02'
  WHERE MSTEQM.USEYN = 'Y'
    AND MSTEQM.EQMGUBUN <> ''
  UNION
  SELECT CHKPLANEQM_APRV.PLANCD
  FROM `MES_SNS2`.`CHKPLANEQM_APRV`
  WHERE CHKPLANEQM_APRV.PLANTP = 'G'
) GRP_PLAN
LEFT JOIN `MES_SNS2`.`CHKPLANEQM_APRV` GRP_APRV
  ON GRP_APRV.PLANTP = 'G'
 AND GRP_APRV.PLANCD = GRP_PLAN.EQMGUBUN
LEFT JOIN `MES_SNS2`.`MSTEQMREV_HEADER` EXIST_REV
  ON EXIST_REV.PLANTP = 'G'
 AND EXIST_REV.PLANCD = GRP_PLAN.EQMGUBUN
WHERE EXIST_REV.PLANCD IS NULL;

-- 설비 REV.0 승인본 (사용 중인 정기점검 항목)
INSERT INTO `MES_SNS2`.`MSTEQMREV_DETAIL` (
  PLANTP, PLANCD, REVNUM, EQMCD, CHKKNDCD,
  CHKCYCLE, SORTNO, CHKKNDNM, CHKLOC, CHKMTH, CHKVALTP, REMARK,
  RTIME, REMP, RPRG
)
SELECT
  'E', EQM_REV.PLANCD, 0, CHKPLANEQM.EQMCD, CHKPLANEQM.CHKKNDCD,
  CHKPLANEQM.CHKCYCLE, CHKPLANEQM.SORTNO, MSTCHKKND.CHKKNDNM, MSTCHKKND.CHKLOC, MSTCHKKND.CHKMTH, MSTCHKKND.CHKVALTP, CHKPLANEQM.REMARK,
  DATE_FORMAT(NOW(), '%Y-%m-%d %H:%i:%s'), 'SYSTEM', 'EQM1001_PLAN_REV_INIT'
FROM `MES_SNS2`.`MSTEQMREV_HEADER` EQM_REV
INNER JOIN `MES_SNS2`.`CHKPLANEQM`
  ON CHKPLANEQM.EQMCD = EQM_REV.PLANCD
 AND CHKPLANEQM.CHKTP = '02'
 AND CHKPLANEQM.USEYN = 'Y'
INNER JOIN `MES_SNS2`.`MSTCHKKND`
  ON MSTCHKKND.CHKKNDCD = CHKPLANEQM.CHKKNDCD
LEFT JOIN `MES_SNS2`.`MSTEQMREV_DETAIL` EXIST_ITEM
  ON EXIST_ITEM.PLANTP = 'E'
 AND EXIST_ITEM.PLANCD = EQM_REV.PLANCD
 AND EXIST_ITEM.REVNUM = 0
 AND EXIST_ITEM.EQMCD = CHKPLANEQM.EQMCD
 AND EXIST_ITEM.CHKKNDCD = CHKPLANEQM.CHKKNDCD
WHERE EQM_REV.PLANTP = 'E'
  AND EQM_REV.REVNUM = 0
  AND EQM_REV.APRVSTT = 'A'
  AND EXIST_ITEM.PLANCD IS NULL;

-- 설비그룹 REV.0 승인본 (승인된 소속 설비의 항목만)
INSERT INTO `MES_SNS2`.`MSTEQMREV_DETAIL` (
  PLANTP, PLANCD, REVNUM, EQMCD, CHKKNDCD,
  CHKCYCLE, SORTNO, CHKKNDNM, CHKLOC, CHKMTH, CHKVALTP, REMARK,
  RTIME, REMP, RPRG
)
SELECT
  'G', GRP_REV.PLANCD, 0, CHKPLANEQM.EQMCD, CHKPLANEQM.CHKKNDCD,
  CHKPLANEQM.CHKCYCLE, CHKPLANEQM.SORTNO, MSTCHKKND.CHKKNDNM, MSTCHKKND.CHKLOC, MSTCHKKND.CHKMTH, MSTCHKKND.CHKVALTP, CHKPLANEQM.REMARK,
  DATE_FORMAT(NOW(), '%Y-%m-%d %H:%i:%s'), 'SYSTEM', 'EQM1001_PLAN_REV_INIT'
FROM `MES_SNS2`.`MSTEQMREV_HEADER` GRP_REV
INNER JOIN `MES_SNS2`.`MSTEQM`
  ON MSTEQM.EQMGUBUN = GRP_REV.PLANCD
 AND MSTEQM.USEYN = 'Y'
INNER JOIN `MES_SNS2`.`MSTEQMREV_HEADER` EQM_REV
  ON EQM_REV.PLANTP = 'E'
 AND EQM_REV.PLANCD = MSTEQM.FANO
 AND EQM_REV.REVNUM = 0
 AND EQM_REV.APRVSTT = 'A'
INNER JOIN `MES_SNS2`.`CHKPLANEQM`
  ON CHKPLANEQM.EQMCD = MSTEQM.FANO
 AND CHKPLANEQM.CHKTP = '02'
 AND CHKPLANEQM.USEYN = 'Y'
INNER JOIN `MES_SNS2`.`MSTCHKKND`
  ON MSTCHKKND.CHKKNDCD = CHKPLANEQM.CHKKNDCD
LEFT JOIN `MES_SNS2`.`MSTEQMREV_DETAIL` EXIST_ITEM
  ON EXIST_ITEM.PLANTP = 'G'
 AND EXIST_ITEM.PLANCD = GRP_REV.PLANCD
 AND EXIST_ITEM.REVNUM = 0
 AND EXIST_ITEM.EQMCD = CHKPLANEQM.EQMCD
 AND EXIST_ITEM.CHKKNDCD = CHKPLANEQM.CHKKNDCD
WHERE GRP_REV.PLANTP = 'G'
  AND GRP_REV.REVNUM = 0
  AND GRP_REV.APRVSTT = 'A'
  AND EXIST_ITEM.PLANCD IS NULL;

-- 승인된 설비그룹에 미승인 설비가 있으면 REV.1 대기 등록 (미승인 설비까지 포함해 다시 승인받도록)
INSERT INTO `MES_SNS2`.`MSTEQMREV_HEADER` (
  PLANTP, PLANCD, REVNUM, APRVSTT, REMARK,
  RTIME, REMP, RPRG
)
SELECT
  'G', GRP_REV.PLANCD, 1, '', '',
  DATE_FORMAT(NOW(), '%Y-%m-%d %H:%i:%s'), 'SYSTEM', 'EQM1001_PLAN_REV_INIT'
FROM `MES_SNS2`.`MSTEQMREV_HEADER` GRP_REV
INNER JOIN (
  SELECT MSTEQM.EQMGUBUN
  FROM `MES_SNS2`.`MSTEQM`
  INNER JOIN `MES_SNS2`.`MSTEQMREV_HEADER` EQM_REV
    ON EQM_REV.PLANTP = 'E'
   AND EQM_REV.PLANCD = MSTEQM.FANO
   AND EQM_REV.REVNUM = 0
   AND EQM_REV.APRVSTT <> 'A'
  WHERE MSTEQM.USEYN = 'Y'
  GROUP BY MSTEQM.EQMGUBUN
) GRP_UNAPRV
  ON GRP_UNAPRV.EQMGUBUN = GRP_REV.PLANCD
LEFT JOIN `MES_SNS2`.`MSTEQMREV_HEADER` EXIST_REV
  ON EXIST_REV.PLANTP = 'G'
 AND EXIST_REV.PLANCD = GRP_REV.PLANCD
 AND EXIST_REV.REVNUM = 1
WHERE GRP_REV.PLANTP = 'G'
  AND GRP_REV.REVNUM = 0
  AND GRP_REV.APRVSTT = 'A'
  AND EXIST_REV.PLANCD IS NULL;

-- 위 설비그룹은 승인 상태도 대기로 맞춤 (설비 수정 시 소속 설비그룹도 대기가 되는 규칙과 동일)
DELETE CHKPLANEQM_APRV
FROM `MES_SNS2`.`CHKPLANEQM_APRV`
INNER JOIN `MES_SNS2`.`MSTEQMREV_HEADER` GRP_REV
  ON GRP_REV.PLANTP = 'G'
 AND GRP_REV.PLANCD = CHKPLANEQM_APRV.PLANCD
 AND GRP_REV.APRVSTT <> 'A'
WHERE CHKPLANEQM_APRV.PLANTP = 'G'
  AND CHKPLANEQM_APRV.APRVSTT = 'A';

-- 확인: 승인 상태인데 승인 리비전이 없는 대상 (0건이어야 함)
SELECT CHKPLANEQM_APRV.PLANTP, CHKPLANEQM_APRV.PLANCD
FROM `MES_SNS2`.`CHKPLANEQM_APRV`
LEFT JOIN `MES_SNS2`.`MSTEQMREV_HEADER` APRV_REV
  ON APRV_REV.PLANTP = CHKPLANEQM_APRV.PLANTP
 AND APRV_REV.PLANCD = CHKPLANEQM_APRV.PLANCD
 AND APRV_REV.APRVSTT = 'A'
WHERE CHKPLANEQM_APRV.APRVSTT = 'A'
  AND APRV_REV.PLANCD IS NULL;
