CREATE DEFINER=`root`@`%` PROCEDURE `MES_SNS2`.`EQM1001_R04`(
-- *****************************************************************************
-- Comment: 설비 정기점검 등록 
-- Create: 	2025-06-27  	생성 			이대규
-- Modify: 	2026-09-15 		마이그레이션	한성수
-- 			2026-09-16 					한성수	MSTEQM.FANO(설비코드) 컬럼 바인딩 변경
-- 			2026-09-22 					한성수	승인된 설비그룹·설비별 정기점검 계획만 실행
-- 			2026-09-30 					한성수	설비 승인 리비전(REV) 승인본 기준 점검 및 점검실적 적용 리비전 기록
-- 			2026-10-01 					한성수	리비전 키(REVCD) 기준 승인본 조회 및 점검실적 적용 리비전 기록 ($REVNUM → $REVCD)
-- 			2026-10-01 					한성수	설비그룹이 없는 설비도 설비 승인만으로 정기점검 조회·등록·수정·삭제 가능
-- 			2026-10-01 					한성수	정기점검 등록 팝업에 주기관리에서 지정한 해당 월 점검자 반환
-- 			2026-10-02 					한성수	정기점검 수정 조회 항목 결과에 실적의 적용 리비전(REVNM) 반환
-- 			2026-10-02 					한성수	조회 성능 개선 (월별 점검실적 확인을 연도별 1회 집계로 변경), 수정 조회 실적을 정기점검으로 한정
-- 			2026-10-02 					한성수	정기점검 등록 시 같은 달 중복 등록 및 주기관리 점검자가 없는 달 등록 불가
-- 			2026-10-02 					한성수	정기점검 등록·수정 시 점검 항목 유무와 점검값 필수 확인 (화면 확인을 프로시저로 이동)
-- *****************************************************************************
  IN $SYEAR           VARCHAR(50),
  IN $YYYYMM          VARCHAR(50),

  IN $EQMCD           VARCHAR(20),
  IN $CHKRSTKEY       VARCHAR(20),
  IN $CHKKNDCD_LIST   MEDIUMTEXT,
  IN $CHKKNDNM_LIST   MEDIUMTEXT,
  IN $CHKLOC_LIST     MEDIUMTEXT,
  IN $CHKMTH_LIST     MEDIUMTEXT,
  IN $CHKVALTP_LIST   MEDIUMTEXT,
  IN $CHKCYCLE_LIST   MEDIUMTEXT,
  IN $CHKVALUE_LIST   MEDIUMTEXT,
    
  IN $BASEDATE        VARCHAR(50),
  IN $EMPCD           VARCHAR(20),
  IN $PROBLEM         VARCHAR(1000),
  IN $SOLUTION        VARCHAR(1000),
  IN $REVCD           VARCHAR(20),

  
  IN $CHKRSTKEY_LIST  MEDIUMTEXT,
  IN $EMPCD_LIST      MEDIUMTEXT,
  IN $PROBLEM_LIST    MEDIUMTEXT,
  IN $SOLUTION_LIST   MEDIUMTEXT,


-- *****************************************************************************
IN  $CALLTYPE VARCHAR(50), IN $KEYWORD VARCHAR(1000))
PROC: BEGIN -- @CALLEMP, @CALLPRG, @CALLHOST, @CALLIP, @CALLMAC
-- SET @DEBUGLOGYN = 'Y'; 
-- *****************************************************************************
  DECLARE _$CHKKNDCD     VARCHAR(100);
  DECLARE _$CHKKNDNM     VARCHAR(100);
  DECLARE _$CHKLOC       VARCHAR(100);
  DECLARE _$CHKMTH       VARCHAR(100);
  DECLARE _$CHKVALTP     VARCHAR(100);
  DECLARE _$CHKCYCLE     VARCHAR(100);
  DECLARE _$CHKVALUE     VARCHAR(100);
  DECLARE _$CHKRSTKEY    VARCHAR(100);

  DECLARE _$EMPCD        VARCHAR(20);
  DECLARE _$PROBLEM      VARCHAR(1000);
  DECLARE _$SOLUTION     VARCHAR(1000);

  DECLARE _$SORTNO       DECIMAL(20, 8);
  DECLARE _$PLANAPRV_CNT INT DEFAULT 0;
  DECLARE _$REVNUM       INT;
  DECLARE _$PENDREVNUM   INT;
  DECLARE _$REVCD        VARCHAR(20);
  DECLARE _$PLANEMP      VARCHAR(100);
  DECLARE _$PLANEMPCD    VARCHAR(20);
  DECLARE _$PLANEMP_CNT  INT DEFAULT 0;
  DECLARE _$NAME_LIST    MEDIUMTEXT;
  DECLARE _$VALUE_LIST   MEDIUMTEXT;
  DECLARE _$ROWNO        INT DEFAULT 0;

CASE $CALLTYPE
-- ****************************************************************************
WHEN 'LIST_CYCLE_EQMCD' THEN  -- 정기점검 계획조회
  -- 주기관리 점검자가 지정된 월을 점검 계획 월로 판단하고, 그 달 정기점검 실적이 있으면 점검완료
  
  IF $SYEAR = '' THEN
    CALL COMERR('조회년도를 지정해주세요.');
    LEAVE PROC;
  END IF;  

  SELECT 
    MSTEQM.FANO,
    MSTEQM.FANO AS EQMCD,
    MSTEQM.EQMNM,
    $SYEAR AS YEAR,
    CASE WHEN CHKPLANEQM_YEARPLAN.MONTH_01 <> '' THEN IF(FIND_IN_SET('01', RST.RSTMM), '점검완료', '점검필요') ELSE '' END AS M01,
    CASE WHEN CHKPLANEQM_YEARPLAN.MONTH_02 <> '' THEN IF(FIND_IN_SET('02', RST.RSTMM), '점검완료', '점검필요') ELSE '' END AS M02,
    CASE WHEN CHKPLANEQM_YEARPLAN.MONTH_03 <> '' THEN IF(FIND_IN_SET('03', RST.RSTMM), '점검완료', '점검필요') ELSE '' END AS M03,
    CASE WHEN CHKPLANEQM_YEARPLAN.MONTH_04 <> '' THEN IF(FIND_IN_SET('04', RST.RSTMM), '점검완료', '점검필요') ELSE '' END AS M04,
    CASE WHEN CHKPLANEQM_YEARPLAN.MONTH_05 <> '' THEN IF(FIND_IN_SET('05', RST.RSTMM), '점검완료', '점검필요') ELSE '' END AS M05,
    CASE WHEN CHKPLANEQM_YEARPLAN.MONTH_06 <> '' THEN IF(FIND_IN_SET('06', RST.RSTMM), '점검완료', '점검필요') ELSE '' END AS M06,
    CASE WHEN CHKPLANEQM_YEARPLAN.MONTH_07 <> '' THEN IF(FIND_IN_SET('07', RST.RSTMM), '점검완료', '점검필요') ELSE '' END AS M07,
    CASE WHEN CHKPLANEQM_YEARPLAN.MONTH_08 <> '' THEN IF(FIND_IN_SET('08', RST.RSTMM), '점검완료', '점검필요') ELSE '' END AS M08,
    CASE WHEN CHKPLANEQM_YEARPLAN.MONTH_09 <> '' THEN IF(FIND_IN_SET('09', RST.RSTMM), '점검완료', '점검필요') ELSE '' END AS M09,
    CASE WHEN CHKPLANEQM_YEARPLAN.MONTH_10 <> '' THEN IF(FIND_IN_SET('10', RST.RSTMM), '점검완료', '점검필요') ELSE '' END AS M10,
    CASE WHEN CHKPLANEQM_YEARPLAN.MONTH_11 <> '' THEN IF(FIND_IN_SET('11', RST.RSTMM), '점검완료', '점검필요') ELSE '' END AS M11,
    CASE WHEN CHKPLANEQM_YEARPLAN.MONTH_12 <> '' THEN IF(FIND_IN_SET('12', RST.RSTMM), '점검완료', '점검필요') ELSE '' END AS M12
  FROM MSTEQM
  LEFT JOIN CHKPLANEQM_YEARPLAN 
         ON CHKPLANEQM_YEARPLAN.EQMCD = MSTEQM.FANO
        AND CHKPLANEQM_YEARPLAN.YEAR = $SYEAR
  -- 조회년도 정기점검 실적이 있는 월 (예: 01,03)
  LEFT JOIN (
    SELECT
      CHKRSTEQM.EQMCD,
      GROUP_CONCAT(DISTINCT SUBSTRING(CHKRSTEQM.BASEDATE, 6, 2)) AS RSTMM
    FROM CHKRSTEQM
    WHERE CHKRSTEQM.CHKTP = '02'
      AND CHKRSTEQM.BASEDATE LIKE CONCAT($SYEAR, '-%')
    GROUP BY CHKRSTEQM.EQMCD
  ) RST
    ON RST.EQMCD = MSTEQM.FANO
  -- 설비의 최신 승인 리비전에 정기점검 항목이 있고, 설비그룹이 있으면 설비그룹 승인 리비전도 있는 설비 (개정 중에도 직전 승인본으로 점검)
  LEFT JOIN (
    SELECT MSTEQMREV_HEADER.PLANCD
    FROM MSTEQMREV_HEADER
    WHERE MSTEQMREV_HEADER.PLANTP = 'G'
      AND MSTEQMREV_HEADER.APRVSTT = 'A'
    GROUP BY MSTEQMREV_HEADER.PLANCD
  ) GRP_REV
    ON GRP_REV.PLANCD = MSTEQM.EQMGUBUN
  INNER JOIN (
    SELECT EQM_LAST.PLANCD
    FROM (
      SELECT MSTEQMREV_HEADER.PLANCD,
             MAX(MSTEQMREV_HEADER.REVNUM) AS REVNUM
      FROM MSTEQMREV_HEADER
      WHERE MSTEQMREV_HEADER.PLANTP = 'E'
        AND MSTEQMREV_HEADER.APRVSTT = 'A'
      GROUP BY MSTEQMREV_HEADER.PLANCD
    ) EQM_LAST
    INNER JOIN MSTEQMREV_HEADER LAST_REV
      ON LAST_REV.PLANTP = 'E'
     AND LAST_REV.PLANCD = EQM_LAST.PLANCD
     AND LAST_REV.REVNUM = EQM_LAST.REVNUM
    INNER JOIN MSTEQMREV_DETAIL
      ON MSTEQMREV_DETAIL.REVCD = LAST_REV.REVCD
    GROUP BY EQM_LAST.PLANCD
  ) EQM_REV
    ON EQM_REV.PLANCD = MSTEQM.FANO
  WHERE MSTEQM.USEYN = 'Y'
    AND (IFNULL(MSTEQM.EQMGUBUN, '') = '' OR GRP_REV.PLANCD IS NOT NULL)
    AND (MSTEQM.FANO LIKE CONCAT('%', $EQMCD, '%') OR MSTEQM.EQMNM LIKE CONCAT('%', $EQMCD, '%'))
  GROUP BY MSTEQM.FANO
  ORDER BY MSTEQM.FANO;
-- *****************************************************************************
WHEN 'LIST_CHKPLANEQM_EQM02' THEN -- 정기점검계획 조회 (설비 승인 리비전 승인본)

  -- 적용 리비전: 설비의 승인된 최신 리비전 (설비그룹도 승인 리비전이 있어야 함)
  SELECT MAX(EQM_REV.REVNUM) INTO _$REVNUM
  FROM MSTEQM
  LEFT JOIN MSTEQMREV_HEADER GRP_REV
    ON GRP_REV.PLANTP = 'G'
   AND GRP_REV.PLANCD = MSTEQM.EQMGUBUN
   AND GRP_REV.APRVSTT = 'A'
  INNER JOIN MSTEQMREV_HEADER EQM_REV
    ON EQM_REV.PLANTP = 'E'
   AND EQM_REV.PLANCD = MSTEQM.FANO
   AND EQM_REV.APRVSTT = 'A'
  WHERE MSTEQM.FANO = $EQMCD
    AND MSTEQM.USEYN = 'Y'
    AND (IFNULL(MSTEQM.EQMGUBUN, '') = '' OR GRP_REV.PLANCD IS NOT NULL);

  IF _$REVNUM IS NULL THEN
    CALL COMERR('승인된 정기점검 계획만 처리할 수 있습니다.');
    LEAVE PROC;
  END IF;

  SELECT MSTEQMREV_HEADER.REVCD INTO _$REVCD
  FROM MSTEQMREV_HEADER
  WHERE MSTEQMREV_HEADER.PLANTP = 'E'
    AND MSTEQMREV_HEADER.PLANCD = $EQMCD
    AND MSTEQMREV_HEADER.REVNUM = _$REVNUM
  LIMIT 1;

  -- 진행 중(대기·반려)인 다음 리비전 안내용
  SET _$PENDREVNUM = (SELECT MSTEQMREV_HEADER.REVNUM
                      FROM MSTEQMREV_HEADER
                      WHERE MSTEQMREV_HEADER.PLANTP = 'E'
                        AND MSTEQMREV_HEADER.PLANCD = $EQMCD
                        AND MSTEQMREV_HEADER.APRVSTT <> 'A'
                      LIMIT 1);

  -- 주기관리에서 지정한 해당 월 점검자 (사원코드 우선, 예전 사원명 저장값은 사원 1명과 일치할 때만)
  SET _$PLANEMP = (SELECT ELT(CAST(RIGHT($YYYYMM, 2) AS UNSIGNED),
                              CHKPLANEQM_YEARPLAN.MONTH_01, CHKPLANEQM_YEARPLAN.MONTH_02, CHKPLANEQM_YEARPLAN.MONTH_03,
                              CHKPLANEQM_YEARPLAN.MONTH_04, CHKPLANEQM_YEARPLAN.MONTH_05, CHKPLANEQM_YEARPLAN.MONTH_06,
                              CHKPLANEQM_YEARPLAN.MONTH_07, CHKPLANEQM_YEARPLAN.MONTH_08, CHKPLANEQM_YEARPLAN.MONTH_09,
                              CHKPLANEQM_YEARPLAN.MONTH_10, CHKPLANEQM_YEARPLAN.MONTH_11, CHKPLANEQM_YEARPLAN.MONTH_12)
                   FROM CHKPLANEQM_YEARPLAN
                   WHERE CHKPLANEQM_YEARPLAN.EQMCD = $EQMCD
                     AND CHKPLANEQM_YEARPLAN.YEAR = LEFT($YYYYMM, 4)
                   ORDER BY (CHKPLANEQM_YEARPLAN.CHKTP = '02') DESC
                   LIMIT 1);
  SET _$PLANEMP = TRIM(COALESCE(_$PLANEMP, ''));

  IF _$PLANEMP <> '' THEN
    SET _$PLANEMPCD = (SELECT MSTEMP.EMPCD FROM MSTEMP WHERE MSTEMP.EMPCD = _$PLANEMP LIMIT 1);

    IF _$PLANEMPCD IS NULL THEN
      SELECT COUNT(*), MIN(MSTEMP.EMPCD)
        INTO _$PLANEMP_CNT, _$PLANEMPCD
      FROM MSTEMP
      WHERE MSTEMP.EMPNM = _$PLANEMP;

      IF _$PLANEMP_CNT <> 1 THEN
        SET _$PLANEMPCD = NULL;
      END IF;
    END IF;
  END IF;

  SELECT
    MSTEQMREV_DETAIL.EQMCD,
    MSTEQMREV_DETAIL.CHKKNDCD,
    MSTEQMREV_DETAIL.CHKKNDNM,
    MSTEQMREV_DETAIL.CHKLOC,
    MSTEQMREV_DETAIL.CHKMTH,
    MSTEQMREV_DETAIL.CHKVALTP,
    MSTEQMREV_DETAIL.CHKCYCLE,
    '' AS CHKVALUE,
    _$REVCD AS REVCD,
    _$REVNUM AS REVNUM,
    CONCAT('REV.', _$REVNUM) AS REVNM,
    COALESCE(CONCAT('REV.', _$PENDREVNUM), '') AS PENDREVNM,
    COALESCE(_$PLANEMPCD, '') AS PLANEMPCD,
    _$PLANEMP AS PLANEMPNM
  FROM MSTEQMREV_DETAIL
  WHERE MSTEQMREV_DETAIL.REVCD = _$REVCD
  ORDER BY MSTEQMREV_DETAIL.SORTNO
  ;    

-- ****************************************************************************
WHEN 'ADD_CHKRSTEQM' THEN -- 정기점검 등록 

  IF $EQMCD = '' THEN
    CALL COMERR('설비코드가 비어있습니다.');
    LEAVE PROC;
  END IF;
  
  IF $BASEDATE = '' THEN
    CALL COMERR('점검일자를 선택해주세요.');
    LEAVE PROC;
  END IF;

  IF LEFT($BASEDATE, 7) != $YYYYMM THEN
    CALL COMERR('점검일자의 년월이 계획년월과 다릅니다.');
    LEAVE PROC;
  END IF;

  IF $EMPCD = '' THEN
    CALL COMERR('점검자를 선택해주세요.');
    LEAVE PROC;
  END IF;

  -- 점검 항목이 없거나 점검값이 빈 항목이 있으면 등록·저장 불가
  IF COALESCE($CHKKNDCD_LIST, '') = '' THEN
    CALL COMERR('정기점검 항목이 없습니다. 정기점검 계획을 확인해주세요.');
    LEAVE PROC;
  END IF;

  SET _$NAME_LIST  = $CHKKNDNM_LIST;
  SET _$VALUE_LIST = $CHKVALUE_LIST;
  SET _$ROWNO      = 0;
  WHILE LENGTH(_$NAME_LIST) > 0 DO
    CALL COMSPLIT(_$NAME_LIST, _$CHKKNDNM);
    CALL COMSPLIT(_$VALUE_LIST, _$CHKVALUE);
    SET _$ROWNO = _$ROWNO + 1;

    IF TRIM(COALESCE(_$CHKVALUE, '')) = '' THEN
      CALL COMERR(CONCAT(_$ROWNO, '번째 항목(', COALESCE(_$CHKKNDNM, ''), ')의 점검값을 입력해주세요.'));
      LEAVE PROC;
    END IF;
  END WHILE;

  IF COALESCE($REVCD, '') = '' THEN
    CALL COMERR('적용 REV가 없습니다. 정기점검 등록 창을 다시 열어주세요.');
    LEAVE PROC;
  END IF;

  -- 팝업을 열 때 적용한 리비전이 그 설비의 승인 리비전인지 확인 (그 사이 새 리비전이 승인돼도 원래 리비전으로 기록)
  SELECT COUNT(*) INTO _$PLANAPRV_CNT
  FROM MSTEQM
  LEFT JOIN MSTEQMREV_HEADER GRP_REV
    ON GRP_REV.PLANTP = 'G'
   AND GRP_REV.PLANCD = MSTEQM.EQMGUBUN
   AND GRP_REV.APRVSTT = 'A'
  INNER JOIN MSTEQMREV_HEADER EQM_REV
    ON EQM_REV.PLANTP = 'E'
   AND EQM_REV.PLANCD = MSTEQM.FANO
   AND EQM_REV.REVCD = $REVCD
   AND EQM_REV.APRVSTT = 'A'
  WHERE MSTEQM.FANO = $EQMCD
    AND MSTEQM.USEYN = 'Y'
    AND (IFNULL(MSTEQM.EQMGUBUN, '') = '' OR GRP_REV.PLANCD IS NOT NULL);

  IF _$PLANAPRV_CNT = 0 THEN
    CALL COMERR('승인된 정기점검 계획만 처리할 수 있습니다.');
    LEAVE PROC;
  END IF;

  -- 주기관리에서 점검자가 지정된 달만 등록 (팝업을 연 뒤 계획이 빠진 경우 차단)
  SET _$PLANEMP = (SELECT ELT(CAST(RIGHT($YYYYMM, 2) AS UNSIGNED),
                              CHKPLANEQM_YEARPLAN.MONTH_01, CHKPLANEQM_YEARPLAN.MONTH_02, CHKPLANEQM_YEARPLAN.MONTH_03,
                              CHKPLANEQM_YEARPLAN.MONTH_04, CHKPLANEQM_YEARPLAN.MONTH_05, CHKPLANEQM_YEARPLAN.MONTH_06,
                              CHKPLANEQM_YEARPLAN.MONTH_07, CHKPLANEQM_YEARPLAN.MONTH_08, CHKPLANEQM_YEARPLAN.MONTH_09,
                              CHKPLANEQM_YEARPLAN.MONTH_10, CHKPLANEQM_YEARPLAN.MONTH_11, CHKPLANEQM_YEARPLAN.MONTH_12)
                   FROM CHKPLANEQM_YEARPLAN
                   WHERE CHKPLANEQM_YEARPLAN.EQMCD = $EQMCD
                     AND CHKPLANEQM_YEARPLAN.YEAR = LEFT($YYYYMM, 4)
                   ORDER BY (CHKPLANEQM_YEARPLAN.CHKTP = '02') DESC
                   LIMIT 1);

  IF COALESCE(_$PLANEMP, '') = '' THEN
    CALL COMERR('주기관리에서 점검자가 지정된 달만 정기점검을 등록할 수 있습니다. 화면을 다시 조회해주세요.');
    LEAVE PROC;
  END IF;

  -- 같은 달 정기점검 중복 등록 차단
  IF EXISTS (SELECT 1
             FROM CHKRSTEQM
             WHERE CHKRSTEQM.EQMCD = $EQMCD
               AND CHKRSTEQM.CHKTP = '02'
               AND LEFT(CHKRSTEQM.BASEDATE, 7) = $YYYYMM) THEN
    CALL COMERR('이미 등록된 정기점검이 있습니다. 화면을 다시 조회해주세요.');
    LEAVE PROC;
  END IF;

  SET _$CHKRSTKEY = GETKEY('CHKRSTKEY'); 


  INSERT INTO CHKRSTEQM (
    CHKRSTKEY, CHKTP, EQMCD, 
    EMPCD, BASEDATE, PROBLEM, 
    SOLUTION, REVCD, RTIME, REMP, RPRG
  ) 
  VALUES (
    _$CHKRSTKEY, '02', $EQMCD,
    $EMPCD, $BASEDATE, $PROBLEM,
    $SOLUTION, $REVCD, CALLTIME(), CALLEMP(), CALLPRG()
  ); 


  WHILE LENGTH($CHKKNDCD_LIST) > 0 DO  
    CALL COMSPLIT($CHKKNDCD_LIST, _$CHKKNDCD);
    CALL COMSPLIT($CHKKNDNM_LIST, _$CHKKNDNM);
    CALL COMSPLIT($CHKLOC_LIST, _$CHKLOC);
    CALL COMSPLIT($CHKMTH_LIST, _$CHKMTH);
    CALL COMSPLIT($CHKVALTP_LIST, _$CHKVALTP);
    CALL COMSPLIT($CHKCYCLE_LIST, _$CHKCYCLE);  
    CALL COMSPLIT($CHKVALUE_LIST, _$CHKVALUE);
   
    SET _$SORTNO = (SELECT SORTNO FROM MSTEQMREV_DETAIL WHERE REVCD = $REVCD AND CHKKNDCD = _$CHKKNDCD LIMIT 1); 
         
    INSERT INTO CHKRSTEQMKND (
    CHKRSTKEY, CHKKNDCD, CHKKNDNM, CHKLOC, 
    CHKMTH, CHKVALTP, CHKVALUE, SORTNO,
    RTIME, REMP, RPRG
    ) VALUES (
    _$CHKRSTKEY, _$CHKKNDCD, _$CHKKNDNM, _$CHKLOC,
    _$CHKMTH, _$CHKVALTP, _$CHKVALUE, _$SORTNO,
    CALLTIME(), CALLEMP(), CALLPRG())
    ;
  
  END WHILE;

-- *****************************************************************************
WHEN 'SEARCH_CHKRSTEQM' THEN  -- 해당월의 정기점검 조회

  IF $EQMCD = '' THEN
    CALL COMERR('설비코드가 비어있습니다.');
    LEAVE PROC;
  END IF;

  SELECT COUNT(*) INTO _$PLANAPRV_CNT
  FROM MSTEQM
  LEFT JOIN MSTEQMREV_HEADER GRP_REV
    ON GRP_REV.PLANTP = 'G'
   AND GRP_REV.PLANCD = MSTEQM.EQMGUBUN
   AND GRP_REV.APRVSTT = 'A'
  INNER JOIN MSTEQMREV_HEADER EQM_REV
    ON EQM_REV.PLANTP = 'E'
   AND EQM_REV.PLANCD = MSTEQM.FANO
   AND EQM_REV.APRVSTT = 'A'
  WHERE MSTEQM.FANO = $EQMCD
    AND MSTEQM.USEYN = 'Y'
    AND (IFNULL(MSTEQM.EQMGUBUN, '') = '' OR GRP_REV.PLANCD IS NOT NULL);

  IF _$PLANAPRV_CNT = 0 THEN
    CALL COMERR('승인된 정기점검 계획만 처리할 수 있습니다.');
    LEAVE PROC;
  END IF;
  SET _$CHKRSTKEY = IFNULL((SELECT CHKRSTKEY FROM CHKRSTEQM WHERE EQMCD = $EQMCD AND CHKTP = '02' AND LEFT(BASEDATE,7) = $YYYYMM ORDER BY BASEDATE, CHKRSTKEY LIMIT 1), '');


  SELECT 
    CHKRSTEQM.CHKRSTKEY,
    CHKRSTEQM.CHKTP,
    CHKRSTEQM.EQMCD,
    CHKRSTEQM.EMPCD,
    CHKRSTEQM.BASEDATE,
    LEFT(CHKRSTEQM.BASEDATE, 7) AS YYYYMM,
    CHKRSTEQM.PROBLEM,
    CHKRSTEQM.SOLUTION,
    CHKRSTEQM.RTIME,
    CHKRSTEQM.REVCD,
    RST_REV.REVNUM,
    COALESCE(CONCAT('REV.', RST_REV.REVNUM), '') AS REVNM
  FROM CHKRSTEQM  
  LEFT JOIN MSTEQMREV_HEADER RST_REV
    ON RST_REV.REVCD = CHKRSTEQM.REVCD
  WHERE CHKRSTEQM.CHKRSTKEY = _$CHKRSTKEY
  ;

  SELECT 
    CHKRSTEQMKND.CHKRSTKEY,
    CHKRSTEQMKND.CHKKNDCD,
    CHKRSTEQMKND.CHKKNDNM,
    CHKRSTEQMKND.CHKLOC,
    CHKRSTEQMKND.CHKMTH,
    CHKRSTEQMKND.CHKVALTP,
    CHKRSTEQMKND.CHKVALUE,
    COALESCE(CONCAT('REV.', RST_REV.REVNUM), '') AS REVNM
  FROM CHKRSTEQMKND
  INNER JOIN CHKRSTEQM
    ON CHKRSTEQM.CHKRSTKEY = CHKRSTEQMKND.CHKRSTKEY
  LEFT JOIN MSTEQMREV_HEADER RST_REV
    ON RST_REV.REVCD = CHKRSTEQM.REVCD
  WHERE CHKRSTEQMKND.CHKRSTKEY = _$CHKRSTKEY  
  ORDER BY CHKRSTEQMKND.SORTNO
  ;
-- ****************************************************************************
WHEN 'SAVE_CHKRSTEQM' THEN -- 정기점검 수정

  IF $CHKRSTKEY = '' THEN
    CALL COMERR('점검키가 없습니다.');
    LEAVE PROC;
  END IF;

  IF $BASEDATE = '' THEN
    CALL COMERR('점검일자를 선택해주세요.');
    LEAVE PROC;
  END IF;

  IF LEFT($BASEDATE, 7) != $YYYYMM THEN
    CALL COMERR('점검일자의 년월이 계획년월과 다릅니다.');
    LEAVE PROC;
  END IF;

  IF $EMPCD = '' THEN
    CALL COMERR('점검자를 선택해주세요.');
    LEAVE PROC;
  END IF;

  -- 점검 항목이 없거나 점검값이 빈 항목이 있으면 등록·저장 불가
  IF COALESCE($CHKKNDCD_LIST, '') = '' THEN
    CALL COMERR('정기점검 항목이 없습니다. 정기점검 계획을 확인해주세요.');
    LEAVE PROC;
  END IF;

  SET _$NAME_LIST  = $CHKKNDNM_LIST;
  SET _$VALUE_LIST = $CHKVALUE_LIST;
  SET _$ROWNO      = 0;
  WHILE LENGTH(_$NAME_LIST) > 0 DO
    CALL COMSPLIT(_$NAME_LIST, _$CHKKNDNM);
    CALL COMSPLIT(_$VALUE_LIST, _$CHKVALUE);
    SET _$ROWNO = _$ROWNO + 1;

    IF TRIM(COALESCE(_$CHKVALUE, '')) = '' THEN
      CALL COMERR(CONCAT(_$ROWNO, '번째 항목(', COALESCE(_$CHKKNDNM, ''), ')의 점검값을 입력해주세요.'));
      LEAVE PROC;
    END IF;
  END WHILE;

  SELECT COUNT(*) INTO _$PLANAPRV_CNT
  FROM CHKRSTEQM
  INNER JOIN MSTEQM
    ON MSTEQM.FANO = CHKRSTEQM.EQMCD
  LEFT JOIN MSTEQMREV_HEADER GRP_REV
    ON GRP_REV.PLANTP = 'G'
   AND GRP_REV.PLANCD = MSTEQM.EQMGUBUN
   AND GRP_REV.APRVSTT = 'A'
  INNER JOIN MSTEQMREV_HEADER EQM_REV
    ON EQM_REV.PLANTP = 'E'
   AND EQM_REV.PLANCD = MSTEQM.FANO
   AND EQM_REV.APRVSTT = 'A'
  WHERE CHKRSTEQM.CHKRSTKEY = $CHKRSTKEY
    AND MSTEQM.USEYN = 'Y'
    AND (IFNULL(MSTEQM.EQMGUBUN, '') = '' OR GRP_REV.PLANCD IS NOT NULL);

  IF _$PLANAPRV_CNT = 0 THEN
    CALL COMERR('승인된 정기점검 계획만 처리할 수 있습니다.');
    LEAVE PROC;
  END IF;
  UPDATE CHKRSTEQM 

  SET
    EMPCD = $EMPCD,
    BASEDATE = $BASEDATE,
    PROBLEM = $PROBLEM,
    SOLUTION = $SOLUTION,
    MTIME = CALLTIME(),
    MEMP = CALLEMP(),
    MPRG = CALLPRG()
  WHERE CHKRSTKEY = $CHKRSTKEY
  ;

  WHILE LENGTH($CHKKNDCD_LIST) > 0 DO
    CALL COMSPLIT($CHKKNDCD_LIST, _$CHKKNDCD);
    CALL COMSPLIT($CHKVALUE_LIST, _$CHKVALUE);

    UPDATE CHKRSTEQMKND 
    SET
      CHKVALUE = _$CHKVALUE,
      MTIME = CALLTIME(),
      MEMP = CALLEMP(),
      MPRG = CALLPRG()
    WHERE CHKRSTKEY = $CHKRSTKEY
      AND CHKKNDCD = _$CHKKNDCD
    ;
  END WHILE;
  
-- ****************************************************************************
WHEN 'DELETE_CHKRSTEQM' THEN -- 정기점검 삭제
  IF $CHKRSTKEY = '' THEN
    CALL COMERR('점검키가 없습니다.');
    LEAVE PROC;
  END IF;

  SELECT COUNT(*) INTO _$PLANAPRV_CNT
  FROM CHKRSTEQM
  INNER JOIN MSTEQM
    ON MSTEQM.FANO = CHKRSTEQM.EQMCD
  LEFT JOIN MSTEQMREV_HEADER GRP_REV
    ON GRP_REV.PLANTP = 'G'
   AND GRP_REV.PLANCD = MSTEQM.EQMGUBUN
   AND GRP_REV.APRVSTT = 'A'
  INNER JOIN MSTEQMREV_HEADER EQM_REV
    ON EQM_REV.PLANTP = 'E'
   AND EQM_REV.PLANCD = MSTEQM.FANO
   AND EQM_REV.APRVSTT = 'A'
  WHERE CHKRSTEQM.CHKRSTKEY = $CHKRSTKEY
    AND MSTEQM.USEYN = 'Y'
    AND (IFNULL(MSTEQM.EQMGUBUN, '') = '' OR GRP_REV.PLANCD IS NOT NULL);

  IF _$PLANAPRV_CNT = 0 THEN
    CALL COMERR('승인된 정기점검 계획만 처리할 수 있습니다.');
    LEAVE PROC;
  END IF;
  DELETE FROM CHKRSTEQMKND WHERE CHKRSTKEY = $CHKRSTKEY;    

  DELETE FROM CHKRSTEQM WHERE CHKRSTKEY = $CHKRSTKEY; 

-- ****************************************************************************
END CASE; END