-- *****************************************************************************
-- Comment: 리비전 DETAIL의 HEADER 중복 컬럼 제거
-- Create:  2026-10-06  한성수  REVCD 연결 유지 및 PLANTP·PLANCD·REVNUM·EQMCD 제거
-- *****************************************************************************
-- 기존 DB: 이 파일 → PLAN_APRV_HISTORY → 최신 R03·R04 프로시저 반영
-- 신규 DB: 최신 PLAN_REV로 테이블 생성 후 PLAN_APRV_HISTORY 실행
DELIMITER $$
BEGIN NOT ATOMIC
  IF EXISTS (SELECT 1 FROM MES_SNS2.MSTEQMREV_DETAIL
             LEFT JOIN MES_SNS2.MSTEQMREV_HEADER
               ON MSTEQMREV_HEADER.REVCD = MSTEQMREV_DETAIL.REVCD
             WHERE MSTEQMREV_HEADER.REVCD IS NULL LIMIT 1) THEN
    SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'HEADER가 없는 DETAIL이 있습니다. REVCD 연결을 먼저 확인해주세요.';
  END IF;

  ALTER TABLE MES_SNS2.MSTEQMREV_DETAIL
    DROP COLUMN IF EXISTS PLANTP,
    DROP COLUMN IF EXISTS PLANCD,
    DROP COLUMN IF EXISTS REVNUM,
    DROP COLUMN IF EXISTS EQMCD;
END $$
DELIMITER ;

-- DETAIL의 PK는 REVCD·CHKKNDCD 유지
SELECT COLUMN_NAME, COLUMN_TYPE, COLUMN_KEY
FROM information_schema.COLUMNS
WHERE TABLE_SCHEMA = 'MES_SNS2' AND TABLE_NAME = 'MSTEQMREV_DETAIL'
ORDER BY ORDINAL_POSITION;
