CREATE DEFINER = 'root'@'%'
PROCEDURE MES_SNS2.MST1003_R04(
-- *****************************************************************************
-- Comment: 품목마스터관리
-- Create: 2024-02-22 13:50: 김영철
-- Modify: 
-- *****************************************************************************
  IN $COMPANYCD VARCHAR(100),
  IN $FACTORYCD VARCHAR(100),
  IN $ITEMID VARCHAR(100),
  IN $ITEMCG VARCHAR(100),
  IN $CALLTYPE VARCHAR(100),
  IN $ENDYN VARCHAR(1), 
  IN $KEYWORD VARCHAR(1000)
  )
PROC: BEGIN -- @CALLEMP, @CALLPRG, @CALLHOST, @CALLIP, @CALLMAC
-- SET @DEBUGLOGYN = 'Y';
-- *****************************************************************************
  CASE $CALLTYPE
-- ****************************************************************************
  WHEN 'SEL_ITEM' THEN
   IF $COMPANYCD = '' THEN 
      CALL COMERR('법인을 선택하십시오.');
      LEAVE PROC;
   END IF; 

   IF $ITEMCG = '' THEN 
      CALL COMERR('품목분류을 선택하십시오.');
      LEAVE PROC;
   END IF; 
  
    SELECT
      CAST(MSTITEM.ITEMID AS CHAR) AS ITEMID, 
      MSTITEM.ITEMCD, MSTITEM.COMPANYCD, MSTITEM.MODELCD, 
      MSTITEM.COLORCD, MSTITEM.MYCD, MSTITEM.ITEMNM, MSTITEM.ITEMBNM, 
      MSTITEM.MAINPARTID, MSTITEM.MAINITEMID, MSTITEM.TRANGOODSID, 
      MSTITEM.PAIRID, MSTITEM.PAIRCD, MSTITEM.ITEMSPEC, MSTITEM.ITEMUNIT, 
      MSTITEM.ITEMSRC, MSTITEM.ITEMCG, MSTITEM.ITEM_LVL1, MSTITEM.ITEM_LVL2, 
      MSTITEM.ITEM_LVL3, MSTITEM.ITEM_LVL4, MSTITEM.VALID_FROM_DT, MSTITEM.VALID_TO_DT, 
      MSTITEM.ENDYN, MSTITEM.ENDUSEID, MSTITEM.ENDREASON, MSTITEM.INSPEC, 
      MSTITEM.PRDPLANGROUP, MSTITEM.ITEMOLDCD, MSTITEM.BARCD, 
      MSTITEM.GRADE, MSTITEM.CBITEMNO, MSTITEM.CBYN, MSTITEM.ITEM_LVL5, 
      MSTITEM.PARTNO, MSTITEM.INITCD, MSTITEM.IOYN, MSTITEM.SEPAYN, 
      MSTITEM.NAT_CD, MSTITEM.HS_CD, MSTITEM.REV, MSTITEM.EONO, 
      MSTITEM.SECT_NO, MSTITEM.EODT, MSTITEM.EOSIZE, MSTITEM.EOQTY, 
      MSTITEM.ITWEIGHT, MSTITEM.ITMAT, MSTITEM.ITLENGTH, MSTITEM.SIZE_UNIT, 
      MSTITEM.DUKE, MSTITEM.POK, MSTITEM.SPEC2, MSTITEM.ST, 
      MSTITEM.CT, MSTITEM.TRANDAY, MSTITEM.SPEC1, MSTITEM.SPEC3, 
      MSTITEM.SPEC4, MSTITEM.SPEC5, MSTITEM.SPEC6, MSTITEM.SPEC7, 
      MSTITEM.SPEC8, MSTITEM.SPEC9, MSTITEM.SPEC10, MSTITEM.SPEC11, 
      MSTITEM.SPEC12, MSTITEM.SPEC13, MSTITEM.SPEC14, MSTITEM.SPEC15, 
      MSTITEM.SPEC16, MSTITEM.SPEC17, MSTITEM.SPEC18, MSTITEM.SPEC19,
      MSTITEM.SPEC20, MSTITEM.EXPDAY, MSTITEM.BOXQTY, MSTITEM.LINK_ID, 
      MSTITEM.WONGA_ID, MSTITEM.PRODUCT_DT, MSTITEM.PACK_QTY, MSTITEM.PACK_LAY, 
      MSTITEM.DEPT_CD, MSTITEM.DEV_RID, MSTITEM.REMARK, MSTITEM.REMP, 
      MSTITEM.RTIME, MSTITEM.MEMP, MSTITEM.MTIME
    FROM MSTITEM
    WHERE MSTITEM.COMPANYCD = $COMPANYCD
      AND MSTITEM.ITEMCG = $ITEMCG
      AND MSTITEM.ENDYN = $ENDYN
      AND (   MSTITEM.ITEMID LIKE CONCAT('%', $ITEMID, '%')
           OR MSTITEM.ITEMCD LIKE CONCAT('%', $ITEMID, '%')
          )
    ORDER BY MSTITEM.COMPANYCD, MSTITEM.ITEMCD
    ;

-- ****************************************************************************
  END CASE;
END