-- *****************************************************************************
-- Comment: EQM1001_R05 COMCALLC 파라미터 메타데이터
-- Create:  2026-09-22  한성수  설비점검계획 승인관리 프로시저 파라미터 등록
-- *****************************************************************************
INSERT INTO SYSTEM_PARAMETERS (
  SPECIFIC_CATALOG,
  SPECIFIC_SCHEMA,
  SPECIFIC_NAME,
  ORDINAL_POSITION,
  PARAMETER_MODE,
  PARAMETER_NAME,
  DATA_TYPE,
  CHARACTER_MAXIMUM_LENGTH,
  CHARACTER_OCTET_LENGTH,
  NUMERIC_PRECISION,
  NUMERIC_SCALE,
  DATETIME_PRECISION,
  CHARACTER_SET_NAME,
  COLLATION_NAME,
  DTD_IDENTIFIER,
  ROUTINE_TYPE
)
SELECT
  SPECIFIC_CATALOG,
  SPECIFIC_SCHEMA,
  SPECIFIC_NAME,
  ORDINAL_POSITION,
  PARAMETER_MODE,
  PARAMETER_NAME,
  DATA_TYPE,
  CHARACTER_MAXIMUM_LENGTH,
  CHARACTER_OCTET_LENGTH,
  NUMERIC_PRECISION,
  NUMERIC_SCALE,
  DATETIME_PRECISION,
  CHARACTER_SET_NAME,
  COLLATION_NAME,
  DTD_IDENTIFIER,
  ROUTINE_TYPE
FROM information_schema.PARAMETERS
WHERE SPECIFIC_SCHEMA = 'MES_SNS2'
  AND SPECIFIC_NAME = 'EQM1001_R05'
ON DUPLICATE KEY UPDATE
  PARAMETER_MODE = VALUES(PARAMETER_MODE),
  PARAMETER_NAME = VALUES(PARAMETER_NAME),
  DATA_TYPE = VALUES(DATA_TYPE),
  CHARACTER_MAXIMUM_LENGTH = VALUES(CHARACTER_MAXIMUM_LENGTH),
  CHARACTER_OCTET_LENGTH = VALUES(CHARACTER_OCTET_LENGTH),
  NUMERIC_PRECISION = VALUES(NUMERIC_PRECISION),
  NUMERIC_SCALE = VALUES(NUMERIC_SCALE),
  DATETIME_PRECISION = VALUES(DATETIME_PRECISION),
  CHARACTER_SET_NAME = VALUES(CHARACTER_SET_NAME),
  COLLATION_NAME = VALUES(COLLATION_NAME),
  DTD_IDENTIFIER = VALUES(DTD_IDENTIFIER),
  ROUTINE_TYPE = VALUES(ROUTINE_TYPE);
