CREATE DEFINER=`root`@`%` PROCEDURE `MES_SNS2`.`EQM1001_R03`(
-- *****************************************************************************
-- Comment: 설비점검계획 
-- Create: 	2025-06-27  	생성 			이대규
-- Modify: 	2026-09-15 		마이그레이션	한성수
-- 			2026-09-16 					한성수	MSTEQM.FANO(설비코드) 컬럼 바인딩 변경
-- 			2026-09-21 					한성수	설비별 그룹 조회, 필터 기능 추가 및 CRUD 기능 추가
-- 			2026-09-21 					한성수	설비그룹 정기점검 조회·CRUD 불필요 조인 및 IFNULL 조건 단순화
-- 			2026-09-22 					한성수	설비그룹 재조회 선택 키를 EQMGUBUN 기준으로 정리
-- 			2026-09-23 					한성수	정기점검 주기관리 설비등급 조회 추가
-- 			2026-09-29 					한성수	설비그룹 점검계획 조회를 설비그룹코드 단위로 변경 및 그룹 승인상태·반려사유 표시
-- 			2026-09-29 					한성수	설비그룹 점검계획 조회 사용 설비그룹(COMTYPE.USEYN = 'Y')만 조회 및 그룹 단위 사전집계 튜닝
-- 			2026-09-30 					한성수	설비그룹·설비 현재 승인 리비전(REV) 조회 추가, 주기관리 승인 확인을 승인 리비전 기준으로 변경 및 승인 테이블 이름 변경
-- 			2026-09-30 					한성수	정기점검 항목·주기관리 조회에 점검항목·점검방법·점검값구분·설비등급 코드명 반환 추가 (화면 콤보 목록 조회 제거)
-- 			2026-10-01 					한성수	주기관리 조회·저장·삭제에 설비그룹이 없는 설비 포함 (설비 승인만 확인, 설비그룹이 있으면 설비그룹 승인도 확인)
-- 			2026-10-02 					한성수	주기관리 월별 점검자를 사원코드로 저장·조회 (월 칸은 사원명 표시, MxxCD는 저장값, 기존 사원명 저장값은 그대로 표시)
-- *****************************************************************************
  IN $FANO           VARCHAR(20),
  IN $FANO_COPY      VARCHAR(20),
  IN $SYEAR          VARCHAR(50),
  IN $EQMGRP         VARCHAR(50),
  IN $CHKKNDCD_LIST  MEDIUMTEXT,
  IN $REMARK_LIST    MEDIUMTEXT,
  IN $USEYN_LIST     MEDIUMTEXT,
  IN $SORTNO_LIST    MEDIUMTEXT,
  IN $YEAR_LIST      MEDIUMTEXT,
  IN $FANO_LIST      MEDIUMTEXT,
  IN $M01_LIST       MEDIUMTEXT,
  IN $M02_LIST       MEDIUMTEXT,
  IN $M03_LIST       MEDIUMTEXT,
  IN $M04_LIST       MEDIUMTEXT,
  IN $M05_LIST       MEDIUMTEXT,
  IN $M06_LIST       MEDIUMTEXT,
  IN $M07_LIST       MEDIUMTEXT,
  IN $M08_LIST       MEDIUMTEXT,
  IN $M09_LIST       MEDIUMTEXT,
  IN $M10_LIST       MEDIUMTEXT,
  IN $M11_LIST       MEDIUMTEXT,
  IN $M12_LIST       MEDIUMTEXT,

-- *****************************************************************************
IN  $CALLTYPE VARCHAR(50), IN $KEYWORD VARCHAR(1000))
PROC: BEGIN -- @CALLEMP, @CALLPRG, @CALLHOST, @CALLIP, @CALLMAC
-- *****************************************************************************
  DECLARE _$CHKKNDCD      VARCHAR(20);
  DECLARE _$REMARK        VARCHAR(1000);
  DECLARE _$CHKTP         VARCHAR(20);
  DECLARE _$SORTNO        DECIMAL(20, 8);
  DECLARE _$MAXSORTNO     DECIMAL(20, 8);
  DECLARE _$USEYN         VARCHAR(2);
  DECLARE _$CHKCYCLE      VARCHAR(20);

  DECLARE _$CHKKNDCD_LIST MEDIUMTEXT;

  DECLARE _$M01           VARCHAR(20);
  DECLARE _$M02           VARCHAR(20);
  DECLARE _$M03           VARCHAR(20);
  DECLARE _$M04           VARCHAR(20);
  DECLARE _$M05           VARCHAR(20);
  DECLARE _$M06           VARCHAR(20);
  DECLARE _$M07           VARCHAR(20);
  DECLARE _$M08           VARCHAR(20);
  DECLARE _$M09           VARCHAR(20);
  DECLARE _$M10           VARCHAR(20);
  DECLARE _$M11           VARCHAR(20);
  DECLARE _$M12           VARCHAR(20);
  DECLARE _$YEAR          VARCHAR(20);
  DECLARE _$FANO          VARCHAR(20);
  DECLARE _$PLANAPRV_CNT  INT DEFAULT 0;

CASE $CALLTYPE
-- *****************************************************************************
WHEN 'LIST_MSTEQM_GRP' THEN -- 설비그룹 점검계획 조회

  SELECT
    GRP_EQM.EQMGUBUN,
    COMTYPE.TPNM AS EQMGRPNM,
    COMTYPE.SORTNO AS EQMGRPSORTNO,
    CASE WHEN GRP_EQM02.EQMGUBUN IS NULL THEN 'N' ELSE 'Y' END AS EQM02,
    COALESCE(CONCAT('REV.', GRP_REV.REVNUM), '') AS REVNM,
    CASE GRP_APRV.APRVSTT
      WHEN 'A' THEN '승인'
      WHEN 'R' THEN '반려'
      ELSE '대기'
    END AS APRVSTTNM,
    COALESCE(GRP_APRV.APRVSTT, '') AS APRVSTT,
    COALESCE(GRP_APRV.REJREASON, '') AS REJREASON
  FROM COMTYPE
  -- 사용 설비가 있는 설비그룹 추출
  INNER JOIN (
    SELECT DISTINCT
      MSTEQM.EQMGUBUN
    FROM MSTEQM
    WHERE MSTEQM.USEYN = 'Y'
  ) GRP_EQM
    ON GRP_EQM.EQMGUBUN = COMTYPE.TPCD
  LEFT JOIN COMTYPE SELECTED_COMTYPE
    ON SELECTED_COMTYPE.GPCD = 'FM116'
   AND SELECTED_COMTYPE.TPCD = $EQMGRP
  LEFT JOIN CHKPLANEQM_APRV GRP_APRV
    ON GRP_APRV.PLANTP = 'G'
   AND GRP_APRV.PLANCD = GRP_EQM.EQMGUBUN
  -- 현재 승인 리비전 (개정 중이어도 직전 승인 번호)
  LEFT JOIN (
    SELECT MSTEQMREV_HEADER.PLANCD, MAX(MSTEQMREV_HEADER.REVNUM) AS REVNUM
    FROM MSTEQMREV_HEADER
    WHERE MSTEQMREV_HEADER.PLANTP = 'G'
      AND MSTEQMREV_HEADER.APRVSTT = 'A'
    GROUP BY MSTEQMREV_HEADER.PLANCD
  ) GRP_REV
    ON GRP_REV.PLANCD = GRP_EQM.EQMGUBUN
  LEFT JOIN (
    SELECT DISTINCT
      MSTEQM.EQMGUBUN
    FROM MSTEQM
    INNER JOIN CHKPLANEQM
      ON CHKPLANEQM.EQMCD = MSTEQM.FANO
     AND CHKPLANEQM.CHKTP = '02'
     AND CHKPLANEQM.USEYN = 'Y'
    WHERE MSTEQM.USEYN = 'Y'
  ) GRP_EQM02
    ON GRP_EQM02.EQMGUBUN = GRP_EQM.EQMGUBUN
  WHERE COMTYPE.GPCD = 'FM116'
    AND COMTYPE.USEYN = 'Y'
    AND (
      $EQMGRP IS NULL
      OR $EQMGRP = ''
      OR COMTYPE.TPNM = SELECTED_COMTYPE.TPNM
    )
  ORDER BY COMTYPE.SORTNO, GRP_EQM.EQMGUBUN
  ;
-- *****************************************************************************
WHEN 'LIST_GRP_EQM02' THEN -- 설비그룹 정기점검 항목 조회

  SELECT
    CHKPLANEQM.CHKKNDCD,
    MSTCHKKND.CHKKNDNM,
    MSTCHKKND.CHKLOC,
    MSTCHKKND.CHKMTH,
    MSTCHKKND.CHKVALTP,
    COALESCE(NULLIF(GPCD('CHKLOC', MSTCHKKND.CHKLOC), ''), MSTCHKKND.CHKLOC) AS CHKLOCNM,
    COALESCE(NULLIF(GPCD('CHKMTH', MSTCHKKND.CHKMTH), ''), MSTCHKKND.CHKMTH) AS CHKMTHNM,
    COALESCE(NULLIF(GPCD('CHKVALTP', MSTCHKKND.CHKVALTP), ''), MSTCHKKND.CHKVALTP) AS CHKVALTPNM,
    MSTCHKKND.CHKCYCLE,
    MIN(CHKPLANEQM.SORTNO) AS SORTNO,
    MAX(CASE WHEN CHKPLANEQM.USEYN = 'Y' THEN 'Y' ELSE 'N' END) AS USEYN,
    MAX(CHKPLANEQM.REMARK) AS REMARK
  FROM CHKPLANEQM
  INNER JOIN MSTCHKKND
    ON MSTCHKKND.CHKKNDCD = CHKPLANEQM.CHKKNDCD
  INNER JOIN MSTEQM
    ON MSTEQM.FANO = CHKPLANEQM.EQMCD
  WHERE MSTEQM.EQMGUBUN = $EQMGRP
    AND MSTEQM.USEYN = 'Y'
    AND MSTCHKKND.CHKTP = '02'
  GROUP BY CHKPLANEQM.CHKKNDCD, MSTCHKKND.CHKKNDNM, MSTCHKKND.CHKLOC, MSTCHKKND.CHKMTH, MSTCHKKND.CHKVALTP, MSTCHKKND.CHKCYCLE
  ORDER BY MIN(CHKPLANEQM.SORTNO)
  ;

-- *****************************************************************************
WHEN 'LIST_GRP_EQM02_ADD' THEN -- 설비그룹 미등록 정기점검 항목 조회

  SELECT
    MSTCHKKND.CHKKNDCD,
    MSTCHKKND.CHKKNDNM,
    MSTCHKKND.CHKTP,
    MSTCHKKND.CHKLOC,
    MSTCHKKND.CHKMTH,
    MSTCHKKND.CHKVALTP,
    COALESCE(NULLIF(GPCD('CHKLOC', MSTCHKKND.CHKLOC), ''), MSTCHKKND.CHKLOC) AS CHKLOCNM,
    COALESCE(NULLIF(GPCD('CHKMTH', MSTCHKKND.CHKMTH), ''), MSTCHKKND.CHKMTH) AS CHKMTHNM,
    COALESCE(NULLIF(GPCD('CHKVALTP', MSTCHKKND.CHKVALTP), ''), MSTCHKKND.CHKVALTP) AS CHKVALTPNM,
    MSTCHKKND.SORTNO,
    MSTCHKKND.USEYN,
    '' AS REMARK
  FROM MSTCHKKND
  CROSS JOIN MSTEQM
  LEFT JOIN CHKPLANEQM
    ON CHKPLANEQM.EQMCD = MSTEQM.FANO
   AND CHKPLANEQM.CHKKNDCD = MSTCHKKND.CHKKNDCD
   AND CHKPLANEQM.CHKTP = '02'
  WHERE MSTEQM.EQMGUBUN = $EQMGRP
    AND MSTEQM.USEYN = 'Y'
    AND MSTCHKKND.USEYN = 'Y'
    AND MSTCHKKND.CHKTP = '02'
  GROUP BY MSTCHKKND.CHKKNDCD, MSTCHKKND.CHKKNDNM, MSTCHKKND.CHKTP, MSTCHKKND.CHKLOC, MSTCHKKND.CHKMTH, MSTCHKKND.CHKVALTP, MSTCHKKND.SORTNO, MSTCHKKND.USEYN
  HAVING COUNT(DISTINCT CHKPLANEQM.EQMCD) < COUNT(DISTINCT MSTEQM.FANO)
  ORDER BY MSTCHKKND.SORTNO
  ;

-- *****************************************************************************
WHEN 'REG_GRP_EQM02' THEN -- 설비그룹 정기점검 항목 등록

  IF $EQMGRP IS NULL OR $EQMGRP = '' THEN
    CALL COMERR('설비그룹을 지정해주세요.');
    LEAVE PROC;
  END IF;

  CALL EQM1001_R05('', '', 'G', $EQMGRP, '', '', '', '', 'REQUEST_PLAN', '');

  WHILE LENGTH($CHKKNDCD_LIST) > 0 DO
    CALL COMSPLIT($CHKKNDCD_LIST, _$CHKKNDCD);
    CALL COMSPLIT($REMARK_LIST, _$REMARK);

    SET _$CHKTP = (SELECT CHKTP FROM MSTCHKKND WHERE CHKKNDCD = _$CHKKNDCD LIMIT 1);

    INSERT INTO CHKPLANEQM (
      EQMCD, CHKTP, CHKKNDCD, CHKCYCLE,
      SORTNO, USEYN, REMARK,
      RTIME, REMP, RPRG
    )
    SELECT
      MSTEQM.FANO, _$CHKTP, _$CHKKNDCD, 'MONTH',
      COALESCE(SORT_INFO.MAXSORTNO, 0) + 1, 'Y', _$REMARK,
      CALLTIME(), CALLEMP(), CALLPRG()
    FROM MSTEQM
    LEFT JOIN CHKPLANEQM
      ON CHKPLANEQM.EQMCD = MSTEQM.FANO
     AND CHKPLANEQM.CHKKNDCD = _$CHKKNDCD
     AND CHKPLANEQM.CHKTP = _$CHKTP
    LEFT JOIN (
      SELECT EQMCD, MAX(SORTNO) AS MAXSORTNO
      FROM CHKPLANEQM
      WHERE CHKTP = '02'
      GROUP BY EQMCD
    ) SORT_INFO
      ON SORT_INFO.EQMCD = MSTEQM.FANO
    WHERE MSTEQM.EQMGUBUN = $EQMGRP
      AND MSTEQM.USEYN = 'Y'
      AND CHKPLANEQM.EQMCD IS NULL;
  END WHILE;

-- *****************************************************************************
WHEN 'SAVE_GRP_EQM02' THEN -- 설비그룹 정기점검 항목 저장

  IF $EQMGRP IS NULL OR $EQMGRP = '' THEN
    CALL COMERR('설비그룹을 지정해주세요.');
    LEAVE PROC;
  END IF;

  CALL EQM1001_R05('', '', 'G', $EQMGRP, '', '', '', '', 'REQUEST_PLAN', '');

  WHILE LENGTH($CHKKNDCD_LIST) > 0 DO
    CALL COMSPLIT($CHKKNDCD_LIST, _$CHKKNDCD);
    CALL COMSPLIT($USEYN_LIST, _$USEYN);
    CALL COMSPLIT($SORTNO_LIST, _$SORTNO);
    CALL COMSPLIT($REMARK_LIST, _$REMARK);

    UPDATE CHKPLANEQM
    INNER JOIN MSTEQM
      ON MSTEQM.FANO = CHKPLANEQM.EQMCD
    SET
      CHKPLANEQM.USEYN  = _$USEYN,
      CHKPLANEQM.SORTNO = _$SORTNO,
      CHKPLANEQM.REMARK = _$REMARK,
      CHKPLANEQM.MTIME  = CALLTIME(),
      CHKPLANEQM.MEMP   = CALLEMP(),
      CHKPLANEQM.MPRG   = CALLPRG()
    WHERE MSTEQM.EQMGUBUN = $EQMGRP
      AND MSTEQM.USEYN = 'Y'
      AND CHKPLANEQM.CHKKNDCD = _$CHKKNDCD
      AND CHKPLANEQM.CHKTP = '02'
    ;
  END WHILE;

-- *****************************************************************************
WHEN 'DEL_GRP_EQM02' THEN -- 설비그룹 정기점검 항목 삭제

  IF $EQMGRP IS NULL OR $EQMGRP = '' THEN
    CALL COMERR('설비그룹을 지정해주세요.');
    LEAVE PROC;
  END IF;

  CALL EQM1001_R05('', '', 'G', $EQMGRP, '', '', '', '', 'REQUEST_PLAN', '');

  WHILE LENGTH($CHKKNDCD_LIST) > 0 DO
    CALL COMSPLIT($CHKKNDCD_LIST, _$CHKKNDCD);

    DELETE CHKPLANEQM
    FROM CHKPLANEQM
    INNER JOIN MSTEQM
      ON MSTEQM.FANO = CHKPLANEQM.EQMCD
    WHERE MSTEQM.EQMGUBUN = $EQMGRP
      AND MSTEQM.USEYN = 'Y'
      AND CHKPLANEQM.CHKKNDCD = _$CHKKNDCD
      AND CHKPLANEQM.CHKTP = '02';
  END WHILE;

-- *****************************************************************************
WHEN 'LIST_COPY_GRP_EQM02' THEN -- 설비그룹 복사 원본 목록 조회

  SELECT
    MSTEQM.EQMGUBUN AS EQMGRP,
    COMTYPE.TPNM AS EQMGRPNM,
    MIN(MSTEQM.FANO) AS FANO,
    COUNT(DISTINCT CHKPLANEQM.CHKKNDCD) AS EQM02CNT
  FROM MSTEQM
  INNER JOIN COMTYPE
    ON COMTYPE.GPCD = 'FM116'
   AND COMTYPE.TPCD = MSTEQM.EQMGUBUN
  INNER JOIN CHKPLANEQM
    ON CHKPLANEQM.EQMCD = MSTEQM.FANO
   AND CHKPLANEQM.CHKTP = '02'
  WHERE MSTEQM.USEYN = 'Y'
    AND MSTEQM.EQMGUBUN <> $EQMGRP
  GROUP BY MSTEQM.EQMGUBUN, COMTYPE.TPNM, COMTYPE.SORTNO
  ORDER BY COMTYPE.SORTNO, MSTEQM.EQMGUBUN
  ;

-- *****************************************************************************
WHEN 'LIST_COPY_GRP_EQM02_DTL' THEN -- 설비그룹 복사 상세 항목 조회

  SELECT
    CHKPLANEQM.CHKKNDCD,
    MSTCHKKND.CHKKNDNM,
    MSTCHKKND.CHKLOC,
    MSTCHKKND.CHKMTH,
    MSTCHKKND.CHKVALTP,
    COALESCE(NULLIF(GPCD('CHKLOC', MSTCHKKND.CHKLOC), ''), MSTCHKKND.CHKLOC) AS CHKLOCNM,
    COALESCE(NULLIF(GPCD('CHKMTH', MSTCHKKND.CHKMTH), ''), MSTCHKKND.CHKMTH) AS CHKMTHNM,
    COALESCE(NULLIF(GPCD('CHKVALTP', MSTCHKKND.CHKVALTP), ''), MSTCHKKND.CHKVALTP) AS CHKVALTPNM,
    MIN(CHKPLANEQM.SORTNO) AS SORTNO,
    MAX(CASE WHEN CHKPLANEQM.USEYN = 'Y' THEN 'Y' ELSE 'N' END) AS USEYN
  FROM CHKPLANEQM
  INNER JOIN MSTEQM
    ON MSTEQM.FANO = CHKPLANEQM.EQMCD
  INNER JOIN MSTCHKKND
    ON MSTCHKKND.CHKKNDCD = CHKPLANEQM.CHKKNDCD
  WHERE MSTEQM.EQMGUBUN = $EQMGRP
    AND MSTEQM.USEYN = 'Y'
    AND CHKPLANEQM.CHKTP = '02'
  GROUP BY CHKPLANEQM.CHKKNDCD, MSTCHKKND.CHKKNDNM, MSTCHKKND.CHKLOC, MSTCHKKND.CHKMTH, MSTCHKKND.CHKVALTP
  ORDER BY MIN(CHKPLANEQM.SORTNO), CHKPLANEQM.CHKKNDCD
  ;

-- *****************************************************************************
WHEN 'COPY_GRP_EQM02' THEN -- 설비그룹 정기점검 항목 복사

  IF $EQMGRP IS NULL OR $EQMGRP = '' THEN
    CALL COMERR('설비그룹을 지정해주세요.');
    LEAVE PROC;
  END IF;

  IF $FANO_COPY IS NULL OR $FANO_COPY = '' THEN
    CALL COMERR('복사할 설비그룹을 지정해주세요.');
    LEAVE PROC;
  END IF;

  CALL EQM1001_R05('', '', 'G', $EQMGRP, '', '', '', '', 'REQUEST_PLAN', '');

  DROP TEMPORARY TABLE IF EXISTS TMP_COPY_EQM02;
  CREATE TEMPORARY TABLE TMP_COPY_EQM02 AS
  SELECT
    CHKPLANEQM.CHKTP,
    CHKPLANEQM.CHKKNDCD,
    MIN(CHKPLANEQM.CHKCYCLE) AS CHKCYCLE,
    MIN(CHKPLANEQM.SORTNO) AS SORTNO,
    MAX(CHKPLANEQM.USEYN) AS USEYN,
    MAX(CHKPLANEQM.REMARK) AS REMARK
  FROM MSTEQM SOURCE_EQM
  INNER JOIN MSTEQM SOURCE_SELECTED
    ON SOURCE_SELECTED.FANO = $FANO_COPY
   AND SOURCE_SELECTED.EQMGUBUN = SOURCE_EQM.EQMGUBUN
  INNER JOIN CHKPLANEQM
    ON CHKPLANEQM.EQMCD = SOURCE_EQM.FANO
   AND CHKPLANEQM.CHKTP = '02'
  WHERE SOURCE_EQM.USEYN = 'Y'
  GROUP BY CHKPLANEQM.CHKTP, CHKPLANEQM.CHKKNDCD;

  IF (SELECT COUNT(*) FROM TMP_COPY_EQM02) = 0 THEN
    DROP TEMPORARY TABLE IF EXISTS TMP_COPY_EQM02;
    CALL COMERR('복사할 정기점검 항목이 없습니다.');
    LEAVE PROC;
  END IF;

  INSERT INTO CHKPLANEQM (
    EQMCD, CHKTP, CHKKNDCD, CHKCYCLE,
    SORTNO, USEYN, REMARK,
    RTIME, REMP, RPRG
  )
  SELECT
    MSTEQM.FANO, TMP_COPY_EQM02.CHKTP, TMP_COPY_EQM02.CHKKNDCD, TMP_COPY_EQM02.CHKCYCLE,
    TMP_COPY_EQM02.SORTNO, TMP_COPY_EQM02.USEYN, TMP_COPY_EQM02.REMARK,
    CALLTIME(), CALLEMP(), CALLPRG()
  FROM MSTEQM
  CROSS JOIN TMP_COPY_EQM02
  WHERE MSTEQM.EQMGUBUN = $EQMGRP
    AND MSTEQM.USEYN = 'Y'
  ON DUPLICATE KEY UPDATE
    CHKTP   = VALUES(CHKTP),
    CHKCYCLE = VALUES(CHKCYCLE),
    SORTNO  = VALUES(SORTNO),
    USEYN   = VALUES(USEYN),
    REMARK  = VALUES(REMARK),
    MTIME   = CALLTIME(),
    MEMP    = CALLEMP(),
    MPRG    = CALLPRG();

  DELETE CHKPLANEQM
  FROM CHKPLANEQM
  INNER JOIN MSTEQM
    ON MSTEQM.FANO = CHKPLANEQM.EQMCD
  LEFT JOIN TMP_COPY_EQM02
    ON TMP_COPY_EQM02.CHKKNDCD = CHKPLANEQM.CHKKNDCD
  WHERE MSTEQM.EQMGUBUN = $EQMGRP
    AND MSTEQM.USEYN = 'Y'
    AND CHKPLANEQM.CHKTP = '02'
    AND TMP_COPY_EQM02.CHKKNDCD IS NULL;

  DROP TEMPORARY TABLE IF EXISTS TMP_COPY_EQM02;

-- *****************************************************************************
WHEN 'LIST_MSTEQM' THEN -- 설비 목록 조회

  SELECT 
    MSTEQM.FANO,
    MSTEQM.EQMNM,
    MAX(CASE WHEN CHKPLANEQM.CHKTP = '02' AND CHKPLANEQM.USEYN = 'Y' THEN 'Y' ELSE 'N' END) AS EQM02,
    COALESCE(CONCAT('REV.', EQM_REV.REVNUM), '') AS REVNM,
    CASE EQM_APRV.APRVSTT
      WHEN 'A' THEN '승인'
      WHEN 'R' THEN '반려'
      ELSE '대기'
    END AS APRVSTTNM,
    COALESCE(EQM_APRV.APRVSTT, '') AS APRVSTT,
    COALESCE(EQM_APRV.REJREASON, '') AS REJREASON
  FROM MSTEQM
  LEFT JOIN CHKPLANEQM ON CHKPLANEQM.EQMCD = MSTEQM.FANO
  LEFT JOIN CHKPLANEQM_APRV EQM_APRV
    ON EQM_APRV.PLANTP = 'E'
   AND EQM_APRV.PLANCD = MSTEQM.FANO
  -- 현재 승인 리비전 (개정 중이어도 직전 승인 번호)
  LEFT JOIN (
    SELECT MSTEQMREV_HEADER.PLANCD, MAX(MSTEQMREV_HEADER.REVNUM) AS REVNUM
    FROM MSTEQMREV_HEADER
    WHERE MSTEQMREV_HEADER.PLANTP = 'E'
      AND MSTEQMREV_HEADER.APRVSTT = 'A'
    GROUP BY MSTEQMREV_HEADER.PLANCD
  ) EQM_REV
    ON EQM_REV.PLANCD = MSTEQM.FANO
  WHERE MSTEQM.USEYN = 'Y'
    AND (MSTEQM.FANO LIKE CONCAT('%', $FANO, '%') OR MSTEQM.EQMNM LIKE CONCAT('%', $FANO, '%'))
    
  GROUP BY MSTEQM.FANO, MSTEQM.EQMNM, EQM_REV.REVNUM, EQM_APRV.APRVSTT, EQM_APRV.REJREASON
  ORDER BY MSTEQM.FANO
  ;

-- *****************************************************************************
WHEN 'LIST_MSTEQM_EQM02' THEN -- 설비별 정기점검 항목 조회
  SELECT 
    CHKPLANEQM.CHKKNDCD,
    MSTCHKKND.CHKKNDNM,
    MSTCHKKND.CHKLOC,
    MSTCHKKND.CHKMTH,
    MSTCHKKND.CHKVALTP,
    COALESCE(NULLIF(GPCD('CHKLOC', MSTCHKKND.CHKLOC), ''), MSTCHKKND.CHKLOC) AS CHKLOCNM,
    COALESCE(NULLIF(GPCD('CHKMTH', MSTCHKKND.CHKMTH), ''), MSTCHKKND.CHKMTH) AS CHKMTHNM,
    COALESCE(NULLIF(GPCD('CHKVALTP', MSTCHKKND.CHKVALTP), ''), MSTCHKKND.CHKVALTP) AS CHKVALTPNM,
    MSTCHKKND.CHKCYCLE,
    CHKPLANEQM.SORTNO,
    CASE WHEN CHKPLANEQM.USEYN = 'Y' THEN 'Y' ELSE 'N' END AS USEYN,
    CHKPLANEQM.REMARK
  FROM CHKPLANEQM
  INNER JOIN MSTCHKKND 
    ON MSTCHKKND.CHKKNDCD = CHKPLANEQM.CHKKNDCD  
  WHERE CHKPLANEQM.EQMCD = $FANO
    AND MSTCHKKND.CHKTP = '02'  
  ORDER BY  CHKPLANEQM.SORTNO
  ;

-- *****************************************************************************
WHEN 'LIST_EQM02' THEN -- 설비별 미등록 정기점검 항목 조회

  SELECT 
    MSTCHKKND.CHKKNDCD,
    MSTCHKKND.CHKKNDNM,
    MSTCHKKND.CHKTP,
    MSTCHKKND.CHKLOC,
    MSTCHKKND.CHKMTH,
    MSTCHKKND.CHKVALTP,
    COALESCE(NULLIF(GPCD('CHKLOC', MSTCHKKND.CHKLOC), ''), MSTCHKKND.CHKLOC) AS CHKLOCNM,
    COALESCE(NULLIF(GPCD('CHKMTH', MSTCHKKND.CHKMTH), ''), MSTCHKKND.CHKMTH) AS CHKMTHNM,
    COALESCE(NULLIF(GPCD('CHKVALTP', MSTCHKKND.CHKVALTP), ''), MSTCHKKND.CHKVALTP) AS CHKVALTPNM,
    MSTCHKKND.SORTNO,
    MSTCHKKND.USEYN,
    '' AS REMARK
  FROM MSTCHKKND
  LEFT JOIN CHKPLANEQM 
    ON CHKPLANEQM.CHKKNDCD = MSTCHKKND.CHKKNDCD 
   AND CHKPLANEQM.EQMCD = $FANO
  WHERE MSTCHKKND.USEYN = 'Y'
    AND MSTCHKKND.CHKTP = '02'
    AND CHKPLANEQM.CHKKNDCD IS NULL
  ORDER BY MSTCHKKND.SORTNO
  ;

-- *****************************************************************************
WHEN 'REG_EQM02' THEN -- 설비별 정기점검 항목 등록

  CALL EQM1001_R05('', '', 'E', $FANO, '', '', '', '', 'REQUEST_PLAN', '');
  
  WHILE LENGTH($CHKKNDCD_LIST) > 0 DO
    CALL COMSPLIT($CHKKNDCD_LIST, _$CHKKNDCD);
    CALL COMSPLIT($REMARK_LIST, _$REMARK);
  
    SET _$CHKTP = (SELECT CHKTP FROM MSTCHKKND WHERE CHKKNDCD = _$CHKKNDCD LIMIT 1);
    SET _$MAXSORTNO = (SELECT IFNULL(MAX(SORTNO), 0) FROM CHKPLANEQM  WHERE EQMCD = $FANO AND CHKTP = _$CHKTP);
    SET _$SORTNO = _$MAXSORTNO + 1;

    INSERT INTO CHKPLANEQM ( 
      EQMCD, CHKTP, CHKKNDCD, CHKCYCLE, 
      SORTNO, USEYN, REMARK, 
      RTIME, REMP, RPRG 
    ) 
    VALUES (
      $FANO, _$CHKTP, _$CHKKNDCD, 'MONTH',
      _$SORTNO, 'Y', _$REMARK,
      CALLTIME(), CALLEMP(), CALLPRG()
    );     
  END WHILE;
-- *****************************************************************************
WHEN 'SAVE_EQM02' THEN -- 설비별 정기점검 항목 저장

  CALL EQM1001_R05('', '', 'E', $FANO, '', '', '', '', 'REQUEST_PLAN', '');
  
  WHILE LENGTH($CHKKNDCD_LIST) > 0 DO
    CALL COMSPLIT($CHKKNDCD_LIST, _$CHKKNDCD);
    CALL COMSPLIT($USEYN_LIST, _$USEYN);
    CALL COMSPLIT($SORTNO_LIST, _$SORTNO);
    CALL COMSPLIT($REMARK_LIST, _$REMARK);

    UPDATE CHKPLANEQM SET
      USEYN  = _$USEYN,
      SORTNO = _$SORTNO,
      REMARK = _$REMARK,
      MTIME  = CALLTIME(),
      MEMP   = CALLEMP(),
      MPRG   = CALLPRG()
    WHERE EQMCD = $FANO
     AND CHKKNDCD = _$CHKKNDCD
     AND CHKTP = '02'
    ;
  END WHILE;
-- *****************************************************************************
WHEN 'DEL_EQM02' THEN -- 설비별 정기점검 항목 삭제

  CALL EQM1001_R05('', '', 'E', $FANO, '', '', '', '', 'REQUEST_PLAN', '');
  
  WHILE LENGTH($CHKKNDCD_LIST) > 0 DO
    CALL COMSPLIT($CHKKNDCD_LIST, _$CHKKNDCD);
    
    DELETE FROM CHKPLANEQM 
    WHERE EQMCD = $FANO 
    AND CHKKNDCD = _$CHKKNDCD  
    AND CHKTP = '02';    
  END WHILE;

-- *****************************************************************************
WHEN 'LIST_COPY_EQM02' THEN -- 설비별 복사 원본 목록 조회

  SELECT 
    MSTEQM.FANO,
    MSTEQM.EQMNM
  FROM MSTEQM
  INNER JOIN CHKPLANEQM CP 
    ON CP.EQMCD = MSTEQM.FANO 
   AND CP.CHKTP = '02'
  WHERE MSTEQM.FANO <> $FANO
  GROUP BY MSTEQM.FANO, MSTEQM.EQMNM
  ORDER BY MSTEQM.FANO;

  SELECT 
    CHKPLANEQM.CHKKNDCD,
    MSTCHKKND.CHKKNDNM,
    MSTCHKKND.CHKLOC,
    MSTCHKKND.CHKMTH,
    MSTCHKKND.CHKVALTP,
    COALESCE(NULLIF(GPCD('CHKLOC', MSTCHKKND.CHKLOC), ''), MSTCHKKND.CHKLOC) AS CHKLOCNM,
    COALESCE(NULLIF(GPCD('CHKMTH', MSTCHKKND.CHKMTH), ''), MSTCHKKND.CHKMTH) AS CHKMTHNM,
    COALESCE(NULLIF(GPCD('CHKVALTP', MSTCHKKND.CHKVALTP), ''), MSTCHKKND.CHKVALTP) AS CHKVALTPNM,
    CHKPLANEQM.SORTNO
  FROM CHKPLANEQM
  INNER JOIN MSTCHKKND 
    ON MSTCHKKND.CHKKNDCD = CHKPLANEQM.CHKKNDCD  
  WHERE CHKPLANEQM.EQMCD = $FANO
    AND CHKPLANEQM.CHKTP = '02'  
  ORDER BY  CHKPLANEQM.SORTNO
  ;

-- *****************************************************************************
WHEN 'COPY_EQM02' THEN -- 설비별 정기점검 항목 복사

  CALL EQM1001_R05('', '', 'E', $FANO, '', '', '', '', 'REQUEST_PLAN', '');

  SET _$CHKKNDCD_LIST = IFNULL((SELECT GROUP_CONCAT(CHKKNDCD ORDER BY SORTNO ASC SEPARATOR '»')
                                FROM CHKPLANEQM
                                WHERE EQMCD = $FANO_COPY
                                  AND CHKTP = '02')                              
                             , '');
  
  DELETE FROM CHKPLANEQM 
  WHERE EQMCD = $FANO  
  AND CHKTP = '02'; 

  WHILE LENGTH(_$CHKKNDCD_LIST) > 0 DO                    
    CALL COMSPLIT(_$CHKKNDCD_LIST, _$CHKKNDCD);
       
    SET _$CHKTP = (SELECT CHKTP FROM MSTCHKKND WHERE CHKKNDCD = _$CHKKNDCD LIMIT 1);
    SET _$SORTNO = (SELECT SORTNO FROM CHKPLANEQM WHERE CHKKNDCD = _$CHKKNDCD AND EQMCD = $FANO_COPY LIMIT 1);
    SET _$CHKCYCLE = (SELECT CHKCYCLE FROM CHKPLANEQM WHERE CHKKNDCD = _$CHKKNDCD AND EQMCD = $FANO_COPY LIMIT 1);
    SET _$USEYN = (SELECT USEYN FROM CHKPLANEQM WHERE CHKKNDCD = _$CHKKNDCD AND EQMCD = $FANO_COPY LIMIT 1);
    SET _$REMARK = (SELECT REMARK FROM CHKPLANEQM WHERE CHKKNDCD = _$CHKKNDCD AND EQMCD = $FANO_COPY LIMIT 1);

    INSERT INTO CHKPLANEQM ( 
      EQMCD, CHKTP, CHKKNDCD, CHKCYCLE, 
      SORTNO, USEYN, REMARK, 
      RTIME, REMP, RPRG 
    ) 
    VALUES (
      $FANO, _$CHKTP, _$CHKKNDCD, _$CHKCYCLE,
      _$SORTNO, _$USEYN, _$REMARK,
      CALLTIME(), CALLEMP(), CALLPRG()
    );      
  END WHILE;

-- *****************************************************************************
WHEN 'LIST_CYCLE_EQMCD' THEN -- 설비별 월별 점검계획 조회
  
  IF $SYEAR = '' THEN
    CALL COMERR('조회년도를 지정해주세요.');
    LEAVE PROC;
  END IF;  
    
  SELECT 
    MSTEQM.FANO,
    MSTEQM.EQMNM,
    MSTEQM.EQMGRADE,
    COALESCE(NULLIF(GPCD('FM110', MSTEQM.EQMGRADE), ''), MSTEQM.EQMGRADE) AS EQMGRADENM,
    $SYEAR AS YEAR,
    -- 월별 점검자: 사원코드로 저장된 값은 사원명으로 표시 (MxxCD는 저장값 그대로)
    COALESCE(NULLIF(GPCD('EMPCD', CHKPLANEQM_YEARPLAN.MONTH_01), ''), IFNULL(CHKPLANEQM_YEARPLAN.MONTH_01, '')) AS M01,
    IFNULL(CHKPLANEQM_YEARPLAN.MONTH_01, '') AS M01CD,
    COALESCE(NULLIF(GPCD('EMPCD', CHKPLANEQM_YEARPLAN.MONTH_02), ''), IFNULL(CHKPLANEQM_YEARPLAN.MONTH_02, '')) AS M02,
    IFNULL(CHKPLANEQM_YEARPLAN.MONTH_02, '') AS M02CD,
    COALESCE(NULLIF(GPCD('EMPCD', CHKPLANEQM_YEARPLAN.MONTH_03), ''), IFNULL(CHKPLANEQM_YEARPLAN.MONTH_03, '')) AS M03,
    IFNULL(CHKPLANEQM_YEARPLAN.MONTH_03, '') AS M03CD,
    COALESCE(NULLIF(GPCD('EMPCD', CHKPLANEQM_YEARPLAN.MONTH_04), ''), IFNULL(CHKPLANEQM_YEARPLAN.MONTH_04, '')) AS M04,
    IFNULL(CHKPLANEQM_YEARPLAN.MONTH_04, '') AS M04CD,
    COALESCE(NULLIF(GPCD('EMPCD', CHKPLANEQM_YEARPLAN.MONTH_05), ''), IFNULL(CHKPLANEQM_YEARPLAN.MONTH_05, '')) AS M05,
    IFNULL(CHKPLANEQM_YEARPLAN.MONTH_05, '') AS M05CD,
    COALESCE(NULLIF(GPCD('EMPCD', CHKPLANEQM_YEARPLAN.MONTH_06), ''), IFNULL(CHKPLANEQM_YEARPLAN.MONTH_06, '')) AS M06,
    IFNULL(CHKPLANEQM_YEARPLAN.MONTH_06, '') AS M06CD,
    COALESCE(NULLIF(GPCD('EMPCD', CHKPLANEQM_YEARPLAN.MONTH_07), ''), IFNULL(CHKPLANEQM_YEARPLAN.MONTH_07, '')) AS M07,
    IFNULL(CHKPLANEQM_YEARPLAN.MONTH_07, '') AS M07CD,
    COALESCE(NULLIF(GPCD('EMPCD', CHKPLANEQM_YEARPLAN.MONTH_08), ''), IFNULL(CHKPLANEQM_YEARPLAN.MONTH_08, '')) AS M08,
    IFNULL(CHKPLANEQM_YEARPLAN.MONTH_08, '') AS M08CD,
    COALESCE(NULLIF(GPCD('EMPCD', CHKPLANEQM_YEARPLAN.MONTH_09), ''), IFNULL(CHKPLANEQM_YEARPLAN.MONTH_09, '')) AS M09,
    IFNULL(CHKPLANEQM_YEARPLAN.MONTH_09, '') AS M09CD,
    COALESCE(NULLIF(GPCD('EMPCD', CHKPLANEQM_YEARPLAN.MONTH_10), ''), IFNULL(CHKPLANEQM_YEARPLAN.MONTH_10, '')) AS M10,
    IFNULL(CHKPLANEQM_YEARPLAN.MONTH_10, '') AS M10CD,
    COALESCE(NULLIF(GPCD('EMPCD', CHKPLANEQM_YEARPLAN.MONTH_11), ''), IFNULL(CHKPLANEQM_YEARPLAN.MONTH_11, '')) AS M11,
    IFNULL(CHKPLANEQM_YEARPLAN.MONTH_11, '') AS M11CD,
    COALESCE(NULLIF(GPCD('EMPCD', CHKPLANEQM_YEARPLAN.MONTH_12), ''), IFNULL(CHKPLANEQM_YEARPLAN.MONTH_12, '')) AS M12,
    IFNULL(CHKPLANEQM_YEARPLAN.MONTH_12, '') AS M12CD,
    IFNULL(CHKPLANEQM_YEARPLAN.REMARK, '') AS REMARK
  FROM MSTEQM
  LEFT JOIN CHKPLANEQM_YEARPLAN 
         ON CHKPLANEQM_YEARPLAN.EQMCD = MSTEQM.FANO
        AND CHKPLANEQM_YEARPLAN.YEAR = $SYEAR
  LEFT JOIN CHKPLANEQM
         ON CHKPLANEQM.EQMCD = MSTEQM.FANO
  -- 설비 승인 리비전이 있는 설비 (설비그룹이 있으면 설비그룹 승인 리비전도 필요)
  LEFT JOIN (
    SELECT MSTEQMREV_HEADER.PLANCD
    FROM MSTEQMREV_HEADER
    WHERE MSTEQMREV_HEADER.PLANTP = 'G'
      AND MSTEQMREV_HEADER.APRVSTT = 'A'
    GROUP BY MSTEQMREV_HEADER.PLANCD
  ) GRP_REV
    ON GRP_REV.PLANCD = MSTEQM.EQMGUBUN
  INNER JOIN (
    SELECT MSTEQMREV_HEADER.PLANCD
    FROM MSTEQMREV_HEADER
    WHERE MSTEQMREV_HEADER.PLANTP = 'E'
      AND MSTEQMREV_HEADER.APRVSTT = 'A'
    GROUP BY MSTEQMREV_HEADER.PLANCD
  ) EQM_REV
    ON EQM_REV.PLANCD = MSTEQM.FANO
 
  WHERE MSTEQM.USEYN = 'Y'
    AND (IFNULL(MSTEQM.EQMGUBUN, '') = '' OR GRP_REV.PLANCD IS NOT NULL)
    AND (MSTEQM.FANO LIKE CONCAT('%', $FANO, '%') OR MSTEQM.EQMNM LIKE CONCAT('%', $FANO, '%'))
    AND CHKPLANEQM.CHKTP = '02'

  GROUP BY MSTEQM.FANO
  ORDER BY MSTEQM.FANO;

-- *****************************************************************************
WHEN 'SAVE_CYCLE_EQMCD' THEN -- 설비별 월별 점검계획 저장
  WHILE LENGTH($FANO_LIST) > 0 DO
    CALL COMSPLIT($FANO_LIST, _$FANO);
    CALL COMSPLIT($YEAR_LIST, _$YEAR);
    CALL COMSPLIT($M01_LIST, _$M01);
    CALL COMSPLIT($M02_LIST, _$M02);
    CALL COMSPLIT($M03_LIST, _$M03);
    CALL COMSPLIT($M04_LIST, _$M04);
    CALL COMSPLIT($M05_LIST, _$M05);
    CALL COMSPLIT($M06_LIST, _$M06);
    CALL COMSPLIT($M07_LIST, _$M07);
    CALL COMSPLIT($M08_LIST, _$M08);
    CALL COMSPLIT($M09_LIST, _$M09);
    CALL COMSPLIT($M10_LIST, _$M10);
    CALL COMSPLIT($M11_LIST, _$M11);
    CALL COMSPLIT($M12_LIST, _$M12);
    CALL COMSPLIT($REMARK_LIST, _$REMARK);

    SELECT COUNT(*) INTO _$PLANAPRV_CNT
    FROM MSTEQM
    LEFT JOIN MSTEQMREV_HEADER GRP_REV
      ON GRP_REV.PLANTP = 'G'
     AND GRP_REV.PLANCD = MSTEQM.EQMGUBUN
     AND GRP_REV.APRVSTT = 'A'
    INNER JOIN MSTEQMREV_HEADER EQM_REV
      ON EQM_REV.PLANTP = 'E'
     AND EQM_REV.PLANCD = MSTEQM.FANO
     AND EQM_REV.APRVSTT = 'A'
    WHERE MSTEQM.FANO = _$FANO
      AND MSTEQM.USEYN = 'Y'
      AND (IFNULL(MSTEQM.EQMGUBUN, '') = '' OR GRP_REV.PLANCD IS NOT NULL);

    IF _$PLANAPRV_CNT = 0 THEN
      CALL COMERR('승인된 정기점검 계획만 주기관리할 수 있습니다.');
      LEAVE PROC;
    END IF;
  
    IF EXISTS (SELECT 1 FROM CHKPLANEQM_YEARPLAN WHERE EQMCD = _$FANO AND YEAR =_$YEAR AND CHKTP = '02') THEN  
      
      UPDATE CHKPLANEQM_YEARPLAN SET
        MONTH_01 = _$M01, 
        MONTH_02 = _$M02, 
        MONTH_03 = _$M03, 
        MONTH_04 = _$M04, 
        MONTH_05 = _$M05, 
        MONTH_06 = _$M06, 
        MONTH_07 = _$M07, 
        MONTH_08 = _$M08, 
        MONTH_09 = _$M09, 
        MONTH_10 = _$M10, 
        MONTH_11 = _$M11, 
        MONTH_12 = _$M12, 
        REMARK   = _$REMARK,
        MTIME = CALLTIME(),
        MEMP = CALLEMP(),
        MPRG = CALLPRG()
      WHERE EQMCD = _$FANO
        AND YEAR  = _$YEAR
        AND CHKTP = '02'
     ;
        
      IF EXISTS (
        SELECT 1 FROM CHKPLANEQM_YEARPLAN WHERE EQMCD = _$FANO AND YEAR = _$YEAR AND CHKTP = '02' AND REMARK = ''
                                                                AND MONTH_01 = '' AND MONTH_02 = '' AND MONTH_03 = '' AND MONTH_04 = ''
                                                                AND MONTH_05 = '' AND MONTH_06 = '' AND MONTH_07 = '' AND MONTH_08 = ''
                                                                AND MONTH_09 = '' AND MONTH_10 = '' AND MONTH_11 = '' AND MONTH_12 = '') THEN

        DELETE FROM CHKPLANEQM_YEARPLAN 
        WHERE EQMCD = _$FANO 
        AND YEAR = _$YEAR 
        AND CHKTP = '02';
      END IF;  
    ELSE
      INSERT INTO CHKPLANEQM_YEARPLAN (
        EQMCD, CHKTP, YEAR, 
        MONTH_01, MONTH_02, MONTH_03, MONTH_04, 
        MONTH_05, MONTH_06, MONTH_07, MONTH_08, 
        MONTH_09, MONTH_10, MONTH_11, MONTH_12, 
        REMARK, RTIME, REMP, RPRG
      ) 
      VALUES (
        _$FANO, '02', _$YEAR,
        _$M01, _$M02, _$M03, _$M04,
        _$M05, _$M06, _$M07, _$M08,
        _$M09, _$M10, _$M11, _$M12,
        _$REMARK, CALLTIME(), CALLEMP(), CALLPRG()
      );
   
      IF EXISTS (
        SELECT 1 FROM CHKPLANEQM_YEARPLAN WHERE EQMCD = _$FANO AND YEAR = _$YEAR AND CHKTP = '02' AND REMARK = ''
                                                                AND MONTH_01 = '' AND MONTH_02 = '' AND MONTH_03 = '' AND MONTH_04 = ''
                                                                AND MONTH_05 = '' AND MONTH_06 = '' AND MONTH_07 = '' AND MONTH_08 = ''
                                                                AND MONTH_09 = '' AND MONTH_10 = '' AND MONTH_11 = '' AND MONTH_12 = '') THEN

        DELETE FROM CHKPLANEQM_YEARPLAN 
        WHERE EQMCD = _$FANO
        AND YEAR = _$YEAR 
        AND CHKTP = '02';
      END IF;
    END IF;
  END WHILE;
-- *****************************************************************************
WHEN 'DELETE_CYCLE_EQMCD' THEN -- 설비별 월별 점검계획 삭제

  WHILE LENGTH($FANO_LIST) > 0 DO
    CALL COMSPLIT($FANO_LIST, _$FANO);
    CALL COMSPLIT($YEAR_LIST, _$YEAR);

    SELECT COUNT(*) INTO _$PLANAPRV_CNT
    FROM MSTEQM
    LEFT JOIN MSTEQMREV_HEADER GRP_REV
      ON GRP_REV.PLANTP = 'G'
     AND GRP_REV.PLANCD = MSTEQM.EQMGUBUN
     AND GRP_REV.APRVSTT = 'A'
    INNER JOIN MSTEQMREV_HEADER EQM_REV
      ON EQM_REV.PLANTP = 'E'
     AND EQM_REV.PLANCD = MSTEQM.FANO
     AND EQM_REV.APRVSTT = 'A'
    WHERE MSTEQM.FANO = _$FANO
      AND MSTEQM.USEYN = 'Y'
      AND (IFNULL(MSTEQM.EQMGUBUN, '') = '' OR GRP_REV.PLANCD IS NOT NULL);

    IF _$PLANAPRV_CNT = 0 THEN
      CALL COMERR('승인된 정기점검 계획만 주기관리할 수 있습니다.');
      LEAVE PROC;
    END IF;
  
    DELETE FROM CHKPLANEQM_YEARPLAN 
    WHERE EQMCD = _$FANO 
    AND YEAR = _$YEAR 
    AND CHKTP = '02';
  END WHILE;

-- *****************************************************************************
END CASE; END
