CREATE DEFINER = 'root'@'%'
PROCEDURE MES_SNS2.SYS0001_R02(
-- *****************************************************************************
-- Comment: 공통타입관리
-- Create: 2025-03-27 이대규 
-- *****************************************************************************
 IN $GPCD1 VARCHAR(20), -- 헤더코드
 IN $GPNM VARCHAR(100), -- 헤더명
 IN $SYSYN VARCHAR(1), -- 시스템여부
 IN $REF01NM VARCHAR(100), -- 참조설명01
 IN $REF02NM VARCHAR(100), -- 참조설명02
 IN $REF03NM VARCHAR(100), -- 참조설명03
 IN $REF04NM VARCHAR(100), -- 참조설명04
 IN $REF05NM VARCHAR(100), -- 참조설명05
 IN $REF06NM VARCHAR(100), -- 참조설명06
 IN $REF07NM VARCHAR(100), -- 참조설명07
 IN $REF08NM VARCHAR(100), -- 참조설명08
 IN $REF09NM VARCHAR(100), -- 참조설명09
 IN $REF10NM VARCHAR(100), -- 참조설명10
 IN $REF11NM VARCHAR(100), -- 참조설명11
 IN $REF12NM VARCHAR(100), -- 참조설명12
 IN $REF13NM VARCHAR(100), -- 참조설명13
 IN $REF14NM VARCHAR(100), -- 참조설명14
 IN $REF15NM VARCHAR(100), -- 참조설명15
 IN $REF16NM VARCHAR(100), -- 참조설명16
 IN $REF17NM VARCHAR(100), -- 참조설명17
 IN $REF18NM VARCHAR(100), -- 참조설명18
 IN $REF19NM VARCHAR(100), -- 참조설명19
 IN $REF20NM VARCHAR(100), -- 참조설명20
 IN $REMARK VARCHAR(1000), -- 비고
 IN $MESCOLUMN VARCHAR(100),
-- *****************************************************************************
 IN $CALLTYPE VARCHAR(50), IN $KEYWORD VARCHAR(1000))
PROC: BEGIN -- @CALLEMP, @CALLPRG, @CALLHOST, @CALLIP, @CALLMAC
-- SET @DEBUGLOGYN = 'Y';
-- *****************************************************************************

-- DECLARE _$V01 VARCHAR(1000);

-- ****************************************************************************
CASE $CALLTYPE
-- * ***************************************************************************
WHEN 'LIST_COMTYPEGP' THEN

  SELECT COMTYPEGP.GPCD AS GPCD1, COMTYPEGP.GPNM, COMTYPEGP.SYSYN, 
    COMTYPEGP.MESCOLUMN,
    COMTYPEGP.REF01NM, COMTYPEGP.REF02NM, COMTYPEGP.REF03NM, 
    COMTYPEGP.REF04NM, COMTYPEGP.REF05NM, COMTYPEGP.REF06NM, 
    COMTYPEGP.REF07NM,  COMTYPEGP.REF08NM,  COMTYPEGP.REF09NM, 
    COMTYPEGP.REF10NM,  COMTYPEGP.REF11NM, COMTYPEGP.REF12NM, 
    COMTYPEGP.REF13NM,  COMTYPEGP.REF14NM,  COMTYPEGP.REF15NM,  
    COMTYPEGP.REF16NM, COMTYPEGP.REF17NM, COMTYPEGP.REF18NM, 
    COMTYPEGP.REF19NM, COMTYPEGP.REF20NM, COMTYPEGP.REMARK
    FROM COMTYPEGP
    WHERE (COMTYPEGP.GPCD LIKE CONCAT('%', $KEYWORD, '%')
      OR COMTYPEGP.GPNM LIKE CONCAT('%', $KEYWORD, '%')
      OR COMTYPEGP.SYSYN LIKE CONCAT('%', $KEYWORD, '%')
      OR COMTYPEGP.REF01NM LIKE CONCAT('%', $KEYWORD, '%')
      OR COMTYPEGP.REF02NM LIKE CONCAT('%', $KEYWORD, '%')
      OR COMTYPEGP.REF03NM LIKE CONCAT('%', $KEYWORD, '%')
      OR COMTYPEGP.REF04NM LIKE CONCAT('%', $KEYWORD, '%')
      OR COMTYPEGP.REF05NM LIKE CONCAT('%', $KEYWORD, '%')
      OR COMTYPEGP.REF06NM LIKE CONCAT('%', $KEYWORD, '%')
      OR COMTYPEGP.REF07NM LIKE CONCAT('%', $KEYWORD, '%')
      OR COMTYPEGP.REF08NM LIKE CONCAT('%', $KEYWORD, '%')
      OR COMTYPEGP.REF09NM LIKE CONCAT('%', $KEYWORD, '%')
      OR COMTYPEGP.REF10NM LIKE CONCAT('%', $KEYWORD, '%')
      OR COMTYPEGP.REF11NM LIKE CONCAT('%', $KEYWORD, '%')
      OR COMTYPEGP.REF12NM LIKE CONCAT('%', $KEYWORD, '%')
      OR COMTYPEGP.REF13NM LIKE CONCAT('%', $KEYWORD, '%')
      OR COMTYPEGP.REF14NM LIKE CONCAT('%', $KEYWORD, '%')
      OR COMTYPEGP.REF15NM LIKE CONCAT('%', $KEYWORD, '%')
      OR COMTYPEGP.REF16NM LIKE CONCAT('%', $KEYWORD, '%')
      OR COMTYPEGP.REF17NM LIKE CONCAT('%', $KEYWORD, '%')
      OR COMTYPEGP.REF18NM LIKE CONCAT('%', $KEYWORD, '%')
      OR COMTYPEGP.REF19NM LIKE CONCAT('%', $KEYWORD, '%')
      OR COMTYPEGP.REF20NM LIKE CONCAT('%', $KEYWORD, '%')
      OR COMTYPEGP.REMARK LIKE CONCAT('%', $KEYWORD, '%')
      OR COMTYPEGP.MESCOLUMN LIKE CONCAT('%', $KEYWORD, '%'));

-- * ***************************************************************************
WHEN 'ADD_COMTYPEGP' THEN

  IF $GPCD1 = '' THEN 
    CALL COMERR('공통타입이 비어있습니다.');
    LEAVE PROC;
  END IF;

  IF EXISTS ( SELECT GPCD AS GPCD1 FROM COMTYPEGP 
    WHERE GPCD = $GPCD1 
    AND GPNM = $GPNM ) THEN

    CALL COMERR('이미 추가된 공통타입입니다.');
    LEAVE PROC;

  END IF;

  INSERT INTO COMTYPEGP (
    GPCD, GPNM, SYSYN, 
    MESCOLUMN,
    REF01NM, REF02NM, 
    REF03NM, REF04NM, REF05NM, REF06NM,
    REF07NM, REF08NM, REF09NM, REF10NM,
    REF11NM, REF12NM, REF13NM, REF14NM,
    REF15NM, REF16NM, REF17NM, REF18NM,
    REF19NM, REF20NM, REMARK,
    RTIME, REMP, RPRG
    ) VALUES (
    $GPCD1, $GPNM, $SYSYN, 
    $MESCOLUMN,
    $REF01NM, $REF02NM, 
    $REF03NM, $REF04NM, $REF05NM, $REF06NM,
    $REF07NM, $REF08NM, $REF09NM, $REF10NM,
    $REF11NM, $REF12NM, $REF13NM, $REF14NM,
    $REF15NM, $REF16NM, $REF17NM, $REF18NM,
    $REF19NM, $REF20NM, $REMARK,
    CALLTIME(), CALLEMP(), CALLPRG()
    );

-- ****************************************************************************
WHEN 'DEL_COMTYPEGP' THEN

  DELETE COMTYPEGP
    FROM COMTYPEGP
    WHERE COMTYPEGP.GPCD = $GPCD1;

-- ****************************************************************************
WHEN 'UP_COMTYPEGP' THEN

  UPDATE COMTYPEGP SET  
    COMTYPEGP.GPNM = $GPNM, 
    COMTYPEGP.SYSYN = $SYSYN, 
    COMTYPEGP.MESCOLUMN = $MESCOLUMN,
    COMTYPEGP.REF01NM = $REF01NM, 
    COMTYPEGP.REF02NM = $REF02NM, 
    COMTYPEGP.REF03NM = $REF03NM, 
    COMTYPEGP.REF04NM = $REF04NM, 
    COMTYPEGP.REF05NM = $REF05NM, 
    COMTYPEGP.REF06NM = $REF06NM, 
    COMTYPEGP.REF07NM = $REF07NM, 
    COMTYPEGP.REF08NM = $REF08NM, 
    COMTYPEGP.REF09NM = $REF09NM, 
    COMTYPEGP.REF10NM = $REF10NM, 
    COMTYPEGP.REF11NM = $REF11NM, 
    COMTYPEGP.REF12NM = $REF12NM, 
    COMTYPEGP.REF13NM = $REF13NM, 
    COMTYPEGP.REF14NM = $REF14NM, 
    COMTYPEGP.REF15NM = $REF15NM, 
    COMTYPEGP.REF16NM = $REF16NM, 
    COMTYPEGP.REF17NM = $REF17NM, 
    COMTYPEGP.REF18NM = $REF18NM, 
    COMTYPEGP.REF19NM = $REF19NM, 
    COMTYPEGP.REF20NM = $REF20NM, 
    COMTYPEGP.REMARK = $REMARK,
    COMTYPEGP.MTIME = CALLTIME(),
    COMTYPEGP.MEMP = CALLEMP(),
    COMTYPEGP.MPRG = CALLPRG()    
    WHERE COMTYPEGP.GPCD = $GPCD1;

-- ****************************************************************************
END CASE;  END