-- *****************************************************************************
-- Comment: EQM1001_R04 미사용 입력값 제거 후 파라미터 재등록
-- Create:  2026-10-08  한성수
-- *****************************************************************************
-- MES_SNS2_EQM1001_R04.sql을 먼저 반영한 후 실행합니다.
START TRANSACTION;
DELETE FROM MES_SNS2.SYSTEM_PARAMETERS
WHERE SPECIFIC_SCHEMA = 'MES_SNS2'
  AND SPECIFIC_NAME = 'EQM1001_R04';

INSERT INTO MES_SNS2.SYSTEM_PARAMETERS
SELECT * FROM information_schema.PARAMETERS
WHERE SPECIFIC_SCHEMA = 'MES_SNS2'
  AND SPECIFIC_NAME = 'EQM1001_R04';
COMMIT;

-- 17건: 15번 REVCD, 16번 CALLTYPE, 17번 KEYWORD
SELECT ORDINAL_POSITION, PARAMETER_NAME, DATA_TYPE
FROM MES_SNS2.SYSTEM_PARAMETERS
WHERE SPECIFIC_SCHEMA = 'MES_SNS2'
  AND SPECIFIC_NAME = 'EQM1001_R04'
ORDER BY ORDINAL_POSITION;
