CREATE DEFINER=`root`@`%` PROCEDURE `MES_SNS2`.`EQM1001_R01`(
-- *****************************************************************************
-- Comment: 설비이력관리 
-- Create: 	2025-06-24  	생성 			이대규
-- Modify: 	2026-09-16 		마이그레이션	한성수
-- 			2026-09-16 					한성수	MSTEQM.FANO(설비코드) 컬럼 바인딩 변경 및 구분선/코드 정렬
-- 			2026-10-06 					한성수	작업자 검색·이력 누락 보완, 수리유형 등 입력값 검증 및 부품 미사용 정리
-- *****************************************************************************
  IN $SDATE            VARCHAR(10),     -- 조회 시작일자
  IN $EDATE            VARCHAR(10),     -- 조회 종료일자
  IN $EQMCD            VARCHAR(20),     -- 설비코드
  IN $EMPCD            VARCHAR(20),     -- 사원코드
  IN $EQMREPKEY        VARCHAR(20),     -- 설비수리키
  IN $PARTCD           VARCHAR(20),
  IN $REGDAY           VARCHAR(100),    -- 등록일자
  IN $REPSDAY          VARCHAR(100),    -- 발생일자
  IN $REPEDAY          VARCHAR(100),    -- 완료일자
  IN $REGTIME          VARCHAR(100),    -- 등록시간
  IN $REPSTIME         VARCHAR(100),    -- 발생시간
  IN $REPETIME         VARCHAR(100),    -- 완료시간
  IN $REPCUST          VARCHAR(100),    -- 수리업체
  IN $REPUTIME         DECIMAL(20, 8),  -- 소요일
  IN $REPAMT           DECIMAL(20, 8),  -- 수리금액
  IN $ISSUE            VARCHAR(20),     -- 수리유형
  IN $PARTQTY          DECIMAL(20, 8),  -- 부품수량
  IN $MALFUNCTION      VARCHAR(1000),   -- 고장내용
  IN $HANDLE           VARCHAR(1000),   -- 조치내용
  IN $REMARK           VARCHAR(100),    -- 비고

  IN $EMPCD_LIST       MEDIUMTEXT,
  IN $EQMREPKEY_LIST   MEDIUMTEXT,
  IN $REGDAY_LIST      MEDIUMTEXT,
  IN $REGTIME_LIST     MEDIUMTEXT,
  IN $REPSDAY_LIST     MEDIUMTEXT,
  IN $REPSTIME_LIST    MEDIUMTEXT,
  IN $REPEDAY_LIST     MEDIUMTEXT,
  IN $REPETIME_LIST    MEDIUMTEXT,
  IN $REPUTIME_LIST    MEDIUMTEXT,
  IN $EQMCD_LIST       MEDIUMTEXT,
  IN $PARTCD_LIST      MEDIUMTEXT,
  IN $PARTQTY_LIST     MEDIUMTEXT,
  IN $REPAMT_LIST      MEDIUMTEXT,
  IN $REPCUST_LIST     MEDIUMTEXT,
  IN $ISSUE_LIST       MEDIUMTEXT,
  IN $MALFUNCTION_LIST MEDIUMTEXT,
  IN $HANDLE_LIST      MEDIUMTEXT,
  IN $REMARK_LIST      MEDIUMTEXT,

-- *****************************************************************************
  IN $CALLTYPE         VARCHAR(50),
  IN $KEYWORD          VARCHAR(1000)
)
PROC: BEGIN -- @CALLEMP, @CALLPRG, @CALLHOST, @CALLIP, @CALLMAC
-- SET @DEBUGLOGYN = 'Y';
-- *****************************************************************************
  DECLARE _$EMPCD       VARCHAR(100);
  DECLARE _$EMPCD_LIST  MEDIUMTEXT;
  DECLARE _$REPSDAYTIME VARCHAR(20);
  DECLARE _$REGDAYTIME  VARCHAR(20);
  DECLARE _$REPEDAYTIME VARCHAR(20);
  DECLARE _$EQMREPKEY   VARCHAR(20);
  DECLARE _$REGDAY      VARCHAR(100);
  DECLARE _$REGTIME     VARCHAR(100);
  DECLARE _$REPSDAY     VARCHAR(100);
  DECLARE _$REPSTIME    VARCHAR(100);
  DECLARE _$REPEDAY     VARCHAR(100);
  DECLARE _$REPETIME    VARCHAR(100);
  DECLARE _$REPUTIME    DECIMAL(20, 8);
  DECLARE _$EQMCD       VARCHAR(100);
  DECLARE _$REPAMT      DECIMAL(20, 8);
  DECLARE _$REPCUST     VARCHAR(100);
  DECLARE _$ISSUE       VARCHAR(100);
  DECLARE _$MALFUNCTION VARCHAR(1000);
  DECLARE _$HANDLE      VARCHAR(1000);
  DECLARE _$REMARK      VARCHAR(1000);

CASE $CALLTYPE

-- *****************************************************************************
WHEN 'LIST_EQMREP' THEN  -- 설비이력조회
  SELECT
    EQMREP.EQMREPKEY,                    -- 설비수리키
    LEFT(EQMREP.REGTIME, 10)  AS REGDAY, -- 등록일자
    SUBSTRING(EQMREP.REGTIME, 12, 5)  AS REGTIME,-- 등록시간
    LEFT(EQMREP.REPSTIME, 10) AS REPSDAY,-- 발생일자
    SUBSTRING(EQMREP.REPSTIME, 12, 5) AS REPSTIME,-- 발생시간
    LEFT(EQMREP.REPETIME, 10) AS REPEDAY,-- 완료일자
    SUBSTRING(EQMREP.REPETIME, 12, 5) AS REPETIME,-- 완료시간
    EQMREP.REPUTIME,                     -- 소요일
    EQMREP.EQMCD,                        -- 설비코드
    MSTEQM.EQMNM,                        -- 설비명
    EQMREP.REPAMT,
    EQMREP.REPCUST,
    EQMREP.ISSUE,
    EQMREP.MALFUNCTION,
    EQMREP.HANDLE,
    EQMREP.REMARK
  FROM EQMREP
  LEFT JOIN MSTEQM ON MSTEQM.FANO = EQMREP.EQMCD
  LEFT JOIN (
    SELECT DISTINCT EQMREPKEY
    FROM EQMREP_EMP
    WHERE EMPCD = $EMPCD
  ) REPEMP ON REPEMP.EQMREPKEY = EQMREP.EQMREPKEY
  WHERE EQMREP.REGTIME BETWEEN CONCAT($SDATE, ' 00:00') AND CONCAT($EDATE, ' 23:59:59')
    AND EQMREP.EQMCD LIKE CONCAT('%', $EQMCD, '%')
    AND ($EMPCD = '' OR REPEMP.EQMREPKEY IS NOT NULL)
    AND EQMREP.EQMREPTP = 'EQM01'
  ORDER BY EQMREP.REGTIME, EQMREP.EQMREPKEY;

-- *****************************************************************************
WHEN 'LIST_EMPCD' THEN  -- 설비이력 관련 작업자 조회
  SELECT
    EQMREP_EMP.EQMREPKEY,
    EQMREP_EMP.EMPCD,
    IFNULL(MSTEMP.EMPNM, EQMREP_EMP.EMPCD) AS EMPNM
  FROM EQMREP_EMP
  LEFT JOIN MSTEMP ON MSTEMP.EMPCD = EQMREP_EMP.EMPCD
  WHERE EQMREP_EMP.EQMREPKEY = $EQMREPKEY
  ORDER BY EQMREP_EMP.EMPCD;

-- *****************************************************************************
WHEN 'ADD_EQMREP' THEN  -- 팝업창 설비이력 저장
  SET $REPEDAY = TRIM(IFNULL($REPEDAY, ''));
  SET $REPETIME = TRIM(IFNULL($REPETIME, ''));
  IF TRIM(IFNULL($EQMCD, '')) = '' THEN
    CALL COMERR('설비코드를 입력하세요.');
    LEAVE PROC;
  END IF;

  IF TRIM(IFNULL($REGDAY, '')) = '' THEN
    CALL COMERR('등록일자를 입력하세요.');
    LEAVE PROC;
  ELSE
    IF TRIM(IFNULL($REGTIME, '')) = '' THEN
      CALL COMERR('등록시간을 입력하세요.');
      LEAVE PROC;
    END IF;
  END IF;

  IF TRIM(IFNULL($REPSDAY, '')) = '' THEN
    CALL COMERR('발생일자를 입력하세요.');
    LEAVE PROC;
  ELSE
    IF TRIM(IFNULL($REPSTIME, '')) = '' THEN
      CALL COMERR('발생시간을 입력하세요.');
      LEAVE PROC;
    END IF;
  END IF;

  IF $REPEDAY <> '' AND $REPETIME = '' THEN
    CALL COMERR('완료시간을 입력하세요.');
    LEAVE PROC;
  END IF;

  IF TRIM(IFNULL($REPCUST, '')) = '' THEN
    CALL COMERR('수리업체를 입력하세요.');
    LEAVE PROC;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM COMTYPE WHERE GPCD = 'ISSUE' AND TPCD = $ISSUE) THEN
    CALL COMERR('수리유형을 선택하세요.');
    LEAVE PROC;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM MSTEQM WHERE FANO = $EQMCD) THEN
    CALL COMERR('등록된 설비를 선택하세요.');
    LEAVE PROC;
  END IF;

  IF IFNULL($EMPCD_LIST, '') = '' THEN
    CALL COMERR('작업자를 추가해주세요.');
    LEAVE PROC;
  END IF;
  SET _$EMPCD_LIST = $EMPCD_LIST;
  WHILE LENGTH(_$EMPCD_LIST) > 0 DO
    CALL COMSPLIT(_$EMPCD_LIST, _$EMPCD);
    IF NOT EXISTS (SELECT 1 FROM MSTEMP WHERE EMPCD = _$EMPCD) THEN
      CALL COMERR('등록된 작업자를 선택하세요.');
      LEAVE PROC;
    END IF;
  END WHILE;

  IF CHAR_LENGTH($REPCUST) > 100 OR CHAR_LENGTH($MALFUNCTION) > 100
    OR CHAR_LENGTH($HANDLE) > 100 OR CHAR_LENGTH($REMARK) > 100 THEN
    CALL COMERR('수리업체, 고장원인, 처리내용, 비고는 각각 100자 이내로 입력하세요.');
    LEAVE PROC;
  END IF;

  SET _$REGDAYTIME = CONCAT($REGDAY, ' ', $REGTIME);
  SET _$REPSDAYTIME = CONCAT($REPSDAY, ' ', $REPSTIME);
  SET _$REPEDAYTIME = CASE WHEN $REPEDAY = '' THEN '' ELSE CONCAT($REPEDAY, ' ', $REPETIME) END;

  IF $REGTIME NOT REGEXP '^(0[0-9]|1[0-9]|2[0-3]):[0-5][0-9]$'
    OR $REPSTIME NOT REGEXP '^(0[0-9]|1[0-9]|2[0-3]):[0-5][0-9]$'
    OR $REGDAY NOT REGEXP '^[1-9][0-9]{3}-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])$'
    OR $REPSDAY NOT REGEXP '^[1-9][0-9]{3}-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])$'
    OR DAY(STR_TO_DATE($REGDAY, '%Y-%m-%d')) > DAY(LAST_DAY(CONCAT(LEFT($REGDAY, 7), '-01')))
    OR DAY(STR_TO_DATE($REPSDAY, '%Y-%m-%d')) > DAY(LAST_DAY(CONCAT(LEFT($REPSDAY, 7), '-01'))) THEN
    CALL COMERR('등록일시와 발생일시를 올바르게 입력하세요.');
    LEAVE PROC;
  END IF;

  IF _$REPEDAYTIME <> '' THEN
    IF $REPETIME NOT REGEXP '^(0[0-9]|1[0-9]|2[0-3]):[0-5][0-9]$'
      OR $REPEDAY NOT REGEXP '^[1-9][0-9]{3}-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])$'
      OR DAY(STR_TO_DATE($REPEDAY, '%Y-%m-%d')) > DAY(LAST_DAY(CONCAT(LEFT($REPEDAY, 7), '-01'))) THEN
      CALL COMERR('완료일시를 올바르게 입력하세요.');
      LEAVE PROC;
    END IF;
    IF _$REPEDAYTIME < _$REPSDAYTIME THEN
      CALL COMERR('완료일시는 발생일시 이후로 입력하세요.');
      LEAVE PROC;
    END IF;
  END IF;
  SET _$REPUTIME = CASE WHEN _$REPEDAYTIME = '' THEN 0 ELSE DATEDIFF($REPEDAY, $REPSDAY) + 1 END;

  SET $EQMREPKEY = GETKEY('EQMREPKEY');

  INSERT INTO EQMREP (
    EQMREPKEY, EQMCD, EQMREPTP,
    REGTIME, REPSTIME, REPETIME, REPUTIME,
    REPAMT, REPCUST, EMPCD,
    HANDLE, MALFUNCTION, ISSUE, REMARK,
    RTIME, REMP, RPRG
  ) VALUES (
    $EQMREPKEY, $EQMCD, 'EQM01',
    _$REGDAYTIME, _$REPSDAYTIME, _$REPEDAYTIME, _$REPUTIME,
    $REPAMT, $REPCUST, CALLEMP(),
    $HANDLE, $MALFUNCTION, $ISSUE, $REMARK,
    CALLTIME(), CALLEMP(), CALLPRG()
  );

  WHILE LENGTH($EMPCD_LIST) > 0 DO
    CALL COMSPLIT($EMPCD_LIST, _$EMPCD);

    INSERT INTO EQMREP_EMP (
      EQMREPKEY, EMPCD,
      RTIME, REMP, RPRG
    ) VALUES (
      $EQMREPKEY, _$EMPCD,
      CALLTIME(), CALLEMP(), CALLPRG()
    );
  END WHILE;

-- *****************************************************************************
WHEN 'SAVE_EQMREP' THEN  -- 수정 후 저장
  WHILE LENGTH($EQMREPKEY_LIST) > 0 DO
    CALL COMSPLIT($EQMREPKEY_LIST, _$EQMREPKEY);
    CALL COMSPLIT($REGDAY_LIST, _$REGDAY);
    CALL COMSPLIT($REGTIME_LIST, _$REGTIME);
    CALL COMSPLIT($REPSDAY_LIST, _$REPSDAY);
    CALL COMSPLIT($REPSTIME_LIST, _$REPSTIME);
    CALL COMSPLIT($REPEDAY_LIST, _$REPEDAY);
    CALL COMSPLIT($REPETIME_LIST, _$REPETIME);
    CALL COMSPLIT($REPUTIME_LIST, _$REPUTIME);
    CALL COMSPLIT($EQMCD_LIST, _$EQMCD);
    CALL COMSPLIT($REPAMT_LIST, _$REPAMT);
    CALL COMSPLIT($REPCUST_LIST, _$REPCUST);
    CALL COMSPLIT($ISSUE_LIST, _$ISSUE);
    CALL COMSPLIT($MALFUNCTION_LIST, _$MALFUNCTION);
    CALL COMSPLIT($HANDLE_LIST, _$HANDLE);
    CALL COMSPLIT($REMARK_LIST, _$REMARK);
    SET _$REPEDAY = TRIM(IFNULL(_$REPEDAY, ''));
    SET _$REPETIME = TRIM(IFNULL(_$REPETIME, ''));

    IF TRIM(IFNULL(_$REGDAY, '')) = '' THEN
      CALL COMERR('등록일자를 입력하세요.');
      LEAVE PROC;
    END IF;

    IF TRIM(IFNULL(_$REGTIME, '')) = '' THEN
      CALL COMERR('등록일시를 입력하세요.');
      LEAVE PROC;
    END IF;

    IF TRIM(IFNULL(_$REPSDAY, '')) = '' THEN
      CALL COMERR('발생일자를 입력하세요.');
      LEAVE PROC;
    END IF;

    IF TRIM(IFNULL(_$REPSTIME, '')) = '' THEN
      CALL COMERR('발생일시를 입력하세요.');
      LEAVE PROC;
    END IF;

    IF _$REPEDAY <> '' AND _$REPETIME = '' THEN
      CALL COMERR('완료일시를 입력하세요.');
      LEAVE PROC;
    END IF;

    IF TRIM(IFNULL(_$EQMCD, '')) = '' THEN
      CALL COMERR('설비를 입력하세요.');
      LEAVE PROC;
    END IF;

    IF TRIM(IFNULL(_$REPCUST, '')) = '' THEN
      CALL COMERR('수리 업체를 입력하세요.');
      LEAVE PROC;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM COMTYPE WHERE GPCD = 'ISSUE' AND TPCD = _$ISSUE) THEN
      CALL COMERR('수리유형을 선택하세요.');
      LEAVE PROC;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM EQMREP WHERE EQMREPKEY = _$EQMREPKEY AND EQMREPTP = 'EQM01') THEN
      CALL COMERR('수리이력을 다시 조회한 후 저장하세요.');
      LEAVE PROC;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM MSTEQM WHERE FANO = _$EQMCD)
      AND NOT EXISTS (SELECT 1 FROM EQMREP WHERE EQMREPKEY = _$EQMREPKEY AND EQMCD = _$EQMCD) THEN
      CALL COMERR('등록된 설비를 선택하세요.');
      LEAVE PROC;
    END IF;

    IF CHAR_LENGTH(_$REPCUST) > 100 OR CHAR_LENGTH(_$MALFUNCTION) > 100
      OR CHAR_LENGTH(_$HANDLE) > 100 OR CHAR_LENGTH(_$REMARK) > 100 THEN
      CALL COMERR('수리업체, 고장원인, 처리내용, 비고는 각각 100자 이내로 입력하세요.');
      LEAVE PROC;
    END IF;

    SET _$REGDAYTIME = CONCAT(_$REGDAY, ' ', _$REGTIME);
    SET _$REPSDAYTIME = CONCAT(_$REPSDAY, ' ', _$REPSTIME);
    SET _$REPEDAYTIME = CASE WHEN _$REPEDAY = '' THEN '' ELSE CONCAT(_$REPEDAY, ' ', _$REPETIME) END;

    IF _$REGTIME NOT REGEXP '^(0[0-9]|1[0-9]|2[0-3]):[0-5][0-9]$'
      OR _$REPSTIME NOT REGEXP '^(0[0-9]|1[0-9]|2[0-3]):[0-5][0-9]$'
      OR _$REGDAY NOT REGEXP '^[1-9][0-9]{3}-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])$'
      OR _$REPSDAY NOT REGEXP '^[1-9][0-9]{3}-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])$'
      OR DAY(STR_TO_DATE(_$REGDAY, '%Y-%m-%d')) > DAY(LAST_DAY(CONCAT(LEFT(_$REGDAY, 7), '-01')))
      OR DAY(STR_TO_DATE(_$REPSDAY, '%Y-%m-%d')) > DAY(LAST_DAY(CONCAT(LEFT(_$REPSDAY, 7), '-01'))) THEN
      CALL COMERR('등록일시와 발생일시를 올바르게 입력하세요.');
      LEAVE PROC;
    END IF;

    IF _$REPEDAYTIME <> '' THEN
      IF _$REPETIME NOT REGEXP '^(0[0-9]|1[0-9]|2[0-3]):[0-5][0-9]$'
        OR _$REPEDAY NOT REGEXP '^[1-9][0-9]{3}-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])$'
        OR DAY(STR_TO_DATE(_$REPEDAY, '%Y-%m-%d')) > DAY(LAST_DAY(CONCAT(LEFT(_$REPEDAY, 7), '-01'))) THEN
        CALL COMERR('완료일시를 올바르게 입력하세요.');
        LEAVE PROC;
      END IF;
      IF _$REPEDAYTIME < _$REPSDAYTIME THEN
        CALL COMERR('완료일시는 발생일시 이후로 입력하세요.');
        LEAVE PROC;
      END IF;
    END IF;
    SET _$REPUTIME = CASE WHEN _$REPEDAYTIME = '' THEN 0 ELSE DATEDIFF(_$REPEDAY, _$REPSDAY) + 1 END;

    UPDATE EQMREP SET
      EQMCD       = _$EQMCD,
      REGTIME     = _$REGDAYTIME,
      REPSTIME    = _$REPSDAYTIME,
      REPETIME    = _$REPEDAYTIME,
      REPUTIME    = _$REPUTIME,
      REPAMT      = _$REPAMT,
      REPCUST     = _$REPCUST,
      HANDLE      = _$HANDLE,
      MALFUNCTION = _$MALFUNCTION,
      ISSUE       = _$ISSUE,
      REMARK      = _$REMARK,
      MTIME       = CALLTIME(),
      MEMP        = CALLEMP(),
      MPRG        = CALLPRG()
    WHERE EQMREPKEY = _$EQMREPKEY AND EQMREPTP = 'EQM01';
  END WHILE;

-- *****************************************************************************
WHEN 'DELETE_EQMREP' THEN  -- 설비이력 삭제
  WHILE LENGTH($EQMREPKEY_LIST) > 0 DO
    CALL COMSPLIT($EQMREPKEY_LIST, _$EQMREPKEY);
    DELETE FROM EQMREP_EMP WHERE EQMREPKEY = _$EQMREPKEY;
    DELETE FROM EQMREP     WHERE EQMREPKEY = _$EQMREPKEY;
  END WHILE;

-- *****************************************************************************
WHEN 'SAVE_EMPCD' THEN  -- 작업자 사원 추가
  IF NOT EXISTS (SELECT 1 FROM EQMREP WHERE EQMREPKEY = $EQMREPKEY AND EQMREPTP = 'EQM01') THEN
    CALL COMERR('수리이력을 선택하세요.');
    LEAVE PROC;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM MSTEMP WHERE EMPCD = $EMPCD) THEN
    CALL COMERR('등록된 작업자를 선택하세요.');
    LEAVE PROC;
  END IF;
  IF EXISTS (SELECT 1 FROM EQMREP_EMP WHERE EQMREPKEY = $EQMREPKEY AND EMPCD = $EMPCD) THEN
    CALL COMERR('이미 추가되어 있는 사원정보입니다.');
    LEAVE PROC;
  END IF;

  INSERT INTO EQMREP_EMP (
    EQMREPKEY, EMPCD,
    RTIME, REMP, RPRG
  ) VALUES (
    $EQMREPKEY, $EMPCD,
    CALLTIME(), CALLEMP(), CALLPRG()
  );

-- *****************************************************************************
WHEN 'DELETE_EMPCD' THEN  -- 작업자 사원 행삭제
  WHILE LENGTH($EMPCD_LIST) > 0 DO
    CALL COMSPLIT($EMPCD_LIST, _$EMPCD);

    IF (SELECT COUNT(*) FROM EQMREP_EMP WHERE EQMREPKEY = $EQMREPKEY AND EMPCD <> _$EMPCD) = 0 THEN
      CALL COMERR('최소 한 명의 사원은 남아있어야 합니다.');
      LEAVE PROC;
    END IF;

    DELETE FROM EQMREP_EMP WHERE EQMREPKEY = $EQMREPKEY AND EMPCD = _$EMPCD;
  END WHILE;

-- *****************************************************************************
END CASE; 

END
