CREATE DEFINER=`root`@`%` PROCEDURE `MES_SNS2`.`EQM1001_R05`(
-- *****************************************************************************
-- Comment: 설비점검계획 승인관리
-- Create:  2026-09-22  한성수  설비그룹·설비별 정기점검 계획 승인, 반려 및 계획서 출력 데이터 조회
-- Modify: 	2026-09-23 					한성수	승인자 조회 추가
-- 			2026-09-29 					한성수	반려 시 승인자 비움 처리 및 설비별 승인자 조회 추가
-- 			2026-09-30 					한성수	리비전(REV) 이력·승인본 저장/조회 추가, 개정내용 저장 및 항목 코드명 반환
-- 			2026-10-01 					한성수	REVCD 기준 승인본 관리, 설비그룹 승인 시 소속 반려 설비 검증 추가
-- 			2026-10-02 					한성수	승인상태 필터 추가, 계획서 출력 개편(설비별 지원·제한 해제), 승인/REV 검증 처리
-- *****************************************************************************
  IN $EQMGRP     VARCHAR(50),
  IN $FANO       VARCHAR(50),
  IN $PLANTP     CHAR(1),
  IN $PLANCD     VARCHAR(50),
  IN $APRVSTT    CHAR(1),
  IN $REJREASON  VARCHAR(1000),
  IN $REVNUM     VARCHAR(20),
  IN $REMARK     VARCHAR(1000),

-- *****************************************************************************
  IN $CALLTYPE   VARCHAR(50),
  IN $KEYWORD    VARCHAR(1000)
)
PROC: BEGIN -- @CALLEMP, @CALLPRG, @CALLHOST, @CALLIP, @CALLMAC
-- *****************************************************************************
  DECLARE _$APRVSTT        CHAR(1);
  DECLARE _$REVNUM         INT;
  DECLARE _$REVCD          VARCHAR(20);
  DECLARE _$REMARK         VARCHAR(1000);
  DECLARE _$REVDATE        VARCHAR(10);
  DECLARE _$REJECT_CNT     INT DEFAULT 0;
  DECLARE _$REJECT_EQM     VARCHAR(1000);
  DECLARE _$PLANTP         CHAR(1);
  DECLARE _$PLANCD         VARCHAR(50);

CASE $CALLTYPE

-- *****************************************************************************
WHEN 'LIST_PLAN' THEN -- 점검계획 목록 조회

  IF $PLANTP = 'G' THEN
    SELECT
      'G' AS PLANTP,
      '설비그룹' AS PLANTPNM,
      MSTEQM.EQMGUBUN AS PLANCD,
      COMTYPE.TPNM AS PLANNM,
      COUNT(DISTINCT CHKPLANEQM.CHKKNDCD) AS PLANITEMCNT,
      COALESCE(CONCAT('REV.', PLAN_REV.REVNUM), '') AS REVNM,
      COALESCE(PLAN_REV.REMARK, '') AS REMARK,
      CASE CHKPLANEQM_APRV.APRVSTT
        WHEN 'A' THEN '승인'
        WHEN 'R' THEN '반려'
        ELSE '대기'
      END AS APRVSTTNM,
      CASE WHEN CHKPLANEQM_APRV.APRVSTT = 'A' THEN COALESCE(CHKPLANEQM_APRV.APRVEMP, '') ELSE '' END AS APRVEMP,
      COALESCE(CHKPLANEQM_APRV.REQTIME, '') AS REQTIME,
      COALESCE(CHKPLANEQM_APRV.APRVTIME, '') AS APRVTIME,
      COALESCE(CHKPLANEQM_APRV.REJREASON, '') AS REJREASON,
      COALESCE(CHKPLANEQM_APRV.APRVSTT, '') AS APRVSTT
    FROM MSTEQM
    INNER JOIN CHKPLANEQM
      ON CHKPLANEQM.EQMCD = MSTEQM.FANO
     AND CHKPLANEQM.CHKTP = '02'
     AND CHKPLANEQM.USEYN = 'Y'
    INNER JOIN COMTYPE
      ON COMTYPE.GPCD = 'FM116'
     AND COMTYPE.TPCD = MSTEQM.EQMGUBUN
    LEFT JOIN CHKPLANEQM_APRV
      ON CHKPLANEQM_APRV.PLANTP = 'G'
     AND CHKPLANEQM_APRV.PLANCD = MSTEQM.EQMGUBUN
    -- 최신 리비전 (진행 중인 리비전이 있으면 그 리비전)
    LEFT JOIN (
      SELECT MSTEQMREV_HEADER.PLANCD, MAX(MSTEQMREV_HEADER.REVNUM) AS REVNUM
      FROM MSTEQMREV_HEADER
      WHERE MSTEQMREV_HEADER.PLANTP = 'G'
      GROUP BY MSTEQMREV_HEADER.PLANCD
    ) LAST_REV
      ON LAST_REV.PLANCD = MSTEQM.EQMGUBUN
    LEFT JOIN MSTEQMREV_HEADER PLAN_REV
      ON PLAN_REV.PLANTP = 'G'
     AND PLAN_REV.PLANCD = LAST_REV.PLANCD
     AND PLAN_REV.REVNUM = LAST_REV.REVNUM
    WHERE MSTEQM.USEYN = 'Y'
      AND MSTEQM.EQMGUBUN <> ''
      AND ($EQMGRP IS NULL OR $EQMGRP = '' OR MSTEQM.EQMGUBUN = $EQMGRP)
      -- 승인상태 필터 (W: 대기 = 승인·반려가 아닌 상태)
      AND (COALESCE($APRVSTT, '') = ''
        OR ($APRVSTT = 'W' AND COALESCE(CHKPLANEQM_APRV.APRVSTT, '') NOT IN ('A', 'R'))
        OR CHKPLANEQM_APRV.APRVSTT = $APRVSTT)
    GROUP BY MSTEQM.EQMGUBUN, COMTYPE.TPNM, PLAN_REV.REVNUM, PLAN_REV.REMARK, CHKPLANEQM_APRV.APRVEMP, CHKPLANEQM_APRV.APRVSTT, CHKPLANEQM_APRV.REJREASON, CHKPLANEQM_APRV.REQTIME, CHKPLANEQM_APRV.APRVTIME
    ORDER BY MSTEQM.EQMGUBUN;

  ELSEIF $PLANTP = 'E' THEN
    SELECT
      'E' AS PLANTP,
      '설비별' AS PLANTPNM,
      MSTEQM.FANO AS PLANCD,
      MSTEQM.EQMNM AS PLANNM,
      COUNT(DISTINCT CHKPLANEQM.CHKKNDCD) AS PLANITEMCNT,
      COALESCE(CONCAT('REV.', PLAN_REV.REVNUM), '') AS REVNM,
      COALESCE(PLAN_REV.REMARK, '') AS REMARK,
      CASE CHKPLANEQM_APRV.APRVSTT
        WHEN 'A' THEN '승인'
        WHEN 'R' THEN '반려'
        ELSE '대기'
      END AS APRVSTTNM,
      CASE WHEN CHKPLANEQM_APRV.APRVSTT = 'A' THEN COALESCE(CHKPLANEQM_APRV.APRVEMP, '') ELSE '' END AS APRVEMP,
      COALESCE(CHKPLANEQM_APRV.REQTIME, '') AS REQTIME,
      COALESCE(CHKPLANEQM_APRV.APRVTIME, '') AS APRVTIME,
      COALESCE(CHKPLANEQM_APRV.REJREASON, '') AS REJREASON,
      COALESCE(CHKPLANEQM_APRV.APRVSTT, '') AS APRVSTT
    FROM MSTEQM
    INNER JOIN CHKPLANEQM
      ON CHKPLANEQM.EQMCD = MSTEQM.FANO
     AND CHKPLANEQM.CHKTP = '02'
     AND CHKPLANEQM.USEYN = 'Y'
    LEFT JOIN CHKPLANEQM_APRV
      ON CHKPLANEQM_APRV.PLANTP = 'E'
     AND CHKPLANEQM_APRV.PLANCD = MSTEQM.FANO
    -- 최신 리비전 (진행 중인 리비전이 있으면 그 리비전)
    LEFT JOIN (
      SELECT MSTEQMREV_HEADER.PLANCD, MAX(MSTEQMREV_HEADER.REVNUM) AS REVNUM
      FROM MSTEQMREV_HEADER
      WHERE MSTEQMREV_HEADER.PLANTP = 'E'
      GROUP BY MSTEQMREV_HEADER.PLANCD
    ) LAST_REV
      ON LAST_REV.PLANCD = MSTEQM.FANO
    LEFT JOIN MSTEQMREV_HEADER PLAN_REV
      ON PLAN_REV.PLANTP = 'E'
     AND PLAN_REV.PLANCD = LAST_REV.PLANCD
     AND PLAN_REV.REVNUM = LAST_REV.REVNUM
    WHERE MSTEQM.USEYN = 'Y'
      AND ($FANO IS NULL OR $FANO = '' OR MSTEQM.FANO LIKE CONCAT('%', $FANO, '%') OR MSTEQM.EQMNM LIKE CONCAT('%', $FANO, '%'))
      -- 승인상태 필터 (W: 대기 = 승인·반려가 아닌 상태)
      AND (COALESCE($APRVSTT, '') = ''
        OR ($APRVSTT = 'W' AND COALESCE(CHKPLANEQM_APRV.APRVSTT, '') NOT IN ('A', 'R'))
        OR CHKPLANEQM_APRV.APRVSTT = $APRVSTT)
    GROUP BY MSTEQM.FANO, MSTEQM.EQMNM, PLAN_REV.REVNUM, PLAN_REV.REMARK, CHKPLANEQM_APRV.APRVEMP, CHKPLANEQM_APRV.APRVSTT, CHKPLANEQM_APRV.REJREASON, CHKPLANEQM_APRV.REQTIME, CHKPLANEQM_APRV.APRVTIME
    ORDER BY MSTEQM.FANO;

  ELSE
    CALL COMERR('점검계획 구분이 올바르지 않습니다.');
    LEAVE PROC;
  END IF;
-- *****************************************************************************
WHEN 'REQUEST_PLAN' THEN -- 점검계획 승인 요청(상태 초기화, 진행 중 리비전 생성)
  IF $PLANTP NOT IN ('G', 'E') OR $PLANCD IS NULL OR $PLANCD = '' THEN
    CALL COMERR('승인 요청 대상이 올바르지 않습니다.');
    LEAVE PROC;
  END IF;

  DELETE FROM CHKPLANEQM_APRV
  WHERE PLANTP = $PLANTP
    AND PLANCD = $PLANCD;

  IF $PLANTP = 'G' THEN
    DELETE CHKPLANEQM_APRV
    FROM CHKPLANEQM_APRV
    INNER JOIN MSTEQM
      ON MSTEQM.FANO = CHKPLANEQM_APRV.PLANCD
    WHERE CHKPLANEQM_APRV.PLANTP = 'E'
      AND MSTEQM.EQMGUBUN = $PLANCD
      AND MSTEQM.USEYN = 'Y';
  ELSE
    -- 설비를 수정하면 소속 설비그룹 계획서도 대기
    DELETE CHKPLANEQM_APRV
    FROM CHKPLANEQM_APRV
    INNER JOIN MSTEQM
      ON MSTEQM.EQMGUBUN = CHKPLANEQM_APRV.PLANCD
    WHERE CHKPLANEQM_APRV.PLANTP = 'G'
      AND MSTEQM.FANO = $PLANCD;
  END IF;

  -- 수정 대상과 연동 대상(설비그룹이면 소속 설비, 설비면 소속 설비그룹)의 반려·대기 리비전은 같은 번호로 다시 대기
  UPDATE MSTEQMREV_HEADER
  INNER JOIN (
    SELECT $PLANTP AS PLANTP, $PLANCD AS PLANCD
    UNION ALL
    SELECT 'E', MSTEQM.FANO FROM MSTEQM WHERE $PLANTP = 'G' AND MSTEQM.EQMGUBUN = $PLANCD AND MSTEQM.USEYN = 'Y'
    UNION ALL
    SELECT 'G', MSTEQM.EQMGUBUN FROM MSTEQM WHERE $PLANTP = 'E' AND MSTEQM.FANO = $PLANCD AND MSTEQM.EQMGUBUN <> ''
  ) PLAN_KEY
    ON PLAN_KEY.PLANTP = MSTEQMREV_HEADER.PLANTP
   AND PLAN_KEY.PLANCD = MSTEQMREV_HEADER.PLANCD
  SET
    MSTEQMREV_HEADER.APRVSTT = '',
    MSTEQMREV_HEADER.REQTIME = CALLTIME(),
    MSTEQMREV_HEADER.REQEMP  = CALLEMP(),
    MSTEQMREV_HEADER.REQPRG  = CALLPRG(),
    MSTEQMREV_HEADER.MTIME   = CALLTIME(),
    MSTEQMREV_HEADER.MEMP    = CALLEMP(),
    MSTEQMREV_HEADER.MPRG    = CALLPRG()
  WHERE MSTEQMREV_HEADER.APRVSTT <> 'A';

  -- 마지막 리비전이 승인이거나 없으면 다음 번호로 대기 리비전 생성 (처음은 0: 제정)
  INSERT INTO MSTEQMREV_HEADER (
    REVCD, PLANTP, PLANCD, REVNUM, APRVSTT,
    REQTIME, REQEMP, REQPRG,
    RTIME, REMP, RPRG
  )
  SELECT
    GETKEY('REVCD'), PLAN_KEY.PLANTP, PLAN_KEY.PLANCD, COALESCE(LAST_REV.REVNUM + 1, 0), '',
    CALLTIME(), CALLEMP(), CALLPRG(),
    CALLTIME(), CALLEMP(), CALLPRG()
  FROM (
    SELECT $PLANTP AS PLANTP, $PLANCD AS PLANCD
    UNION ALL
    SELECT 'E', MSTEQM.FANO FROM MSTEQM WHERE $PLANTP = 'G' AND MSTEQM.EQMGUBUN = $PLANCD AND MSTEQM.USEYN = 'Y'
    UNION ALL
    SELECT 'G', MSTEQM.EQMGUBUN FROM MSTEQM WHERE $PLANTP = 'E' AND MSTEQM.FANO = $PLANCD AND MSTEQM.EQMGUBUN <> ''
  ) PLAN_KEY
  LEFT JOIN (
    SELECT MSTEQMREV_HEADER.PLANTP, MSTEQMREV_HEADER.PLANCD, MAX(MSTEQMREV_HEADER.REVNUM) AS REVNUM
    FROM MSTEQMREV_HEADER
    GROUP BY MSTEQMREV_HEADER.PLANTP, MSTEQMREV_HEADER.PLANCD
  ) LAST_REV
    ON LAST_REV.PLANTP = PLAN_KEY.PLANTP
   AND LAST_REV.PLANCD = PLAN_KEY.PLANCD
  LEFT JOIN MSTEQMREV_HEADER LAST_ROW
    ON LAST_ROW.PLANTP = LAST_REV.PLANTP
   AND LAST_ROW.PLANCD = LAST_REV.PLANCD
   AND LAST_ROW.REVNUM = LAST_REV.REVNUM
  WHERE LAST_ROW.APRVSTT IS NULL
     OR LAST_ROW.APRVSTT = 'A';

-- *****************************************************************************
WHEN 'SAVE_PLAN_STATUS' THEN -- 점검계획 승인/반려 상태 저장
  IF COALESCE($PLANCD, '') = '' THEN
    CALL COMERR('승인·반려할 점검계획을 선택해주세요.');
    LEAVE PROC;
  END IF;

  IF $PLANTP NOT IN ('G', 'E') OR $PLANCD IS NULL OR $PLANCD = '' THEN
    CALL COMERR('승인 대상이 올바르지 않습니다.');
    LEAVE PROC;
  END IF;

  IF $APRVSTT IS NULL OR $APRVSTT NOT IN ('A', 'R') THEN
    CALL COMERR('승인 상태가 올바르지 않습니다.');
    LEAVE PROC;
  END IF;

  IF $APRVSTT = 'R' AND ($REJREASON IS NULL OR $REJREASON = '') THEN
    CALL COMERR('반려 사유를 입력해주세요.');
    LEAVE PROC;
  END IF;

  SELECT MSTEQMREV_HEADER.REVCD, MSTEQMREV_HEADER.REVNUM, MSTEQMREV_HEADER.REMARK
    INTO _$REVCD, _$REVNUM, _$REMARK
  FROM MSTEQMREV_HEADER
  WHERE MSTEQMREV_HEADER.PLANTP = $PLANTP
    AND MSTEQMREV_HEADER.PLANCD = $PLANCD
    AND MSTEQMREV_HEADER.APRVSTT <> 'A'
  LIMIT 1;

  IF _$REVNUM IS NULL THEN
    CALL COMERR('진행 중인 개정이 없습니다. 점검계획을 수정한 뒤 승인·반려해주세요.');
    LEAVE PROC;
  END IF;

  IF $APRVSTT = 'A' AND COALESCE(_$REMARK, '') = '' THEN
    CALL COMERR('개정내용이 없는 REV는 승인할 수 없습니다. 개정내용을 입력해주세요.');
    LEAVE PROC;
  END IF;

  -- 설비그룹 승인 시 반려된 소속 설비가 있으면 승인 불가 (반려 설비를 수정하거나 설비별로 승인한 뒤 그룹 승인)
  IF $PLANTP = 'G' AND $APRVSTT = 'A' THEN
    SELECT COUNT(*),
           SUBSTRING_INDEX(GROUP_CONCAT(MSTEQM.FANO ORDER BY MSTEQM.FANO SEPARATOR ', '), ', ', 5)
      INTO _$REJECT_CNT, _$REJECT_EQM
    FROM MSTEQM
    INNER JOIN MSTEQMREV_HEADER EQM_REV
      ON EQM_REV.PLANTP = 'E'
     AND EQM_REV.PLANCD = MSTEQM.FANO
     AND EQM_REV.APRVSTT = 'R'
    WHERE MSTEQM.EQMGUBUN = $PLANCD
      AND MSTEQM.USEYN = 'Y';

    IF _$REJECT_CNT > 0 THEN
      CALL COMERR(CONCAT('반려된 설비가 있어 설비그룹을 승인할 수 없습니다. [', _$REJECT_EQM,
                         CASE WHEN _$REJECT_CNT > 5 THEN CONCAT(' 외 ', _$REJECT_CNT - 5, '대') ELSE '' END,
                         '] 해당 설비의 점검계획을 수정하거나 설비별로 승인한 뒤 다시 승인해주세요.'));
      LEAVE PROC;
    END IF;
  END IF;

  IF $APRVSTT = 'A' THEN
    -- 설비 승인본 (선택 설비, 설비그룹이면 진행 중인 소속 설비)
    INSERT INTO MSTEQMREV_DETAIL (
      REVCD, PLANTP, PLANCD, REVNUM, EQMCD, CHKKNDCD,
      CHKCYCLE, SORTNO, CHKKNDNM, CHKLOC, CHKMTH, CHKVALTP, REMARK,
      RTIME, REMP, RPRG
    )
    SELECT
      EQM_REV.REVCD, EQM_REV.PLANTP, EQM_REV.PLANCD, EQM_REV.REVNUM, CHKPLANEQM.EQMCD, CHKPLANEQM.CHKKNDCD,
      CHKPLANEQM.CHKCYCLE, CHKPLANEQM.SORTNO, MSTCHKKND.CHKKNDNM, MSTCHKKND.CHKLOC, MSTCHKKND.CHKMTH, MSTCHKKND.CHKVALTP, CHKPLANEQM.REMARK,
      CALLTIME(), CALLEMP(), CALLPRG()
    FROM MSTEQM
    INNER JOIN MSTEQMREV_HEADER EQM_REV
      ON EQM_REV.PLANTP = 'E'
     AND EQM_REV.PLANCD = MSTEQM.FANO
     AND EQM_REV.APRVSTT <> 'A'
    INNER JOIN CHKPLANEQM
      ON CHKPLANEQM.EQMCD = MSTEQM.FANO
     AND CHKPLANEQM.CHKTP = '02'
     AND CHKPLANEQM.USEYN = 'Y'
    INNER JOIN MSTCHKKND
      ON MSTCHKKND.CHKKNDCD = CHKPLANEQM.CHKKNDCD
    WHERE MSTEQM.USEYN = 'Y'
      AND (($PLANTP = 'E' AND MSTEQM.FANO = $PLANCD)
        OR ($PLANTP = 'G' AND MSTEQM.EQMGUBUN = $PLANCD));

    -- 설비그룹 승인본 (소속 설비 전체 항목을 점검항목 단위로)
    IF $PLANTP = 'G' THEN
      INSERT INTO MSTEQMREV_DETAIL (
        REVCD, PLANTP, PLANCD, REVNUM, EQMCD, CHKKNDCD,
        CHKCYCLE, SORTNO, CHKKNDNM, CHKLOC, CHKMTH, CHKVALTP, REMARK,
        RTIME, REMP, RPRG
      )
      SELECT
        _$REVCD, 'G', $PLANCD, _$REVNUM, '', CHKPLANEQM.CHKKNDCD,
        MIN(CHKPLANEQM.CHKCYCLE), MIN(CHKPLANEQM.SORTNO), MSTCHKKND.CHKKNDNM, MSTCHKKND.CHKLOC, MSTCHKKND.CHKMTH, MSTCHKKND.CHKVALTP, MAX(CHKPLANEQM.REMARK),
        CALLTIME(), CALLEMP(), CALLPRG()
      FROM MSTEQM
      INNER JOIN CHKPLANEQM
        ON CHKPLANEQM.EQMCD = MSTEQM.FANO
       AND CHKPLANEQM.CHKTP = '02'
       AND CHKPLANEQM.USEYN = 'Y'
      INNER JOIN MSTCHKKND
        ON MSTCHKKND.CHKKNDCD = CHKPLANEQM.CHKKNDCD
      WHERE MSTEQM.EQMGUBUN = $PLANCD
        AND MSTEQM.USEYN = 'Y'
      GROUP BY CHKPLANEQM.CHKKNDCD, MSTCHKKND.CHKKNDNM, MSTCHKKND.CHKLOC, MSTCHKKND.CHKMTH, MSTCHKKND.CHKVALTP;
    END IF;
  END IF;

  INSERT INTO CHKPLANEQM_APRV (
    PLANTP, PLANCD, APRVSTT,
    REQTIME, REQEMP, REQPRG,
    APRVTIME, APRVEMP, APRVPRG, REJREASON,
    RTIME, REMP, RPRG
  ) VALUES (
    $PLANTP, $PLANCD, $APRVSTT,
    CALLTIME(), CALLEMP(), CALLPRG(),
    CALLTIME(),
    CASE WHEN $APRVSTT = 'A' THEN CALLEMP() ELSE '' END,
    CALLPRG(),
    CASE WHEN $APRVSTT = 'R' THEN $REJREASON ELSE '' END,
    CALLTIME(), CALLEMP(), CALLPRG()
  ) ON DUPLICATE KEY UPDATE
    APRVSTT = $APRVSTT,
    APRVTIME = CALLTIME(),
    APRVEMP = CASE WHEN $APRVSTT = 'A' THEN CALLEMP() ELSE '' END,
    APRVPRG = CALLPRG(),
    REJREASON = CASE WHEN $APRVSTT = 'R' THEN $REJREASON ELSE '' END,
    MTIME = CALLTIME(),
    MEMP = CALLEMP(),
    MPRG = CALLPRG();

  IF $PLANTP = 'G' THEN
    INSERT INTO CHKPLANEQM_APRV (
      PLANTP, PLANCD, APRVSTT,
      REQTIME, REQEMP, REQPRG,
      APRVTIME, APRVEMP, APRVPRG, REJREASON,
      RTIME, REMP, RPRG
    )
    SELECT
      'E', MSTEQM.FANO, $APRVSTT,
      CALLTIME(), CALLEMP(), CALLPRG(),
      CALLTIME(),
      CASE WHEN $APRVSTT = 'A' THEN CALLEMP() ELSE '' END,
      CALLPRG(),
      CASE WHEN $APRVSTT = 'R' THEN $REJREASON ELSE '' END,
      CALLTIME(), CALLEMP(), CALLPRG()
    FROM MSTEQM
    INNER JOIN MSTEQMREV_HEADER EQM_REV
      ON EQM_REV.PLANTP = 'E'
     AND EQM_REV.PLANCD = MSTEQM.FANO
     AND EQM_REV.APRVSTT <> 'A'
    WHERE MSTEQM.EQMGUBUN = $PLANCD
      AND MSTEQM.USEYN = 'Y'
    ON DUPLICATE KEY UPDATE
      APRVSTT = $APRVSTT,
      APRVTIME = CALLTIME(),
      APRVEMP = CASE WHEN $APRVSTT = 'A' THEN CALLEMP() ELSE '' END,
      APRVPRG = CALLPRG(),
      REJREASON = CASE WHEN $APRVSTT = 'R' THEN $REJREASON ELSE '' END,
      MTIME = CALLTIME(),
      MEMP = CALLEMP(),
      MPRG = CALLPRG();
  END IF;

  -- 진행 중 리비전 확정 (설비그룹이면 진행 중인 소속 설비 리비전도 함께, 빈 개정내용은 선택 대상 내용으로)
  UPDATE MSTEQMREV_HEADER
  LEFT JOIN MSTEQM
    ON MSTEQMREV_HEADER.PLANTP = 'E'
   AND MSTEQM.FANO = MSTEQMREV_HEADER.PLANCD
  SET
    MSTEQMREV_HEADER.APRVSTT   = $APRVSTT,
    MSTEQMREV_HEADER.REMARK    = CASE WHEN $APRVSTT = 'A' AND MSTEQMREV_HEADER.REMARK = '' THEN _$REMARK ELSE MSTEQMREV_HEADER.REMARK END,
    MSTEQMREV_HEADER.APRVTIME  = CALLTIME(),
    MSTEQMREV_HEADER.APRVEMP   = CASE WHEN $APRVSTT = 'A' THEN CALLEMP() ELSE '' END,
    MSTEQMREV_HEADER.APRVPRG   = CALLPRG(),
    MSTEQMREV_HEADER.REJREASON = CASE WHEN $APRVSTT = 'R' THEN $REJREASON ELSE '' END,
    MSTEQMREV_HEADER.MTIME     = CALLTIME(),
    MSTEQMREV_HEADER.MEMP      = CALLEMP(),
    MSTEQMREV_HEADER.MPRG      = CALLPRG()
  WHERE MSTEQMREV_HEADER.APRVSTT <> 'A'
    AND ((MSTEQMREV_HEADER.PLANTP = $PLANTP AND MSTEQMREV_HEADER.PLANCD = $PLANCD)
      OR ($PLANTP = 'G' AND MSTEQMREV_HEADER.PLANTP = 'E' AND MSTEQM.EQMGUBUN = $PLANCD AND MSTEQM.USEYN = 'Y'));

-- *****************************************************************************
WHEN 'CALL_PLAN_RPT' THEN -- 점검계획서 출력 데이터 조회 (설비그룹·설비, 승인상태와 무관)
  SET _$PLANTP = CASE WHEN $PLANTP = 'E' THEN 'E' ELSE 'G' END;
  SET _$PLANCD = CASE WHEN _$PLANTP = 'E' THEN $FANO ELSE $EQMGRP END;

  -- 출력 리비전: 가장 최근 리비전 (승인이면 승인본, 대기·반려이거나 리비전이 없으면 현재 계획으로 출력)
  SELECT MSTEQMREV_HEADER.REVCD, MSTEQMREV_HEADER.REVNUM, MSTEQMREV_HEADER.APRVSTT,
         LEFT(CASE WHEN MSTEQMREV_HEADER.APRVSTT = 'A' THEN MSTEQMREV_HEADER.APRVTIME ELSE MSTEQMREV_HEADER.REQTIME END, 10)
    INTO _$REVCD, _$REVNUM, _$APRVSTT, _$REVDATE
  FROM MSTEQMREV_HEADER
  WHERE MSTEQMREV_HEADER.PLANTP = _$PLANTP
    AND MSTEQMREV_HEADER.PLANCD = _$PLANCD
  ORDER BY MSTEQMREV_HEADER.REVNUM DESC
  LIMIT 1;

  -- 계획서 상단 (설비그룹은 소속 설비의 설비번호·규격·라인·공정을 모아서 표시)
  SELECT
    CASE WHEN _$PLANTP = 'E' THEN MAX(MSTEQM.EQMNM) ELSE COALESCE(MAX(COMTYPE.TPNM), _$PLANCD) END AS EQMNM,
    GROUP_CONCAT(MSTEQM.FANO ORDER BY MSTEQM.FANO SEPARATOR ', ') AS EQMCD,
    COALESCE(GROUP_CONCAT(DISTINCT NULLIF(MSTEQM.EQMNM_DETAIL, '') SEPARATOR ', '), '') AS EQMSPEC,
    COALESCE(GROUP_CONCAT(DISTINCT COALESCE(NULLIF(MSTLINE.LINENM, ''), NULLIF(MSTEQM.LINECD, '')) SEPARATOR ', '), '') AS LINENM,
    COALESCE(GROUP_CONCAT(DISTINCT COALESCE(NULLIF(GPCD('FM100', MSTEQM.EQMTP), ''), NULLIF(MSTEQM.EQMTP, '')) SEPARATOR ', '), '') AS PROCESSNM,
    COALESCE(CONCAT('REV.', _$REVNUM), '') AS REVNM,
    COALESCE(_$REVDATE, '') AS REVDATE
  FROM MSTEQM
  -- 정기점검 사용 항목이 있는 설비
  INNER JOIN (
    SELECT CHKPLANEQM.EQMCD
    FROM CHKPLANEQM
    WHERE CHKPLANEQM.CHKTP = '02'
      AND CHKPLANEQM.USEYN = 'Y'
    GROUP BY CHKPLANEQM.EQMCD
  ) PLAN_EQM
    ON PLAN_EQM.EQMCD = MSTEQM.FANO
  LEFT JOIN MSTLINE
    ON MSTLINE.LINECD = MSTEQM.LINECD
  LEFT JOIN COMTYPE
    ON COMTYPE.GPCD = 'FM116'
   AND COMTYPE.TPCD = MSTEQM.EQMGUBUN
  WHERE MSTEQM.USEYN = 'Y'
    AND ((_$PLANTP = 'E' AND MSTEQM.FANO = _$PLANCD)
      OR (_$PLANTP = 'G' AND MSTEQM.EQMGUBUN = _$PLANCD))
  HAVING COUNT(*) > 0;

  -- 계획서 점검 항목
  IF _$APRVSTT = 'A' THEN
    -- 승인된 리비전: 승인본
    SELECT
      ROW_NUMBER() OVER (ORDER BY MSTEQMREV_DETAIL.SORTNO, MSTEQMREV_DETAIL.CHKKNDCD) AS NO,
      COALESCE(NULLIF(GPCD('CHKLOC', MSTEQMREV_DETAIL.CHKLOC), ''), MSTEQMREV_DETAIL.CHKLOC) AS CHKITEM,
      MSTEQMREV_DETAIL.CHKKNDNM AS CHKCONTENT,
      COALESCE(NULLIF(GPCD('CHKMTH', MSTEQMREV_DETAIL.CHKMTH), ''), MSTEQMREV_DETAIL.CHKMTH) AS CHKDEVICE,
      COALESCE(NULLIF(GPCD('CHKVALTP', MSTEQMREV_DETAIL.CHKVALTP), ''), MSTEQMREV_DETAIL.CHKVALTP) AS CHKRESULT,
      '' AS CONFIRM,
      '' AS REMARK
    FROM MSTEQMREV_DETAIL
    WHERE MSTEQMREV_DETAIL.REVCD = _$REVCD
    ORDER BY MSTEQMREV_DETAIL.SORTNO, MSTEQMREV_DETAIL.CHKKNDCD;
  ELSE
    -- 대기·반려 리비전 또는 리비전 없음: 현재 계획 (설비그룹은 점검항목 단위로 합침)
    SELECT
      ROW_NUMBER() OVER (ORDER BY PLAN_ITEM.SORTNO, PLAN_ITEM.CHKKNDCD) AS NO,
      COALESCE(NULLIF(GPCD('CHKLOC', MSTCHKKND.CHKLOC), ''), MSTCHKKND.CHKLOC) AS CHKITEM,
      MSTCHKKND.CHKKNDNM AS CHKCONTENT,
      COALESCE(NULLIF(GPCD('CHKMTH', MSTCHKKND.CHKMTH), ''), MSTCHKKND.CHKMTH) AS CHKDEVICE,
      COALESCE(NULLIF(GPCD('CHKVALTP', MSTCHKKND.CHKVALTP), ''), MSTCHKKND.CHKVALTP) AS CHKRESULT,
      '' AS CONFIRM,
      '' AS REMARK
    FROM (
      SELECT CHKPLANEQM.CHKKNDCD, MIN(CHKPLANEQM.SORTNO) AS SORTNO
      FROM CHKPLANEQM
      INNER JOIN MSTEQM
        ON MSTEQM.FANO = CHKPLANEQM.EQMCD
      WHERE CHKPLANEQM.CHKTP = '02'
        AND CHKPLANEQM.USEYN = 'Y'
        AND MSTEQM.USEYN = 'Y'
        AND ((_$PLANTP = 'E' AND MSTEQM.FANO = _$PLANCD)
          OR (_$PLANTP = 'G' AND MSTEQM.EQMGUBUN = _$PLANCD))
      GROUP BY CHKPLANEQM.CHKKNDCD
    ) PLAN_ITEM
    INNER JOIN MSTCHKKND
      ON MSTCHKKND.CHKKNDCD = PLAN_ITEM.CHKKNDCD
    ORDER BY PLAN_ITEM.SORTNO, PLAN_ITEM.CHKKNDCD;
  END IF;

  -- 개정 이력 (승인 리비전과 출력 리비전, 최근 4건)
  SELECT
    MSTEQMREV_HEADER.REVNUM,
    LEFT(CASE WHEN MSTEQMREV_HEADER.APRVSTT = 'A' THEN MSTEQMREV_HEADER.APRVTIME ELSE MSTEQMREV_HEADER.REQTIME END, 10) AS REVDATE,
    MSTEQMREV_HEADER.REMARK,
    COALESCE(REQ_EMP.EMPNM, MSTEQMREV_HEADER.REQEMP) AS REQEMPNM,
    CASE WHEN MSTEQMREV_HEADER.APRVSTT = 'A' THEN COALESCE(APRV_EMP.EMPNM, MSTEQMREV_HEADER.APRVEMP) ELSE '' END AS APRVEMPNM
  FROM MSTEQMREV_HEADER
  LEFT JOIN MSTEMP REQ_EMP
    ON REQ_EMP.EMPCD = MSTEQMREV_HEADER.REQEMP
  LEFT JOIN MSTEMP APRV_EMP
    ON APRV_EMP.EMPCD = MSTEQMREV_HEADER.APRVEMP
  WHERE MSTEQMREV_HEADER.PLANTP = _$PLANTP
    AND MSTEQMREV_HEADER.PLANCD = _$PLANCD
    AND (MSTEQMREV_HEADER.APRVSTT = 'A' OR MSTEQMREV_HEADER.REVNUM = _$REVNUM)
  ORDER BY MSTEQMREV_HEADER.REVNUM DESC
  LIMIT 4;

-- *****************************************************************************
WHEN 'LIST_PLAN_REV' THEN -- 점검계획 리비전 이력 조회
  SELECT
    CONCAT('REV.', MSTEQMREV_HEADER.REVNUM) AS REVNM,
    CASE MSTEQMREV_HEADER.APRVSTT
      WHEN 'A' THEN '승인'
      WHEN 'R' THEN '반려'
      ELSE '대기'
    END AS APRVSTTNM,
    MSTEQMREV_HEADER.REMARK,
    COALESCE(REQ_EMP.EMPNM, MSTEQMREV_HEADER.REQEMP) AS REQEMP,
    MSTEQMREV_HEADER.REQTIME,
    COALESCE(APRV_EMP.EMPNM, MSTEQMREV_HEADER.APRVEMP) AS APRVEMP,
    MSTEQMREV_HEADER.APRVTIME,
    MSTEQMREV_HEADER.REJREASON,
    MSTEQMREV_HEADER.REVNUM,
    MSTEQMREV_HEADER.APRVSTT
  FROM MSTEQMREV_HEADER
  LEFT JOIN MSTEMP REQ_EMP
    ON REQ_EMP.EMPCD = MSTEQMREV_HEADER.REQEMP
  LEFT JOIN MSTEMP APRV_EMP
    ON APRV_EMP.EMPCD = MSTEQMREV_HEADER.APRVEMP
  WHERE MSTEQMREV_HEADER.PLANTP = $PLANTP
    AND MSTEQMREV_HEADER.PLANCD = $PLANCD
  ORDER BY MSTEQMREV_HEADER.REVNUM DESC;

-- *****************************************************************************
WHEN 'LIST_PLAN_REV_ITEM' THEN -- 리비전 승인본 점검 항목 조회
  SELECT
    MSTEQMREV_DETAIL.CHKKNDCD,
    MSTEQMREV_DETAIL.CHKKNDNM,
    MSTEQMREV_DETAIL.CHKLOC,
    MSTEQMREV_DETAIL.CHKMTH,
    MSTEQMREV_DETAIL.CHKVALTP,
    COALESCE(NULLIF(GPCD('CHKLOC', MSTEQMREV_DETAIL.CHKLOC), ''), MSTEQMREV_DETAIL.CHKLOC) AS CHKLOCNM,
    COALESCE(NULLIF(GPCD('CHKMTH', MSTEQMREV_DETAIL.CHKMTH), ''), MSTEQMREV_DETAIL.CHKMTH) AS CHKMTHNM,
    COALESCE(NULLIF(GPCD('CHKVALTP', MSTEQMREV_DETAIL.CHKVALTP), ''), MSTEQMREV_DETAIL.CHKVALTP) AS CHKVALTPNM,
    MIN(MSTEQMREV_DETAIL.SORTNO) AS SORTNO,
    'Y' AS USEYN,
    MAX(MSTEQMREV_DETAIL.REMARK) AS REMARK
  FROM MSTEQMREV_HEADER ITEM_REV
  INNER JOIN MSTEQMREV_DETAIL
    ON MSTEQMREV_DETAIL.REVCD = ITEM_REV.REVCD
  WHERE ITEM_REV.PLANTP = $PLANTP
    AND ITEM_REV.PLANCD = $PLANCD
    AND ITEM_REV.REVNUM = $REVNUM
  GROUP BY MSTEQMREV_DETAIL.CHKKNDCD, MSTEQMREV_DETAIL.CHKKNDNM, MSTEQMREV_DETAIL.CHKLOC,
           MSTEQMREV_DETAIL.CHKMTH, MSTEQMREV_DETAIL.CHKVALTP
  ORDER BY MIN(MSTEQMREV_DETAIL.SORTNO);

-- *****************************************************************************
WHEN 'SAVE_PLAN_REV' THEN -- 진행 중 리비전 개정내용 저장
  IF COALESCE($PLANTP, '') NOT IN ('G', 'E') OR COALESCE($PLANCD, '') = '' OR COALESCE($REVNUM, '') NOT REGEXP '^[0-9]+$' THEN
    CALL COMERR('진행 중인 REV가 없습니다. 정기점검을 수정하면 새 REV가 생깁니다.');
    LEAVE PROC;
  END IF;

  IF NOT EXISTS (SELECT 1
                 FROM MSTEQMREV_HEADER
                 WHERE PLANTP = $PLANTP
                   AND PLANCD = $PLANCD
                   AND REVNUM = $REVNUM
                   AND APRVSTT <> 'A') THEN
    CALL COMERR('진행 중인 REV가 없습니다. 정기점검을 수정하면 새 REV가 생깁니다.');
    LEAVE PROC;
  END IF;

  UPDATE MSTEQMREV_HEADER
  SET
    REMARK = COALESCE($REMARK, ''),
    MTIME  = CALLTIME(),
    MEMP   = CALLEMP(),
    MPRG   = CALLPRG()
  WHERE PLANTP = $PLANTP
    AND PLANCD = $PLANCD
    AND REVNUM = $REVNUM;

-- *****************************************************************************
END CASE;
END
