CREATE DEFINER = 'root'@'%'
PROCEDURE MES_SNS2.DC_FIND(
  IN $GPCD VARCHAR(20), 
  IN $KEYWORD VARCHAR(1000),
  IN $REF01 VARCHAR(20), 
  IN $REF02 VARCHAR(20), 
  IN $REF03 VARCHAR(20), 
  IN $REF04 VARCHAR(20), 
  IN $REF05 VARCHAR(20),
  IN $REF06 VARCHAR(20),
  IN $REF07 VARCHAR(20),
  IN $REF08 VARCHAR(20),
  IN $REF09 VARCHAR(20),
  IN $REF10 VARCHAR(20),
  IN $LIMIT VARCHAR(20)
)
  NO SQL
PROC: BEGIN
-- *****************************************************************************  
DECLARE _$FIND_1    VARCHAR(100);
DECLARE _$FIND_2    VARCHAR(100);
DECLARE _$FIND_3    VARCHAR(100);
DECLARE _$FIND_4    VARCHAR(100);
DECLARE _$FIND_5    VARCHAR(100);

DECLARE _$GPCD VARCHAR(20);
DECLARE _$LIMIT INT;

DECLARE _$SPEC1  VARCHAR(100);  
DECLARE _$SPEC2  VARCHAR(100);  
DECLARE _$SPEC3  VARCHAR(100);   
DECLARE _$SPEC4  VARCHAR(100);   
DECLARE _$SPEC5  VARCHAR(100);   

SET _$SPEC1 = SUBSTRING_INDEX(SUBSTRING_INDEX($KEYWORD, ' ', 1), ' ', -1);
SET _$SPEC2 = SUBSTRING_INDEX(SUBSTRING_INDEX($KEYWORD, ' ', 2), ' ', -1);
SET _$SPEC3 = SUBSTRING_INDEX(SUBSTRING_INDEX($KEYWORD, ' ', 3), ' ', -1);
SET _$SPEC4 = SUBSTRING_INDEX(SUBSTRING_INDEX($KEYWORD, ' ', 4), ' ', -1);
SET _$SPEC5 = SUBSTRING_INDEX(SUBSTRING_INDEX($KEYWORD, ' ', 5), ' ', -1);

SET _$GPCD = REPLACE(REPLACE(REPLACE($GPCD, '_HEAD', ''), '_LIST', ''), '_INFO', '');
SET _$LIMIT = 100;

IF $LIMIT <> '' THEN 
  SET _$LIMIT = CAST($LIMIT AS INT);
END IF;

IF EXISTS (SELECT GPCD FROM COMTYPEGP WHERE GPCD = _$GPCD AND GPCD <> 'DEPTP' ) THEN 
    
  IF RIGHT($GPCD, 5) = '_HEAD' THEN

    SELECT '유형코드' AS CODE, '유형명' AS NAME;
    SELECT 100 AS CODE, 200 AS NAME;
    SELECT 1 AS EVENTLENGTH;

  ELSEIF RIGHT($GPCD, 5) = '_LIST' THEN

    SELECT COMTYPE.TPCD AS CODE, COMTYPE.TPNM AS NAME
      FROM COMTYPE
      WHERE COMTYPE.GPCD = _$GPCD
      
      AND COMTYPE.USEYN = 'Y'
      AND COMTYPE.REF01 LIKE CONCAT('%', $REF01, '%')
      AND COMTYPE.REF02 LIKE CONCAT('%', $REF02, '%')
      AND COMTYPE.REF03 LIKE CONCAT('%', $REF03, '%')
      AND COMTYPE.REF04 LIKE CONCAT('%', $REF04, '%')
      AND COMTYPE.REF05 LIKE CONCAT('%', $REF05, '%')
      AND (
        COMTYPE.TPCD LIKE CONCAT('%', $KEYWORD, '%')
        OR COMTYPE.TPNM LIKE CONCAT('%', $KEYWORD, '%')
      )
      ORDER BY COMTYPE.SORTNO;

  ELSEIF RIGHT($GPCD, 5) = '_INFO' THEN

    SELECT COMTYPE.TPCD AS CODE, COMTYPE.TPNM AS NAME
      FROM COMTYPE
      WHERE COMTYPE.GPCD = _$GPCD 
      AND COMTYPE.USEYN = 'Y'
      AND COMTYPE.REF01 LIKE CONCAT('%', $REF01, '%')
      AND COMTYPE.REF02 LIKE CONCAT('%', $REF02, '%')
      AND COMTYPE.REF03 LIKE CONCAT('%', $REF03, '%')
      AND COMTYPE.REF04 LIKE CONCAT('%', $REF04, '%')
      AND COMTYPE.REF05 LIKE CONCAT('%', $REF05, '%')
      AND COMTYPE.TPCD = $KEYWORD;

  END IF;

-- *****************************************************************************
   ELSEIF $GPCD = 'CUSTCD_HEAD' THEN
  
    SELECT '코드' AS CODE, '거래처명' AS NAME;
    SELECT 100 AS CODE, 200 AS NAME;

    ELSEIF $GPCD = 'CUSTCD_LIST' THEN

      WITH custitem_v AS (
        SELECT
          ITEMID, CUSTCD,
          'PUR' AS CUSTTP
        FROM MSTITEM_MMV
        WHERE EDT = ''
        GROUP BY CUSTCD, ITEMID
        UNION ALL 
        SELECT
          ITEMID, CUSTCD,
          'SAL' AS CUSTTP
        FROM MSTITEM_SDV
        WHERE EDT = ''
        GROUP BY CUSTCD, ITEMID
      )
      SELECT MSTCUST.CUSTCD AS CODE, MSTCUST.CUSTNM AS NAME
        FROM MSTCUST
        LEFT JOIN (
          SELECT CUSTCD, CUSTTP
            FROM custitem_v
            GROUP BY CUSTCD, CUSTTP 
        ) AS CUSTGB ON MSTCUST.CUSTCD = CUSTGB.CUSTCD
        WHERE IF($REF01 = 'Y', CUSTGB.CUSTTP = 'PUR', 1=1)
          AND IF($REF02 = 'Y', CUSTGB.CUSTTP = 'SAL', 1=1)
          AND (MSTCUST.CUSTCD LIKE CONCAT('%', $KEYWORD, '%')
           OR MSTCUST.CUSTNM LIKE CONCAT('%', $KEYWORD, '%'))
          AND MSTCUST.TRADEEDT = ''
          AND MSTCUST.USEYN = 'Y'
          ORDER BY MSTCUST.CUSTCD, MSTCUST.CUSTNM
          LIMIT _$LIMIT;

    ELSEIF $GPCD = 'CUSTCD_INFO' THEN
  
       SELECT CUSTCD AS CODE, CUSTNM AS NAME
        FROM MSTCUST
        WHERE A.CUSTCD = $KEYWORD;

-- *****************************************************************************
ELSEIF $GPCD = 'CUSTCD2_HEAD' THEN
  
    SELECT '거래처코드' AS CODE, '거래처명' AS NAME, '영문명' AS REF01, '담당자' AS REF04, '전화번호' AS REF05, 'E-MAIL' AS REF06;
    SELECT 100 AS CODE, 200 AS NAME, 100 AS REF01, 100 AS REF04, 100 AS REF05, 100 AS REF06;

  ELSEIF $GPCD = 'CUSTCD2_LIST' THEN

    IF $REF03 <> '' THEN
    
     SELECT MSTCUST.CUSTCD AS CODE, 
            MSTCUST.CUSTNM AS NAME, 
            MSTCUST.CUSTNMEN AS REF01,
            MSTCUST.CHARGENM AS REF04,
            MSTCUST.CHARGETEL AS REF05,
            MSTCUST.CHARGEMAIL AS REF06
      FROM MSTCUST
      WHERE MSTCUST.CUSTTP LIKE CONCAT('%', $REF01, '%')
        AND MSTCUST.PURYN  LIKE CONCAT('%', $REF02, '%')
        AND MSTCUST.SALEYN = 'Y'
        AND (MSTCUST.CUSTCD LIKE CONCAT('%', $KEYWORD, '%')
          OR MSTCUST.CUSTNM LIKE CONCAT('%', $KEYWORD, '%')
          OR MSTCUST.CUSTNMEN LIKE CONCAT('%', $KEYWORD, '%')
        )
      LIMIT _$LIMIT;
  
    ELSE    
    
      SELECT MSTCUST.CUSTCD AS CODE, 
             MSTCUST.CUSTNM AS NAME, 
             MSTCUST.CUSTNMEN AS REF01,
             MSTCUST.CHARGENM AS REF04,
             MSTCUST.CHARGETEL AS REF05,
             MSTCUST.CHARGEMAIL AS REF06
        FROM MSTCUST
        WHERE MSTCUST.CUSTTP LIKE CONCAT('%', $REF01, '%')
          AND MSTCUST.PURYN  LIKE CONCAT('%', $REF02, '%')
          AND (MSTCUST.CUSTCD LIKE CONCAT('%', $KEYWORD, '%')
            OR MSTCUST.CUSTNM LIKE CONCAT('%', $KEYWORD, '%')
            OR MSTCUST.CUSTNMEN LIKE CONCAT('%', $KEYWORD, '%')
          )
        
        LIMIT _$LIMIT;
    END IF;

  ELSEIF $GPCD = 'CUSTCD2_INFO' THEN
  
      SELECT MSTCUST.CUSTCD AS CODE, MSTCUST.CUSTNM AS NAME
      FROM MSTCUST
        WHERE MSTCUST.CUSTTP LIKE CONCAT('%', $REF01, '%')
        AND MSTCUST.PURYN  LIKE CONCAT('%', $REF02, '%')
        AND MSTCUST.CUSTCD = $KEYWORD;

-- *****************************************************************************
        ELSEIF $GPCD = 'CUSTCD3_HEAD' THEN
  
    SELECT '거래처코드' AS CODE, '거래처명' AS NAME, '영문명' AS REF01;
    SELECT 100 AS CODE, 200 AS NAME, 100 AS REF01;

  ELSEIF $GPCD = 'CUSTCD3_LIST' THEN

    IF $REF03 <> '' THEN
    
     SELECT MSTCUST.CUSTCD AS CODE, MSTCUST.CUSTNM AS NAME, MSTCUST.CUSTNMEN AS REF01
      FROM MSTCUST
      WHERE MSTCUST.CUSTTP LIKE CONCAT('%', $REF01, '%')
        AND (MSTCUST.CUSTCD LIKE CONCAT('%', $KEYWORD, '%')
          OR MSTCUST.CUSTNM LIKE CONCAT('%', $KEYWORD, '%')
          OR MSTCUST.CUSTNMEN LIKE CONCAT('%', $KEYWORD, '%')
        )
      ;
--       LIMIT _$LIMIT;
  
    ELSE    
      SELECT MSTCUST.CUSTCD AS CODE, MSTCUST.CUSTNM AS NAME, MSTCUST.CUSTNMEN AS REF01
        FROM MSTCUST
        WHERE MSTCUST.CUSTTP LIKE CONCAT('%', $REF01, '%')
          AND (MSTCUST.CUSTCD LIKE CONCAT('%', $KEYWORD, '%')
            OR MSTCUST.CUSTNM LIKE CONCAT('%', $KEYWORD, '%')
            OR MSTCUST.CUSTNMEN LIKE CONCAT('%', $KEYWORD, '%')
          )
        ;
--         LIMIT _$LIMIT;
    END IF;

  ELSEIF $GPCD = 'CUSTCD3_INFO' THEN

      SELECT MSTCUST.CUSTCD AS CODE, MSTCUST.CUSTNM AS NAME
      FROM MSTCUST
        WHERE MSTCUST.CUSTTP LIKE CONCAT('%', $REF01, '%')
        AND MSTCUST.CUSTCD = $KEYWORD;

-- *****************************************************************************
  ELSEIF $GPCD = 'ITEMID_HEAD' THEN
  
    SELECT '품목ID' AS CODE, '품목코드' AS NAME, '품명' AS REF01, '품목유형' AS SPEC;
    SELECT 80 AS CODE, 130 AS NAME, 250 AS REF01, 200 AS SPEC;

  ELSEIF $GPCD = 'ITEMID_LIST' THEN

    SELECT
      MSTITEM.ITEMID AS CODE,
      MSTITEM.ITEMCD AS NAME,
      MSTITEM.ITEMNM AS REF01,
      GPCD('DM100', MSTITEM.ITEMCG) AS SPEC  
      FROM MSTITEM
      WHERE MSTITEM.COMPANYCD LIKE CONCAT('%', $REF01, '%')
        AND MSTITEM.ITEMCG LIKE CONCAT('%', $REF02, '%')
        AND (MSTITEM.ITEMCD LIKE CONCAT('%', $KEYWORD, '%') 
        OR MSTITEM.ITEMNM LIKE CONCAT('%', $KEYWORD, '%')
        OR MSTITEM.ITEMSPEC LIKE CONCAT('%', $KEYWORD, '%')
        OR MSTITEM.EONO LIKE CONCAT('%', $KEYWORD, '%')
        OR MSTITEM.SPEC6 LIKE CONCAT('%', $KEYWORD, '%'))
        AND MSTITEM.ENDYN = 'N'
      LIMIT _$LIMIT; 

  ELSEIF $GPCD = 'ITEMID_INFO' THEN

    SELECT 
      MSTITEM.ITEMID AS CODE,
      MSTITEM.ITEMCD AS NAME,
      MSTITEM.ITEMNM AS REF01,
      GPCD('DM100', MSTITEM.ITEMCG) AS SPEC
      FROM MSTITEM
      WHERE MSTITEM.ITEMID = $KEYWORD;   

-- *****************************************************************************
  ELSEIF $GPCD = 'ITEMCD_HEAD' THEN

    SELECT '품목코드' AS CODE, '품명' AS NAME, '품목ID' AS REF01, '규격' AS REF02, '품목유형' AS REF03, '단위' AS REF04;
    SELECT 150 AS CODE, 250 AS NAME, 100 AS REF01, 80 AS REF02, 50 AS REF03, 50 AS REF04;
  
  ELSEIF $GPCD = 'ITEMCD_LIST' THEN
   
    SELECT 
      MSTITEM.ITEMCD AS CODE,
      MSTITEM.ITEMNM AS NAME,
      MSTITEM.ITEMID AS REF01,
      MSTITEM.ITEMSPEC AS REF02,
      GPCD('DM100', MSTITEM.ITEMCG) AS REF03,
      GPCD('ITEMUNIT', MSTITEM.ITEMUNIT) AS REF04
    FROM MSTITEM
    WHERE (     MSTITEM.ITEMID LIKE CONCAT('%', $KEYWORD, '%')   
            OR  MSTITEM.ITEMCD LIKE CONCAT('%', $KEYWORD, '%')  
          )
      AND MSTITEM.ITEMCG  LIKE CONCAT('%', $REF01, '%')   
    ORDER BY MSTITEM.ITEMCD
    LIMIT _$LIMIT;

  
  ELSEIF $GPCD = 'ITEMCD_INFO' THEN  

    SELECT 
      MSTITEM.ITEMCD AS CODE,
      MSTITEM.ITEMNM AS NAME,
      MSTITEM.ITEMID AS REF01,
      MSTITEM.ITEMSPEC AS REF02,
      GPCD('DM100', MSTITEM.ITEMCG) AS REF03,
      GPCD('ITEMUNIT', MSTITEM.ITEMUNIT) AS REF04
    FROM MSTITEM
    WHERE MSTITEM.ITEMCD = $KEYWORD
    LIMIT _$LIMIT;

-- *****************************************************************************
  ELSEIF $GPCD = 'ITEMCDMTR_HEAD' THEN  -- 원부자재 리스트 (2026-04-29 신정수)

    SELECT '품목코드' AS CODE, '품명' AS NAME, '품목유형' AS REF01, '재질' AS REF02, '두께' AS REF03, '길이' AS REF04, '폭' AS REF05, '단위' AS REF06 ;
    SELECT 100 AS CODE, 100 AS NAME, 100 AS REF01, 80 AS REF02, 50 AS REF03, 50 AS REF04, 50 AS REF05, 50 AS REF06;
  
  ELSEIF $GPCD = 'ITEMCDMTR_LIST' THEN       
    SELECT 
      MSTITEM.ITEMCD AS CODE,
      MSTITEM.ITEMNM AS NAME,
      GPCD('ITEMTP', MSTITEM.ITEMTP) AS REF01,
      GPCD('MATERIAL',MSTITEM.MATERIAL) AS REF02,
      ROUND(MSTITEM.THICK, 2) AS REF03,
      ROUND(MSTITEM.LENGTH,2) AS REF04,
      ROUND(MSTITEM.WIDTH, 2) AS REF05,
      GPCD('ITEMUNIT', MSTITEM.ITEMUNIT) AS REF06
    FROM MSTITEM
    WHERE MSTITEM.ITEMCD LIKE CONCAT('%', $KEYWORD, '%')  
      AND MSTITEM.ITEMTP IN ('10', '20')
    ORDER BY MSTITEM.ITEMTP, MSTITEM.ITEMCD  
    LIMIT _$LIMIT;   
  
  ELSEIF $GPCD = 'ITEMCDMTR_INFO' THEN  
     SELECT 
      MSTITEM.ITEMCD AS CODE,
      MSTITEM.ITEMNM AS NAME,
      MSTITEM.ITEMNUM AS REF01,
      GPCD('ITEMTP', MSTITEM.ITEMTP) AS REF02,
      GPCD('ITEMUNIT', MSTITEM.ITEMUNIT) AS REF03    
    FROM MSTITEM
    WHERE MSTITEM.ITEMCD = $KEYWORD
    ORDER BY MSTITEM.ITEMTP, MSTITEM.ITEMCD
    LIMIT _$LIMIT;

-- *****************************************************************************
  ELSEIF $GPCD = 'ITEMCDMTRLEFT_HEAD' THEN  -- 잔재품목코드 리스트 (2026-05-18 신정수)

    SELECT '품목코드' AS CODE, '품명' AS NAME, '품목유형' AS REF01, '재질' AS REF02, '두께' AS REF03, '길이' AS REF04, '폭' AS REF05, '단위' AS REF06 ;
    SELECT 100 AS CODE, 100 AS NAME, 100 AS REF01, 80 AS REF02, 50 AS REF03, 50 AS REF04, 50 AS REF05, 50 AS REF06;
  
  ELSEIF $GPCD = 'ITEMCDMTRLEFT_LIST' THEN       
    SELECT 
      MSTITEM.ITEMCD AS CODE,
      MSTITEM.ITEMNM AS NAME,
      GPCD('ITEMTP', MSTITEM.ITEMTP) AS REF01,
      GPCD('MATERIAL',MSTITEM.MATERIAL) AS REF02,
      ROUND(MSTITEM.THICK, 2) AS REF03,
      ROUND(MSTITEM.LENGTH,2) AS REF04,
      ROUND(MSTITEM.WIDTH, 2) AS REF05,
      GPCD('ITEMUNIT', MSTITEM.ITEMUNIT) AS REF06
    FROM MSTITEM
    WHERE MSTITEM.ITEMCD LIKE CONCAT('%', $KEYWORD, '%')  
      AND MSTITEM.MTRLEFT_YN = 'Y'
      AND MSTITEM.ITEMCD_PARENT LIKE CONCAT('%', $REF01, '%')  
    ORDER BY MSTITEM.ITEMTP, MSTITEM.ITEMCD  
    LIMIT _$LIMIT;   
  
  ELSEIF $GPCD = 'ITEMCDMTRLEFT_INFO' THEN  
     SELECT 
      MSTITEM.ITEMCD AS CODE,
      MSTITEM.ITEMNM AS NAME,
      MSTITEM.ITEMNUM AS REF01,
      GPCD('ITEMTP', MSTITEM.ITEMTP) AS REF02,
      GPCD('ITEMUNIT', MSTITEM.ITEMUNIT) AS REF03    
    FROM MSTITEM
    WHERE MSTITEM.ITEMCD = $KEYWORD
    ORDER BY MSTITEM.ITEMTP, MSTITEM.ITEMCD
    LIMIT _$LIMIT;

-- *****************************************************************************
  ELSEIF $GPCD = 'EMPCD_HEAD' THEN

    SELECT '사원코드' AS CODE, '성명' AS NAME, '부서' AS REF01;
    SELECT 100 AS CODE, 100 AS NAME, 100 AS REF01;
  
  ELSEIF $GPCD = 'EMPCD_LIST' THEN

    SELECT 
        ME.EMPCD AS CODE
      , ME.EMPNM AS NAME
      , IFNULL(MSTDEPT.DEPTNM, '') AS REF01
    FROM MSTEMP AS ME
    LEFT JOIN MSTDEPT
      ON MSTDEPT.DEPTCD = ME.DEPTCD
    WHERE (ME.EMPCD LIKE CONCAT('%', $KEYWORD, '%') OR
           ME.EMPNM LIKE CONCAT('%', $KEYWORD, '%'))
      AND ME.EMPTP  LIKE CONCAT('%', $REF05,   '%')
      AND EMPSTT = 'HR125100';
  
  ELSEIF $GPCD = 'EMPCD_INFO' THEN
  
    SELECT ME.EMPCD AS CODE, ME.EMPNM AS NAME
      FROM MSTEMP AS ME
      WHERE ME.EMPTP LIKE CONCAT('%', $REF05, '%')
        AND ME.EMPCD = $KEYWORD;

-- *****************************************************************************

  ELSEIF $GPCD = 'HRMEMPCD_HEAD' THEN

    SELECT '사원코드' AS CODE, '성명' AS NAME, '직위' AS REF01, '부서' AS REF02, '상태' AS REF03;
    SELECT 100 AS CODE, 100 AS NAME, 100 AS REF01, 100 AS REF02, 60 AS REF03;

  ELSEIF $GPCD = 'HRMEMPCD_LIST' THEN

    SELECT
      ME.EMPCD AS CODE, ME.EMPNM      AS NAME,
      GPCD('COLONELCY', ME.COLONELCY) AS REF01,
      GPCD('DEPTP',     ME.DEPTP)     AS REF02,
      GPCD('EMPSTT',    ME.EMPSTT)    AS REF03,
      ME.SITEYN                       AS REF10
      FROM MSTEMP AS ME
      WHERE ME.EMPTP IN ('01', '02', '03', '04')
        AND ME.FOREIGNWORKER LIKE CONCAT('%', $REF05, '%')
        AND ME.WORKCOMP LIKE CONCAT('%', $REF04, '%')
        AND ME.EMPSTT   LIKE CONCAT('%', $REF03, '%')
        AND (ME.EMPCD LIKE CONCAT('%', $KEYWORD, '%') OR
             ME.EMPNM LIKE CONCAT('%', $KEYWORD, '%') OR
             ME.ENNM  LIKE CONCAT('%', $KEYWORD, '%')
        )
        AND ME.VISIBLEYN = 'Y'
        AND CASE WHEN $REF02 = '' THEN 1 = 1
                 ELSE ME.DEPTP IN ( SELECT D5.DEPTP
                                      FROM MSTDEPT AS D5
                                      LEFT JOIN MSTDEPT AS D4 ON D5.UPDEPT = D4.DEPTP
                                      LEFT JOIN MSTDEPT AS D3 ON D4.UPDEPT = D3.DEPTP
                                      LEFT JOIN MSTDEPT AS D2 ON D3.UPDEPT = D2.DEPTP
                                      LEFT JOIN MSTDEPT AS D1 ON D2.UPDEPT = D1.DEPTP
                                      WHERE D5.DEPTP = $REF02
                                         OR ( D5.UPDEPT = $REF02 OR
                                              D4.UPDEPT = $REF02 OR
                                              D3.UPDEPT = $REF02 OR
                                              D2.UPDEPT = $REF02 OR
                                              D1.UPDEPT = $REF02 )
                                  )
              END
        AND ME.BDVCD LIKE CONCAT('%', $REF01, '%')
        -- AND ME.VISIBLEYN = 'Y'
      ORDER BY ME.EMPSTT, ME.BDVCD, ME.DEPTP = '' ASC, ME.DEPTP ASC, ME.COLONELCY = '' ASC, ME.COLONELCY ASC, ME.EMPCD;

  ELSEIF $GPCD = 'HRMEMPCD_INFO' THEN

    SELECT
      ME.EMPCD     AS CODE,   ME.EMPNM AS NAME,
      ME.COLONELCY AS REF01,  ME.DEPTP AS REF02,  ME.EMPSTT AS REF03
      FROM MSTEMP AS ME
      WHERE ME.EMPCD = $KEYWORD;

-- *****************************************************************************
  ELSEIF $GPCD = 'EMPCD_DEPTP_HEAD' THEN

  SELECT '사원코드' AS CODE, '사원명' AS NAME, '부서' AS REF02;
  SELECT 100 AS CODE, 100 AS NAME, 180 AS REF02;

  ELSEIF $GPCD = 'EMPCD_DEPTP_LIST' THEN
    
    SELECT MSTEMP.EMPCD AS CODE, MSTEMP.EMPNM AS NAME, MSTEMP.DEPTP AS REF01, GPCD('DEPTP', MSTEMP.DEPTP) AS REF02
      FROM MSTEMP
      WHERE MSTEMP.VISIBLEYN = 'Y'
        AND MSTEMP.DEPTP LIKE CONCAT('%', $REF01, '%')
        AND MSTEMP.EMPSTT <> '9'
        AND (MSTEMP.EMPCD LIKE CONCAT('%', $KEYWORD, '%')
          OR MSTEMP.EMPNM LIKE CONCAT('%', $KEYWORD, '%')
          OR MSTEMP.ENNM LIKE CONCAT('%', $KEYWORD, '%')
          OR GPCD('DEPTP',MSTEMP.DEPTP) LIKE CONCAT('%', $KEYWORD, '%'))
        LIMIT _$LIMIT;
  
  ELSEIF $GPCD = 'EMPCD_DEPTP_INFO' THEN
  
      SELECT MSTEMP.EMPCD AS CODE, MSTEMP.EMPNM AS NAME, MSTEMP.DEPTP AS REF01, GPCD('DEPTP', MSTEMP.DEPTP) AS REF02
        FROM MSTEMP
        WHERE MSTEMP.DEPTP LIKE CONCAT('%', $REF01, '%')
          AND MSTEMP.EMPSTT <> '9'
          AND MSTEMP.EMPCD = $KEYWORD;

-- *****************************************************************************
  ELSEIF $GPCD = 'MILITARYEMPCD_HEAD' THEN

    SELECT '사원코드' AS CODE, '성명' AS NAME, '부서' AS REF01, '복무상태' AS REF02;
    SELECT 80 AS CODE, 80 AS NAME, 100 AS REF01, 80 AS REF02;
    SELECT 2 AS EVENTLENGTH;

  ELSEIF $GPCD = 'MILITARYEMPCD_LIST' THEN

    SELECT
      MEHM.EMPCD AS CODE,                 MEHM.EMPNM AS NAME,
      GPCD('DEPTP', MEHM.DEPTP) AS REF01, GPCD('MILITARYSTS', MEHM.MILITARYSTS) AS REF02
      FROM (  SELECT
                ME.EMPCD,     ME.EMPNM,
                ME.BDVCD,     ME.DEPTP,
                ME.COLONELCY, IFNULL(HM.MILITARYSTS, '') AS MILITARYSTS
                FROM MSTEMP AS ME
                LEFT JOIN HRMMILITARY AS HM ON ME.EMPCD = HM.EMPCD
                WHERE ME.MILITARYSVC = 'Y'
                  AND ME.EMPTP IN ('01', '02', '03', '04')
                  AND ME.EMPSTT LIKE CONCAT('%', $REF03, '%')
                  AND ME.EMPCD LIKE CONCAT('%', $KEYWORD, '%')
                  AND CASE WHEN $REF02 = '' THEN 1 = 1
                           ELSE ME.DEPTP IN ( SELECT MD5.DEPTP
                                                FROM MSTDEPT AS MD5
                                                LEFT JOIN MSTDEPT AS MD4 ON MD5.UPDEPT = MD4.DEPTP
                                                LEFT JOIN MSTDEPT AS MD3 ON MD4.UPDEPT = MD3.DEPTP
                                                LEFT JOIN MSTDEPT AS MD2 ON MD3.UPDEPT = MD2.DEPTP
                                                LEFT JOIN MSTDEPT AS MD1 ON MD2.UPDEPT = MD1.DEPTP
                                                WHERE MD5.DEPTP = $REF02
                                                   OR ( MD5.UPDEPT = $REF02 OR
                                                        MD4.UPDEPT = $REF02 OR
                                                        MD3.UPDEPT = $REF02 OR
                                                        MD2.UPDEPT = $REF02 OR
                                                        MD1.UPDEPT = $REF02 )
                                            )
                      END
                  AND ME.BDVCD LIKE CONCAT('%', $REF01, '%')
          ) AS MEHM
      WHERE MEHM.MILITARYSTS LIKE CONCAT('%', $REF04, '%')
      ORDER BY MEHM.BDVCD, MEHM.DEPTP, MEHM.COLONELCY, MEHM.EMPCD
      LIMIT _$LIMIT;

  ELSEIF $GPCD = 'MILITARYEMPCD_INFO' THEN

    SELECT ME.EMPCD AS CODE, ME.EMPNM AS NAME
      FROM MSTEMP AS ME
      WHERE ME.EMPCD = $KEYWORD;

-- *****************************************************************************

  ELSEIF $GPCD = 'FOREIGNEMPCD_HEAD' THEN
    
    SELECT '사원코드' AS CODE, '성명' AS NAME, '부서' AS REF01;
    SELECT 80 AS CODE, 80 AS NAME, 100 AS REF01;
    SELECT 2 AS EVENTLENGTH;
        

  ELSEIF $GPCD = 'FOREIGNEMPCD_LIST' THEN

    SELECT 
      ME.EMPCD AS CODE,                   ME.EMPNM AS NAME,
      GPCD('DEPTP', ME.DEPTP) AS REF01
      FROM MSTEMP AS ME
      WHERE ME.FOREIGNWORKER = 'Y'
        AND ME.EMPTP IN ('01', '02', '03', '04')
        AND ME.EMPSTT LIKE CONCAT('%', $REF03, '%')
        AND ME.EMPCD LIKE CONCAT('%', $KEYWORD, '%')
        AND ME.DEPTP IN ( SELECT MD5.DEPTP
                                FROM MSTDEPT AS MD5
                                LEFT JOIN MSTDEPT AS MD4 ON MD5.UPDEPT = MD4.DEPTP
                                LEFT JOIN MSTDEPT AS MD3 ON MD4.UPDEPT = MD3.DEPTP
                                LEFT JOIN MSTDEPT AS MD2 ON MD3.UPDEPT = MD2.DEPTP
                                LEFT JOIN MSTDEPT AS MD1 ON MD2.UPDEPT = MD1.DEPTP
                                WHERE MD5.DEPTP = $REF02
                                   OR ( MD5.UPDEPT = $REF02 OR
                                        MD4.UPDEPT = $REF02 OR
                                        MD3.UPDEPT = $REF02 OR
                                        MD2.UPDEPT = $REF02 OR
                                        MD1.UPDEPT = $REF02 )
                        )
        AND ME.BDVCD LIKE CONCAT('%', $REF01, '%')
      ORDER BY ME.BDVCD, ME.DEPTP, ME.COLONELCY, ME.EMPCD
      LIMIT _$LIMIT;

  ELSEIF $GPCD = 'FOREIGNEMPCD_INFO' THEN
  
      SELECT ME.EMPCD AS CODE, ME.EMPNM AS NAME, ME.DEPTP AS REF01
        FROM MSTEMP AS ME
        WHERE ME.EMPCD = $KEYWORD;

-- *****************************************************************************

  ELSEIF $GPCD = 'ALLOWCD_HEAD' THEN
  
    SELECT '수당공제코드' AS CODE, '수당공제명' AS NAME;
    SELECT 80 AS CODE, 220 AS NAME;
    SELECT 2 AS EVENTLENGTH;

  ELSEIF $GPCD = 'ALLOWCD_LIST' THEN

    SELECT 
      HRMALLOWCD.ALLOWCD AS CODE, HRMALLOWCD.ALLOWNM AS NAME
      FROM HRMALLOWCD
      WHERE (HRMALLOWCD.ALLOWCD LIKE CONCAT('%', $KEYWORD, '%')
          OR HRMALLOWCD.ALLOWNM LIKE CONCAT('%', $KEYWORD, '%')
        ) 
      LIMIT _$LIMIT;
  
  ELSEIF $GPCD = 'ALLOWCD_INFO' THEN
  
    SELECT HRMALLOWCD.ALLOWCD AS CODE, HRMALLOWCD.ALLOWNM AS NAME
      FROM HRMALLOWCD
      WHERE HRMALLOWCD.ALLOWCD = $KEYWORD;
-- *****************************************************************************
  ELSEIF $GPCD = 'ALLOWCD1_HEAD' THEN
  
    SELECT '수당공제코드' AS CODE, '수당공제명' AS NAME;
    SELECT 80 AS CODE, 220 AS NAME;
    SELECT 2 AS EVENTLENGTH;

  ELSEIF $GPCD = 'ALLOWCD1_LIST' THEN

    SELECT 
      HRMALLOWCD.ALLOWCD AS CODE, HRMALLOWCD.ALLOWNM AS NAME
      FROM HRMALLOWCD
      LEFT JOIN HRMPAYCALSTD ON HRMALLOWCD.ALLOWCD = HRMPAYCALSTD.ALLOWCD
      WHERE (HRMALLOWCD.ALLOWCD LIKE CONCAT('%', $KEYWORD, '%')
          OR HRMALLOWCD.ALLOWNM LIKE CONCAT('%', $KEYWORD, '%')
        )
        AND HRMPAYCALSTD.BASPAYYN = 'N'
      GROUP BY HRMALLOWCD.ALLOWCD
      LIMIT _$LIMIT;
  
  ELSEIF $GPCD = 'ALLOWCD1_INFO' THEN
  
    SELECT HRMALLOWCD.ALLOWCD AS CODE, HRMALLOWCD.ALLOWNM AS NAME
      FROM HRMALLOWCD
      LEFT JOIN HRMPAYCALSTD ON HRMALLOWCD.ALLOWCD = HRMPAYCALSTD.ALLOWCD
      WHERE HRMALLOWCD.ALLOWCD = $KEYWORD
        AND HRMPAYCALSTD.PAYCALT = '40';

-- *****************************************************************************
  ELSEIF $GPCD = 'DILIGCD_HEAD' THEN
  
    SELECT '근태코드' AS CODE, '근태명' AS NAME;
    SELECT 80 AS CODE, 220 AS NAME;
    SELECT 2 AS EVENTLENGTH;

  ELSEIF $GPCD = 'DILIGCD_LIST' THEN

    SELECT 
      HRMDILIGENCD.DILIGCD AS CODE, HRMDILIGENCD.DILIGNM AS NAME
      FROM HRMDILIGENCD
      WHERE (HRMDILIGENCD.DILIGCD LIKE CONCAT('%', $KEYWORD, '%')
          OR HRMDILIGENCD.DILIGNM LIKE CONCAT('%', $KEYWORD, '%')
        ) 
      LIMIT _$LIMIT;
  
  ELSEIF $GPCD = 'DILIGCD_INFO' THEN
  
    SELECT HRMDILIGENCD.DILIGCD AS CODE, HRMDILIGENCD.DILIGNM AS NAME
      FROM HRMDILIGENCD
      WHERE HRMDILIGENCD.DILIGCD = $KEYWORD;

-- *****************************************************************************


  ELSEIF $GPCD = 'UPDROPDEPT_HEAD' THEN
  
    SELECT '부서코드' AS CODE, '부서명' AS NAME, '생성일' AS REF01, '폐쇄일' AS REF02;
    SELECT 80 AS CODE, 220 AS NAME, 80 AS REF01, 80 AS REF02;

  ELSEIF $GPCD = 'UPDROPDEPT_LIST' THEN

    SELECT 
      MD.DEPTP AS CODE,
      CONCAT(CASE WHEN MD.LEVEL = 1 THEN ''
                  ELSE REPEAT('-', MD.LEVEL * 2) END,
      MD.DEPTNM) AS NAME,
      MD.STARTDAY AS REF01,
      IF(MD.ENDDAY = '9999-12-31', '', MD.ENDDAY) AS REF02
      FROM MSTDEPT AS MD
      WHERE (MD.DEPTP <> $REF01 or MD.STARTDAY <> $REF02)
        AND MD.USEYN = 'Y'
      LIMIT _$LIMIT;
  
  ELSEIF $GPCD = 'UPDROPDEPT_INFO' THEN
    
    SELECT MD.DEPTP AS CODE, MD.DEPTNM AS NAME, MD.STARTDAY AS REF01, IF(MD.ENDDAY = '9999-12-31', '', MD.ENDDAY) AS REF02
      FROM MSTDEPT AS MD
      WHERE MD.DEPTP = $KEYWORD;
-- *****************************************************************************

ELSEIF $GPCD = 'WORKDATELIST_HEAD' THEN
  
    SELECT '스케줄 코드' AS CODE, '스케줄 이름' AS NAME, '시작' AS REF01, '종료' AS REF02;
    SELECT 80 AS CODE, 160 AS NAME, 80 AS REF01, 80 AS REF02;
    SELECT 2 AS EVENTLENGTH;

  ELSEIF $GPCD = 'WORKDATELIST_LIST' THEN

    SELECT
      COMTYPE.TPCD AS CODE, COMTYPE.TPNM AS NAME, COMTYPE.REF01 AS REF01, COMTYPE.REF02 AS REF02
      FROM COMTYPE
      WHERE COMTYPE.GPCD = 'WORKDATE'
        AND COMTYPE.USEYN = 'Y'
      LIMIT _$LIMIT;

  ELSEIF $GPCD = 'WORKDATELIST_INFO' THEN
  
    SELECT COMTYPE.TPCD AS CODE, COMTYPE.TPNM AS NAME
      FROM COMTYPE
      WHERE COMTYPE.GPCD = 'WORKDATE'
        AND COMTYPE.USEYN = 'Y';

-- *****************************************************************************

  ELSEIF $GPCD = 'SRCWORKDATE_HEAD' THEN
  
    SELECT '스케줄 코드' AS CODE, '스케줄 이름' AS NAME, '시작' AS REF01, '종료' AS REF02;
    SELECT 80 AS CODE, 160 AS NAME, 80 AS REF01, 80 AS REF02;
    SELECT 2 AS EVENTLENGTH;

  ELSEIF $GPCD = 'SRCWORKDATE_LIST' THEN

    SELECT
      COMTYPE.TPCD AS CODE, COMTYPE.TPNM AS NAME, COMTYPE.REF01 AS REF01, COMTYPE.REF02 AS REF02
      FROM COMTYPE
      WHERE COMTYPE.GPCD = 'WORKDATE'
        AND COMTYPE.USEYN = 'Y'
        AND COMTYPE.TPCD <> $REF01
      LIMIT _$LIMIT;

  ELSEIF $GPCD = 'SRCWORKDATE_INFO' THEN
  
    SELECT COMTYPE.TPCD AS CODE, COMTYPE.TPNM AS NAME
      FROM COMTYPE
      WHERE COMTYPE.GPCD = 'WORKDATE'
        AND COMTYPE.USEYN = 'Y'
        AND COMTYPE.TPCD <> $REF01;

-- *****************************************************************************

  ELSEIF $GPCD = 'EQMCD_HEAD' OR $GPCD = 'FANO_HEAD' THEN
  
  SELECT '설비코드' AS CODE, '설비명' AS NAME, '호기명' AS REF01;
  SELECT 100 AS CODE, 200 AS NAME, 100 AS REF01;

ELSEIF $GPCD = 'EQMCD_LIST' OR $GPCD = 'FANO_LIST' THEN

  SELECT  MSTEQM.FANO AS CODE, MSTEQM.EQMNM AS NAME,
          MSTEQM.EQMNM_DETAIL AS REF01,
          GPCD('FM100', MSTEQM.EQMTP) AS REF02,
          ''  AS REF03,
          ''  AS REF04, 
          ''  AS REF05
    FROM MSTEQM
    WHERE MSTEQM.EQMTP LIKE CONCAT('%', $REF01, '%')
      AND ( MSTEQM.FANO LIKE CONCAT('%', $KEYWORD, '%')
            OR MSTEQM.EQMNM LIKE CONCAT('%', $KEYWORD, '%')
            OR MSTEQM.EQMNM_DETAIL LIKE CONCAT('%', $KEYWORD, '%')
          )
    LIMIT _$LIMIT;
  ELSEIF $GPCD = 'EQMCD_INFO' OR $GPCD = 'FANO_INFO' THEN

    SELECT MSTEQM.FANO AS CODE, MSTEQM.EQMNM AS NAME
    FROM MSTEQM
      WHERE MSTEQM.EQMTP LIKE CONCAT('%', $REF01, '%')
        AND MSTEQM.FANO = $KEYWORD;

-- *****************************************************************************
  ELSEIF $GPCD = 'WARECD_HEAD' THEN
  
    SELECT '창고코드' AS CODE, '창고명' AS NAME;
    SELECT 100 AS CODE, 120 AS NAME;
    SELECT 5 AS EVENTLENGTH;

  ELSEIF $GPCD = 'WARECD_LIST' THEN

    SELECT 
      MSTWARE.WARECD AS Label, 
      MSTWARE.WARENM AS Value
      FROM MSTWARE
      WHERE MSTWARE.USEYN = 'Y'
        AND CASE WHEN $REF01 = '' THEN MSTWARE.FACTORYCD = '07' 
            ELSE MSTWARE.FACTORYCD LIKE CONCAT('%', $REF01, '%') END
        AND ($REF02 = '' OR MSTWARE.SUBYN = $REF02)
        AND (MSTWARE.WARECD LIKE CONCAT('%', $KEYWORD, '%')
         OR MSTWARE.WARENM LIKE CONCAT('%', $KEYWORD, '%'))
      LIMIT _$LIMIT;
  
  ELSEIF $GPCD = 'WARECD_INFO' THEN
  
    SELECT 
      MSTWARE.WARECD AS CODE, 
      MSTWARE.WARENM AS NAME
      FROM MSTWARE
      WHERE MSTWARE.WARECD = $KEYWORD;

-- *****************************************************************************

  ELSEIF $GPCD = 'TOOLCD_HEAD' THEN
    
    SELECT '금형코드' AS CODE, '금형명' AS NAME, '캐비티' AS REF01;
    SELECT 100 AS CODE, 150 AS NAME, 80 AS REF01;
  
  ELSEIF $GPCD = 'TOOLCD_LIST' THEN
  
    IF $REF02 <> '' THEN
  
      SELECT MSTTOOL.TOOLCD AS CODE, MSTTOOL.TOOLNM AS NAME, MSTTOOL.MAXCAVITY AS REF01
        FROM MSTTOOL
        WHERE MSTTOOL.TOOLTP IN ('IP', 'IQ', 'IR')
          AND (MSTTOOL.TOOLCD LIKE CONCAT('%', $KEYWORD, '%')
          OR MSTTOOL.TOOLNM LIKE CONCAT('%', $KEYWORD, '%'))
        LIMIT _$LIMIT;
  
    ELSEIF $REF03 <> '' THEN
  
      SELECT MSTTOOL.TOOLCD AS CODE, MSTTOOL.TOOLNM AS NAME, MSTTOOL.MAXCAVITY AS REF01
        FROM MSTTOOL
        WHERE MSTTOOL.TOOLTP IN ('IM', 'IN', 'IO')
          AND (MSTTOOL.TOOLCD LIKE CONCAT('%', $KEYWORD, '%')
          OR MSTTOOL.TOOLNM LIKE CONCAT('%', $KEYWORD, '%'))
        LIMIT _$LIMIT;

    ELSE
  
      SELECT MSTTOOL.TOOLCD AS CODE, MSTTOOL.TOOLNM AS NAME, MSTTOOL.MAXCAVITY AS REF01
        FROM MSTTOOL
        WHERE MSTTOOL.TOOLTP LIKE CONCAT('%', $REF01, '%')
          AND (MSTTOOL.TOOLCD LIKE CONCAT('%', $KEYWORD, '%')
          OR MSTTOOL.TOOLNM LIKE CONCAT('%', $KEYWORD, '%'))
        LIMIT _$LIMIT;
  
    END IF;
  
  ELSEIF $GPCD = 'TOOLCD_INFO' THEN
  
    SELECT MSTTOOL.TOOLCD AS CODE, MSTTOOL.TOOLNM AS NAME
      FROM MSTTOOL
        WHERE MSTTOOL.TOOLTP LIKE CONCAT('%', $REF01, '%')
          AND MSTTOOL.TOOLCD = $KEYWORD;

-- *****************************************************************************

ELSEIF $GPCD = 'TOOLITEM_HEAD' THEN
  
  SELECT '금형코드' AS CODE, '금형명' AS NAME, '캐비티' AS REF01;
  SELECT 100 AS CODE, 150 AS NAME, 80 AS REF01;

ELSEIF $GPCD = 'TOOLITEM_LIST' THEN

  SELECT MSTTOOLITEM.TOOLCD AS CODE, MSTTOOL.TOOLNM AS NAME, MSTTOOL.MAXCAVITY AS REF01
    FROM MSTTOOLITEM
    LEFT JOIN MSTTOOL ON MSTTOOLITEM.TOOLCD = MSTTOOL.TOOLCD
    LEFT JOIN TOOLREP ON TOOLREP.TOOLCD = MSTTOOLITEM.TOOLCD
          AND GETTIME() BETWEEN TOOLREP.REPSTIME AND TOOLREP.REPETIME
    WHERE MSTTOOLITEM.ITEMCD = $REF01
      AND (MSTTOOLITEM.TOOLCD LIKE CONCAT('%', $KEYWORD, '%')
      OR MSTTOOL.TOOLNM LIKE CONCAT('%', $KEYWORD, '%'))
      AND TOOLREPKEY IS NULL
    GROUP BY MSTTOOLITEM.TOOLCD
    LIMIT _$LIMIT;

ELSEIF $GPCD = 'TOOLITEM_INFO' THEN

  SELECT MSTTOOLITEM.TOOLCD AS CODE, MSTTOOL.TOOLNM AS NAME
    FROM MSTTOOLITEM
    LEFT JOIN MSTTOOL ON MSTTOOLITEM.TOOLCD = MSTTOOL.TOOLCD
      WHERE MSTTOOLITEM.ITEMCD = $REF01
        AND MSTTOOLITEM.TOOLCD = $KEYWORD;

-- ****************************************************************************
 ELSEIF $GPCD = 'STDCD_HEAD' THEN
    
    SELECT '검사유형' AS CODE,  '검사코드' AS NAME, '검사항목' AS REF01, '검사방법'AS REF02, '값유형' AS REF03, '단위' AS REF04, '범위' AS REF05;
    SELECT 100 AS CODE, 100 AS NAME, 100 AS REF01, 80 AS REF02, 80 AS REF03, 50 AS REF04, 50 AS REF05;
  
  ELSEIF $GPCD = 'STDCD_LIST' THEN
--  CALL COMERR('ASDFASDF');
    SELECT 
      GPCD('STDTP', MSTSTD.STDTP) AS CODE, 
      MSTSTD.STDCD AS NAME,
      MSTSTD.STDNM AS REF01,
      GPCD('STDCHKTP', MSTSTD.STDCHKTP) AS REF02,
      GPCD('STDVALTP', MSTSTD.STDVALTP) AS REF03,
      GPCD('STDUNIT', MSTSTD.STDUNIT) AS REF04,
      GPCD('STDRANGE', MSTSTD.STDRANGE) AS REF05
    FROM MSTSTD
    ORDER BY MSTSTD.STDTP, MSTSTD.STDCD
    LIMIT _$LIMIT;
  
  ELSEIF $GPCD = 'STDCD_INFO' THEN
  
    SELECT 
--       MSTSTD.STDTP AS TITLE,
      MSTSTD.STDCD AS CODE,
      MSTSTD.STDNM AS NAME,
      MSTSTD.STDCHKTP AS REF01,
      MSTSTD.STDVALTP AS REF02,
      MSTSTD.STDUNIT AS REF03,
      MSTSTD.STDRANGE AS REF04,
      MSTSTD.STDTP AS REF05
    
    FROM MSTSTD
    ORDER BY MSTSTD.STDTP, MSTSTD.STDCD
    LIMIT _$LIMIT;
  
-- ****************************************************************************

 
  ELSEIF $GPCD = 'STDKNDCD_HEAD' THEN
    
    SELECT '항목코드' AS CODE, '항목명' AS NAME;
    SELECT 100 AS CODE, 150 AS NAME;
  
  ELSEIF $GPCD = 'STDKNDCD_LIST' THEN
  
    IF $REF01 <> '' THEN
      SELECT MSTSTDKND.STDKNDCD AS CODE, MSTSTDKND.STDKNDNM AS NAME
      FROM MSTSTDKND 
      LEFT JOIN MSTSTDD ON MSTSTDKND.STDKNDCD = MSTSTDD.STDKNDCD AND MSTSTDD.STDRANGE IN ($REF01, $REF02)
      WHERE (MSTSTDKND.STDKNDCD LIKE CONCAT('%', $KEYWORD, '%')
        OR MSTSTDKND.STDKNDNM LIKE CONCAT('%', $KEYWORD, '%'))
        GROUP BY MSTSTDD.STDKNDCD
      LIMIT _$LIMIT;
  
    ELSE
  
      SELECT MSTSTDKND.STDKNDCD AS CODE, MSTSTDKND.STDKNDNM AS NAME
        FROM MSTSTDKND 
        WHERE (MSTSTDKND.STDKNDCD LIKE CONCAT('%', $KEYWORD, '%')
          OR MSTSTDKND.STDKNDNM LIKE CONCAT('%', $KEYWORD, '%'))
        LIMIT _$LIMIT;
  
    END IF;
  
  ELSEIF $GPCD = 'STDKNDCD_INFO' THEN
  
    SELECT MSTSTDKND.STDKNDCD AS CODE, MSTSTDKND.STDKNDNM AS NAME
    FROM MSTSTDKND 
    WHERE MSTSTDKND.STDKNDCD = $KEYWORD;

-- *****************************************************************************
--   ELSEIF $GPCD = 'DEPTP_HEAD' THEN
--   
--     SELECT '부서코드' AS CODE, '부서명' AS NAME;
--     SELECT 80 AS CODE, 220 AS NAME;
-- 
--   ELSEIF $GPCD = 'DEPTP_LIST' THEN
-- 
--     SELECT 
--       MSTDEPT.DEPTP AS CODE,
--       CONCAT(CASE WHEN MSTDEPT.LEVEL = 1 THEN ''
--                   ELSE REPEAT('-', MSTDEPT.LEVEL * 2) END,
--       MSTDEPT.DEPTNM) AS NAME
--       FROM MSTDEPT
--       WHERE (MSTDEPT.DEPTP LIKE CONCAT('%', $KEYWORD, '%') OR MSTDEPT.DEPTNM LIKE CONCAT('%', $KEYWORD, '%'))
--         AND MSTDEPT.USEYN = 'Y'
--         AND (GETDATE() BETWEEN MSTDEPT.STARTDAY AND MSTDEPT.ENDDAY)
--         AND MSTDEPT.BDVCD LIKE CONCAT('%', $REF01, '%')
--       LIMIT _$LIMIT;
--   
--   ELSEIF $GPCD = 'DEPTP_INFO' THEN
--   
--     SELECT MSTDEPT.DEPTP AS CODE, MSTDEPT.DEPTNM AS NAME
--       FROM MSTDEPT
--       WHERE MSTDEPT.DEPTP = $KEYWORD
--         AND MSTDEPT.USEYN = 'Y'
--         AND (GETDATE() BETWEEN MSTDEPT.STARTDAY AND MSTDEPT.ENDDAY)
--         AND MSTDEPT.BDVCD LIKE CONCAT('%', $REF01, '%');

-- *****************************************************************************

ELSEIF $GPCD = 'DEPTLIST_HEAD' THEN
  
    SELECT '부서코드' AS CODE, '부서명' AS NAME, '사업장' AS REF01, '부서장' AS REF02;
    SELECT 80 AS CODE, 100 AS NAME, 100 AS REF01, 80 AS REF02;
    SELECT 2 AS EVENTLENGTH;

  ELSEIF $GPCD = 'DEPTLIST_LIST' THEN

    SELECT
      MSTDEPT.DEPTP AS CODE, MSTDEPT.DEPTNM AS NAME, GPCD('BDVCD', MSTDEPT.BDVCD) AS REF01, GPCD('EMPCD', MSTDEPT.DEPTOWNER) AS REF02
      FROM MSTDEPT
      WHERE MSTDEPT.USEYN = 'Y'
        AND CASE WHEN $REF01 = '' THEN 1 = 1
                 ELSE MSTDEPT.BDVCD = $REF01 END
      LIMIT _$LIMIT;

  ELSEIF $GPCD = 'DEPTLIST_INFO' THEN
  
    SELECT
      MSTDEPT.DEPTP AS CODE, MSTDEPT.DEPTNM AS NAME
      FROM MSTDEPT
      WHERE MSTDEPT.USEYN = 'Y'
        AND CASE WHEN $REF01 = '' THEN 1 = 1
                 ELSE MSTDEPT.BDVCD = $REF01 END;
-- *****************************************************************************
  ELSEIF $GPCD = 'BADCD_HEAD' THEN

    SELECT '불량코드' AS CODE, '불량명' AS NAME;
    SELECT 100 AS CODE, 150 AS NAME;

  ELSEIF $GPCD = 'BADCD_LIST' THEN
  
    SELECT MSTBAD.BADCD AS CODE, MSTBAD.BADNM AS NAME
      FROM MSTBAD
      WHERE (MSTBAD.BADCD LIKE CONCAT('%', $KEYWORD, '%')
        OR MSTBAD.BADNM LIKE CONCAT('%', $KEYWORD, '%'))
      LIMIT _$LIMIT;
  
  ELSEIF $GPCD = 'BADCD_INFO' THEN
  
    SELECT MSTBAD.BADCD AS CODE, MSTBAD.BADNM AS NAME
      FROM MSTBAD
      WHERE MSTBAD.BADCD = $KEYWORD;

-- *****************************************************************************
  ELSEIF $GPCD = 'PRCCD_HEAD' THEN

    SELECT '공정코드' AS CODE, '공정명' AS NAME;
    SELECT 100 AS CODE, 150 AS NAME;

  ELSEIF $GPCD = 'PRCCD_LIST' THEN
  
    SELECT PRCCD AS CODE, PRCNM AS NAME
      FROM MSTPRC
      WHERE IF($REF01 = '', 1=1, MSTPRC.PRCTP = $REF01)
        AND (PRCCD LIKE CONCAT('%', $KEYWORD, '%')
        OR PRCNM LIKE CONCAT('%', $KEYWORD, '%'))
      ORDER BY SORTNO
      LIMIT _$LIMIT;
  
  ELSEIF $GPCD = 'PRCCD_INFO' THEN
  
    SELECT PRCCD AS CODE, PRCNM AS NAME
      FROM MSTPRC
      WHERE PRCCD = $KEYWORD;
-- ****************************************************************************
ELSEIF $GPCD = 'ROUTPRC_HEAD' THEN  -- BOM등록 화면에서 공정선택시 (2024-01-25 신정수 추가)
  
  SELECT '공정코드' AS CODE, '공정명' AS NAME, '공정유형' AS REF01;
  SELECT 100 AS CODE, 200 AS NAME, 80 AS REF01;

ELSEIF $GPCD = 'ROUTPRC_LIST' THEN

  SELECT 
      GPCD('PRCTP', MSTPRC.PRCTP) AS REF01
    , MSTROUT.PRCCD AS CODE
    , MSTPRC.PRCNM AS NAME
    
  FROM MSTROUT
  INNER JOIN MSTPRC
  ON  MSTROUT.PRCCD = MSTPRC.PRCCD
  WHERE IF($REF01 = '', 1=1, MSTROUT.ITEMCD = $REF01)
  AND   MSTPRC.USEYN = 'Y'
  ORDER BY MSTROUT.PRCSEQ
  ;

ELSEIF $GPCD = 'ROUTPRC_INFO' THEN

  SELECT 
      GPCD('PRCTP', MSTPRC.PRCTP) AS REF01
    , MSTROUT.PRCCD AS CODE
    , MSTPRC.PRCNM AS NAME
  FROM MSTROUT
  INNER JOIN MSTPRC
  ON  MSTROUT.PRCCD = MSTPRC.PRCCD
  WHERE MSTROUT.PRCCD = $KEYWORD
  AND   MSTPRC.USEYN = 'Y'
  ORDER BY MSTROUT.PRCSEQ
  ;

-- ***************************************************************************** 
ELSEIF $GPCD = 'SALODRDKEY_HEAD' THEN
  
  SELECT '수주품목 번호' AS CODE, '수주명' AS REF03, '거래처' AS NAME, '품목코드'AS REF01, '수주잔량' AS REF02;
  SELECT 110 AS CODE, 100 AS REF03, 100 AS NAME, 120 AS REF01, 100 AS REF02;

ELSEIF $GPCD = 'SALODRDKEY_LIST' THEN

  SELECT SALODRD.SALODRDKEY AS CODE, SALODR.SALODRNM AS REF03, MSTCUST.CUSTNM AS NAME, SALODRD.ITEMCD AS REF01, SALODRD.ODRQTY AS REF02
    FROM SALODRD
    LEFT JOIN SALODR ON SALODRD.SALODRKEY = SALODR.SALODRKEY
    LEFT JOIN SALOUT ON SALOUT.SALODRDKEY = SALODRD.SALODRDKEY
    LEFT JOIN MSTCUST ON SALODR.CUSTCD = MSTCUST.CUSTCD
    WHERE SALODRD.SALOUTYN = 'N'
      AND (SALOUT.SALODRDKEY = '' OR SALOUT.SALODRDKEY IS NULL)
      AND (SALODRD.SALODRDKEY LIKE CONCAT('%',$KEYWORD, '%')
       OR SALODR.CUSTCD LIKE CONCAT('%',$KEYWORD, '%')
       OR SALODRD.ITEMCD LIKE CONCAT('%',$KEYWORD, '%')
       OR MSTCUST.CUSTNM LIKE CONCAT('%',$KEYWORD, '%'))
    ORDER BY SALODRD.ORDERDATE DESC      
    LIMIT _$LIMIT;

ELSEIF $GPCD = 'SALODRDKEY_INFO' THEN

  SELECT SALODRD.SALODRDKEY AS CODE,CONCAT(MSTCUST.CUSTNM, ' / ', SALODRD.ITEMCD) AS NAME
    FROM SALODRD
    LEFT JOIN SALODR ON SALODRD.SALODRKEY = SALODR.SALODRKEY
    LEFT JOIN MSTCUST ON SALODR.CUSTCD = MSTCUST.CUSTCD 
    WHERE SALODRD.SALODRDKEY = $KEYWORD
      AND SALODRD.SALOUTYN = 'N';
-- *****************************************************************************
ELSEIF $GPCD = 'EXPDATA_HEAD' THEN
  
  SELECT '수출품목키' AS CODE, '품목코드' AS NAME, '부품번호'AS REF01, '차종' AS REF02, '지역' AS REF03,'납품장소' AS REF04;
  SELECT 100 AS CODE, 110 AS NAME, 120 AS REF01, 70 AS REF02, 70 AS REF03, 100 AS REF04;

ELSEIF $GPCD = 'EXPDATA_LIST' THEN

  SELECT MSTITEMEXP.ITEMEXPKEY AS CODE, MSTITEMEXP.ITEMCD AS NAME, MSTITEMEXP.PARTNO AS REF01,
         MSTITEMEXP.MODELTP AS REF02, MSTITEMEXP.LOCALPLACE AS REF03, MSTITEMEXP.PLACE AS REF04,
         MSTITEMEXP.APPYN AS REF05
      FROM MSTITEMEXP
      WHERE (CASE WHEN $REF01 = '' THEN MSTITEMEXP.ITEMCD LIKE CONCAT('%', $KEYWORD, '%')                         
                                     OR MSTITEMEXP.ITEMEXPKEY LIKE CONCAT('%', $KEYWORD, '%')
                                     OR MSTITEMEXP.PARTNO LIKE CONCAT('%', $KEYWORD, '%')
                                     OR MSTITEMEXP.PARTNM LIKE CONCAT('%', $KEYWORD, '%')
                                     OR MSTITEMEXP.MODELTP LIKE CONCAT('%', $KEYWORD, '%')
                                     OR MSTITEMEXP.PLACE LIKE CONCAT('%', $KEYWORD, '%')
                                     OR MSTITEMEXP.LOCALPLACE LIKE CONCAT('%', $KEYWORD, '%')
                 WHEN $REF01 <> '' THEN MSTITEMEXP.ITEMCD = $REF01
                                    AND (MSTITEMEXP.ITEMEXPKEY LIKE CONCAT('%', $KEYWORD, '%')
                                     OR MSTITEMEXP.PARTNO LIKE CONCAT('%', $KEYWORD, '%')
                                     OR MSTITEMEXP.PARTNM LIKE CONCAT('%', $KEYWORD, '%')
                                     OR MSTITEMEXP.MODELTP LIKE CONCAT('%', $KEYWORD, '%')
                                     OR MSTITEMEXP.PLACE LIKE CONCAT('%', $KEYWORD, '%')
                                     OR MSTITEMEXP.LOCALPLACE LIKE CONCAT('%', $KEYWORD, '%')) END)              
       LIMIT _$LIMIT;

ELSEIF $GPCD = 'EXPDATA_INFO' THEN

  SELECT MSTITEMEXP.ITEMEXPKEY AS CODE, MSTITEMEXP.PARTNO AS NAME
      FROM MSTITEMEXP
      WHERE MSTITEMEXP.ITEMEXPKEY = $KEYWORD;

-- *****************************************************************************

  ELSEIF $GPCD = 'BRANDCD_HEAD' THEN

    SELECT '차종코드' AS CODE, '차종' AS NAME;
    SELECT 100 AS CODE, 150 AS NAME;

  ELSEIF $GPCD = 'BRANDCD_LIST' THEN
  
    SELECT MSTBRAND.BRANDCD AS CODE, MSTBRAND.BRANDNM AS NAME
      FROM MSTBRAND
      WHERE (MSTBRAND.BRANDCD LIKE CONCAT('%', $KEYWORD, '%')
        OR MSTBRAND.BRANDNM LIKE CONCAT('%', $KEYWORD, '%'))
      LIMIT _$LIMIT;
  
  ELSEIF $GPCD = 'BRANDCD_INFO' THEN
  
    SELECT MSTBRAND.BRANDCD AS CODE, MSTBRAND.BRANDNM AS NAME
      FROM MSTBRAND
      WHERE MSTBRAND.BRANDCD = $KEYWORD;
-- *****************************************************************************
  ELSEIF $GPCD = 'PRGCD_E_HEAD' THEN

    SELECT '프로그램코드' AS CODE, '프로그램명' AS NAME;
    SELECT 100 AS CODE, 150 AS NAME;

  ELSEIF $GPCD = 'PRGCD_E_LIST' THEN
  
    SELECT PRGCD AS CODE, PRGNM AS NAME
      FROM SYSPRG_E
      WHERE (PRGCD LIKE CONCAT('%', $KEYWORD, '%')
        OR PRGNM LIKE CONCAT('%', $KEYWORD, '%'))
      LIMIT _$LIMIT;
  
  ELSEIF $GPCD = 'PRGCD_E_INFO' THEN
  
    SELECT PRGCD AS CODE, PRGNM AS NAME
      FROM SYSPRG_E
      WHERE PRGCD = $KEYWORD;

-- *****************************************************************************

  ELSEIF $GPCD = 'PRGCD_HEAD' THEN

    SELECT '프로그램코드' AS CODE, '프로그램명' AS NAME;
    SELECT 100 AS CODE, 150 AS NAME;

  ELSEIF $GPCD = 'PRGCD_LIST' THEN

    SELECT SYSPRG.PRGCD AS CODE, SYSPRG.PRGNM AS NAME
    FROM SYSPRG
    INNER JOIN SYSPKG
    ON SYSPKG.PKGTP = SYSPRG.PKGTP
    AND SYSPKG.USEYN = 'Y'
    WHERE (SYSPRG.PRGCD LIKE CONCAT('%', $KEYWORD, '%')
    OR SYSPRG.PRGNM LIKE CONCAT('%', $KEYWORD, '%'))
    AND LEFT(SYSPRG.PRGCD, 3) LIKE CONCAT('%', $REF05, '%')
    LIMIT _$LIMIT;

  ELSEIF $GPCD = 'PRGCD_INFO' THEN
  
    SELECT PRGCD AS CODE, PRGNM AS NAME
      FROM SYSPRG
      WHERE PRGCD = $KEYWORD;

-- *****************************************************************************
  ELSEIF $GPCD = 'USERID_HEAD' THEN

    SELECT '로그인ID' AS CODE, '사원명' AS NAME, '사원코드' AS REF01;
    SELECT 80 AS CODE, 120 AS NAME, 80 AS REF01;

  ELSEIF $GPCD = 'USERID_LIST' THEN
  
    SELECT SYSUSER.USERID AS CODE, MSTEMP.EMPNM AS NAME, SYSUSER.EMPCD AS REF01
      FROM SYSUSER
      LEFT JOIN MSTEMP ON SYSUSER.EMPCD = MSTEMP.EMPCD
      WHERE (  SYSUSER.USERID LIKE CONCAT('%', $KEYWORD, '%')
            OR SYSUSER.EMPCD  LIKE CONCAT('%', $KEYWORD, '%')
            OR MSTEMP.EMPNM   LIKE CONCAT('%', $KEYWORD, '%')
      )
      LIMIT _$LIMIT;
  
  ELSEIF $GPCD = 'USERID_INFO' THEN
  
    SELECT SYSUSER.USERID AS CODE, MSTEMP.EMPNM AS NAME, SYSUSER.EMPCD AS REF01
      FROM SYSUSER
      LEFT JOIN MSTEMP ON SYSUSER.EMPCD = MSTEMP.EMPCD
      WHERE SYSUSER.USERID = $KEYWORD;
-- *****************************************************************************
  ELSEIF $GPCD = 'CARCD_HEAD' THEN

    SELECT '차량코드' AS CODE, '차량번호' AS NAME, '차량명' AS REF01, '구분' AS REF02;
    SELECT 80 AS CODE, 120 AS NAME, 120 AS REF01, 120 AS REF02;

  ELSEIF $GPCD = 'CARCD_LIST' THEN

    SELECT MCI.CARCD AS CODE, MCI.CARNO AS NAME, MCI.CARNAME AS REF01, GPCD('CARTYPE', MCI.CARTYPE) AS REF02
      FROM MSTCARINFO AS MCI
      WHERE MCI.CARCD LIKE CONCAT('%', $KEYWORD, '%')
        AND MCI.USEYN = 'Y';

  ELSEIF $GPCD = 'CARCD_INFO' THEN

    SELECT MCI.CARCD AS CODE, MCI.CARNO AS NAME, MCI.CARNAME AS REF01, GPCD('CARTYPE', MCI.CARTYPE) AS REF02
      FROM MSTCARINFO AS MCI
      WHERE MCI.CARCD LIKE CONCAT('%', $KEYWORD, '%')
        AND MCI.USEYN = 'Y';

-- *****************************************************************************
  ELSEIF $GPCD = 'DEVLOPKEY_HEAD' THEN
  
    SELECT '프로젝트코드' AS CODE, '프로젝트명' AS NAME;
    SELECT 100 AS CODE, 150 AS NAME;

  ELSEIF $GPCD = 'DEVLOPKEY_LIST' THEN
  
    SELECT TQMDEVLOP.DEVLOPKEY AS CODE, TQMDEVLOP.DEVLOPNM AS NAME
      FROM TQMDEVLOP
      WHERE TQMDEVLOP.BDVCD LIKE CONCAT('%', $REF01, '%')
        AND (TQMDEVLOP.DEVLOPKEY LIKE CONCAT('%', $KEYWORD, '%')
        OR TQMDEVLOP.DEVLOPNM LIKE CONCAT('%', $KEYWORD, '%'))
      LIMIT _$LIMIT;
  
  ELSEIF $GPCD = 'DEVLOPKEY_INFO' THEN
  
    SELECT TQMDEVLOP.DEVLOPKEY AS CODE, TQMDEVLOP.DEVLOPNM AS NAME
      FROM TQMDEVLOP
      WHERE TQMDEVLOP.DEVLOPKEY = $KEYWORD;

-- *****************************************************************************

  ELSEIF $GPCD = 'IQCLOT_HEAD' THEN
    
    SELECT 'LOT번호' AS CODE, '품목코드' AS NAME, '품명' AS REF01, '대기수량' AS REF02;
    SELECT 120 AS CODE, 100 AS NAME, 200 AS REF01, 80 AS REF02;
  
  ELSEIF $GPCD = 'IQCLOT_LIST' THEN

    SELECT MTRINLOT.LOTKEY AS CODE, MTRIN.ITEMCD AS NAME, 
      GPCD('ITEMCD', MTRIN.ITEMCD) AS REF01, 
      CAST(MTRINLOT.LOTQTY AS DECIMAL(20, 2)) AS REF02
      FROM MTRINLOT
      LEFT JOIN MTRIN ON MTRIN.MTRINKEY = MTRINLOT.MTRINKEY
      LEFT JOIN MSTITEM ON MTRIN.ITEMCD = MSTITEM.ITEMCD
      LEFT JOIN TQMIQC ON MTRINLOT.LOTKEY = TQMIQC.LOTKEY
      WHERE TQMIQC.LOTKEY IS NULL 
        AND (MTRINLOT.PRDDATE >= $REF02 AND MTRINLOT.PRDDATE <= $REF03)
        AND MTRINLOT.INYN = 'N'
        AND (MTRINLOT.LOTKEY LIKE CONCAT('%', $KEYWORD, '%')
        OR MTRIN.MTRINKEY LIKE CONCAT('%', $KEYWORD, '%')
        OR MTRIN.ITEMCD LIKE CONCAT('%', $KEYWORD, '%')
        OR MSTITEM.ITEMNM LIKE CONCAT('%', $KEYWORD, '%'))
      LIMIT _$LIMIT;
  
  ELSEIF $GPCD = 'IQCLOT_INFO' THEN
  
    SELECT MTRINLOT.LOTKEY AS CODE,
      CONCAT(CAST(MTRINLOT.LOTQTY AS DECIMAL(20, 2)), '/', MTRIN.ITEMCD, '/', IFNULL(MSTITEM.ITEMNM, '')) AS NAME
      FROM MTRINLOT
      LEFT JOIN MTRIN ON MTRIN.MTRINKEY = MTRINLOT.MTRINKEY
      LEFT JOIN MSTITEM ON MTRIN.ITEMCD = MSTITEM.ITEMCD
      LEFT JOIN TQMIQC ON MTRINLOT.LOTKEY = TQMIQC.LOTKEY
      WHERE TQMIQC.LOTKEY IS NULL 
        AND MTRINLOT.LOTKEY = $KEYWORD
        AND (MTRINLOT.PRDDATE >= $REF02 AND MTRINLOT.PRDDATE <= $REF03);

    -- *****************************************************************************
ELSEIF $GPCD = 'FILERHEO_HEAD' THEN
  
  SELECT '파일코드' AS CODE, '파일이름' AS NAME;
  SELECT 100 AS CODE, 150 AS NAME;

ELSEIF $GPCD = 'FILERHEO_LIST' THEN

  SELECT COMFILE.FILEKEY AS CODE, COMFILE.FILENAME AS NAME
    FROM COMFILE
    LEFT JOIN TQMRHEO ON COMFILE.FILEKEY = TQMRHEO.FILEKEY 
    WHERE COMFILE.FILEKEY LIKE CONCAT('%', '', '%')
      AND COMFILE.FILENAME LIKE CONCAT('%', '', '%')
      AND COMFILE.REMARK = 'RHEO'
    GROUP BY COMFILE.FILEKEY
    HAVING COUNT(TQMRHEO.LOTKEY) < 10
    LIMIT _$LIMIT;

ELSEIF $GPCD = 'FILERHEO_INFO' THEN

  SELECT COMFILE.FILEKEY AS CODE, COMFILE.FILENAME AS NAME
    FROM COMFILE 
    WHERE COMFILE.FILEKEY = $KEYWORD
      AND COMFILE.REMARK = 'RHEO';

-- *****************************************************************************
ELSEIF $GPCD = 'FILEMOONEY_HEAD' THEN
  
  SELECT '파일코드' AS CODE, '파일이름' AS NAME;
  SELECT 100 AS CODE, 150 AS NAME;

ELSEIF $GPCD = 'FILEMOONEY_LIST' THEN

  SELECT COMFILE.FILEKEY AS CODE, COMFILE.FILENAME AS NAME
    FROM COMFILE
    LEFT JOIN TQMMOONEY ON COMFILE.FILEKEY = TQMMOONEY.FILEKEY  
    WHERE COMFILE.FILEKEY LIKE CONCAT('%', $KEYWORD, '%')
      AND COMFILE.FILENAME LIKE CONCAT('%', $KEYWORD, '%')
      AND COMFILE.REMARK = 'MOONEY'
    GROUP BY COMFILE.FILEKEY
    HAVING COUNT(TQMMOONEY.LOTKEY) < 10
    LIMIT _$LIMIT;

ELSEIF $GPCD = 'FILEMOONEY_INFO' THEN

  SELECT COMFILE.FILEKEY AS CODE, COMFILE.FILENAME AS NAME
    FROM COMFILE 
    WHERE COMFILE.FILEKEY = $KEYWORD
      AND COMFILE.REMARK = 'MOONEY';

-- *****************************************************************************
ELSEIF $GPCD = 'FILESPRING_HEAD' THEN
  
  SELECT '파일코드' AS CODE, '파일이름' AS NAME;
  SELECT 100 AS CODE, 150 AS NAME;

ELSEIF $GPCD = 'FILESPRING_LIST' THEN

  SELECT COMFILE.FILEKEY AS CODE, COMFILE.FILENAME AS NAME
    FROM COMFILE
    LEFT JOIN TQMSPRING ON COMFILE.FILEKEY = TQMSPRING.FILEKEY 
    WHERE COMFILE.FILEKEY LIKE CONCAT('%', $KEYWORD, '%')
      AND COMFILE.FILENAME LIKE CONCAT('%', $KEYWORD, '%')
      AND COMFILE.REMARK = 'SPRING'
      AND (TQMSPRING.FILEKEY IS NULL 
      OR TQMSPRING.FILEKEY = '')
    LIMIT _$LIMIT;

ELSEIF $GPCD = 'FILESPRING_INFO' THEN

  SELECT COMFILE.FILEKEY AS CODE, COMFILE.FILENAME AS NAME
    FROM COMFILE 
    WHERE COMFILE.FILEKEY = $KEYWORD
      AND COMFILE.REMARK = 'SPRING';

-- *****************************************************************************
  ELSEIF $GPCD = 'DELIVERYCD_HEAD' THEN
  
    SELECT '배송지코드' AS CODE, '배송지명' AS NAME, '거래처' AS REF01, '인수자' AS REF02, '주소' AS REF03;
    SELECT 100 AS CODE, 150 AS NAME, 150 AS REF01, 100 AS REF02, 250 AS REF03;
    SELECT 2 AS EVENTLENGTH;

  ELSEIF $GPCD = 'DELIVERYCD_LIST' THEN

    SELECT 
      MSTDELIVERY.DELIVERYCD AS CODE, MSTDELIVERY.DELIVERYNM AS NAME,
      GPCD('CUSTCD', MSTDELIVERY.CUSTCD) AS REF01, MSTDELIVERY.DELIVERYACCEPTER AS REF02,
      MSTDELIVERY.DELIVERYADDRESS AS REF03
      FROM MSTDELIVERY
      WHERE (MSTDELIVERY.DELIVERYCD LIKE CONCAT('%', $KEYWORD, '%')
          OR MSTDELIVERY.DELIVERYNM LIKE CONCAT('%', $KEYWORD, '%')
        ) AND MSTDELIVERY.CUSTCD = $REF01
      LIMIT _$LIMIT;
  
  ELSEIF $GPCD = 'DELIVERYCD_INFO' THEN
  
    SELECT MSTDELIVERY.DELIVERYCD AS CODE, MSTDELIVERY.DELIVERYNM AS NAME,
      GPCD('CUSTCD', MSTDELIVERY.CUSTCD) AS REF01, MSTDELIVERY.DELIVERYACCEPTER AS REF02,
      MSTDELIVERY.DELIVERYADDRESS AS REF03
      FROM MSTDELIVERY
      WHERE MSTDELIVERY.DELIVERYCD = $KEYWORD
        AND MSTDELIVERY.CUSTCD = $REF01;

-- ****************************************************************************

ELSEIF $GPCD = 'CHKCD_HEAD' THEN
  
  SELECT '점검코드' AS CODE, '점검명' AS NAME;
  SELECT 100 AS CODE, 150 AS NAME;

ELSEIF $GPCD = 'CHKCD_LIST' THEN

  SELECT MSTCHKKND.CHKKNDCD AS CODE, MSTCHKKND.CHKKNDNM AS NAME 
  FROM MSTCHKKND 
  WHERE MSTCHKKND.CHKLOC REGEXP $REF01
    AND (MSTCHKKND.CHKKNDCD LIKE CONCAT('%', $KEYWORD, '%')
    OR MSTCHKKND.CHKKNDNM LIKE CONCAT('%', $KEYWORD, '%'));

ELSEIF $GPCD = 'CHKCD_INFO' THEN

  SELECT MSTCHKKND.CHKKNDCD AS CODE, MSTCHKKND.CHKKNDNM AS NAME
  FROM MSTCHKKND 
  WHERE MSTCHKKND.CHKKNDCD = $KEYWORD;

-- *****************************************************************************
ELSEIF $GPCD = 'MIXITEM_HEAD' THEN
  
  SELECT '배합코드' AS CODE, '배합명' AS NAME, '번호' AS REF01;
  SELECT 100 AS CODE, 150 AS NAME, 100 AS REF01;

ELSEIF $GPCD = 'MIXITEM_LIST' THEN

  SELECT CONCAT(MSTMIXITEM.ITEMCD, '⊙', MSTMIXITEM.MIXVER) AS CODE, MSTMIXITEM.MIXNM AS NAME,
    MSTMIXITEM.MIXNO AS REF01
  FROM MSTMIXITEM 
  WHERE (MSTMIXITEM.ITEMCD LIKE CONCAT('%', $KEYWORD, '%')
    OR MSTMIXITEM.MIXNO LIKE CONCAT('%', $KEYWORD, '%')
    )
  LIMIT _$LIMIT;

ELSEIF $GPCD = 'MIXITEM_INFO' THEN

  SELECT CONCAT(MSTMIXITEM.ITEMCD, '⊙', MSTMIXITEM.MIXVER) AS CODE, MSTMIXITEM.MIXNM AS NAME,
    MSTMIXITEM.MIXNO AS REF01
  FROM MSTMIXITEM 
  WHERE MSTMIXITEM.ITEMCD = $KEYWORD;
-- *****************************************************************************

  ELSEIF $GPCD = 'PARTNO_HEAD' THEN

    SELECT '부품번호' AS CODE, '부품명' AS NAME;
    SELECT 150 AS CODE, 100 AS NAME;

  ELSEIF $GPCD = 'PARTNO_LIST' THEN
  
    SELECT MSTITEMEXP.PARTNO AS CODE, MSTITEMEXP.PARTNM AS NAME
      FROM MSTITEMEXP
     WHERE MSTITEMEXP.APPYN = 'Y'
       AND (MSTITEMEXP.PARTNO LIKE CONCAT('%', $KEYWORD, '%')
        OR MSTITEMEXP.PARTNM LIKE CONCAT('%', $KEYWORD, '%'))
      LIMIT _$LIMIT;
  
  ELSEIF $GPCD = 'PARTNO_INFO' THEN
  
    SELECT MSTITEMEXP.PARTNO AS CODE, MSTITEMEXP.PARTNM AS NAME
      FROM MSTITEMEXP
      WHERE MSTBRAND.PARTNO = $KEYWORD;

-- *****************************************************************************

  ELSEIF $GPCD = 'TMLCD_HEAD' THEN

    SELECT '단말기 코드' AS CODE, '단말기명' AS NAME;
    SELECT 100 AS CODE, 120 AS NAME;

  ELSEIF $GPCD = 'TMLCD_LIST' THEN

    SELECT MSTTML.TMLCD AS CODE, MSTTML.TMLNM AS NAME 
      FROM MSTTML
      WHERE (MSTTML.TMLCD LIKE CONCAT('%', $KEYWORD, '%') OR MSTTML.TMLNM LIKE CONCAT('%', $KEYWORD, '%'))
      ORDER BY MSTTML.SORTNO, MSTTML.TMLCD, MSTTML.TMLNM
      LIMIT _$LIMIT;

  ELSEIF $GPCD = 'TMLCD_INFO' THEN

    SELECT MSTTML.TMLCD AS CODE, MSTTML.TMLNM AS NAME
      FROM MSTTML
      WHERE MSTTML.TMLCD = $KEYWORD;

-- *****************************************************************************
  ELSEIF $GPCD = 'MITEM_HEAD' THEN

    SELECT '상위품목' AS CODE, '품목명' AS NAME, '품번' AS REF01;
    SELECT 100 AS CODE, 220 AS NAME, 220 AS REF01;

  ELSEIF $GPCD = 'MITEM_LIST' THEN

    SELECT A.MITEMCD AS CODE, C.ITEMNM AS NAME, C.ITEMCDCUST
      FROM MSTBOM AS A
      JOIN MSTITEM AS B ON A.CITEMCD = B.ITEMCD
      JOIN MSTITEM AS C ON A.MITEMCD = C.ITEMCD
      WHERE A.USEYN = 'Y'
        AND A.CITEMCD = $REF01
        AND (B.ITEMNM LIKE CONCAT('%', $KEYWORD, '%')
        OR B.ITEMCDCUST LIKE CONCAT('%', $KEYWORD, '%'))

      LIMIT _$LIMIT;

  ELSEIF $GPCD = 'MITEM_INFO' THEN

    SELECT A.MITEMCD AS CODE, B.ITEMNM AS NAME, B.ITEMCDCUST AS REF01
      FROM MSTBOM AS A
      JOIN MSTITEM AS B ON A.MITEMCD = B.ITEMCD
      WHERE A.USEYN = 'Y'
        AND A.CITEMCD = $KEYWORD;

-- *****************************************************************************
  ELSEIF $GPCD = 'DETAILCD_HEAD' THEN -- 일련번호 (2024-01-31 신정수 추가)

    SELECT 
        '일련번호코드' AS CODE
      , '일련번호' AS NAME
      , '일련번호명' AS REF01
      , '품목유형' AS REF02
      , '용도구분' AS REF03
      , '공장' AS REF04;

    SELECT  
        80 AS CODE
      , 80 AS NAME
      , 150 AS REF01
      , 80 AS REF02
      , 80 AS REF03
      , 80 AS REF04;

  ELSEIF $GPCD = 'DETAILCD_LIST' THEN
  
    SELECT 
        DETAILCD AS CODE
      , DETAILNUM AS NAME
      , DETAILNM AS REF01
      , GPCD('ITEMTP', DETAIL_NUM.ITEMTP) AS REF02
      , MSTUSETP.USETPNM  AS REF03     
      , GPCD('FACTORY', DETAIL_NUM.FACTORY) AS REF04             
    FROM DETAIL_NUM
    LEFT JOIN MSTUSETP
      ON MSTUSETP.FACTORY = DETAIL_NUM.FACTORY
     AND MSTUSETP.ITEMTP = DETAIL_NUM.ITEMTP
     AND MSTUSETP.USETPCD = DETAIL_NUM.USETP
    WHERE IF($REF01 = '', 1=1, DETAIL_NUM.ITEMTP = $REF01)
      AND IF($REF02 = '', 1=1, DETAIL_NUM.USETP = $REF02)
      AND IF($REF03 = '', 1=1, DETAIL_NUM.FACTORY = $REF03)
    ;
  
  ELSEIF $GPCD = 'DETAILCD_INFO' THEN
  
    SELECT 
        DETAILCD AS CODE
      , DETAILNUM AS NAME
      , DETAILNM AS REF01
      , GPCD('ITEMTP', DETAIL_NUM.ITEMTP) AS REF02
      , MSTUSETP.USETPNM  AS REF03     
      , GPCD('FACTORY', DETAIL_NUM.FACTORY) AS REF04                 
    FROM DETAIL_NUM
    LEFT JOIN MSTUSETP
      ON MSTUSETP.FACTORY = DETAIL_NUM.FACTORY
     AND MSTUSETP.ITEMTP = DETAIL_NUM.ITEMTP
     AND MSTUSETP.USETPCD = DETAIL_NUM.USETP
    WHERE IF($REF01 = '', 1=1, DETAIL_NUM.ITEMTP = $REF01)
      AND IF($REF02 = '', 1=1, DETAIL_NUM.USETP = $REF02)
      AND IF($REF03 = '', 1=1, DETAIL_NUM.FACTORY = $REF03)
    ;

-- *****************************************************************************
  ELSEIF $GPCD = 'ACCBANKCD2_HEAD' THEN -- 사업장계좌번호 (2024-04-22 박민식 추가)

    SELECT 
         
         '용도' AS CODE      
       , '은행명' AS NAME     
       , '계좌번호' AS REF02
    ;  

    SELECT  
        80 AS CODE      
      , 100 AS NAME
      , 200 AS REF02 
    ;  

  ELSEIF $GPCD = 'ACCBANKCD2_LIST' THEN
  
    SELECT 
        
        TPNM AS CODE      
      ,REF01  AS NAME
      ,REF02  AS REF02
    FROM COMTYPE
    WHERE GPCD = 'ACCBANKCD'
     AND USEYN = 'Y'
     AND (REF01 LIKE CONCAT('%', $KEYWORD, '%')
      OR REF02 LIKE CONCAT('%', $KEYWORD, '%')      
      OR TPNM LIKE CONCAT('%',$KEYWORD,'%'))
    ;
  
--   ELSEIF $GPCD = 'ACCBANKCD2_INFO' THEN
--   
--     SELECT 
--         
--         REF01 AS CODE          
--       , REF02 AS NAME
--       , TPNM AS REF02
--     FROM COMTYPE
--     WHERE GPCD = 'ACCBANKCD'
--       AND USEYN = 'Y'
--       AND (REF01 LIKE CONCAT('%', $KEYWORD, '%')
--        OR REF02 LIKE CONCAT('%', $KEYWORD, '%'))
--     ;

-- *****************************************************************************
ELSE SELECT 'ERROR' AS CODE, $GPCD AS NAME;
-- ****************************************************************************
END IF; END