-- *****************************************************************************
-- Comment: 설비점검 공통코드 마이그레이션 (MES_ALPHA -> MES_SNS2)
-- Create: 2026-09-15 점검 관련 공통코드 5종 등록
-- 대상: CHKLOC(설비점검항목), CHKTP(점검유형), CHKMTH(점검방법), CHKCYCLE(점검주기), CHKVALTP(점검값유형), ISSUE(수리유형)
-- *****************************************************************************
USE `MES_SNS2`;

-- =============================================================================
-- 1. COMTYPEGP (공통코드 그룹 5종)
-- =============================================================================
INSERT INTO `COMTYPEGP` (`GPCD`, `GPNM`, `SYSYN`, `OPENYN`, `REF01NM`, `REF02NM`, `REF03NM`, `REF04NM`, `REF05NM`, `REF06NM`, `REF07NM`, `REF08NM`, `REF09NM`, `REF10NM`, `REF11NM`, `REF12NM`, `REF13NM`, `REF14NM`, `REF15NM`, `REF16NM`, `REF17NM`, `REF18NM`, `REF19NM`, `REF20NM`, `REMARK`, `RTIME`, `REMP`, `RPRG`, `MTIME`, `MEMP`, `MPRG`, `USEYN`) VALUES ('CHKCYCLE', '점검주기', 'Y', 'N', '', '월단위', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 'Y') ON DUPLICATE KEY UPDATE `GPNM` = VALUES(`GPNM`), `USEYN` = 'Y';
INSERT INTO `COMTYPEGP` (`GPCD`, `GPNM`, `SYSYN`, `OPENYN`, `REF01NM`, `REF02NM`, `REF03NM`, `REF04NM`, `REF05NM`, `REF06NM`, `REF07NM`, `REF08NM`, `REF09NM`, `REF10NM`, `REF11NM`, `REF12NM`, `REF13NM`, `REF14NM`, `REF15NM`, `REF16NM`, `REF17NM`, `REF18NM`, `REF19NM`, `REF20NM`, `REMARK`, `RTIME`, `REMP`, `RPRG`, `MTIME`, `MEMP`, `MPRG`, `USEYN`) VALUES ('CHKLOC', '설비점검항목', 'Y', 'N', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '2026-05-08 17:58:46', 'admin', 'SYS0001_R02', '', '', '', 'Y') ON DUPLICATE KEY UPDATE `GPNM` = VALUES(`GPNM`), `USEYN` = 'Y';
INSERT INTO `COMTYPEGP` (`GPCD`, `GPNM`, `SYSYN`, `OPENYN`, `REF01NM`, `REF02NM`, `REF03NM`, `REF04NM`, `REF05NM`, `REF06NM`, `REF07NM`, `REF08NM`, `REF09NM`, `REF10NM`, `REF11NM`, `REF12NM`, `REF13NM`, `REF14NM`, `REF15NM`, `REF16NM`, `REF17NM`, `REF18NM`, `REF19NM`, `REF20NM`, `REMARK`, `RTIME`, `REMP`, `RPRG`, `MTIME`, `MEMP`, `MPRG`, `USEYN`) VALUES ('CHKMTH', '점검방법', 'Y', 'N', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '2026-05-11 09:15:41', 'admin', 'SYS0001_R02', '', '', '', 'Y') ON DUPLICATE KEY UPDATE `GPNM` = VALUES(`GPNM`), `USEYN` = 'Y';
INSERT INTO `COMTYPEGP` (`GPCD`, `GPNM`, `SYSYN`, `OPENYN`, `REF01NM`, `REF02NM`, `REF03NM`, `REF04NM`, `REF05NM`, `REF06NM`, `REF07NM`, `REF08NM`, `REF09NM`, `REF10NM`, `REF11NM`, `REF12NM`, `REF13NM`, `REF14NM`, `REF15NM`, `REF16NM`, `REF17NM`, `REF18NM`, `REF19NM`, `REF20NM`, `REMARK`, `RTIME`, `REMP`, `RPRG`, `MTIME`, `MEMP`, `MPRG`, `USEYN`) VALUES ('CHKTP', '점검유형', 'Y', 'N', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 'Y') ON DUPLICATE KEY UPDATE `GPNM` = VALUES(`GPNM`), `USEYN` = 'Y';
INSERT INTO `COMTYPEGP` (`GPCD`, `GPNM`, `SYSYN`, `OPENYN`, `REF01NM`, `REF02NM`, `REF03NM`, `REF04NM`, `REF05NM`, `REF06NM`, `REF07NM`, `REF08NM`, `REF09NM`, `REF10NM`, `REF11NM`, `REF12NM`, `REF13NM`, `REF14NM`, `REF15NM`, `REF16NM`, `REF17NM`, `REF18NM`, `REF19NM`, `REF20NM`, `REMARK`, `RTIME`, `REMP`, `RPRG`, `MTIME`, `MEMP`, `MPRG`, `USEYN`) VALUES ('CHKVALTP', '점검값유형', 'Y', 'N', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 'Y') ON DUPLICATE KEY UPDATE `GPNM` = VALUES(`GPNM`), `USEYN` = 'Y';
INSERT INTO `COMTYPEGP` (`GPCD`, `GPNM`, `SYSYN`, `OPENYN`, `USEYN`) VALUES ('ISSUE', '수리유형', 'Y', 'N', 'Y') ON DUPLICATE KEY UPDATE `GPNM` = VALUES(`GPNM`), `USEYN` = 'Y';

-- =============================================================================
-- 2. COMTYPE (공통코드 상세 34건)
-- =============================================================================
INSERT INTO `COMTYPE` (`GPCD`, `TPCD`, `TPNM`, `SORTNO`, `USEYN`, `REF01`, `REF02`, `REF03`, `REF04`, `REF05`, `REF06`, `REF07`, `REF08`, `REF09`, `REF10`, `REF11`, `REF12`, `REF13`, `REF14`, `REF15`, `REF16`, `REF17`, `REF18`, `REF19`, `REF20`, `REMARK`, `RTIME`, `REMP`, `RPRG`, `MTIME`, `MEMP`, `MPRG`) VALUES ('CHKCYCLE', 'DAILY', '일간', '101', 'Y', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '') ON DUPLICATE KEY UPDATE `TPNM` = VALUES(`TPNM`), `SORTNO` = VALUES(`SORTNO`), `USEYN` = VALUES(`USEYN`);
INSERT INTO `COMTYPE` (`GPCD`, `TPCD`, `TPNM`, `SORTNO`, `USEYN`, `REF01`, `REF02`, `REF03`, `REF04`, `REF05`, `REF06`, `REF07`, `REF08`, `REF09`, `REF10`, `REF11`, `REF12`, `REF13`, `REF14`, `REF15`, `REF16`, `REF17`, `REF18`, `REF19`, `REF20`, `REMARK`, `RTIME`, `REMP`, `RPRG`, `MTIME`, `MEMP`, `MPRG`) VALUES ('CHKCYCLE', 'WEEK', '주간', '102', 'Y', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '') ON DUPLICATE KEY UPDATE `TPNM` = VALUES(`TPNM`), `SORTNO` = VALUES(`SORTNO`), `USEYN` = VALUES(`USEYN`);
INSERT INTO `COMTYPE` (`GPCD`, `TPCD`, `TPNM`, `SORTNO`, `USEYN`, `REF01`, `REF02`, `REF03`, `REF04`, `REF05`, `REF06`, `REF07`, `REF08`, `REF09`, `REF10`, `REF11`, `REF12`, `REF13`, `REF14`, `REF15`, `REF16`, `REF17`, `REF18`, `REF19`, `REF20`, `REMARK`, `RTIME`, `REMP`, `RPRG`, `MTIME`, `MEMP`, `MPRG`) VALUES ('CHKCYCLE', 'MONTH', '월간', '103', 'Y', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '') ON DUPLICATE KEY UPDATE `TPNM` = VALUES(`TPNM`), `SORTNO` = VALUES(`SORTNO`), `USEYN` = VALUES(`USEYN`);
INSERT INTO `COMTYPE` (`GPCD`, `TPCD`, `TPNM`, `SORTNO`, `USEYN`, `REF01`, `REF02`, `REF03`, `REF04`, `REF05`, `REF06`, `REF07`, `REF08`, `REF09`, `REF10`, `REF11`, `REF12`, `REF13`, `REF14`, `REF15`, `REF16`, `REF17`, `REF18`, `REF19`, `REF20`, `REMARK`, `RTIME`, `REMP`, `RPRG`, `MTIME`, `MEMP`, `MPRG`) VALUES ('CHKCYCLE', 'QUARTER', '분기', '104', 'Y', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '') ON DUPLICATE KEY UPDATE `TPNM` = VALUES(`TPNM`), `SORTNO` = VALUES(`SORTNO`), `USEYN` = VALUES(`USEYN`);
INSERT INTO `COMTYPE` (`GPCD`, `TPCD`, `TPNM`, `SORTNO`, `USEYN`, `REF01`, `REF02`, `REF03`, `REF04`, `REF05`, `REF06`, `REF07`, `REF08`, `REF09`, `REF10`, `REF11`, `REF12`, `REF13`, `REF14`, `REF15`, `REF16`, `REF17`, `REF18`, `REF19`, `REF20`, `REMARK`, `RTIME`, `REMP`, `RPRG`, `MTIME`, `MEMP`, `MPRG`) VALUES ('CHKCYCLE', 'HALF', '반기', '105', 'Y', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '') ON DUPLICATE KEY UPDATE `TPNM` = VALUES(`TPNM`), `SORTNO` = VALUES(`SORTNO`), `USEYN` = VALUES(`USEYN`);
INSERT INTO `COMTYPE` (`GPCD`, `TPCD`, `TPNM`, `SORTNO`, `USEYN`, `REF01`, `REF02`, `REF03`, `REF04`, `REF05`, `REF06`, `REF07`, `REF08`, `REF09`, `REF10`, `REF11`, `REF12`, `REF13`, `REF14`, `REF15`, `REF16`, `REF17`, `REF18`, `REF19`, `REF20`, `REMARK`, `RTIME`, `REMP`, `RPRG`, `MTIME`, `MEMP`, `MPRG`) VALUES ('CHKCYCLE', 'YEAR', '년도', '106', 'Y', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '') ON DUPLICATE KEY UPDATE `TPNM` = VALUES(`TPNM`), `SORTNO` = VALUES(`SORTNO`), `USEYN` = VALUES(`USEYN`);
INSERT INTO `COMTYPE` (`GPCD`, `TPCD`, `TPNM`, `SORTNO`, `USEYN`, `REF01`, `REF02`, `REF03`, `REF04`, `REF05`, `REF06`, `REF07`, `REF08`, `REF09`, `REF10`, `REF11`, `REF12`, `REF13`, `REF14`, `REF15`, `REF16`, `REF17`, `REF18`, `REF19`, `REF20`, `REMARK`, `RTIME`, `REMP`, `RPRG`, `MTIME`, `MEMP`, `MPRG`) VALUES ('CHKCYCLE', 'ANYTIME', '상시', '107', 'Y', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '') ON DUPLICATE KEY UPDATE `TPNM` = VALUES(`TPNM`), `SORTNO` = VALUES(`SORTNO`), `USEYN` = VALUES(`USEYN`);
INSERT INTO `COMTYPE` (`GPCD`, `TPCD`, `TPNM`, `SORTNO`, `USEYN`, `REF01`, `REF02`, `REF03`, `REF04`, `REF05`, `REF06`, `REF07`, `REF08`, `REF09`, `REF10`, `REF11`, `REF12`, `REF13`, `REF14`, `REF15`, `REF16`, `REF17`, `REF18`, `REF19`, `REF20`, `REMARK`, `RTIME`, `REMP`, `RPRG`, `MTIME`, `MEMP`, `MPRG`) VALUES ('CHKCYCLE', 'M01', '1월', '201', 'Y', '', 'Y', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '') ON DUPLICATE KEY UPDATE `TPNM` = VALUES(`TPNM`), `SORTNO` = VALUES(`SORTNO`), `USEYN` = VALUES(`USEYN`);
INSERT INTO `COMTYPE` (`GPCD`, `TPCD`, `TPNM`, `SORTNO`, `USEYN`, `REF01`, `REF02`, `REF03`, `REF04`, `REF05`, `REF06`, `REF07`, `REF08`, `REF09`, `REF10`, `REF11`, `REF12`, `REF13`, `REF14`, `REF15`, `REF16`, `REF17`, `REF18`, `REF19`, `REF20`, `REMARK`, `RTIME`, `REMP`, `RPRG`, `MTIME`, `MEMP`, `MPRG`) VALUES ('CHKCYCLE', 'M02', '2월', '202', 'Y', '', 'Y', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '') ON DUPLICATE KEY UPDATE `TPNM` = VALUES(`TPNM`), `SORTNO` = VALUES(`SORTNO`), `USEYN` = VALUES(`USEYN`);
INSERT INTO `COMTYPE` (`GPCD`, `TPCD`, `TPNM`, `SORTNO`, `USEYN`, `REF01`, `REF02`, `REF03`, `REF04`, `REF05`, `REF06`, `REF07`, `REF08`, `REF09`, `REF10`, `REF11`, `REF12`, `REF13`, `REF14`, `REF15`, `REF16`, `REF17`, `REF18`, `REF19`, `REF20`, `REMARK`, `RTIME`, `REMP`, `RPRG`, `MTIME`, `MEMP`, `MPRG`) VALUES ('CHKCYCLE', 'M03', '3월', '203', 'Y', '', 'Y', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '') ON DUPLICATE KEY UPDATE `TPNM` = VALUES(`TPNM`), `SORTNO` = VALUES(`SORTNO`), `USEYN` = VALUES(`USEYN`);
INSERT INTO `COMTYPE` (`GPCD`, `TPCD`, `TPNM`, `SORTNO`, `USEYN`, `REF01`, `REF02`, `REF03`, `REF04`, `REF05`, `REF06`, `REF07`, `REF08`, `REF09`, `REF10`, `REF11`, `REF12`, `REF13`, `REF14`, `REF15`, `REF16`, `REF17`, `REF18`, `REF19`, `REF20`, `REMARK`, `RTIME`, `REMP`, `RPRG`, `MTIME`, `MEMP`, `MPRG`) VALUES ('CHKCYCLE', 'M04', '4월', '204', 'Y', '', 'Y', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '') ON DUPLICATE KEY UPDATE `TPNM` = VALUES(`TPNM`), `SORTNO` = VALUES(`SORTNO`), `USEYN` = VALUES(`USEYN`);
INSERT INTO `COMTYPE` (`GPCD`, `TPCD`, `TPNM`, `SORTNO`, `USEYN`, `REF01`, `REF02`, `REF03`, `REF04`, `REF05`, `REF06`, `REF07`, `REF08`, `REF09`, `REF10`, `REF11`, `REF12`, `REF13`, `REF14`, `REF15`, `REF16`, `REF17`, `REF18`, `REF19`, `REF20`, `REMARK`, `RTIME`, `REMP`, `RPRG`, `MTIME`, `MEMP`, `MPRG`) VALUES ('CHKCYCLE', 'M05', '5월', '205', 'Y', '', 'Y', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '') ON DUPLICATE KEY UPDATE `TPNM` = VALUES(`TPNM`), `SORTNO` = VALUES(`SORTNO`), `USEYN` = VALUES(`USEYN`);
INSERT INTO `COMTYPE` (`GPCD`, `TPCD`, `TPNM`, `SORTNO`, `USEYN`, `REF01`, `REF02`, `REF03`, `REF04`, `REF05`, `REF06`, `REF07`, `REF08`, `REF09`, `REF10`, `REF11`, `REF12`, `REF13`, `REF14`, `REF15`, `REF16`, `REF17`, `REF18`, `REF19`, `REF20`, `REMARK`, `RTIME`, `REMP`, `RPRG`, `MTIME`, `MEMP`, `MPRG`) VALUES ('CHKCYCLE', 'M06', '6월', '206', 'Y', '', 'Y', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '') ON DUPLICATE KEY UPDATE `TPNM` = VALUES(`TPNM`), `SORTNO` = VALUES(`SORTNO`), `USEYN` = VALUES(`USEYN`);
INSERT INTO `COMTYPE` (`GPCD`, `TPCD`, `TPNM`, `SORTNO`, `USEYN`, `REF01`, `REF02`, `REF03`, `REF04`, `REF05`, `REF06`, `REF07`, `REF08`, `REF09`, `REF10`, `REF11`, `REF12`, `REF13`, `REF14`, `REF15`, `REF16`, `REF17`, `REF18`, `REF19`, `REF20`, `REMARK`, `RTIME`, `REMP`, `RPRG`, `MTIME`, `MEMP`, `MPRG`) VALUES ('CHKCYCLE', 'M07', '7월', '207', 'Y', '', 'Y', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '') ON DUPLICATE KEY UPDATE `TPNM` = VALUES(`TPNM`), `SORTNO` = VALUES(`SORTNO`), `USEYN` = VALUES(`USEYN`);
INSERT INTO `COMTYPE` (`GPCD`, `TPCD`, `TPNM`, `SORTNO`, `USEYN`, `REF01`, `REF02`, `REF03`, `REF04`, `REF05`, `REF06`, `REF07`, `REF08`, `REF09`, `REF10`, `REF11`, `REF12`, `REF13`, `REF14`, `REF15`, `REF16`, `REF17`, `REF18`, `REF19`, `REF20`, `REMARK`, `RTIME`, `REMP`, `RPRG`, `MTIME`, `MEMP`, `MPRG`) VALUES ('CHKCYCLE', 'M08', '8월', '208', 'Y', '', 'Y', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '') ON DUPLICATE KEY UPDATE `TPNM` = VALUES(`TPNM`), `SORTNO` = VALUES(`SORTNO`), `USEYN` = VALUES(`USEYN`);
INSERT INTO `COMTYPE` (`GPCD`, `TPCD`, `TPNM`, `SORTNO`, `USEYN`, `REF01`, `REF02`, `REF03`, `REF04`, `REF05`, `REF06`, `REF07`, `REF08`, `REF09`, `REF10`, `REF11`, `REF12`, `REF13`, `REF14`, `REF15`, `REF16`, `REF17`, `REF18`, `REF19`, `REF20`, `REMARK`, `RTIME`, `REMP`, `RPRG`, `MTIME`, `MEMP`, `MPRG`) VALUES ('CHKCYCLE', 'M09', '9월', '209', 'Y', '', 'Y', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '') ON DUPLICATE KEY UPDATE `TPNM` = VALUES(`TPNM`), `SORTNO` = VALUES(`SORTNO`), `USEYN` = VALUES(`USEYN`);
INSERT INTO `COMTYPE` (`GPCD`, `TPCD`, `TPNM`, `SORTNO`, `USEYN`, `REF01`, `REF02`, `REF03`, `REF04`, `REF05`, `REF06`, `REF07`, `REF08`, `REF09`, `REF10`, `REF11`, `REF12`, `REF13`, `REF14`, `REF15`, `REF16`, `REF17`, `REF18`, `REF19`, `REF20`, `REMARK`, `RTIME`, `REMP`, `RPRG`, `MTIME`, `MEMP`, `MPRG`) VALUES ('CHKCYCLE', 'M10', '10월', '210', 'Y', '', 'Y', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '') ON DUPLICATE KEY UPDATE `TPNM` = VALUES(`TPNM`), `SORTNO` = VALUES(`SORTNO`), `USEYN` = VALUES(`USEYN`);
INSERT INTO `COMTYPE` (`GPCD`, `TPCD`, `TPNM`, `SORTNO`, `USEYN`, `REF01`, `REF02`, `REF03`, `REF04`, `REF05`, `REF06`, `REF07`, `REF08`, `REF09`, `REF10`, `REF11`, `REF12`, `REF13`, `REF14`, `REF15`, `REF16`, `REF17`, `REF18`, `REF19`, `REF20`, `REMARK`, `RTIME`, `REMP`, `RPRG`, `MTIME`, `MEMP`, `MPRG`) VALUES ('CHKCYCLE', 'M11', '11월', '211', 'Y', '', 'Y', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '') ON DUPLICATE KEY UPDATE `TPNM` = VALUES(`TPNM`), `SORTNO` = VALUES(`SORTNO`), `USEYN` = VALUES(`USEYN`);
INSERT INTO `COMTYPE` (`GPCD`, `TPCD`, `TPNM`, `SORTNO`, `USEYN`, `REF01`, `REF02`, `REF03`, `REF04`, `REF05`, `REF06`, `REF07`, `REF08`, `REF09`, `REF10`, `REF11`, `REF12`, `REF13`, `REF14`, `REF15`, `REF16`, `REF17`, `REF18`, `REF19`, `REF20`, `REMARK`, `RTIME`, `REMP`, `RPRG`, `MTIME`, `MEMP`, `MPRG`) VALUES ('CHKCYCLE', 'M12', '12월', '212', 'Y', '', 'Y', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '') ON DUPLICATE KEY UPDATE `TPNM` = VALUES(`TPNM`), `SORTNO` = VALUES(`SORTNO`), `USEYN` = VALUES(`USEYN`);
INSERT INTO `COMTYPE` (`GPCD`, `TPCD`, `TPNM`, `SORTNO`, `USEYN`, `REF01`, `REF02`, `REF03`, `REF04`, `REF05`, `REF06`, `REF07`, `REF08`, `REF09`, `REF10`, `REF11`, `REF12`, `REF13`, `REF14`, `REF15`, `REF16`, `REF17`, `REF18`, `REF19`, `REF20`, `REMARK`, `RTIME`, `REMP`, `RPRG`, `MTIME`, `MEMP`, `MPRG`) VALUES ('CHKCYCLE', 'DAYTIME', '일간(주)', '301', 'Y', '08:00:00 ~ 18:59:59', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '') ON DUPLICATE KEY UPDATE `TPNM` = VALUES(`TPNM`), `SORTNO` = VALUES(`SORTNO`), `USEYN` = VALUES(`USEYN`);
INSERT INTO `COMTYPE` (`GPCD`, `TPCD`, `TPNM`, `SORTNO`, `USEYN`, `REF01`, `REF02`, `REF03`, `REF04`, `REF05`, `REF06`, `REF07`, `REF08`, `REF09`, `REF10`, `REF11`, `REF12`, `REF13`, `REF14`, `REF15`, `REF16`, `REF17`, `REF18`, `REF19`, `REF20`, `REMARK`, `RTIME`, `REMP`, `RPRG`, `MTIME`, `MEMP`, `MPRG`) VALUES ('CHKCYCLE', 'NIGHT', '일간(야)', '302', 'Y', '19:00:00 ~ 07:59:59', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '') ON DUPLICATE KEY UPDATE `TPNM` = VALUES(`TPNM`), `SORTNO` = VALUES(`SORTNO`), `USEYN` = VALUES(`USEYN`);
INSERT INTO `COMTYPE` (`GPCD`, `TPCD`, `TPNM`, `SORTNO`, `USEYN`, `REF01`, `REF02`, `REF03`, `REF04`, `REF05`, `REF06`, `REF07`, `REF08`, `REF09`, `REF10`, `REF11`, `REF12`, `REF13`, `REF14`, `REF15`, `REF16`, `REF17`, `REF18`, `REF19`, `REF20`, `REMARK`, `RTIME`, `REMP`, `RPRG`, `MTIME`, `MEMP`, `MPRG`) VALUES ('CHKLOC', '1', '윤할계통', '1', 'Y', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '2026-05-11 09:57:12', 'admin', 'SYS0001_R01', '', '', '') ON DUPLICATE KEY UPDATE `TPNM` = VALUES(`TPNM`), `SORTNO` = VALUES(`SORTNO`), `USEYN` = VALUES(`USEYN`);
INSERT INTO `COMTYPE` (`GPCD`, `TPCD`, `TPNM`, `SORTNO`, `USEYN`, `REF01`, `REF02`, `REF03`, `REF04`, `REF05`, `REF06`, `REF07`, `REF08`, `REF09`, `REF10`, `REF11`, `REF12`, `REF13`, `REF14`, `REF15`, `REF16`, `REF17`, `REF18`, `REF19`, `REF20`, `REMARK`, `RTIME`, `REMP`, `RPRG`, `MTIME`, `MEMP`, `MPRG`) VALUES ('CHKLOC', '2', '전기계통', '2', 'Y', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '2026-05-11 09:57:21', 'admin', 'SYS0001_R01', '', '', '') ON DUPLICATE KEY UPDATE `TPNM` = VALUES(`TPNM`), `SORTNO` = VALUES(`SORTNO`), `USEYN` = VALUES(`USEYN`);
INSERT INTO `COMTYPE` (`GPCD`, `TPCD`, `TPNM`, `SORTNO`, `USEYN`, `REF01`, `REF02`, `REF03`, `REF04`, `REF05`, `REF06`, `REF07`, `REF08`, `REF09`, `REF10`, `REF11`, `REF12`, `REF13`, `REF14`, `REF15`, `REF16`, `REF17`, `REF18`, `REF19`, `REF20`, `REMARK`, `RTIME`, `REMP`, `RPRG`, `MTIME`, `MEMP`, `MPRG`) VALUES ('CHKLOC', '3', '구동계통', '3', 'Y', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '2026-05-11 09:57:27', 'admin', 'SYS0001_R01', '', '', '') ON DUPLICATE KEY UPDATE `TPNM` = VALUES(`TPNM`), `SORTNO` = VALUES(`SORTNO`), `USEYN` = VALUES(`USEYN`);
INSERT INTO `COMTYPE` (`GPCD`, `TPCD`, `TPNM`, `SORTNO`, `USEYN`, `REF01`, `REF02`, `REF03`, `REF04`, `REF05`, `REF06`, `REF07`, `REF08`, `REF09`, `REF10`, `REF11`, `REF12`, `REF13`, `REF14`, `REF15`, `REF16`, `REF17`, `REF18`, `REF19`, `REF20`, `REMARK`, `RTIME`, `REMP`, `RPRG`, `MTIME`, `MEMP`, `MPRG`) VALUES ('CHKMTH', '01', '육안', '1', 'Y', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '2026-05-11 09:50:10', 'admin', 'SYS0001_R01', '', '', '') ON DUPLICATE KEY UPDATE `TPNM` = VALUES(`TPNM`), `SORTNO` = VALUES(`SORTNO`), `USEYN` = VALUES(`USEYN`);
INSERT INTO `COMTYPE` (`GPCD`, `TPCD`, `TPNM`, `SORTNO`, `USEYN`, `REF01`, `REF02`, `REF03`, `REF04`, `REF05`, `REF06`, `REF07`, `REF08`, `REF09`, `REF10`, `REF11`, `REF12`, `REF13`, `REF14`, `REF15`, `REF16`, `REF17`, `REF18`, `REF19`, `REF20`, `REMARK`, `RTIME`, `REMP`, `RPRG`, `MTIME`, `MEMP`, `MPRG`) VALUES ('CHKMTH', '02', '렌치', '2', 'Y', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '2026-05-11 09:50:43', 'admin', 'SYS0001_R01', '', '', '') ON DUPLICATE KEY UPDATE `TPNM` = VALUES(`TPNM`), `SORTNO` = VALUES(`SORTNO`), `USEYN` = VALUES(`USEYN`);
INSERT INTO `COMTYPE` (`GPCD`, `TPCD`, `TPNM`, `SORTNO`, `USEYN`, `REF01`, `REF02`, `REF03`, `REF04`, `REF05`, `REF06`, `REF07`, `REF08`, `REF09`, `REF10`, `REF11`, `REF12`, `REF13`, `REF14`, `REF15`, `REF16`, `REF17`, `REF18`, `REF19`, `REF20`, `REMARK`, `RTIME`, `REMP`, `RPRG`, `MTIME`, `MEMP`, `MPRG`) VALUES ('CHKMTH', '03', '줄자', '3', 'Y', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '2026-05-11 09:50:58', 'admin', 'SYS0001_R01', '', '', '') ON DUPLICATE KEY UPDATE `TPNM` = VALUES(`TPNM`), `SORTNO` = VALUES(`SORTNO`), `USEYN` = VALUES(`USEYN`);
INSERT INTO `COMTYPE` (`GPCD`, `TPCD`, `TPNM`, `SORTNO`, `USEYN`, `REF01`, `REF02`, `REF03`, `REF04`, `REF05`, `REF06`, `REF07`, `REF08`, `REF09`, `REF10`, `REF11`, `REF12`, `REF13`, `REF14`, `REF15`, `REF16`, `REF17`, `REF18`, `REF19`, `REF20`, `REMARK`, `RTIME`, `REMP`, `RPRG`, `MTIME`, `MEMP`, `MPRG`) VALUES ('CHKTP', '03', '점검', '0', 'N', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '2026-05-08 17:59:31', 'admin', 'SYS0001_R01') ON DUPLICATE KEY UPDATE `TPNM` = VALUES(`TPNM`), `SORTNO` = VALUES(`SORTNO`), `USEYN` = VALUES(`USEYN`);
INSERT INTO `COMTYPE` (`GPCD`, `TPCD`, `TPNM`, `SORTNO`, `USEYN`, `REF01`, `REF02`, `REF03`, `REF04`, `REF05`, `REF06`, `REF07`, `REF08`, `REF09`, `REF10`, `REF11`, `REF12`, `REF13`, `REF14`, `REF15`, `REF16`, `REF17`, `REF18`, `REF19`, `REF20`, `REMARK`, `RTIME`, `REMP`, `RPRG`, `MTIME`, `MEMP`, `MPRG`) VALUES ('CHKTP', '04', '검교정', '0', 'N', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '2026-05-08 17:59:35', 'admin', 'SYS0001_R01') ON DUPLICATE KEY UPDATE `TPNM` = VALUES(`TPNM`), `SORTNO` = VALUES(`SORTNO`), `USEYN` = VALUES(`USEYN`);
INSERT INTO `COMTYPE` (`GPCD`, `TPCD`, `TPNM`, `SORTNO`, `USEYN`, `REF01`, `REF02`, `REF03`, `REF04`, `REF05`, `REF06`, `REF07`, `REF08`, `REF09`, `REF10`, `REF11`, `REF12`, `REF13`, `REF14`, `REF15`, `REF16`, `REF17`, `REF18`, `REF19`, `REF20`, `REMARK`, `RTIME`, `REMP`, `RPRG`, `MTIME`, `MEMP`, `MPRG`) VALUES ('CHKTP', '01', '일상점검', '1', 'Y', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '2026-05-08 17:59:59', 'admin', 'SYS0001_R01') ON DUPLICATE KEY UPDATE `TPNM` = VALUES(`TPNM`), `SORTNO` = VALUES(`SORTNO`), `USEYN` = VALUES(`USEYN`);
INSERT INTO `COMTYPE` (`GPCD`, `TPCD`, `TPNM`, `SORTNO`, `USEYN`, `REF01`, `REF02`, `REF03`, `REF04`, `REF05`, `REF06`, `REF07`, `REF08`, `REF09`, `REF10`, `REF11`, `REF12`, `REF13`, `REF14`, `REF15`, `REF16`, `REF17`, `REF18`, `REF19`, `REF20`, `REMARK`, `RTIME`, `REMP`, `RPRG`, `MTIME`, `MEMP`, `MPRG`) VALUES ('CHKTP', '02', '정기점검', '2', 'Y', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '2026-05-08 18:00:02', 'admin', 'SYS0001_R01') ON DUPLICATE KEY UPDATE `TPNM` = VALUES(`TPNM`), `SORTNO` = VALUES(`SORTNO`), `USEYN` = VALUES(`USEYN`);
INSERT INTO `COMTYPE` (`GPCD`, `TPCD`, `TPNM`, `SORTNO`, `USEYN`, `REF01`, `REF02`, `REF03`, `REF04`, `REF05`, `REF06`, `REF07`, `REF08`, `REF09`, `REF10`, `REF11`, `REF12`, `REF13`, `REF14`, `REF15`, `REF16`, `REF17`, `REF18`, `REF19`, `REF20`, `REMARK`, `RTIME`, `REMP`, `RPRG`, `MTIME`, `MEMP`, `MPRG`) VALUES ('CHKVALTP', '01', '숫자', '0', 'Y', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '') ON DUPLICATE KEY UPDATE `TPNM` = VALUES(`TPNM`), `SORTNO` = VALUES(`SORTNO`), `USEYN` = VALUES(`USEYN`);
INSERT INTO `COMTYPE` (`GPCD`, `TPCD`, `TPNM`, `SORTNO`, `USEYN`, `REF01`, `REF02`, `REF03`, `REF04`, `REF05`, `REF06`, `REF07`, `REF08`, `REF09`, `REF10`, `REF11`, `REF12`, `REF13`, `REF14`, `REF15`, `REF16`, `REF17`, `REF18`, `REF19`, `REF20`, `REMARK`, `RTIME`, `REMP`, `RPRG`, `MTIME`, `MEMP`, `MPRG`) VALUES ('CHKVALTP', '02', '문자', '0', 'N', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '2026-05-11 10:16:18', 'admin', 'SYS0001_R01') ON DUPLICATE KEY UPDATE `TPNM` = VALUES(`TPNM`), `SORTNO` = VALUES(`SORTNO`), `USEYN` = VALUES(`USEYN`);
INSERT INTO `COMTYPE` (`GPCD`, `TPCD`, `TPNM`, `SORTNO`, `USEYN`, `REF01`, `REF02`, `REF03`, `REF04`, `REF05`, `REF06`, `REF07`, `REF08`, `REF09`, `REF10`, `REF11`, `REF12`, `REF13`, `REF14`, `REF15`, `REF16`, `REF17`, `REF18`, `REF19`, `REF20`, `REMARK`, `RTIME`, `REMP`, `RPRG`, `MTIME`, `MEMP`, `MPRG`) VALUES ('CHKVALTP', '03', 'OK/NG', '0', 'Y', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '') ON DUPLICATE KEY UPDATE `TPNM` = VALUES(`TPNM`), `SORTNO` = VALUES(`SORTNO`), `USEYN` = VALUES(`USEYN`);
INSERT INTO `COMTYPE` (`GPCD`, `TPCD`, `TPNM`, `SORTNO`, `USEYN`) VALUES ('ISSUE', '01', '사용자작업부주의', '1', 'Y') ON DUPLICATE KEY UPDATE `TPNM` = VALUES(`TPNM`), `SORTNO` = VALUES(`SORTNO`), `USEYN` = VALUES(`USEYN`);
INSERT INTO `COMTYPE` (`GPCD`, `TPCD`, `TPNM`, `SORTNO`, `USEYN`) VALUES ('ISSUE', '02', '보전작업미흡', '2', 'Y') ON DUPLICATE KEY UPDATE `TPNM` = VALUES(`TPNM`), `SORTNO` = VALUES(`SORTNO`), `USEYN` = VALUES(`USEYN`);
INSERT INTO `COMTYPE` (`GPCD`, `TPCD`, `TPNM`, `SORTNO`, `USEYN`) VALUES ('ISSUE', '03', '노후', '3', 'Y') ON DUPLICATE KEY UPDATE `TPNM` = VALUES(`TPNM`), `SORTNO` = VALUES(`SORTNO`), `USEYN` = VALUES(`USEYN`);
