CREATE DEFINER=`root`@`%` PROCEDURE `MES_SNS2`.`EQM1001_R03`(
-- *****************************************************************************
-- Comment: 설비점검계획 
-- Create: 	2025-06-27  	생성 			이대규
-- Modify: 	2026-09-15 		마이그레이션	한성수
-- 			2026-09-16 					한성수	MSTEQM.FANO(설비코드) 컬럼 바인딩 변경
-- 			2026-09-21 					한성수	설비별·설비그룹 정기점검 조회/CRUD 추가 및 불필요 조인 단순화
-- 			2026-09-22 					한성수	설비그룹 재조회 선택 키를 EQMGUBUN 기준으로 정리
-- 			2026-09-23 					한성수	정기점검 주기관리 설비등급 조회 추가
-- 			2026-09-29 					한성수	설비그룹 점검계획 그룹코드 단위 변경, 승인상태·반려사유 표시 및 사전집계 튜닝
-- 			2026-09-30 					한성수	승인 리비전(REV) 기준 승인 검증 적용 및 점검항목·주기관리 코드명 반환 추가
-- 			2026-10-01 					한성수	설비그룹 없는 설비의 주기관리 조회·저장·삭제 지원 (설비 승인 기준)
-- 			2026-10-02 					한성수	주기관리 점검자 사원코드화·실적 월 잠금·승인본 대상 통일, 복사 검증 및 성능 개선
-- 			2026-10-06 					한성수	REV·승인·출력 R03 통합, 그룹 체크 제거·최신 REV 조회, DETAIL 중복 컬럼 제거·APRVKEY 이력 발번, 주기 승인 제한 해제·빈 개정내용 승인/반려 차단
-- 			2026-10-07 					한성수	표시 체크·전용 JOIN 제거, 중복 등록 방지, 양 탭 최신 REV·미등록 상태 공란, 최신 계획·REV별 최종 상태 개정이력 출력
-- *****************************************************************************
  IN $FANO           VARCHAR(20),
  IN $FANO_COPY      VARCHAR(20),
  IN $SYEAR          VARCHAR(50),
  IN $EQMGRP         VARCHAR(50),
  IN $CHKKNDCD_LIST  MEDIUMTEXT,
  IN $REMARK_LIST    MEDIUMTEXT,
  IN $USEYN_LIST     MEDIUMTEXT,
  IN $SORTNO_LIST    MEDIUMTEXT,
  IN $YEAR_LIST      MEDIUMTEXT,
  IN $FANO_LIST      MEDIUMTEXT,
  IN $M01_LIST       MEDIUMTEXT,
  IN $M02_LIST       MEDIUMTEXT,
  IN $M03_LIST       MEDIUMTEXT,
  IN $M04_LIST       MEDIUMTEXT,
  IN $M05_LIST       MEDIUMTEXT,
  IN $M06_LIST       MEDIUMTEXT,
  IN $M07_LIST       MEDIUMTEXT,
  IN $M08_LIST       MEDIUMTEXT,
  IN $M09_LIST       MEDIUMTEXT,
  IN $M10_LIST       MEDIUMTEXT,
  IN $M11_LIST       MEDIUMTEXT,
  IN $M12_LIST       MEDIUMTEXT,
  IN $PLANTP         CHAR(1),
  IN $PLANCD         VARCHAR(50),
  IN $REVNUM         VARCHAR(20),
  IN $REMARK         VARCHAR(1000),
  IN $APRVSTT        CHAR(1),
  IN $REJREASON      VARCHAR(1000),

-- *****************************************************************************
IN  $CALLTYPE VARCHAR(50), IN $KEYWORD VARCHAR(1000))
PROC: BEGIN -- @CALLEMP, @CALLPRG, @CALLHOST, @CALLIP, @CALLMAC
-- *****************************************************************************
  DECLARE _$CHKKNDCD      VARCHAR(20);
  DECLARE _$REMARK        VARCHAR(1000);
  DECLARE _$CHKTP         VARCHAR(20);
  DECLARE _$SORTNO        DECIMAL(20, 8);
  DECLARE _$MAXSORTNO     DECIMAL(20, 8);
  DECLARE _$USEYN         VARCHAR(2);

  DECLARE _$M01           VARCHAR(20);
  DECLARE _$M02           VARCHAR(20);
  DECLARE _$M03           VARCHAR(20);
  DECLARE _$M04           VARCHAR(20);
  DECLARE _$M05           VARCHAR(20);
  DECLARE _$M06           VARCHAR(20);
  DECLARE _$M07           VARCHAR(20);
  DECLARE _$M08           VARCHAR(20);
  DECLARE _$M09           VARCHAR(20);
  DECLARE _$M10           VARCHAR(20);
  DECLARE _$M11           VARCHAR(20);
  DECLARE _$M12           VARCHAR(20);
  DECLARE _$YEAR          VARCHAR(20);
  DECLARE _$FANO          VARCHAR(20);
  DECLARE _$LOCKMM        VARCHAR(100);
  DECLARE _$PLANTP        CHAR(1);
  DECLARE _$PLANCD        VARCHAR(50);
  DECLARE _$EQMGRPNM      VARCHAR(1000);
  DECLARE _$EQMCNT        INT;
  DECLARE _$COPYGRP       VARCHAR(50);
  DECLARE _$REVCD         VARCHAR(20);
  DECLARE _$REVNUM        INT;
  DECLARE _$APRVSTT       CHAR(1);
  DECLARE _$REVDATE       VARCHAR(10);
  DECLARE _$REJECT_CNT    INT DEFAULT 0;
  DECLARE _$REJECT_EQM    VARCHAR(1000);

-- 정기점검 CRUD 공통 승인 요청
IF $CALLTYPE IN ('REG_GRP_EQM02', 'SAVE_GRP_EQM02', 'DEL_GRP_EQM02', 'COPY_GRP_EQM02',
                 'REG_EQM02', 'SAVE_EQM02', 'DEL_EQM02', 'COPY_EQM02') THEN
  IF $CALLTYPE LIKE '%GRP%' THEN
    SET _$PLANTP = 'G';
    SET _$PLANCD = $EQMGRP;
    IF COALESCE(_$PLANCD, '') = '' THEN
      CALL COMERR('설비그룹을 지정해주세요.');
      LEAVE PROC;
    END IF;
  ELSE
    SET _$PLANTP = 'E';
    SET _$PLANCD = $FANO;
    IF COALESCE(_$PLANCD, '') = '' THEN
      CALL COMERR('설비를 지정해주세요.');
      LEAVE PROC;
    END IF;
  END IF;

  IF $CALLTYPE IN ('COPY_GRP_EQM02', 'COPY_EQM02') AND COALESCE($FANO_COPY, '') = '' THEN
    CALL COMERR(CASE WHEN _$PLANTP = 'G' THEN '복사할 설비그룹을 지정해주세요.' ELSE '복사할 설비를 지정해주세요.' END);
    LEAVE PROC;
  END IF;

  -- 수정 대상과 연동 대상(설비그룹이면 소속 설비, 설비면 소속 설비그룹)의 반려·대기 리비전은 같은 번호로 다시 대기
  UPDATE MSTEQMREV_HEADER
  INNER JOIN (
    SELECT _$PLANTP AS PLANTP, _$PLANCD AS PLANCD
    UNION ALL
    SELECT 'E', MSTEQM.FANO FROM MSTEQM WHERE _$PLANTP = 'G' AND MSTEQM.EQMGUBUN = _$PLANCD AND MSTEQM.USEYN = 'Y'
    UNION ALL
    SELECT 'G', MSTEQM.EQMGUBUN FROM MSTEQM WHERE _$PLANTP = 'E' AND MSTEQM.FANO = _$PLANCD AND MSTEQM.EQMGUBUN <> ''
  ) PLAN_KEY
    ON PLAN_KEY.PLANTP = MSTEQMREV_HEADER.PLANTP
   AND PLAN_KEY.PLANCD = MSTEQMREV_HEADER.PLANCD
  SET
    MSTEQMREV_HEADER.APRVSTT = '',
    MSTEQMREV_HEADER.APRVTIME = '',
    MSTEQMREV_HEADER.APRVEMP  = '',
    MSTEQMREV_HEADER.APRVPRG  = '',
    MSTEQMREV_HEADER.REJREASON = '',
    MSTEQMREV_HEADER.REQTIME = CALLTIME(),
    MSTEQMREV_HEADER.REQEMP  = CALLEMP(),
    MSTEQMREV_HEADER.REQPRG  = CALLPRG(),
    MSTEQMREV_HEADER.MTIME   = CALLTIME(),
    MSTEQMREV_HEADER.MEMP    = CALLEMP(),
    MSTEQMREV_HEADER.MPRG    = CALLPRG()
  WHERE MSTEQMREV_HEADER.APRVSTT <> 'A';

  -- 마지막 리비전이 승인이거나 없으면 다음 번호로 대기 리비전 생성 (처음은 0: 제정)
  INSERT INTO MSTEQMREV_HEADER (
    REVCD, PLANTP, PLANCD, REVNUM, APRVSTT,
    REQTIME, REQEMP, REQPRG,
    RTIME, REMP, RPRG
  )
  SELECT
    GETKEY('REVCD'), PLAN_KEY.PLANTP, PLAN_KEY.PLANCD, COALESCE(LAST_REV.REVNUM + 1, 0), '',
    CALLTIME(), CALLEMP(), CALLPRG(),
    CALLTIME(), CALLEMP(), CALLPRG()
  FROM (
    SELECT _$PLANTP AS PLANTP, _$PLANCD AS PLANCD
    UNION ALL
    SELECT 'E', MSTEQM.FANO FROM MSTEQM WHERE _$PLANTP = 'G' AND MSTEQM.EQMGUBUN = _$PLANCD AND MSTEQM.USEYN = 'Y'
    UNION ALL
    SELECT 'G', MSTEQM.EQMGUBUN FROM MSTEQM WHERE _$PLANTP = 'E' AND MSTEQM.FANO = _$PLANCD AND MSTEQM.EQMGUBUN <> ''
  ) PLAN_KEY
  LEFT JOIN (
    SELECT PLANTP, PLANCD, MAX(REVNUM) AS REVNUM,
           MAX(CASE WHEN APRVSTT <> 'A' THEN REVNUM END) AS OPENREVNUM
    FROM MSTEQMREV_HEADER
    GROUP BY PLANTP, PLANCD
  ) LAST_REV
    ON LAST_REV.PLANTP = PLAN_KEY.PLANTP
   AND LAST_REV.PLANCD = PLAN_KEY.PLANCD
  WHERE LAST_REV.OPENREVNUM IS NULL
     OR LAST_REV.OPENREVNUM < LAST_REV.REVNUM;
END IF;

CASE $CALLTYPE
-- *****************************************************************************
WHEN 'LIST_MSTEQM_GRP' THEN -- 설비그룹 최신 리비전 조회
  -- 같은 이름의 그룹코드 함께 조회
  SET _$EQMGRPNM = (SELECT TPNM FROM COMTYPE WHERE GPCD = 'FM116' AND TPCD = $EQMGRP LIMIT 1);

  SELECT
    GRP_EQM.EQMGUBUN,
    COMTYPE.TPNM AS EQMGRPNM,
    COMTYPE.SORTNO AS EQMGRPSORTNO,
    PLAN_REV.REVCD,
    COALESCE(CONCAT('REV.', PLAN_REV.REVNUM), '') AS REVNM,
    CASE
      WHEN PLAN_REV.REVCD IS NULL OR PLAN_REV.REVCD = '' THEN ''
      WHEN PLAN_REV.APRVSTT = 'A' THEN '승인'
      WHEN PLAN_REV.APRVSTT = 'R' THEN '반려'
      ELSE '대기'
    END AS APRVSTTNM,
    COALESCE(PLAN_REV.APRVSTT, '') AS APRVSTT,
    CASE WHEN PLAN_REV.APRVSTT = 'R' THEN PLAN_REV.REJREASON ELSE '' END AS REJREASON
  FROM COMTYPE
  INNER JOIN (
    SELECT DISTINCT EQMGUBUN
    FROM MSTEQM
    WHERE USEYN = 'Y'
  ) GRP_EQM
    ON GRP_EQM.EQMGUBUN = COMTYPE.TPCD
  LEFT JOIN (
    SELECT PLANCD, MAX(REVNUM) AS REVNUM
    FROM MSTEQMREV_HEADER
    WHERE PLANTP = 'G'
    GROUP BY PLANCD
  ) LAST_REV
    ON LAST_REV.PLANCD = GRP_EQM.EQMGUBUN
  LEFT JOIN MSTEQMREV_HEADER PLAN_REV
    ON PLAN_REV.PLANTP = 'G'
   AND PLAN_REV.PLANCD = LAST_REV.PLANCD
   AND PLAN_REV.REVNUM = LAST_REV.REVNUM
  WHERE COMTYPE.GPCD = 'FM116'
    AND COMTYPE.USEYN = 'Y'
    AND ($EQMGRP IS NULL OR $EQMGRP = '' OR COMTYPE.TPNM = _$EQMGRPNM)
  ORDER BY COMTYPE.SORTNO, GRP_EQM.EQMGUBUN;
-- *****************************************************************************
WHEN 'LIST_GRP_EQM02' THEN -- 설비그룹 정기점검 항목 조회

  SELECT
    CHKPLANEQM.CHKKNDCD,
    MSTCHKKND.CHKKNDNM,
    MSTCHKKND.CHKLOC,
    MSTCHKKND.CHKMTH,
    MSTCHKKND.CHKVALTP,
    COALESCE(NULLIF(GPCD('CHKLOC', MSTCHKKND.CHKLOC), ''), MSTCHKKND.CHKLOC) AS CHKLOCNM,
    COALESCE(NULLIF(GPCD('CHKMTH', MSTCHKKND.CHKMTH), ''), MSTCHKKND.CHKMTH) AS CHKMTHNM,
    COALESCE(NULLIF(GPCD('CHKVALTP', MSTCHKKND.CHKVALTP), ''), MSTCHKKND.CHKVALTP) AS CHKVALTPNM,
    MSTCHKKND.CHKCYCLE,
    MIN(CHKPLANEQM.SORTNO) AS SORTNO,
    MAX(CASE WHEN CHKPLANEQM.USEYN = 'Y' THEN 'Y' ELSE 'N' END) AS USEYN,
    MAX(CHKPLANEQM.REMARK) AS REMARK
  FROM CHKPLANEQM
  INNER JOIN MSTCHKKND
    ON MSTCHKKND.CHKKNDCD = CHKPLANEQM.CHKKNDCD
  INNER JOIN MSTEQM
    ON MSTEQM.FANO = CHKPLANEQM.EQMCD
  WHERE MSTEQM.EQMGUBUN = $EQMGRP
    AND MSTEQM.USEYN = 'Y'
    AND MSTCHKKND.CHKTP = '02'
  GROUP BY CHKPLANEQM.CHKKNDCD, MSTCHKKND.CHKKNDNM, MSTCHKKND.CHKLOC, MSTCHKKND.CHKMTH, MSTCHKKND.CHKVALTP, MSTCHKKND.CHKCYCLE
  ORDER BY MIN(CHKPLANEQM.SORTNO)
  ;

-- *****************************************************************************
WHEN 'LIST_GRP_EQM02_ADD' THEN -- 설비그룹 미등록 정기점검 항목 조회
  SELECT COUNT(*) INTO _$EQMCNT FROM MSTEQM WHERE EQMGUBUN = $EQMGRP AND USEYN = 'Y';

  SELECT
    MSTCHKKND.CHKKNDCD,
    MSTCHKKND.CHKKNDNM,
    MSTCHKKND.CHKTP,
    MSTCHKKND.CHKLOC,
    MSTCHKKND.CHKMTH,
    MSTCHKKND.CHKVALTP,
    COALESCE(NULLIF(GPCD('CHKLOC', MSTCHKKND.CHKLOC), ''), MSTCHKKND.CHKLOC) AS CHKLOCNM,
    COALESCE(NULLIF(GPCD('CHKMTH', MSTCHKKND.CHKMTH), ''), MSTCHKKND.CHKMTH) AS CHKMTHNM,
    COALESCE(NULLIF(GPCD('CHKVALTP', MSTCHKKND.CHKVALTP), ''), MSTCHKKND.CHKVALTP) AS CHKVALTPNM,
    MSTCHKKND.SORTNO,
    MSTCHKKND.USEYN,
    '' AS REMARK
  FROM MSTCHKKND
  -- 점검항목별 등록 설비 수
  LEFT JOIN (
    SELECT CHKPLANEQM.CHKKNDCD, COUNT(*) AS EQMCNT
    FROM CHKPLANEQM
    INNER JOIN MSTEQM
      ON MSTEQM.FANO = CHKPLANEQM.EQMCD
    WHERE MSTEQM.EQMGUBUN = $EQMGRP
      AND MSTEQM.USEYN = 'Y'
      AND CHKPLANEQM.CHKTP = '02'
    GROUP BY CHKPLANEQM.CHKKNDCD
  ) REG_EQM
    ON REG_EQM.CHKKNDCD = MSTCHKKND.CHKKNDCD
  WHERE MSTCHKKND.USEYN = 'Y'
    AND MSTCHKKND.CHKTP = '02'
    AND COALESCE(REG_EQM.EQMCNT, 0) < _$EQMCNT
  ORDER BY MSTCHKKND.SORTNO
  ;

-- *****************************************************************************
WHEN 'REG_GRP_EQM02' THEN -- 설비그룹 정기점검 항목 등록


  WHILE LENGTH($CHKKNDCD_LIST) > 0 DO
    CALL COMSPLIT($CHKKNDCD_LIST, _$CHKKNDCD);
    CALL COMSPLIT($REMARK_LIST, _$REMARK);

    SET _$CHKTP = (SELECT CHKTP FROM MSTCHKKND WHERE CHKKNDCD = _$CHKKNDCD LIMIT 1);

    INSERT INTO CHKPLANEQM (
      EQMCD, CHKTP, CHKKNDCD, CHKCYCLE,
      SORTNO, USEYN, REMARK,
      RTIME, REMP, RPRG
    )
    SELECT
      MSTEQM.FANO, _$CHKTP, _$CHKKNDCD, 'MONTH',
      COALESCE(SORT_INFO.MAXSORTNO, 0) + 1, 'Y', _$REMARK,
      CALLTIME(), CALLEMP(), CALLPRG()
    FROM MSTEQM
    -- 기존 항목 유무와 마지막 순서를 함께 집계
    LEFT JOIN (
      SELECT EQMCD,
             MAX(CASE WHEN CHKTP = '02' THEN SORTNO END) AS MAXSORTNO,
             MAX(CASE WHEN CHKKNDCD = _$CHKKNDCD AND CHKTP = _$CHKTP THEN 1 ELSE 0 END) AS ITEMEXIST
      FROM CHKPLANEQM
      WHERE CHKTP IN ('02', _$CHKTP)
      GROUP BY EQMCD
    ) SORT_INFO
      ON SORT_INFO.EQMCD = MSTEQM.FANO
    WHERE MSTEQM.EQMGUBUN = $EQMGRP
      AND MSTEQM.USEYN = 'Y'
      AND COALESCE(SORT_INFO.ITEMEXIST, 0) = 0;
  END WHILE;

-- *****************************************************************************
WHEN 'SAVE_GRP_EQM02' THEN -- 설비그룹 정기점검 항목 저장


  WHILE LENGTH($CHKKNDCD_LIST) > 0 DO
    CALL COMSPLIT($CHKKNDCD_LIST, _$CHKKNDCD);
    CALL COMSPLIT($USEYN_LIST, _$USEYN);
    CALL COMSPLIT($SORTNO_LIST, _$SORTNO);
    CALL COMSPLIT($REMARK_LIST, _$REMARK);

    UPDATE CHKPLANEQM
    INNER JOIN MSTEQM
      ON MSTEQM.FANO = CHKPLANEQM.EQMCD
    SET
      CHKPLANEQM.USEYN  = _$USEYN,
      CHKPLANEQM.SORTNO = _$SORTNO,
      CHKPLANEQM.REMARK = _$REMARK,
      CHKPLANEQM.MTIME  = CALLTIME(),
      CHKPLANEQM.MEMP   = CALLEMP(),
      CHKPLANEQM.MPRG   = CALLPRG()
    WHERE MSTEQM.EQMGUBUN = $EQMGRP
      AND MSTEQM.USEYN = 'Y'
      AND CHKPLANEQM.CHKKNDCD = _$CHKKNDCD
      AND CHKPLANEQM.CHKTP = '02'
    ;
  END WHILE;

-- *****************************************************************************
WHEN 'DEL_GRP_EQM02' THEN -- 설비그룹 정기점검 항목 삭제


  WHILE LENGTH($CHKKNDCD_LIST) > 0 DO
    CALL COMSPLIT($CHKKNDCD_LIST, _$CHKKNDCD);

    DELETE CHKPLANEQM
    FROM CHKPLANEQM
    INNER JOIN MSTEQM
      ON MSTEQM.FANO = CHKPLANEQM.EQMCD
    WHERE MSTEQM.EQMGUBUN = $EQMGRP
      AND MSTEQM.USEYN = 'Y'
      AND CHKPLANEQM.CHKKNDCD = _$CHKKNDCD
      AND CHKPLANEQM.CHKTP = '02';
  END WHILE;

-- *****************************************************************************
WHEN 'LIST_COPY_GRP_EQM02' THEN -- 설비그룹 복사 원본 목록 조회

  SELECT
    MSTEQM.EQMGUBUN AS EQMGRP,
    COMTYPE.TPNM AS EQMGRPNM,
    MIN(MSTEQM.FANO) AS FANO,
    COUNT(DISTINCT CHKPLANEQM.CHKKNDCD) AS EQM02CNT
  FROM MSTEQM
  INNER JOIN COMTYPE
    ON COMTYPE.GPCD = 'FM116'
   AND COMTYPE.TPCD = MSTEQM.EQMGUBUN
  INNER JOIN CHKPLANEQM
    ON CHKPLANEQM.EQMCD = MSTEQM.FANO
   AND CHKPLANEQM.CHKTP = '02'
  WHERE MSTEQM.USEYN = 'Y'
    AND MSTEQM.EQMGUBUN <> $EQMGRP
  GROUP BY MSTEQM.EQMGUBUN, COMTYPE.TPNM, COMTYPE.SORTNO
  ORDER BY COMTYPE.SORTNO, MSTEQM.EQMGUBUN
  ;

-- *****************************************************************************
WHEN 'LIST_COPY_GRP_EQM02_DTL' THEN -- 설비그룹 복사 상세 항목 조회

  SELECT
    CHKPLANEQM.CHKKNDCD,
    MSTCHKKND.CHKKNDNM,
    MSTCHKKND.CHKLOC,
    MSTCHKKND.CHKMTH,
    MSTCHKKND.CHKVALTP,
    COALESCE(NULLIF(GPCD('CHKLOC', MSTCHKKND.CHKLOC), ''), MSTCHKKND.CHKLOC) AS CHKLOCNM,
    COALESCE(NULLIF(GPCD('CHKMTH', MSTCHKKND.CHKMTH), ''), MSTCHKKND.CHKMTH) AS CHKMTHNM,
    COALESCE(NULLIF(GPCD('CHKVALTP', MSTCHKKND.CHKVALTP), ''), MSTCHKKND.CHKVALTP) AS CHKVALTPNM,
    MIN(CHKPLANEQM.SORTNO) AS SORTNO,
    MAX(CASE WHEN CHKPLANEQM.USEYN = 'Y' THEN 'Y' ELSE 'N' END) AS USEYN
  FROM CHKPLANEQM
  INNER JOIN MSTEQM
    ON MSTEQM.FANO = CHKPLANEQM.EQMCD
  INNER JOIN MSTCHKKND
    ON MSTCHKKND.CHKKNDCD = CHKPLANEQM.CHKKNDCD
  WHERE MSTEQM.EQMGUBUN = $EQMGRP
    AND MSTEQM.USEYN = 'Y'
    AND CHKPLANEQM.CHKTP = '02'
  GROUP BY CHKPLANEQM.CHKKNDCD, MSTCHKKND.CHKKNDNM, MSTCHKKND.CHKLOC, MSTCHKKND.CHKMTH, MSTCHKKND.CHKVALTP
  ORDER BY MIN(CHKPLANEQM.SORTNO), CHKPLANEQM.CHKKNDCD
  ;

-- *****************************************************************************
WHEN 'COPY_GRP_EQM02' THEN -- 설비그룹 정기점검 항목 복사
  SET _$COPYGRP = (SELECT EQMGUBUN FROM MSTEQM WHERE FANO = $FANO_COPY LIMIT 1);


  DROP TEMPORARY TABLE IF EXISTS TMP_COPY_EQM02;
  CREATE TEMPORARY TABLE TMP_COPY_EQM02 AS
  SELECT
    CHKPLANEQM.CHKTP,
    CHKPLANEQM.CHKKNDCD,
    MIN(CHKPLANEQM.CHKCYCLE) AS CHKCYCLE,
    MIN(CHKPLANEQM.SORTNO) AS SORTNO,
    MAX(CHKPLANEQM.USEYN) AS USEYN,
    MAX(CHKPLANEQM.REMARK) AS REMARK
  FROM MSTEQM SOURCE_EQM
  INNER JOIN CHKPLANEQM
    ON CHKPLANEQM.EQMCD = SOURCE_EQM.FANO
   AND CHKPLANEQM.CHKTP = '02'
  WHERE SOURCE_EQM.USEYN = 'Y'
    AND SOURCE_EQM.EQMGUBUN = _$COPYGRP
  GROUP BY CHKPLANEQM.CHKTP, CHKPLANEQM.CHKKNDCD;

  IF (SELECT COUNT(*) FROM TMP_COPY_EQM02) = 0 THEN
    DROP TEMPORARY TABLE IF EXISTS TMP_COPY_EQM02;
    CALL COMERR('복사할 정기점검 항목이 없습니다.');
    LEAVE PROC;
  END IF;

  INSERT INTO CHKPLANEQM (
    EQMCD, CHKTP, CHKKNDCD, CHKCYCLE,
    SORTNO, USEYN, REMARK,
    RTIME, REMP, RPRG
  )
  SELECT
    MSTEQM.FANO, TMP_COPY_EQM02.CHKTP, TMP_COPY_EQM02.CHKKNDCD, TMP_COPY_EQM02.CHKCYCLE,
    TMP_COPY_EQM02.SORTNO, TMP_COPY_EQM02.USEYN, TMP_COPY_EQM02.REMARK,
    CALLTIME(), CALLEMP(), CALLPRG()
  FROM MSTEQM
  CROSS JOIN TMP_COPY_EQM02
  WHERE MSTEQM.EQMGUBUN = $EQMGRP
    AND MSTEQM.USEYN = 'Y'
  ON DUPLICATE KEY UPDATE
    CHKTP   = VALUES(CHKTP),
    CHKCYCLE = VALUES(CHKCYCLE),
    SORTNO  = VALUES(SORTNO),
    USEYN   = VALUES(USEYN),
    REMARK  = VALUES(REMARK),
    MTIME   = CALLTIME(),
    MEMP    = CALLEMP(),
    MPRG    = CALLPRG();

  DELETE CHKPLANEQM
  FROM CHKPLANEQM
  INNER JOIN MSTEQM
    ON MSTEQM.FANO = CHKPLANEQM.EQMCD
  LEFT JOIN TMP_COPY_EQM02
    ON TMP_COPY_EQM02.CHKKNDCD = CHKPLANEQM.CHKKNDCD
  WHERE MSTEQM.EQMGUBUN = $EQMGRP
    AND MSTEQM.USEYN = 'Y'
    AND CHKPLANEQM.CHKTP = '02'
    AND TMP_COPY_EQM02.CHKKNDCD IS NULL;

  DROP TEMPORARY TABLE IF EXISTS TMP_COPY_EQM02;

-- *****************************************************************************
WHEN 'LIST_MSTEQM' THEN -- 설비 목록 조회

  SELECT
    MSTEQM.FANO,
    MSTEQM.EQMNM,
    COALESCE(CONCAT('REV.', PLAN_REV.REVNUM), '') AS REVNM,
    CASE
      WHEN PLAN_REV.REVCD IS NULL OR PLAN_REV.REVCD = '' THEN ''
      WHEN PLAN_REV.APRVSTT = 'A' THEN '승인'
      WHEN PLAN_REV.APRVSTT = 'R' THEN '반려'
      ELSE '대기'
    END AS APRVSTTNM,
    COALESCE(PLAN_REV.APRVSTT, '') AS APRVSTT,
    CASE WHEN PLAN_REV.APRVSTT = 'R' THEN PLAN_REV.REJREASON ELSE '' END AS REJREASON
  FROM MSTEQM
  LEFT JOIN (
    SELECT PLANCD, MAX(REVNUM) AS REVNUM
    FROM MSTEQMREV_HEADER
    WHERE PLANTP = 'E'
    GROUP BY PLANCD
  ) LAST_REV
    ON LAST_REV.PLANCD = MSTEQM.FANO
  LEFT JOIN MSTEQMREV_HEADER PLAN_REV
    ON PLAN_REV.PLANTP = 'E'
   AND PLAN_REV.PLANCD = LAST_REV.PLANCD
   AND PLAN_REV.REVNUM = LAST_REV.REVNUM
  WHERE MSTEQM.USEYN = 'Y'
    AND (MSTEQM.FANO LIKE CONCAT('%', $FANO, '%') OR MSTEQM.EQMNM LIKE CONCAT('%', $FANO, '%'))
  ORDER BY MSTEQM.FANO;

-- *****************************************************************************
WHEN 'LIST_MSTEQM_EQM02' THEN -- 설비별 정기점검 항목 조회
  SELECT 
    CHKPLANEQM.CHKKNDCD,
    MSTCHKKND.CHKKNDNM,
    MSTCHKKND.CHKLOC,
    MSTCHKKND.CHKMTH,
    MSTCHKKND.CHKVALTP,
    COALESCE(NULLIF(GPCD('CHKLOC', MSTCHKKND.CHKLOC), ''), MSTCHKKND.CHKLOC) AS CHKLOCNM,
    COALESCE(NULLIF(GPCD('CHKMTH', MSTCHKKND.CHKMTH), ''), MSTCHKKND.CHKMTH) AS CHKMTHNM,
    COALESCE(NULLIF(GPCD('CHKVALTP', MSTCHKKND.CHKVALTP), ''), MSTCHKKND.CHKVALTP) AS CHKVALTPNM,
    MSTCHKKND.CHKCYCLE,
    CHKPLANEQM.SORTNO,
    CASE WHEN CHKPLANEQM.USEYN = 'Y' THEN 'Y' ELSE 'N' END AS USEYN,
    CHKPLANEQM.REMARK
  FROM CHKPLANEQM
  INNER JOIN MSTCHKKND 
    ON MSTCHKKND.CHKKNDCD = CHKPLANEQM.CHKKNDCD  
  WHERE CHKPLANEQM.EQMCD = $FANO
    AND MSTCHKKND.CHKTP = '02'  
  ORDER BY  CHKPLANEQM.SORTNO
  ;

-- *****************************************************************************
WHEN 'LIST_EQM02' THEN -- 설비별 미등록 정기점검 항목 조회

  SELECT 
    MSTCHKKND.CHKKNDCD,
    MSTCHKKND.CHKKNDNM,
    MSTCHKKND.CHKTP,
    MSTCHKKND.CHKLOC,
    MSTCHKKND.CHKMTH,
    MSTCHKKND.CHKVALTP,
    COALESCE(NULLIF(GPCD('CHKLOC', MSTCHKKND.CHKLOC), ''), MSTCHKKND.CHKLOC) AS CHKLOCNM,
    COALESCE(NULLIF(GPCD('CHKMTH', MSTCHKKND.CHKMTH), ''), MSTCHKKND.CHKMTH) AS CHKMTHNM,
    COALESCE(NULLIF(GPCD('CHKVALTP', MSTCHKKND.CHKVALTP), ''), MSTCHKKND.CHKVALTP) AS CHKVALTPNM,
    MSTCHKKND.SORTNO,
    MSTCHKKND.USEYN,
    '' AS REMARK
  FROM MSTCHKKND
  LEFT JOIN CHKPLANEQM 
    ON CHKPLANEQM.CHKKNDCD = MSTCHKKND.CHKKNDCD 
   AND CHKPLANEQM.EQMCD = $FANO
  WHERE MSTCHKKND.USEYN = 'Y'
    AND MSTCHKKND.CHKTP = '02'
    AND CHKPLANEQM.CHKKNDCD IS NULL
  ORDER BY MSTCHKKND.SORTNO
  ;

-- *****************************************************************************
WHEN 'REG_EQM02' THEN -- 설비별 정기점검 항목 등록

  
  WHILE LENGTH($CHKKNDCD_LIST) > 0 DO
    CALL COMSPLIT($CHKKNDCD_LIST, _$CHKKNDCD);
    CALL COMSPLIT($REMARK_LIST, _$REMARK);
  
    SET _$CHKTP = (SELECT CHKTP FROM MSTCHKKND WHERE CHKKNDCD = _$CHKKNDCD LIMIT 1);
    SET _$MAXSORTNO = (SELECT IFNULL(MAX(SORTNO), 0) FROM CHKPLANEQM  WHERE EQMCD = $FANO AND CHKTP = _$CHKTP);
    SET _$SORTNO = _$MAXSORTNO + 1;

    INSERT INTO CHKPLANEQM ( 
      EQMCD, CHKTP, CHKKNDCD, CHKCYCLE, 
      SORTNO, USEYN, REMARK, 
      RTIME, REMP, RPRG 
    ) 
    VALUES (
      $FANO, _$CHKTP, _$CHKKNDCD, 'MONTH',
      _$SORTNO, 'Y', _$REMARK,
      CALLTIME(), CALLEMP(), CALLPRG()
    )
    ON DUPLICATE KEY UPDATE CHKKNDCD = VALUES(CHKKNDCD);     
  END WHILE;
-- *****************************************************************************
WHEN 'SAVE_EQM02' THEN -- 설비별 정기점검 항목 저장

  
  WHILE LENGTH($CHKKNDCD_LIST) > 0 DO
    CALL COMSPLIT($CHKKNDCD_LIST, _$CHKKNDCD);
    CALL COMSPLIT($USEYN_LIST, _$USEYN);
    CALL COMSPLIT($SORTNO_LIST, _$SORTNO);
    CALL COMSPLIT($REMARK_LIST, _$REMARK);

    UPDATE CHKPLANEQM SET
      USEYN  = _$USEYN,
      SORTNO = _$SORTNO,
      REMARK = _$REMARK,
      MTIME  = CALLTIME(),
      MEMP   = CALLEMP(),
      MPRG   = CALLPRG()
    WHERE EQMCD = $FANO
     AND CHKKNDCD = _$CHKKNDCD
     AND CHKTP = '02'
    ;
  END WHILE;
-- *****************************************************************************
WHEN 'DEL_EQM02' THEN -- 설비별 정기점검 항목 삭제

  
  WHILE LENGTH($CHKKNDCD_LIST) > 0 DO
    CALL COMSPLIT($CHKKNDCD_LIST, _$CHKKNDCD);
    
    DELETE FROM CHKPLANEQM 
    WHERE EQMCD = $FANO 
    AND CHKKNDCD = _$CHKKNDCD  
    AND CHKTP = '02';    
  END WHILE;

-- *****************************************************************************
WHEN 'LIST_COPY_EQM02' THEN -- 설비별 복사 원본 목록 조회

  SELECT 
    MSTEQM.FANO,
    MSTEQM.EQMNM
  FROM MSTEQM
  INNER JOIN CHKPLANEQM CP 
    ON CP.EQMCD = MSTEQM.FANO 
   AND CP.CHKTP = '02'
  WHERE MSTEQM.FANO <> $FANO
  GROUP BY MSTEQM.FANO, MSTEQM.EQMNM
  ORDER BY MSTEQM.FANO;

  SELECT 
    CHKPLANEQM.CHKKNDCD,
    MSTCHKKND.CHKKNDNM,
    MSTCHKKND.CHKLOC,
    MSTCHKKND.CHKMTH,
    MSTCHKKND.CHKVALTP,
    COALESCE(NULLIF(GPCD('CHKLOC', MSTCHKKND.CHKLOC), ''), MSTCHKKND.CHKLOC) AS CHKLOCNM,
    COALESCE(NULLIF(GPCD('CHKMTH', MSTCHKKND.CHKMTH), ''), MSTCHKKND.CHKMTH) AS CHKMTHNM,
    COALESCE(NULLIF(GPCD('CHKVALTP', MSTCHKKND.CHKVALTP), ''), MSTCHKKND.CHKVALTP) AS CHKVALTPNM,
    CHKPLANEQM.SORTNO
  FROM CHKPLANEQM
  INNER JOIN MSTCHKKND 
    ON MSTCHKKND.CHKKNDCD = CHKPLANEQM.CHKKNDCD  
  WHERE CHKPLANEQM.EQMCD = $FANO
    AND CHKPLANEQM.CHKTP = '02'  
  ORDER BY  CHKPLANEQM.SORTNO
  ;

-- *****************************************************************************
WHEN 'COPY_EQM02' THEN -- 설비별 정기점검 항목 복사


  DELETE FROM CHKPLANEQM 
  WHERE EQMCD = $FANO  
  AND CHKTP = '02'; 

  -- 원본 설비 정기점검 항목 일괄 등록
  INSERT INTO CHKPLANEQM ( 
    EQMCD, CHKTP, CHKKNDCD, CHKCYCLE, 
    SORTNO, USEYN, REMARK, 
    RTIME, REMP, RPRG 
  ) 
  SELECT
    $FANO, MSTCHKKND.CHKTP, CHKPLANEQM.CHKKNDCD, CHKPLANEQM.CHKCYCLE,
    CHKPLANEQM.SORTNO, CHKPLANEQM.USEYN, CHKPLANEQM.REMARK,
    CALLTIME(), CALLEMP(), CALLPRG()
  FROM CHKPLANEQM
  INNER JOIN MSTCHKKND
    ON MSTCHKKND.CHKKNDCD = CHKPLANEQM.CHKKNDCD
  WHERE CHKPLANEQM.EQMCD = $FANO_COPY
    AND CHKPLANEQM.CHKTP = '02';

-- *****************************************************************************
WHEN 'LIST_PLAN_REV' THEN -- 점검계획 리비전 이력 조회
  SELECT
    CONCAT('REV.', MSTEQMREV_HEADER.REVNUM) AS REVNM,
    CASE MSTEQMREV_HEADER.APRVSTT
      WHEN 'A' THEN '승인'
      WHEN 'R' THEN '반려'
      ELSE '대기'
    END AS APRVSTTNM,
    MSTEQMREV_HEADER.REMARK,
    COALESCE(REQ_EMP.EMPNM, MSTEQMREV_HEADER.REQEMP) AS REQEMP,
    MSTEQMREV_HEADER.REQTIME,
    CASE WHEN MSTEQMREV_HEADER.APRVSTT = 'A' THEN COALESCE(APRV_EMP.EMPNM, MSTEQMREV_HEADER.APRVEMP) ELSE '' END AS APRVEMP,
    CASE WHEN MSTEQMREV_HEADER.APRVSTT IN ('A', 'R') THEN MSTEQMREV_HEADER.APRVTIME ELSE '' END AS APRVTIME,
    CASE WHEN MSTEQMREV_HEADER.APRVSTT = 'R' THEN MSTEQMREV_HEADER.REJREASON ELSE '' END AS REJREASON,
    MSTEQMREV_HEADER.REVNUM,
    MSTEQMREV_HEADER.APRVSTT
  FROM MSTEQMREV_HEADER
  LEFT JOIN MSTEMP REQ_EMP
    ON REQ_EMP.EMPCD = MSTEQMREV_HEADER.REQEMP
  LEFT JOIN MSTEMP APRV_EMP
    ON APRV_EMP.EMPCD = MSTEQMREV_HEADER.APRVEMP
  WHERE MSTEQMREV_HEADER.PLANTP = $PLANTP
    AND MSTEQMREV_HEADER.PLANCD = $PLANCD
  ORDER BY MSTEQMREV_HEADER.REVNUM DESC;

-- *****************************************************************************
WHEN 'LIST_PLAN_REV_ITEM' THEN -- 리비전 승인본 점검 항목 조회
  SELECT
    MSTEQMREV_DETAIL.CHKKNDCD,
    MSTEQMREV_DETAIL.CHKKNDNM,
    MSTEQMREV_DETAIL.CHKLOC,
    MSTEQMREV_DETAIL.CHKMTH,
    MSTEQMREV_DETAIL.CHKVALTP,
    COALESCE(NULLIF(GPCD('CHKLOC', MSTEQMREV_DETAIL.CHKLOC), ''), MSTEQMREV_DETAIL.CHKLOC) AS CHKLOCNM,
    COALESCE(NULLIF(GPCD('CHKMTH', MSTEQMREV_DETAIL.CHKMTH), ''), MSTEQMREV_DETAIL.CHKMTH) AS CHKMTHNM,
    COALESCE(NULLIF(GPCD('CHKVALTP', MSTEQMREV_DETAIL.CHKVALTP), ''), MSTEQMREV_DETAIL.CHKVALTP) AS CHKVALTPNM,
    MSTEQMREV_DETAIL.SORTNO,
    'Y' AS USEYN,
    MSTEQMREV_DETAIL.REMARK
  FROM MSTEQMREV_HEADER ITEM_REV
  INNER JOIN MSTEQMREV_DETAIL
    ON MSTEQMREV_DETAIL.REVCD = ITEM_REV.REVCD
  WHERE ITEM_REV.PLANTP = $PLANTP
    AND ITEM_REV.PLANCD = $PLANCD
    AND ITEM_REV.REVNUM = $REVNUM
  ORDER BY MSTEQMREV_DETAIL.SORTNO;

-- *****************************************************************************
WHEN 'SAVE_PLAN_REV' THEN -- 진행 중 리비전 개정내용 저장
  IF COALESCE($PLANTP, '') NOT IN ('G', 'E') OR COALESCE($PLANCD, '') = '' OR COALESCE($REVNUM, '') NOT REGEXP '^[0-9]+$' THEN
    CALL COMERR('진행 중인 REV가 없습니다. 정기점검을 수정하면 새 REV가 생깁니다.');
    LEAVE PROC;
  END IF;

  IF NOT EXISTS (SELECT 1
                 FROM MSTEQMREV_HEADER
                 WHERE PLANTP = $PLANTP
                   AND PLANCD = $PLANCD
                   AND REVNUM = $REVNUM
                   AND APRVSTT <> 'A') THEN
    CALL COMERR('진행 중인 REV가 없습니다. 정기점검을 수정하면 새 REV가 생깁니다.');
    LEAVE PROC;
  END IF;

  UPDATE MSTEQMREV_HEADER
  SET
    REMARK  = COALESCE($REMARK, ''),
    REQTIME = CALLTIME(),
    REQEMP  = CALLEMP(),
    REQPRG  = CALLPRG(),
    MTIME   = CALLTIME(),
    MEMP    = CALLEMP(),
    MPRG    = CALLPRG()
  WHERE PLANTP = $PLANTP
    AND PLANCD = $PLANCD
    AND REVNUM = $REVNUM
    AND APRVSTT <> 'A';

-- *****************************************************************************
WHEN 'SAVE_PLAN_STATUS' THEN -- 점검계획 승인/반려 상태 저장
  IF COALESCE($PLANCD, '') = '' THEN
    CALL COMERR('승인·반려할 점검계획을 선택해주세요.');
    LEAVE PROC;
  END IF;

  IF $PLANTP IS NULL OR $PLANTP NOT IN ('G', 'E') OR $PLANCD IS NULL OR $PLANCD = '' THEN
    CALL COMERR('승인 대상이 올바르지 않습니다.');
    LEAVE PROC;
  END IF;

  IF $APRVSTT IS NULL OR $APRVSTT NOT IN ('A', 'R') THEN
    CALL COMERR('승인 상태가 올바르지 않습니다.');
    LEAVE PROC;
  END IF;

  IF $APRVSTT = 'R' AND TRIM(COALESCE($REJREASON, '')) = '' THEN
    CALL COMERR('반려 사유를 입력해주세요.');
    LEAVE PROC;
  END IF;

  IF COALESCE($REVNUM, '') NOT REGEXP '^[0-9]+$' THEN
    CALL COMERR('승인·반려할 REV를 선택해주세요.');
    LEAVE PROC;
  END IF;

  SELECT MSTEQMREV_HEADER.REVCD, MSTEQMREV_HEADER.REVNUM, MSTEQMREV_HEADER.REMARK, MSTEQMREV_HEADER.APRVSTT
    INTO _$REVCD, _$REVNUM, _$REMARK, _$APRVSTT
  FROM MSTEQMREV_HEADER
  WHERE MSTEQMREV_HEADER.PLANTP = $PLANTP
    AND MSTEQMREV_HEADER.PLANCD = $PLANCD
  ORDER BY MSTEQMREV_HEADER.REVNUM DESC
  LIMIT 1 FOR UPDATE;

  IF _$REVNUM IS NOT NULL AND _$REVNUM <> CAST($REVNUM AS UNSIGNED) THEN
    CALL COMERR('최신 REV만 승인·반려할 수 있습니다. 다시 조회해주세요.');
    LEAVE PROC;
  END IF;

  IF _$REVNUM IS NULL OR _$APRVSTT = 'A' THEN
    CALL COMERR('진행 중인 개정이 없습니다. 점검계획을 수정한 뒤 승인·반려해주세요.');
    LEAVE PROC;
  END IF;

  IF COALESCE(_$REMARK, '') <> COALESCE($REMARK, '') THEN
    CALL COMERR('개정내용이 변경되었습니다. 개정내용 저장 후 다시 조회해주세요.');
    LEAVE PROC;
  END IF;

  IF TRIM(COALESCE(_$REMARK, '')) = '' THEN
    CALL COMERR('개정내용을 입력하고 [개정내용 저장] 후 승인·반려해주세요.');
    LEAVE PROC;
  END IF;

  -- 설비그룹 승인 시 반려된 소속 설비가 있으면 승인 불가 (반려 설비를 수정하거나 설비별로 승인한 뒤 그룹 승인)
  IF $PLANTP = 'G' AND $APRVSTT = 'A' THEN
    SELECT COUNT(*),
           SUBSTRING_INDEX(GROUP_CONCAT(MSTEQM.FANO ORDER BY MSTEQM.FANO SEPARATOR ', '), ', ', 5)
      INTO _$REJECT_CNT, _$REJECT_EQM
    FROM MSTEQM
    INNER JOIN MSTEQMREV_HEADER EQM_REV
      ON EQM_REV.PLANTP = 'E'
     AND EQM_REV.PLANCD = MSTEQM.FANO
     AND EQM_REV.APRVSTT = 'R'
    WHERE MSTEQM.EQMGUBUN = $PLANCD
      AND MSTEQM.USEYN = 'Y';

    IF _$REJECT_CNT > 0 THEN
      CALL COMERR(CONCAT('반려된 설비가 있어 설비그룹을 승인할 수 없습니다. [', _$REJECT_EQM,
                         CASE WHEN _$REJECT_CNT > 5 THEN CONCAT(' 외 ', _$REJECT_CNT - 5, '대') ELSE '' END,
                         '] 해당 설비의 점검계획을 수정하거나 설비별로 승인한 뒤 다시 승인해주세요.'));
      LEAVE PROC;
    END IF;
  END IF;

  IF $APRVSTT = 'A' THEN
    -- 설비 승인본 (선택 설비, 설비그룹이면 진행 중인 소속 설비)
    INSERT INTO MSTEQMREV_DETAIL (
      REVCD, CHKKNDCD,
      CHKCYCLE, SORTNO, CHKKNDNM, CHKLOC, CHKMTH, CHKVALTP, REMARK,
      RTIME, REMP, RPRG
    )
    SELECT
      EQM_REV.REVCD, CHKPLANEQM.CHKKNDCD,
      CHKPLANEQM.CHKCYCLE, CHKPLANEQM.SORTNO, MSTCHKKND.CHKKNDNM, MSTCHKKND.CHKLOC, MSTCHKKND.CHKMTH, MSTCHKKND.CHKVALTP, CHKPLANEQM.REMARK,
      CALLTIME(), CALLEMP(), CALLPRG()
    FROM MSTEQM
    INNER JOIN MSTEQMREV_HEADER EQM_REV
      ON EQM_REV.PLANTP = 'E'
     AND EQM_REV.PLANCD = MSTEQM.FANO
     AND EQM_REV.APRVSTT <> 'A'
    INNER JOIN CHKPLANEQM
      ON CHKPLANEQM.EQMCD = MSTEQM.FANO
     AND CHKPLANEQM.CHKTP = '02'
     AND CHKPLANEQM.USEYN = 'Y'
    INNER JOIN MSTCHKKND
      ON MSTCHKKND.CHKKNDCD = CHKPLANEQM.CHKKNDCD
    WHERE MSTEQM.USEYN = 'Y'
      AND (($PLANTP = 'E' AND MSTEQM.FANO = $PLANCD)
        OR ($PLANTP = 'G' AND MSTEQM.EQMGUBUN = $PLANCD));

    -- 설비그룹 승인본 (소속 설비 전체 항목을 점검항목 단위로)
    IF $PLANTP = 'G' THEN
      INSERT INTO MSTEQMREV_DETAIL (
        REVCD, CHKKNDCD,
        CHKCYCLE, SORTNO, CHKKNDNM, CHKLOC, CHKMTH, CHKVALTP, REMARK,
        RTIME, REMP, RPRG
      )
      SELECT
        _$REVCD, CHKPLANEQM.CHKKNDCD,
        MIN(CHKPLANEQM.CHKCYCLE), MIN(CHKPLANEQM.SORTNO), MSTCHKKND.CHKKNDNM, MSTCHKKND.CHKLOC, MSTCHKKND.CHKMTH, MSTCHKKND.CHKVALTP, MAX(CHKPLANEQM.REMARK),
        CALLTIME(), CALLEMP(), CALLPRG()
      FROM MSTEQM
      INNER JOIN CHKPLANEQM
        ON CHKPLANEQM.EQMCD = MSTEQM.FANO
       AND CHKPLANEQM.CHKTP = '02'
       AND CHKPLANEQM.USEYN = 'Y'
      INNER JOIN MSTCHKKND
        ON MSTCHKKND.CHKKNDCD = CHKPLANEQM.CHKKNDCD
      WHERE MSTEQM.EQMGUBUN = $PLANCD
        AND MSTEQM.USEYN = 'Y'
      GROUP BY CHKPLANEQM.CHKKNDCD, MSTCHKKND.CHKKNDNM, MSTCHKKND.CHKLOC, MSTCHKKND.CHKMTH, MSTCHKKND.CHKVALTP;
    END IF;
  END IF;

  -- 승인·반려 기록은 리비전별로 누적하고 현재 상태는 헤더에서 관리
  INSERT INTO CHKPLANEQM_APRV (
    APRVKEY, REVCD, PLANTP, PLANCD, APRVSTT, REQTIME, REQEMP, REQPRG,
    APRVTIME, APRVEMP, APRVPRG, REJREASON, RTIME, REMP, RPRG
  )
  SELECT
    GETKEY('APRVKEY'), MSTEQMREV_HEADER.REVCD, MSTEQMREV_HEADER.PLANTP, MSTEQMREV_HEADER.PLANCD, $APRVSTT,
    MSTEQMREV_HEADER.REQTIME, MSTEQMREV_HEADER.REQEMP, MSTEQMREV_HEADER.REQPRG,
    CALLTIME(), CALLEMP(), CALLPRG(), CASE WHEN $APRVSTT = 'R' THEN $REJREASON ELSE '' END,
    CALLTIME(), CALLEMP(), CALLPRG()
  FROM MSTEQMREV_HEADER
  LEFT JOIN MSTEQM
    ON MSTEQMREV_HEADER.PLANTP = 'E'
   AND MSTEQM.FANO = MSTEQMREV_HEADER.PLANCD
  WHERE MSTEQMREV_HEADER.APRVSTT <> 'A'
    AND ((MSTEQMREV_HEADER.PLANTP = $PLANTP AND MSTEQMREV_HEADER.PLANCD = $PLANCD)
      OR ($PLANTP = 'G' AND MSTEQMREV_HEADER.PLANTP = 'E' AND MSTEQM.EQMGUBUN = $PLANCD AND MSTEQM.USEYN = 'Y'));

  -- 진행 중 리비전 확정 (설비그룹이면 진행 중인 소속 설비 리비전도 함께, 빈 개정내용은 선택 대상 내용으로)
  UPDATE MSTEQMREV_HEADER
  LEFT JOIN MSTEQM
    ON MSTEQMREV_HEADER.PLANTP = 'E'
   AND MSTEQM.FANO = MSTEQMREV_HEADER.PLANCD
  SET
    MSTEQMREV_HEADER.APRVSTT   = $APRVSTT,
    MSTEQMREV_HEADER.REMARK    = CASE WHEN $APRVSTT = 'A' AND MSTEQMREV_HEADER.REMARK = '' THEN _$REMARK ELSE MSTEQMREV_HEADER.REMARK END,
    MSTEQMREV_HEADER.APRVTIME  = CALLTIME(),
    MSTEQMREV_HEADER.APRVEMP   = CASE WHEN $APRVSTT = 'A' THEN CALLEMP() ELSE '' END,
    MSTEQMREV_HEADER.APRVPRG   = CALLPRG(),
    MSTEQMREV_HEADER.REJREASON = CASE WHEN $APRVSTT = 'R' THEN $REJREASON ELSE '' END,
    MSTEQMREV_HEADER.MTIME     = CALLTIME(),
    MSTEQMREV_HEADER.MEMP      = CALLEMP(),
    MSTEQMREV_HEADER.MPRG      = CALLPRG()
  WHERE MSTEQMREV_HEADER.APRVSTT <> 'A'
    AND ((MSTEQMREV_HEADER.PLANTP = $PLANTP AND MSTEQMREV_HEADER.PLANCD = $PLANCD)
      OR ($PLANTP = 'G' AND MSTEQMREV_HEADER.PLANTP = 'E' AND MSTEQM.EQMGUBUN = $PLANCD AND MSTEQM.USEYN = 'Y'));

-- *****************************************************************************
WHEN 'LIST_PLAN_APRV' THEN -- 선택 리비전 승인·반려 이력 조회
  IF COALESCE($PLANTP, '') NOT IN ('G', 'E') OR COALESCE($PLANCD, '') = ''
     OR COALESCE($REVNUM, '') NOT REGEXP '^[0-9]+$' THEN
    CALL COMERR('이력을 조회할 REV를 선택해주세요.');
    LEAVE PROC;
  END IF;

  SET _$REVCD = (SELECT REVCD FROM MSTEQMREV_HEADER
                WHERE PLANTP = $PLANTP AND PLANCD = $PLANCD AND REVNUM = $REVNUM LIMIT 1);

  SELECT
    CONCAT('REV.', $REVNUM) AS REVNM,
    CASE CHKPLANEQM_APRV.APRVSTT WHEN 'A' THEN '승인' WHEN 'R' THEN '반려' END AS APRVSTTNM,
    COALESCE(MSTEMP.EMPNM, CHKPLANEQM_APRV.APRVEMP) AS APRVEMP,
    CHKPLANEQM_APRV.APRVTIME,
    CHKPLANEQM_APRV.REJREASON
  FROM CHKPLANEQM_APRV
  LEFT JOIN MSTEMP
    ON MSTEMP.EMPCD = CHKPLANEQM_APRV.APRVEMP
  WHERE CHKPLANEQM_APRV.REVCD = _$REVCD
    AND CHKPLANEQM_APRV.PLANTP = $PLANTP
    AND CHKPLANEQM_APRV.PLANCD = $PLANCD
    AND CHKPLANEQM_APRV.APRVSTT IN ('A', 'R')
  ORDER BY CHKPLANEQM_APRV.APRVTIME DESC, CHKPLANEQM_APRV.APRVKEY DESC;

-- *****************************************************************************
WHEN 'CALL_PLAN_RPT' THEN -- 점검계획서 출력 데이터 조회 (설비그룹·설비, 승인상태와 무관)
  SET _$PLANTP = CASE WHEN $PLANTP = 'E' THEN 'E' ELSE 'G' END;
  SET _$PLANCD = $PLANCD;

  IF COALESCE($PLANTP, '') NOT IN ('G', 'E') OR COALESCE($PLANCD, '') = '' THEN
    CALL COMERR('출력할 설비그룹 또는 설비를 선택해주세요.');
    LEAVE PROC;
  END IF;

  -- 최신 리비전 출력 (승인은 승인본, 진행 중은 현재 계획)
  SELECT MSTEQMREV_HEADER.REVCD, MSTEQMREV_HEADER.REVNUM, MSTEQMREV_HEADER.APRVSTT,
         LEFT(CASE WHEN MSTEQMREV_HEADER.APRVSTT = 'A' THEN MSTEQMREV_HEADER.APRVTIME ELSE MSTEQMREV_HEADER.REQTIME END, 10)
    INTO _$REVCD, _$REVNUM, _$APRVSTT, _$REVDATE
  FROM MSTEQMREV_HEADER
  WHERE MSTEQMREV_HEADER.PLANTP = _$PLANTP
    AND MSTEQMREV_HEADER.PLANCD = _$PLANCD
  ORDER BY MSTEQMREV_HEADER.REVNUM DESC
  LIMIT 1;

  IF _$REVCD IS NULL THEN
    CALL COMERR('출력할 REV가 없습니다. 다시 조회해주세요.');
    LEAVE PROC;
  END IF;

  -- 계획서 상단 (설비그룹은 소속 설비의 설비번호·규격·라인·공정을 모아서 표시)
  SELECT
    CASE WHEN _$PLANTP = 'E' THEN MAX(MSTEQM.EQMNM) ELSE COALESCE(MAX(COMTYPE.TPNM), _$PLANCD) END AS EQMNM,
    GROUP_CONCAT(MSTEQM.FANO ORDER BY MSTEQM.FANO SEPARATOR ', ') AS EQMCD,
    COALESCE(GROUP_CONCAT(DISTINCT NULLIF(MSTEQM.EQMNM_DETAIL, '') SEPARATOR ', '), '') AS EQMSPEC,
    COALESCE(GROUP_CONCAT(DISTINCT COALESCE(NULLIF(MSTLINE.LINENM, ''), NULLIF(MSTEQM.LINECD, '')) SEPARATOR ', '), '') AS LINENM,
    COALESCE(GROUP_CONCAT(DISTINCT COALESCE(NULLIF(GPCD('FM100', MSTEQM.EQMTP), ''), NULLIF(MSTEQM.EQMTP, '')) SEPARATOR ', '), '') AS PROCESSNM,
    COALESCE(CONCAT('REV.', _$REVNUM), '') AS REVNM,
    COALESCE(_$REVDATE, '') AS REVDATE
  FROM MSTEQM
  LEFT JOIN MSTLINE
    ON MSTLINE.LINECD = MSTEQM.LINECD
  LEFT JOIN COMTYPE
    ON COMTYPE.GPCD = 'FM116'
   AND COMTYPE.TPCD = MSTEQM.EQMGUBUN
  WHERE MSTEQM.USEYN = 'Y'
    AND ((_$PLANTP = 'E' AND MSTEQM.FANO = _$PLANCD)
      OR (_$PLANTP = 'G' AND MSTEQM.EQMGUBUN = _$PLANCD))
  HAVING COUNT(*) > 0;

  -- 계획서 점검 항목
  IF _$APRVSTT = 'A' THEN
    -- 승인된 리비전: 승인본
    SELECT
      ROW_NUMBER() OVER (ORDER BY MSTEQMREV_DETAIL.SORTNO, MSTEQMREV_DETAIL.CHKKNDCD) AS NO,
      COALESCE(NULLIF(GPCD('CHKLOC', MSTEQMREV_DETAIL.CHKLOC), ''), MSTEQMREV_DETAIL.CHKLOC) AS CHKITEM,
      MSTEQMREV_DETAIL.CHKKNDNM AS CHKCONTENT,
      COALESCE(NULLIF(GPCD('CHKMTH', MSTEQMREV_DETAIL.CHKMTH), ''), MSTEQMREV_DETAIL.CHKMTH) AS CHKDEVICE,
      COALESCE(NULLIF(GPCD('CHKVALTP', MSTEQMREV_DETAIL.CHKVALTP), ''), MSTEQMREV_DETAIL.CHKVALTP) AS CHKRESULT,
      '' AS CONFIRM,
      '' AS REMARK
    FROM MSTEQMREV_DETAIL
    WHERE MSTEQMREV_DETAIL.REVCD = _$REVCD
    ORDER BY MSTEQMREV_DETAIL.SORTNO, MSTEQMREV_DETAIL.CHKKNDCD;
  ELSE
    -- 대기·반려 리비전: 현재 계획 (설비그룹은 점검항목 단위로 합침)
    SELECT
      ROW_NUMBER() OVER (ORDER BY PLAN_ITEM.SORTNO, PLAN_ITEM.CHKKNDCD) AS NO,
      COALESCE(NULLIF(GPCD('CHKLOC', MSTCHKKND.CHKLOC), ''), MSTCHKKND.CHKLOC) AS CHKITEM,
      MSTCHKKND.CHKKNDNM AS CHKCONTENT,
      COALESCE(NULLIF(GPCD('CHKMTH', MSTCHKKND.CHKMTH), ''), MSTCHKKND.CHKMTH) AS CHKDEVICE,
      COALESCE(NULLIF(GPCD('CHKVALTP', MSTCHKKND.CHKVALTP), ''), MSTCHKKND.CHKVALTP) AS CHKRESULT,
      '' AS CONFIRM,
      '' AS REMARK
    FROM (
      SELECT CHKPLANEQM.CHKKNDCD, MIN(CHKPLANEQM.SORTNO) AS SORTNO
      FROM CHKPLANEQM
      INNER JOIN MSTEQM
        ON MSTEQM.FANO = CHKPLANEQM.EQMCD
      WHERE CHKPLANEQM.CHKTP = '02'
        AND CHKPLANEQM.USEYN = 'Y'
        AND MSTEQM.USEYN = 'Y'
        AND ((_$PLANTP = 'E' AND MSTEQM.FANO = _$PLANCD)
          OR (_$PLANTP = 'G' AND MSTEQM.EQMGUBUN = _$PLANCD))
      GROUP BY CHKPLANEQM.CHKKNDCD
    ) PLAN_ITEM
    INNER JOIN MSTCHKKND
      ON MSTCHKKND.CHKKNDCD = PLAN_ITEM.CHKKNDCD
    ORDER BY PLAN_ITEM.SORTNO, PLAN_ITEM.CHKKNDCD;
  END IF;

  -- REV별 최종 상태의 개정 이력 (상태 변경 로그는 제외)
  SELECT
    MSTEQMREV_HEADER.REVNUM,
    LEFT(CASE WHEN MSTEQMREV_HEADER.APRVSTT IN ('A', 'R') THEN MSTEQMREV_HEADER.APRVTIME ELSE MSTEQMREV_HEADER.REQTIME END, 10) AS REVDATE,
    MSTEQMREV_HEADER.REMARK,
    COALESCE(REQ_EMP.EMPNM, MSTEQMREV_HEADER.REQEMP) AS REQEMPNM,
    CASE WHEN MSTEQMREV_HEADER.APRVSTT = 'A' THEN COALESCE(APRV_EMP.EMPNM, MSTEQMREV_HEADER.APRVEMP) ELSE '' END AS APRVEMPNM
  FROM MSTEQMREV_HEADER
  LEFT JOIN MSTEMP REQ_EMP
    ON REQ_EMP.EMPCD = MSTEQMREV_HEADER.REQEMP
  LEFT JOIN MSTEMP APRV_EMP
    ON APRV_EMP.EMPCD = MSTEQMREV_HEADER.APRVEMP
  WHERE MSTEQMREV_HEADER.PLANTP = _$PLANTP
    AND MSTEQMREV_HEADER.PLANCD = _$PLANCD
  ORDER BY MSTEQMREV_HEADER.REVNUM DESC;

-- *****************************************************************************
WHEN 'LIST_CYCLE_EQMCD' THEN -- 설비별 월별 점검계획 조회
  
  IF $SYEAR = '' THEN
    CALL COMERR('조회년도를 지정해주세요.');
    LEAVE PROC;
  END IF;  
    
  SELECT 
    MSTEQM.FANO,
    MSTEQM.EQMNM,
    MSTEQM.EQMGRADE,
    COALESCE(NULLIF(GPCD('FM110', MSTEQM.EQMGRADE), ''), MSTEQM.EQMGRADE) AS EQMGRADENM,
    $SYEAR AS YEAR,
    -- 월별 점검자: 사원코드로 저장된 값은 사원명으로 표시 (MxxCD는 저장값 그대로)
    COALESCE(NULLIF(GPCD('EMPCD', CHKPLANEQM_YEARPLAN.MONTH_01), ''), IFNULL(CHKPLANEQM_YEARPLAN.MONTH_01, '')) AS M01,
    IFNULL(CHKPLANEQM_YEARPLAN.MONTH_01, '') AS M01CD,
    COALESCE(NULLIF(GPCD('EMPCD', CHKPLANEQM_YEARPLAN.MONTH_02), ''), IFNULL(CHKPLANEQM_YEARPLAN.MONTH_02, '')) AS M02,
    IFNULL(CHKPLANEQM_YEARPLAN.MONTH_02, '') AS M02CD,
    COALESCE(NULLIF(GPCD('EMPCD', CHKPLANEQM_YEARPLAN.MONTH_03), ''), IFNULL(CHKPLANEQM_YEARPLAN.MONTH_03, '')) AS M03,
    IFNULL(CHKPLANEQM_YEARPLAN.MONTH_03, '') AS M03CD,
    COALESCE(NULLIF(GPCD('EMPCD', CHKPLANEQM_YEARPLAN.MONTH_04), ''), IFNULL(CHKPLANEQM_YEARPLAN.MONTH_04, '')) AS M04,
    IFNULL(CHKPLANEQM_YEARPLAN.MONTH_04, '') AS M04CD,
    COALESCE(NULLIF(GPCD('EMPCD', CHKPLANEQM_YEARPLAN.MONTH_05), ''), IFNULL(CHKPLANEQM_YEARPLAN.MONTH_05, '')) AS M05,
    IFNULL(CHKPLANEQM_YEARPLAN.MONTH_05, '') AS M05CD,
    COALESCE(NULLIF(GPCD('EMPCD', CHKPLANEQM_YEARPLAN.MONTH_06), ''), IFNULL(CHKPLANEQM_YEARPLAN.MONTH_06, '')) AS M06,
    IFNULL(CHKPLANEQM_YEARPLAN.MONTH_06, '') AS M06CD,
    COALESCE(NULLIF(GPCD('EMPCD', CHKPLANEQM_YEARPLAN.MONTH_07), ''), IFNULL(CHKPLANEQM_YEARPLAN.MONTH_07, '')) AS M07,
    IFNULL(CHKPLANEQM_YEARPLAN.MONTH_07, '') AS M07CD,
    COALESCE(NULLIF(GPCD('EMPCD', CHKPLANEQM_YEARPLAN.MONTH_08), ''), IFNULL(CHKPLANEQM_YEARPLAN.MONTH_08, '')) AS M08,
    IFNULL(CHKPLANEQM_YEARPLAN.MONTH_08, '') AS M08CD,
    COALESCE(NULLIF(GPCD('EMPCD', CHKPLANEQM_YEARPLAN.MONTH_09), ''), IFNULL(CHKPLANEQM_YEARPLAN.MONTH_09, '')) AS M09,
    IFNULL(CHKPLANEQM_YEARPLAN.MONTH_09, '') AS M09CD,
    COALESCE(NULLIF(GPCD('EMPCD', CHKPLANEQM_YEARPLAN.MONTH_10), ''), IFNULL(CHKPLANEQM_YEARPLAN.MONTH_10, '')) AS M10,
    IFNULL(CHKPLANEQM_YEARPLAN.MONTH_10, '') AS M10CD,
    COALESCE(NULLIF(GPCD('EMPCD', CHKPLANEQM_YEARPLAN.MONTH_11), ''), IFNULL(CHKPLANEQM_YEARPLAN.MONTH_11, '')) AS M11,
    IFNULL(CHKPLANEQM_YEARPLAN.MONTH_11, '') AS M11CD,
    COALESCE(NULLIF(GPCD('EMPCD', CHKPLANEQM_YEARPLAN.MONTH_12), ''), IFNULL(CHKPLANEQM_YEARPLAN.MONTH_12, '')) AS M12,
    IFNULL(CHKPLANEQM_YEARPLAN.MONTH_12, '') AS M12CD,
    IFNULL(CHKPLANEQM_YEARPLAN.REMARK, '') AS REMARK
  FROM MSTEQM
  LEFT JOIN CHKPLANEQM_YEARPLAN 
         ON CHKPLANEQM_YEARPLAN.EQMCD = MSTEQM.FANO
        AND CHKPLANEQM_YEARPLAN.YEAR = $SYEAR
        AND CHKPLANEQM_YEARPLAN.CHKTP = '02'
  WHERE MSTEQM.USEYN = 'Y'
    AND (MSTEQM.FANO LIKE CONCAT('%', $FANO, '%') OR MSTEQM.EQMNM LIKE CONCAT('%', $FANO, '%'))
  ORDER BY MSTEQM.FANO;

-- *****************************************************************************
WHEN 'SAVE_CYCLE_EQMCD' THEN -- 설비별 월별 점검계획 저장
  WHILE LENGTH($FANO_LIST) > 0 DO
    CALL COMSPLIT($FANO_LIST, _$FANO);
    CALL COMSPLIT($YEAR_LIST, _$YEAR);
    CALL COMSPLIT($M01_LIST, _$M01);
    CALL COMSPLIT($M02_LIST, _$M02);
    CALL COMSPLIT($M03_LIST, _$M03);
    CALL COMSPLIT($M04_LIST, _$M04);
    CALL COMSPLIT($M05_LIST, _$M05);
    CALL COMSPLIT($M06_LIST, _$M06);
    CALL COMSPLIT($M07_LIST, _$M07);
    CALL COMSPLIT($M08_LIST, _$M08);
    CALL COMSPLIT($M09_LIST, _$M09);
    CALL COMSPLIT($M10_LIST, _$M10);
    CALL COMSPLIT($M11_LIST, _$M11);
    CALL COMSPLIT($M12_LIST, _$M12);
    CALL COMSPLIT($REMARK_LIST, _$REMARK);

    IF NOT EXISTS (SELECT 1 FROM MSTEQM WHERE FANO = _$FANO AND USEYN = 'Y') THEN
      CALL COMERR('사용 중인 설비를 선택해주세요.');
      LEAVE PROC;
    END IF;

    -- 정기점검 실적이 있는 월은 점검자 변경·삭제 불가 (점검자가 없던 월에 새로 지정하는 것은 허용)
    SELECT GROUP_CONCAT(DISTINCT CONCAT(CAST(SUBSTRING(CHKRSTEQM.BASEDATE, 6, 2) AS UNSIGNED), '월')
                        ORDER BY SUBSTRING(CHKRSTEQM.BASEDATE, 6, 2) SEPARATOR ', ')
      INTO _$LOCKMM
    FROM CHKRSTEQM
    INNER JOIN CHKPLANEQM_YEARPLAN
      ON CHKPLANEQM_YEARPLAN.EQMCD = CHKRSTEQM.EQMCD
     AND CHKPLANEQM_YEARPLAN.YEAR = _$YEAR
     AND CHKPLANEQM_YEARPLAN.CHKTP = '02'
    WHERE CHKRSTEQM.EQMCD = _$FANO
      AND CHKRSTEQM.CHKTP = '02'
      AND CHKRSTEQM.BASEDATE LIKE CONCAT(_$YEAR, '-%')
      AND IFNULL(ELT(CAST(SUBSTRING(CHKRSTEQM.BASEDATE, 6, 2) AS UNSIGNED),
                  CHKPLANEQM_YEARPLAN.MONTH_01, CHKPLANEQM_YEARPLAN.MONTH_02, CHKPLANEQM_YEARPLAN.MONTH_03,
                  CHKPLANEQM_YEARPLAN.MONTH_04, CHKPLANEQM_YEARPLAN.MONTH_05, CHKPLANEQM_YEARPLAN.MONTH_06,
                  CHKPLANEQM_YEARPLAN.MONTH_07, CHKPLANEQM_YEARPLAN.MONTH_08, CHKPLANEQM_YEARPLAN.MONTH_09,
                  CHKPLANEQM_YEARPLAN.MONTH_10, CHKPLANEQM_YEARPLAN.MONTH_11, CHKPLANEQM_YEARPLAN.MONTH_12), '') <> ''
      AND IFNULL(ELT(CAST(SUBSTRING(CHKRSTEQM.BASEDATE, 6, 2) AS UNSIGNED),
                  CHKPLANEQM_YEARPLAN.MONTH_01, CHKPLANEQM_YEARPLAN.MONTH_02, CHKPLANEQM_YEARPLAN.MONTH_03,
                  CHKPLANEQM_YEARPLAN.MONTH_04, CHKPLANEQM_YEARPLAN.MONTH_05, CHKPLANEQM_YEARPLAN.MONTH_06,
                  CHKPLANEQM_YEARPLAN.MONTH_07, CHKPLANEQM_YEARPLAN.MONTH_08, CHKPLANEQM_YEARPLAN.MONTH_09,
                  CHKPLANEQM_YEARPLAN.MONTH_10, CHKPLANEQM_YEARPLAN.MONTH_11, CHKPLANEQM_YEARPLAN.MONTH_12), '') <> IFNULL(ELT(CAST(SUBSTRING(CHKRSTEQM.BASEDATE, 6, 2) AS UNSIGNED),
                  _$M01, _$M02, _$M03, _$M04, _$M05, _$M06,
                  _$M07, _$M08, _$M09, _$M10, _$M11, _$M12), '');

    IF _$LOCKMM IS NOT NULL THEN
      CALL COMERR(CONCAT('[', _$FANO, '] ', _$YEAR, '년 ', _$LOCKMM, '은 정기점검 실적이 있어 점검자를 변경·삭제할 수 없습니다. 설비 정기점검 등록에서 해당 월 점검 실적을 먼저 삭제해주세요.'));
      LEAVE PROC;
    END IF;
  
    IF EXISTS (SELECT 1 FROM CHKPLANEQM_YEARPLAN WHERE EQMCD = _$FANO AND YEAR =_$YEAR AND CHKTP = '02') THEN  
      
      UPDATE CHKPLANEQM_YEARPLAN SET
        MONTH_01 = _$M01, 
        MONTH_02 = _$M02, 
        MONTH_03 = _$M03, 
        MONTH_04 = _$M04, 
        MONTH_05 = _$M05, 
        MONTH_06 = _$M06, 
        MONTH_07 = _$M07, 
        MONTH_08 = _$M08, 
        MONTH_09 = _$M09, 
        MONTH_10 = _$M10, 
        MONTH_11 = _$M11, 
        MONTH_12 = _$M12, 
        REMARK   = _$REMARK,
        MTIME = CALLTIME(),
        MEMP = CALLEMP(),
        MPRG = CALLPRG()
      WHERE EQMCD = _$FANO
        AND YEAR  = _$YEAR
        AND CHKTP = '02'
     ;
        
      IF EXISTS (
        SELECT 1 FROM CHKPLANEQM_YEARPLAN WHERE EQMCD = _$FANO AND YEAR = _$YEAR AND CHKTP = '02' AND REMARK = ''
                                                                AND MONTH_01 = '' AND MONTH_02 = '' AND MONTH_03 = '' AND MONTH_04 = ''
                                                                AND MONTH_05 = '' AND MONTH_06 = '' AND MONTH_07 = '' AND MONTH_08 = ''
                                                                AND MONTH_09 = '' AND MONTH_10 = '' AND MONTH_11 = '' AND MONTH_12 = '') THEN

        DELETE FROM CHKPLANEQM_YEARPLAN 
        WHERE EQMCD = _$FANO 
        AND YEAR = _$YEAR 
        AND CHKTP = '02';
      END IF;  
    ELSE
      INSERT INTO CHKPLANEQM_YEARPLAN (
        EQMCD, CHKTP, YEAR, 
        MONTH_01, MONTH_02, MONTH_03, MONTH_04, 
        MONTH_05, MONTH_06, MONTH_07, MONTH_08, 
        MONTH_09, MONTH_10, MONTH_11, MONTH_12, 
        REMARK, RTIME, REMP, RPRG
      ) 
      VALUES (
        _$FANO, '02', _$YEAR,
        _$M01, _$M02, _$M03, _$M04,
        _$M05, _$M06, _$M07, _$M08,
        _$M09, _$M10, _$M11, _$M12,
        _$REMARK, CALLTIME(), CALLEMP(), CALLPRG()
      );
   
      IF EXISTS (
        SELECT 1 FROM CHKPLANEQM_YEARPLAN WHERE EQMCD = _$FANO AND YEAR = _$YEAR AND CHKTP = '02' AND REMARK = ''
                                                                AND MONTH_01 = '' AND MONTH_02 = '' AND MONTH_03 = '' AND MONTH_04 = ''
                                                                AND MONTH_05 = '' AND MONTH_06 = '' AND MONTH_07 = '' AND MONTH_08 = ''
                                                                AND MONTH_09 = '' AND MONTH_10 = '' AND MONTH_11 = '' AND MONTH_12 = '') THEN

        DELETE FROM CHKPLANEQM_YEARPLAN 
        WHERE EQMCD = _$FANO
        AND YEAR = _$YEAR 
        AND CHKTP = '02';
      END IF;
    END IF;
  END WHILE;
-- *****************************************************************************
WHEN 'DELETE_CYCLE_EQMCD' THEN -- 설비별 월별 점검계획 삭제

  WHILE LENGTH($FANO_LIST) > 0 DO
    CALL COMSPLIT($FANO_LIST, _$FANO);
    CALL COMSPLIT($YEAR_LIST, _$YEAR);

    IF NOT EXISTS (SELECT 1 FROM MSTEQM WHERE FANO = _$FANO AND USEYN = 'Y') THEN
      CALL COMERR('사용 중인 설비를 선택해주세요.');
      LEAVE PROC;
    END IF;

    -- 정기점검 실적이 있는 월이 있으면 삭제 불가
    SELECT GROUP_CONCAT(DISTINCT CONCAT(CAST(SUBSTRING(CHKRSTEQM.BASEDATE, 6, 2) AS UNSIGNED), '월')
                        ORDER BY SUBSTRING(CHKRSTEQM.BASEDATE, 6, 2) SEPARATOR ', ')
      INTO _$LOCKMM
    FROM CHKRSTEQM
    INNER JOIN CHKPLANEQM_YEARPLAN
      ON CHKPLANEQM_YEARPLAN.EQMCD = CHKRSTEQM.EQMCD
     AND CHKPLANEQM_YEARPLAN.YEAR = _$YEAR
     AND CHKPLANEQM_YEARPLAN.CHKTP = '02'
    WHERE CHKRSTEQM.EQMCD = _$FANO
      AND CHKRSTEQM.CHKTP = '02'
      AND CHKRSTEQM.BASEDATE LIKE CONCAT(_$YEAR, '-%')
      AND IFNULL(ELT(CAST(SUBSTRING(CHKRSTEQM.BASEDATE, 6, 2) AS UNSIGNED),
                  CHKPLANEQM_YEARPLAN.MONTH_01, CHKPLANEQM_YEARPLAN.MONTH_02, CHKPLANEQM_YEARPLAN.MONTH_03,
                  CHKPLANEQM_YEARPLAN.MONTH_04, CHKPLANEQM_YEARPLAN.MONTH_05, CHKPLANEQM_YEARPLAN.MONTH_06,
                  CHKPLANEQM_YEARPLAN.MONTH_07, CHKPLANEQM_YEARPLAN.MONTH_08, CHKPLANEQM_YEARPLAN.MONTH_09,
                  CHKPLANEQM_YEARPLAN.MONTH_10, CHKPLANEQM_YEARPLAN.MONTH_11, CHKPLANEQM_YEARPLAN.MONTH_12), '') <> '';

    IF _$LOCKMM IS NOT NULL THEN
      CALL COMERR(CONCAT('[', _$FANO, '] ', _$YEAR, '년 ', _$LOCKMM, '은 정기점검 실적이 있어 점검자를 삭제할 수 없습니다. 설비 정기점검 등록에서 해당 월 점검 실적을 먼저 삭제해주세요.'));
      LEAVE PROC;
    END IF;
  
    DELETE FROM CHKPLANEQM_YEARPLAN 
    WHERE EQMCD = _$FANO 
    AND YEAR = _$YEAR 
    AND CHKTP = '02';
  END WHILE;

-- *****************************************************************************
END CASE; END
