-- *****************************************************************************
-- Comment: 설비점검계획 리비전 키(REVCD) 전환 (기존 구조로 운영 중인 DB)
-- Create:  2026-10-01  한성수  헤더 PK를 REVCD, 디테일 PK를 REVCD·CHKKNDCD로 변경하고 점검실적 적용 리비전을 REVNUM에서 REVCD로 전환
-- *****************************************************************************
-- 대상: MES_SNS2_EQM1001_PLAN_REV.sql·_INIT.sql을 이미 실행한(기존 구조) DB에서 1회 실행합니다.
--       새로 설치하는 DB는 이 스크립트 대신 MES_SNS2_EQM1001_PLAN_REV.sql → _INIT.sql을 실행합니다.
-- 순서: 이 스크립트 → EQM1001_R05·EQM1001_R04 프로시저 교체 → EQM1001_R04 파라미터 재등록 → 화면 반영
--       이 스크립트 실행 후 프로시저 교체 전까지는 기존 프로시저가 동작하지 않으므로 이어서 실행합니다.
-- 키: GETKEY('REVCD')는 COMKEY에 일자별로 자동 등록되므로 별도 등록이 필요 없습니다. (형식: YYMMDD + 순번 6자리, 12자)

-- *****************************************************************************
-- 0. 백업
CREATE TABLE `MES_SNS2`.`MSTEQMREV_HEADER_BAK_REVCD` AS SELECT * FROM `MES_SNS2`.`MSTEQMREV_HEADER`;
CREATE TABLE `MES_SNS2`.`MSTEQMREV_DETAIL_BAK_REVCD` AS SELECT * FROM `MES_SNS2`.`MSTEQMREV_DETAIL`;
CREATE TABLE `MES_SNS2`.`CHKRSTEQM_BAK_REVCD` AS
SELECT CHKRSTKEY, EQMCD, REVNUM FROM `MES_SNS2`.`CHKRSTEQM` WHERE REVNUM IS NOT NULL;

-- *****************************************************************************
-- 1. 헤더: 리비전 키 추가·발번 후 PK 변경 (리비전 번호는 대상별 중복 방지 키로 유지)
ALTER TABLE `MES_SNS2`.`MSTEQMREV_HEADER`
  ADD COLUMN `REVCD` varchar(20) NOT NULL DEFAULT '' COMMENT '리비전키 (GETKEY(''REVCD''))' FIRST;

UPDATE `MES_SNS2`.`MSTEQMREV_HEADER`
SET REVCD = GETKEY('REVCD')
WHERE REVCD = ''
ORDER BY PLANTP, PLANCD, REVNUM;

-- 확인: 빈 키·중복 키 (0건이어야 함)
SELECT REVCD, COUNT(*) AS CNT
FROM `MES_SNS2`.`MSTEQMREV_HEADER`
GROUP BY REVCD
HAVING REVCD = '' OR COUNT(*) > 1;

ALTER TABLE `MES_SNS2`.`MSTEQMREV_HEADER`
  DROP PRIMARY KEY,
  ADD PRIMARY KEY (`REVCD`),
  ADD UNIQUE KEY `UX_MSTEQMREV_HEADER_REV` (`PLANTP`, `PLANCD`, `REVNUM`);

-- *****************************************************************************
-- 2. 디테일: 리비전 키 연결, 설비그룹 승인본은 점검항목 단위로 합친 뒤 PK 변경
ALTER TABLE `MES_SNS2`.`MSTEQMREV_DETAIL`
  ADD COLUMN `REVCD` varchar(20) NOT NULL DEFAULT '' COMMENT '리비전키' FIRST,
  MODIFY COLUMN `EQMCD` varchar(20) NOT NULL DEFAULT '' COMMENT '설비코드 (설비그룹 승인본은 빈 값)';

UPDATE `MES_SNS2`.`MSTEQMREV_DETAIL`
INNER JOIN `MES_SNS2`.`MSTEQMREV_HEADER` ITEM_REV
  ON ITEM_REV.PLANTP = MSTEQMREV_DETAIL.PLANTP
 AND ITEM_REV.PLANCD = MSTEQMREV_DETAIL.PLANCD
 AND ITEM_REV.REVNUM = MSTEQMREV_DETAIL.REVNUM
SET MSTEQMREV_DETAIL.REVCD = ITEM_REV.REVCD;

-- 연결된 리비전이 없는 승인본은 조회되지 않으므로 삭제 (0단계 백업에 보관)
DELETE FROM `MES_SNS2`.`MSTEQMREV_DETAIL`
WHERE REVCD = '';

CREATE TEMPORARY TABLE `MES_SNS2`.`TMP_GRP_DETAIL` AS
SELECT
  REVCD, PLANTP, PLANCD, REVNUM, CHKKNDCD,
  MIN(CHKCYCLE) AS CHKCYCLE, MIN(SORTNO) AS SORTNO,
  MAX(CHKKNDNM) AS CHKKNDNM, MAX(CHKLOC) AS CHKLOC, MAX(CHKMTH) AS CHKMTH, MAX(CHKVALTP) AS CHKVALTP,
  MAX(REMARK) AS REMARK,
  MIN(RTIME) AS RTIME, MIN(REMP) AS REMP, MIN(RPRG) AS RPRG,
  MAX(MTIME) AS MTIME, MAX(MEMP) AS MEMP, MAX(MPRG) AS MPRG
FROM `MES_SNS2`.`MSTEQMREV_DETAIL`
WHERE PLANTP = 'G'
GROUP BY REVCD, PLANTP, PLANCD, REVNUM, CHKKNDCD;

DELETE FROM `MES_SNS2`.`MSTEQMREV_DETAIL`
WHERE PLANTP = 'G';

INSERT INTO `MES_SNS2`.`MSTEQMREV_DETAIL` (
  REVCD, PLANTP, PLANCD, REVNUM, EQMCD, CHKKNDCD,
  CHKCYCLE, SORTNO, CHKKNDNM, CHKLOC, CHKMTH, CHKVALTP, REMARK,
  RTIME, REMP, RPRG, MTIME, MEMP, MPRG
)
SELECT
  REVCD, PLANTP, PLANCD, REVNUM, '', CHKKNDCD,
  CHKCYCLE, SORTNO, CHKKNDNM, CHKLOC, CHKMTH, CHKVALTP, REMARK,
  RTIME, REMP, RPRG, MTIME, MEMP, MPRG
FROM `MES_SNS2`.`TMP_GRP_DETAIL`;

DROP TEMPORARY TABLE `MES_SNS2`.`TMP_GRP_DETAIL`;

-- 확인: 리비전 키·점검항목 중복 (0건이어야 함)
SELECT REVCD, CHKKNDCD, COUNT(*) AS CNT
FROM `MES_SNS2`.`MSTEQMREV_DETAIL`
GROUP BY REVCD, CHKKNDCD
HAVING COUNT(*) > 1;

ALTER TABLE `MES_SNS2`.`MSTEQMREV_DETAIL`
  DROP PRIMARY KEY,
  ADD PRIMARY KEY (`REVCD`, `CHKKNDCD`);

-- *****************************************************************************
-- 3. 점검실적: 적용 리비전을 REVNUM에서 REVCD로 전환
ALTER TABLE `MES_SNS2`.`CHKRSTEQM`
  ADD COLUMN IF NOT EXISTS `REVCD` varchar(20) NULL DEFAULT NULL COMMENT '적용 설비 리비전키' AFTER `REVNUM`;

UPDATE `MES_SNS2`.`CHKRSTEQM`
INNER JOIN `MES_SNS2`.`MSTEQMREV_HEADER` RST_REV
  ON RST_REV.PLANTP = 'E'
 AND RST_REV.PLANCD = CHKRSTEQM.EQMCD
 AND RST_REV.REVNUM = CHKRSTEQM.REVNUM
SET CHKRSTEQM.REVCD = RST_REV.REVCD
WHERE CHKRSTEQM.REVNUM IS NOT NULL;

-- 확인: 리비전 번호는 있는데 리비전 키를 찾지 못한 실적 (0건이어야 함, 0건일 때 아래 컬럼 삭제 실행)
SELECT CHKRSTKEY, EQMCD, REVNUM
FROM `MES_SNS2`.`CHKRSTEQM`
WHERE REVNUM IS NOT NULL
  AND REVCD IS NULL;

ALTER TABLE `MES_SNS2`.`CHKRSTEQM`
  DROP COLUMN `REVNUM`;

-- *****************************************************************************
-- 4. 최종 확인
-- 키 구성: HEADER PRIMARY = REVCD, UX_MSTEQMREV_HEADER_REV = PLANTP,PLANCD,REVNUM / DETAIL PRIMARY = REVCD,CHKKNDCD
SELECT TABLE_NAME, INDEX_NAME, GROUP_CONCAT(COLUMN_NAME ORDER BY SEQ_IN_INDEX) AS COLS
FROM information_schema.STATISTICS
WHERE TABLE_SCHEMA = 'MES_SNS2'
  AND TABLE_NAME IN ('MSTEQMREV_HEADER', 'MSTEQMREV_DETAIL')
GROUP BY TABLE_NAME, INDEX_NAME
ORDER BY TABLE_NAME, INDEX_NAME;

-- 건수: 헤더는 백업과 같고, 디테일은 설비 승인본 + 설비그룹 점검항목 수, 점검실적 리비전 키는 백업 건수와 같아야 함
SELECT 'HEADER' AS TBL, (SELECT COUNT(*) FROM `MES_SNS2`.`MSTEQMREV_HEADER_BAK_REVCD`) AS BEFORE_CNT, (SELECT COUNT(*) FROM `MES_SNS2`.`MSTEQMREV_HEADER`) AS AFTER_CNT
UNION ALL
SELECT 'DETAIL', (SELECT COUNT(*) FROM `MES_SNS2`.`MSTEQMREV_DETAIL_BAK_REVCD`), (SELECT COUNT(*) FROM `MES_SNS2`.`MSTEQMREV_DETAIL`)
UNION ALL
SELECT 'CHKRSTEQM.REVCD', (SELECT COUNT(*) FROM `MES_SNS2`.`CHKRSTEQM_BAK_REVCD`), (SELECT COUNT(*) FROM `MES_SNS2`.`CHKRSTEQM` WHERE REVCD IS NOT NULL);

-- *****************************************************************************
-- 되돌릴 때 (전환 직후 문제 발생 시, 프로시저도 이전 버전으로 되돌린 뒤 실행)
-- ALTER TABLE `MES_SNS2`.`CHKRSTEQM` ADD COLUMN `REVNUM` int(11) NULL DEFAULT NULL COMMENT '적용 설비 리비전 번호' AFTER `REVCD`;
-- UPDATE `MES_SNS2`.`CHKRSTEQM` INNER JOIN `MES_SNS2`.`CHKRSTEQM_BAK_REVCD` BAK ON BAK.CHKRSTKEY = CHKRSTEQM.CHKRSTKEY SET CHKRSTEQM.REVNUM = BAK.REVNUM;
-- ALTER TABLE `MES_SNS2`.`CHKRSTEQM` DROP COLUMN `REVCD`;
-- DELETE FROM `MES_SNS2`.`MSTEQMREV_DETAIL`;
-- ALTER TABLE `MES_SNS2`.`MSTEQMREV_DETAIL` DROP PRIMARY KEY, DROP COLUMN `REVCD`, ADD PRIMARY KEY (`PLANTP`, `PLANCD`, `REVNUM`, `EQMCD`, `CHKKNDCD`);
-- INSERT INTO `MES_SNS2`.`MSTEQMREV_DETAIL` SELECT * FROM `MES_SNS2`.`MSTEQMREV_DETAIL_BAK_REVCD`;
-- ALTER TABLE `MES_SNS2`.`MSTEQMREV_HEADER` DROP PRIMARY KEY, DROP INDEX `UX_MSTEQMREV_HEADER_REV`, DROP COLUMN `REVCD`, ADD PRIMARY KEY (`PLANTP`, `PLANCD`, `REVNUM`);
