-- *****************************************************************************
-- Comment: CHKPLANEQM_APRV 리비전별 승인·반려 누적 이력 전환
-- Create:  2026-10-06  한성수  기존 데이터 보존 및 이력키·리비전키 추가
-- Modify:  2026-10-06  한성수  GETKEY(APRVKEY) 발번 및 기존 PK·APRVID 전환
-- *****************************************************************************
-- 반영 순서: DETAIL 정규화 SQL → 이 파일 → 최신 R03·R04 프로시저
-- GETKEY는 COMKEY에 키종류를 자동 등록하므로 APRVKEY 사전 등록은 필요 없습니다.
-- 기존 PLAN_REV_INIT은 최초 이관 전용이므로 이력 전환 후 재실행하지 않습니다.
CREATE TABLE IF NOT EXISTS MES_SNS2.CHKPLANEQM_APRV (
  APRVKEY    varchar(20) NOT NULL DEFAULT '' COMMENT '승인이력키 (GETKEY(''APRVKEY''))',
  REVCD      varchar(20) NOT NULL DEFAULT '' COMMENT '리비전키',
  PLANTP     char(1) NOT NULL DEFAULT '' COMMENT 'G: 설비그룹, E: 설비',
  PLANCD     varchar(50) NOT NULL DEFAULT '' COMMENT '설비그룹코드 또는 설비코드',
  APRVSTT    char(1) NOT NULL DEFAULT '' COMMENT 'A: 승인, R: 반려',
  REQTIME    varchar(19) NOT NULL DEFAULT '',
  REQEMP     varchar(20) NOT NULL DEFAULT '',
  REQPRG     varchar(100) NOT NULL DEFAULT '',
  APRVTIME   varchar(19) NOT NULL DEFAULT '',
  APRVEMP    varchar(20) NOT NULL DEFAULT '' COMMENT '승인·반려 처리자',
  APRVPRG    varchar(100) NOT NULL DEFAULT '',
  REJREASON  varchar(1000) NOT NULL DEFAULT '',
  RTIME      varchar(19) NOT NULL DEFAULT '',
  REMP       varchar(20) NOT NULL DEFAULT '',
  RPRG       varchar(100) NOT NULL DEFAULT '',
  MTIME      varchar(19) NOT NULL DEFAULT '',
  MEMP       varchar(20) NOT NULL DEFAULT '',
  MPRG       varchar(100) NOT NULL DEFAULT '',
  PRIMARY KEY (APRVKEY),
  KEY IX_EQMPLAN_APRV_REV (REVCD, APRVTIME, APRVKEY)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC COMMENT='리비전별 승인·반려 처리 이력';

-- 구 계획별 PK 및 중간 APRVID 구조 모두 APRVKEY로 전환
ALTER TABLE MES_SNS2.CHKPLANEQM_APRV
  ADD COLUMN IF NOT EXISTS APRVKEY varchar(20) NOT NULL DEFAULT '' COMMENT '승인이력키 (GETKEY(''APRVKEY''))' FIRST,
  ADD COLUMN IF NOT EXISTS REVCD varchar(20) NOT NULL DEFAULT '' COMMENT '리비전키' AFTER APRVKEY;

UPDATE MES_SNS2.CHKPLANEQM_APRV
SET APRVKEY = MES_SNS2.GETKEY('APRVKEY')
WHERE APRVKEY = ''
ORDER BY APRVTIME, PLANTP, PLANCD;

ALTER TABLE MES_SNS2.CHKPLANEQM_APRV
  DROP INDEX IF EXISTS IX_EQMPLAN_APRV_REV,
  DROP PRIMARY KEY,
  DROP COLUMN IF EXISTS APRVID,
  ADD PRIMARY KEY (APRVKEY),
  ADD INDEX IX_EQMPLAN_APRV_REV (REVCD, APRVTIME, APRVKEY);

START TRANSACTION;
-- 기존 기록은 구분·계획·상태·처리시간이 정확하게 일치하는 리비전에만 연결
UPDATE MES_SNS2.CHKPLANEQM_APRV
INNER JOIN (
  SELECT PLANTP, PLANCD, APRVSTT, APRVTIME, MIN(REVCD) AS REVCD
  FROM MES_SNS2.MSTEQMREV_HEADER
  WHERE APRVSTT IN ('A', 'R') AND APRVTIME <> ''
  GROUP BY PLANTP, PLANCD, APRVSTT, APRVTIME
  HAVING COUNT(*) = 1
) PLAN_REV
  ON PLAN_REV.PLANTP = CHKPLANEQM_APRV.PLANTP
 AND PLAN_REV.PLANCD = CHKPLANEQM_APRV.PLANCD
 AND PLAN_REV.APRVSTT = CHKPLANEQM_APRV.APRVSTT
 AND PLAN_REV.APRVTIME = CHKPLANEQM_APRV.APRVTIME
SET CHKPLANEQM_APRV.REVCD = PLAN_REV.REVCD,
    CHKPLANEQM_APRV.APRVEMP = CASE WHEN CHKPLANEQM_APRV.APRVEMP = '' AND CHKPLANEQM_APRV.MTIME = CHKPLANEQM_APRV.APRVTIME THEN CHKPLANEQM_APRV.MEMP ELSE CHKPLANEQM_APRV.APRVEMP END
WHERE CHKPLANEQM_APRV.REVCD = '';

-- 헤더에 남아 있는 처리 기록 중 이력이 없는 건만 보존
INSERT INTO MES_SNS2.CHKPLANEQM_APRV (
  APRVKEY, REVCD, PLANTP, PLANCD, APRVSTT, REQTIME, REQEMP, REQPRG,
  APRVTIME, APRVEMP, APRVPRG, REJREASON, RTIME, REMP, RPRG
)
SELECT
  MES_SNS2.GETKEY('APRVKEY'), PLAN_REV.REVCD, PLAN_REV.PLANTP, PLAN_REV.PLANCD, PLAN_REV.APRVSTT,
  PLAN_REV.REQTIME, PLAN_REV.REQEMP, PLAN_REV.REQPRG, PLAN_REV.APRVTIME,
  CASE WHEN PLAN_REV.APRVEMP = '' AND PLAN_REV.MTIME = PLAN_REV.APRVTIME THEN PLAN_REV.MEMP ELSE PLAN_REV.APRVEMP END,
  PLAN_REV.APRVPRG, PLAN_REV.REJREASON, PLAN_REV.APRVTIME,
  CASE WHEN PLAN_REV.APRVEMP = '' AND PLAN_REV.MTIME = PLAN_REV.APRVTIME THEN PLAN_REV.MEMP ELSE PLAN_REV.APRVEMP END, PLAN_REV.APRVPRG
FROM MES_SNS2.MSTEQMREV_HEADER PLAN_REV
LEFT JOIN MES_SNS2.CHKPLANEQM_APRV
  ON CHKPLANEQM_APRV.REVCD = PLAN_REV.REVCD
 AND CHKPLANEQM_APRV.APRVSTT = PLAN_REV.APRVSTT
 AND CHKPLANEQM_APRV.APRVTIME = PLAN_REV.APRVTIME
WHERE PLAN_REV.APRVSTT IN ('A', 'R')
  AND PLAN_REV.APRVTIME <> ''
  AND CHKPLANEQM_APRV.APRVKEY IS NULL;
COMMIT;

-- REVCD가 빈 구 기록은 보존하되 특정 REV의 이력으로 표시하지 않음
SELECT COUNT(*) AS UNLINKED_HISTORY_COUNT FROM MES_SNS2.CHKPLANEQM_APRV WHERE REVCD = '';
