CREATE DEFINER=`root`@`%` PROCEDURE `MES_SNS2`.`EQM1001_R05`(
-- *****************************************************************************
-- Comment: 설비점검계획 승인관리
-- Create:  2026-09-22  한성수  설비그룹·설비별 정기점검 계획 승인, 반려 및 계획서 출력 데이터 조회
-- 			2026-09-23	한성수  승인자 조회 추가 
-- 			2026-09-29	한성수  반려 시 승인자 비움 처리 및 설비별 승인자 조회 추가
-- *****************************************************************************
  IN $EQMGRP       VARCHAR(50),
  IN $FANO          VARCHAR(50),
  IN $PLANTP        CHAR(1),
  IN $PLANCD        VARCHAR(50),
  IN $APRVSTT       CHAR(1),
  IN $REJREASON     VARCHAR(1000),

-- *****************************************************************************
  IN $CALLTYPE      VARCHAR(50),
  IN $KEYWORD       VARCHAR(1000)
)
PROC: BEGIN -- @CALLEMP, @CALLPRG, @CALLHOST, @CALLIP, @CALLMAC
-- *****************************************************************************
  DECLARE _$APRVSTT CHAR(1);
  DECLARE _$UNAPPROVED_CNT INT DEFAULT 0;

CASE $CALLTYPE

-- *****************************************************************************
WHEN 'LIST_PLAN' THEN -- 점검계획 목록 조회

  IF $PLANTP = 'G' THEN
    SELECT
      'G' AS PLANTP,
      '설비그룹' AS PLANTPNM,
      MSTEQM.EQMGUBUN AS PLANCD,
      COMTYPE.TPNM AS PLANNM,
      COUNT(DISTINCT CHKPLANEQM.CHKKNDCD) AS PLANITEMCNT,
      CASE EQMPLAN_APRV.APRVSTT
        WHEN 'A' THEN '승인'
        WHEN 'R' THEN '반려'
        ELSE '대기'
      END AS APRVSTTNM,
      CASE WHEN EQMPLAN_APRV.APRVSTT = 'A' THEN COALESCE(EQMPLAN_APRV.APRVEMP, '') ELSE '' END AS APRVEMP,
      COALESCE(EQMPLAN_APRV.REQTIME, '') AS REQTIME,
      COALESCE(EQMPLAN_APRV.APRVTIME, '') AS APRVTIME,
      COALESCE(EQMPLAN_APRV.REJREASON, '') AS REJREASON,
      COALESCE(EQMPLAN_APRV.APRVSTT, '') AS APRVSTT
    FROM MSTEQM
    INNER JOIN CHKPLANEQM
      ON CHKPLANEQM.EQMCD = MSTEQM.FANO
     AND CHKPLANEQM.CHKTP = '02'
     AND CHKPLANEQM.USEYN = 'Y'
    INNER JOIN COMTYPE
      ON COMTYPE.GPCD = 'FM116'
     AND COMTYPE.TPCD = MSTEQM.EQMGUBUN
    LEFT JOIN EQMPLAN_APRV
      ON EQMPLAN_APRV.PLANTP = 'G'
     AND EQMPLAN_APRV.PLANCD = MSTEQM.EQMGUBUN
    WHERE MSTEQM.USEYN = 'Y'
      AND MSTEQM.EQMGUBUN <> ''
      AND ($EQMGRP IS NULL OR $EQMGRP = '' OR MSTEQM.EQMGUBUN = $EQMGRP)
    GROUP BY MSTEQM.EQMGUBUN, COMTYPE.TPNM, EQMPLAN_APRV.APRVEMP, EQMPLAN_APRV.APRVSTT, EQMPLAN_APRV.REJREASON, EQMPLAN_APRV.REQTIME, EQMPLAN_APRV.APRVTIME
    ORDER BY MSTEQM.EQMGUBUN;

  ELSEIF $PLANTP = 'E' THEN
    SELECT
      'E' AS PLANTP,
      '설비별' AS PLANTPNM,
      MSTEQM.FANO AS PLANCD,
      MSTEQM.EQMNM AS PLANNM,
      COUNT(DISTINCT CHKPLANEQM.CHKKNDCD) AS PLANITEMCNT,
      CASE EQMPLAN_APRV.APRVSTT
        WHEN 'A' THEN '승인'
        WHEN 'R' THEN '반려'
        ELSE '대기'
      END AS APRVSTTNM,
      CASE WHEN EQMPLAN_APRV.APRVSTT = 'A' THEN COALESCE(EQMPLAN_APRV.APRVEMP, '') ELSE '' END AS APRVEMP,
      COALESCE(EQMPLAN_APRV.REQTIME, '') AS REQTIME,
      COALESCE(EQMPLAN_APRV.APRVTIME, '') AS APRVTIME,
      COALESCE(EQMPLAN_APRV.REJREASON, '') AS REJREASON,
      COALESCE(EQMPLAN_APRV.APRVSTT, '') AS APRVSTT
    FROM MSTEQM
    INNER JOIN CHKPLANEQM
      ON CHKPLANEQM.EQMCD = MSTEQM.FANO
     AND CHKPLANEQM.CHKTP = '02'
     AND CHKPLANEQM.USEYN = 'Y'
    LEFT JOIN EQMPLAN_APRV
      ON EQMPLAN_APRV.PLANTP = 'E'
     AND EQMPLAN_APRV.PLANCD = MSTEQM.FANO
    WHERE MSTEQM.USEYN = 'Y'
      AND ($FANO IS NULL OR $FANO = '' OR MSTEQM.FANO LIKE CONCAT('%', $FANO, '%') OR MSTEQM.EQMNM LIKE CONCAT('%', $FANO, '%'))
    GROUP BY MSTEQM.FANO, MSTEQM.EQMNM, EQMPLAN_APRV.APRVEMP, EQMPLAN_APRV.APRVSTT, EQMPLAN_APRV.REJREASON, EQMPLAN_APRV.REQTIME, EQMPLAN_APRV.APRVTIME
    ORDER BY MSTEQM.FANO;

  ELSE
    CALL COMERR('점검계획 구분이 올바르지 않습니다.');
    LEAVE PROC;
  END IF;
-- *****************************************************************************
WHEN 'REQUEST_PLAN' THEN -- 점검계획 승인 요청(상태 초기화)
  IF $PLANTP NOT IN ('G', 'E') OR $PLANCD IS NULL OR $PLANCD = '' THEN
    CALL COMERR('승인 요청 대상이 올바르지 않습니다.');
    LEAVE PROC;
  END IF;

  DELETE FROM EQMPLAN_APRV
  WHERE PLANTP = $PLANTP
    AND PLANCD = $PLANCD;

  IF $PLANTP = 'G' THEN
    DELETE EQMPLAN_APRV
    FROM EQMPLAN_APRV
    INNER JOIN MSTEQM
      ON MSTEQM.FANO = EQMPLAN_APRV.PLANCD
    WHERE EQMPLAN_APRV.PLANTP = 'E'
      AND MSTEQM.EQMGUBUN = $PLANCD
      AND MSTEQM.USEYN = 'Y';
  END IF;

-- *****************************************************************************
WHEN 'SAVE_PLAN_STATUS' THEN -- 점검계획 승인/반려 상태 저장
  IF $PLANTP NOT IN ('G', 'E') OR $PLANCD IS NULL OR $PLANCD = '' THEN
    CALL COMERR('승인 대상이 올바르지 않습니다.');
    LEAVE PROC;
  END IF;

  IF $APRVSTT IS NULL OR $APRVSTT NOT IN ('A', 'R') THEN
    CALL COMERR('승인 상태가 올바르지 않습니다.');
    LEAVE PROC;
  END IF;

  IF $APRVSTT = 'R' AND ($REJREASON IS NULL OR $REJREASON = '') THEN
    CALL COMERR('반려 사유를 입력해주세요.');
    LEAVE PROC;
  END IF;

  INSERT INTO EQMPLAN_APRV (
    PLANTP, PLANCD, APRVSTT,
    REQTIME, REQEMP, REQPRG,
    APRVTIME, APRVEMP, APRVPRG, REJREASON,
    RTIME, REMP, RPRG
  ) VALUES (
    $PLANTP, $PLANCD, $APRVSTT,
    CALLTIME(), CALLEMP(), CALLPRG(),
    CALLTIME(),
    CASE WHEN $APRVSTT = 'A' THEN CALLEMP() ELSE '' END,
    CALLPRG(),
    CASE WHEN $APRVSTT = 'R' THEN $REJREASON ELSE '' END,
    CALLTIME(), CALLEMP(), CALLPRG()
  ) ON DUPLICATE KEY UPDATE
    APRVSTT = $APRVSTT,
    APRVTIME = CALLTIME(),
    APRVEMP = CASE WHEN $APRVSTT = 'A' THEN CALLEMP() ELSE '' END,
    APRVPRG = CALLPRG(),
    REJREASON = CASE WHEN $APRVSTT = 'R' THEN $REJREASON ELSE '' END,
    MTIME = CALLTIME(),
    MEMP = CALLEMP(),
    MPRG = CALLPRG();

  IF $PLANTP = 'G' THEN
    INSERT INTO EQMPLAN_APRV (
      PLANTP, PLANCD, APRVSTT,
      REQTIME, REQEMP, REQPRG,
      APRVTIME, APRVEMP, APRVPRG, REJREASON,
      RTIME, REMP, RPRG
    )
    SELECT
      'E', MSTEQM.FANO, $APRVSTT,
      CALLTIME(), CALLEMP(), CALLPRG(),
      CALLTIME(),
      CASE WHEN $APRVSTT = 'A' THEN CALLEMP() ELSE '' END,
      CALLPRG(),
      CASE WHEN $APRVSTT = 'R' THEN $REJREASON ELSE '' END,
      CALLTIME(), CALLEMP(), CALLPRG()
    FROM MSTEQM
    WHERE MSTEQM.EQMGUBUN = $PLANCD
      AND MSTEQM.USEYN = 'Y'
    ON DUPLICATE KEY UPDATE
      APRVSTT = $APRVSTT,
      APRVTIME = CALLTIME(),
      APRVEMP = CASE WHEN $APRVSTT = 'A' THEN CALLEMP() ELSE '' END,
      APRVPRG = CALLPRG(),
      REJREASON = CASE WHEN $APRVSTT = 'R' THEN $REJREASON ELSE '' END,
      MTIME = CALLTIME(),
      MEMP = CALLEMP(),
      MPRG = CALLPRG();
  END IF;

-- *****************************************************************************
WHEN 'CALL_PLAN_RPT' THEN -- 점검계획서 출력 데이터 조회
  SELECT APRVSTT
    INTO _$APRVSTT
  FROM EQMPLAN_APRV
  WHERE PLANTP = 'G'
    AND PLANCD = $EQMGRP
  LIMIT 1;

  IF COALESCE(_$APRVSTT, '') <> 'A' THEN
    CALL COMERR('승인된 설비그룹 점검계획만 출력할 수 있습니다.');
    LEAVE PROC;
  END IF;

  SELECT COUNT(DISTINCT MSTEQM.FANO) INTO _$UNAPPROVED_CNT
  FROM MSTEQM
  INNER JOIN CHKPLANEQM
    ON CHKPLANEQM.EQMCD = MSTEQM.FANO
   AND CHKPLANEQM.CHKTP = '02'
   AND CHKPLANEQM.USEYN = 'Y'
  LEFT JOIN EQMPLAN_APRV EQM_APRV
    ON EQM_APRV.PLANTP = 'E'
   AND EQM_APRV.PLANCD = MSTEQM.FANO
  WHERE MSTEQM.USEYN = 'Y'
    AND MSTEQM.EQMGUBUN = $EQMGRP
    AND COALESCE(EQM_APRV.APRVSTT, '') <> 'A';

  IF _$UNAPPROVED_CNT > 0 THEN
    CALL COMERR('설비그룹 내 미승인 설비 점검계획이 있어 출력할 수 없습니다.');
    LEAVE PROC;
  END IF;

  SELECT
    COMTYPE.TPNM AS EQMGRPNM,
    MIN(MSTEQM.FANO) AS EQMCD,
    MIN(MSTEQM.EQMNM) AS EQMNM,
    COALESCE(MIN(MSTEQM.EQMNM_DETAIL), '') AS EQMSPEC,
    COALESCE(MIN(MSTEQM.LINECD), '') AS LINECD,
    COALESCE(MIN(NULLIF(GPCD('FM100', MSTEQM.EQMTP), '')), MIN(MSTEQM.EQMTP), '') AS PROCESSNM
  FROM MSTEQM
  INNER JOIN CHKPLANEQM
    ON CHKPLANEQM.EQMCD = MSTEQM.FANO
   AND CHKPLANEQM.CHKTP = '02'
   AND CHKPLANEQM.USEYN = 'Y'
  LEFT JOIN COMTYPE
    ON COMTYPE.GPCD = 'FM116'
   AND COMTYPE.TPCD = MSTEQM.EQMGUBUN
  WHERE MSTEQM.USEYN = 'Y'
    AND MSTEQM.EQMGUBUN = $EQMGRP
  GROUP BY COMTYPE.TPNM
  LIMIT 1;

  SELECT
    ROW_NUMBER() OVER (ORDER BY MSTEQM.FANO, CHKPLANEQM.SORTNO, MSTCHKKND.CHKKNDCD) AS NO,
    MSTEQM.EQMNM AS CHKITEM,
    MSTCHKKND.CHKKNDNM AS CHKCONTENT,
    COALESCE(NULLIF(GPCD('CHKMTH', MSTCHKKND.CHKMTH), ''), MSTCHKKND.CHKMTH) AS CHKDEVICE,
    COALESCE(NULLIF(GPCD('CHKVALTP', MSTCHKKND.CHKVALTP), ''), MSTCHKKND.CHKVALTP) AS CHKRESULT,
    '' AS CONFIRM,
    '' AS REMARK
  FROM MSTEQM
  INNER JOIN CHKPLANEQM
    ON CHKPLANEQM.EQMCD = MSTEQM.FANO
   AND CHKPLANEQM.CHKTP = '02'
   AND CHKPLANEQM.USEYN = 'Y'
  INNER JOIN MSTCHKKND
    ON MSTCHKKND.CHKKNDCD = CHKPLANEQM.CHKKNDCD
  WHERE MSTEQM.USEYN = 'Y'
    AND MSTEQM.EQMGUBUN = $EQMGRP
  GROUP BY MSTEQM.FANO, MSTEQM.EQMNM, MSTCHKKND.CHKKNDCD, MSTCHKKND.CHKKNDNM, MSTCHKKND.CHKMTH, MSTCHKKND.CHKVALTP, CHKPLANEQM.SORTNO
  ORDER BY MSTEQM.FANO, CHKPLANEQM.SORTNO;

-- *****************************************************************************
END CASE;
END
