#pragma checksum "..\..\..\00_Control\ItsPop.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "11451CA4CF458C35BFBA8768D5A6E557B53934CA"
//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

using DevExpress.Xpf.DXBinding;
using ITSLIB;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Forms.Integration;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace ITSLIB {
    
    
    /// <summary>
    /// Pop
    /// </summary>
    public partial class Pop : System.Windows.Controls.UserControl, System.Windows.Markup.IComponentConnector, System.Windows.Markup.IStyleConnector {
        
        
        #line 102 "..\..\..\00_Control\ItsPop.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Primitives.Popup popupKeypad;
        
        #line default
        #line hidden
        
        
        #line 148 "..\..\..\00_Control\ItsPop.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label keyHanEng;
        
        #line default
        #line hidden
        
        
        #line 179 "..\..\..\00_Control\ItsPop.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Primitives.Popup popupSearch;
        
        #line default
        #line hidden
        
        
        #line 189 "..\..\..\00_Control\ItsPop.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button Select;
        
        #line default
        #line hidden
        
        
        #line 197 "..\..\..\00_Control\ItsPop.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button Clear;
        
        #line default
        #line hidden
        
        
        #line 210 "..\..\..\00_Control\ItsPop.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button Close;
        
        #line default
        #line hidden
        
        
        #line 219 "..\..\..\00_Control\ItsPop.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal ITSLIB.Grid gridView;
        
        #line default
        #line hidden
        
        
        #line 231 "..\..\..\00_Control\ItsPop.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock textBlock;
        
        #line default
        #line hidden
        
        
        #line 239 "..\..\..\00_Control\ItsPop.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.UserControl keyPadIcon;
        
        #line default
        #line hidden
        
        
        #line 244 "..\..\..\00_Control\ItsPop.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Canvas canvasKeypad;
        
        #line default
        #line hidden
        
        
        #line 263 "..\..\..\00_Control\ItsPop.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.UserControl searchIcon;
        
        #line default
        #line hidden
        
        
        #line 271 "..\..\..\00_Control\ItsPop.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Canvas canvasSearch;
        
        #line default
        #line hidden
        
        
        #line 316 "..\..\..\00_Control\ItsPop.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox textCode;
        
        #line default
        #line hidden
        
        
        #line 332 "..\..\..\00_Control\ItsPop.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border borderName;
        
        #line default
        #line hidden
        
        
        #line 338 "..\..\..\00_Control\ItsPop.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock textName;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/ITSLIB;component/00_control/itspop.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\00_Control\ItsPop.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal System.Delegate _CreateDelegate(System.Type delegateType, string handler) {
            return System.Delegate.CreateDelegate(delegateType, this, handler);
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 5:
            this.popupKeypad = ((System.Windows.Controls.Primitives.Popup)(target));
            return;
            case 6:
            this.keyHanEng = ((System.Windows.Controls.Label)(target));
            return;
            case 7:
            this.popupSearch = ((System.Windows.Controls.Primitives.Popup)(target));
            return;
            case 8:
            this.Select = ((System.Windows.Controls.Button)(target));
            
            #line 190 "..\..\..\00_Control\ItsPop.xaml"
            this.Select.Click += new System.Windows.RoutedEventHandler(this.Select_Click);
            
            #line default
            #line hidden
            return;
            case 9:
            this.Clear = ((System.Windows.Controls.Button)(target));
            
            #line 198 "..\..\..\00_Control\ItsPop.xaml"
            this.Clear.Click += new System.Windows.RoutedEventHandler(this.Clear_Click);
            
            #line default
            #line hidden
            return;
            case 10:
            this.Close = ((System.Windows.Controls.Button)(target));
            
            #line 211 "..\..\..\00_Control\ItsPop.xaml"
            this.Close.Click += new System.Windows.RoutedEventHandler(this.Close_Click);
            
            #line default
            #line hidden
            return;
            case 11:
            this.gridView = ((ITSLIB.Grid)(target));
            return;
            case 12:
            this.textBlock = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 13:
            this.keyPadIcon = ((System.Windows.Controls.UserControl)(target));
            
            #line 242 "..\..\..\00_Control\ItsPop.xaml"
            this.keyPadIcon.MouseUp += new System.Windows.Input.MouseButtonEventHandler(this.keyPad_MouseUp);
            
            #line default
            #line hidden
            return;
            case 14:
            this.canvasKeypad = ((System.Windows.Controls.Canvas)(target));
            return;
            case 15:
            this.searchIcon = ((System.Windows.Controls.UserControl)(target));
            
            #line 268 "..\..\..\00_Control\ItsPop.xaml"
            this.searchIcon.MouseUp += new System.Windows.Input.MouseButtonEventHandler(this.search_MouseUp);
            
            #line default
            #line hidden
            return;
            case 16:
            this.canvasSearch = ((System.Windows.Controls.Canvas)(target));
            return;
            case 17:
            this.textCode = ((System.Windows.Controls.TextBox)(target));
            
            #line 327 "..\..\..\00_Control\ItsPop.xaml"
            this.textCode.PreviewKeyDown += new System.Windows.Input.KeyEventHandler(this.textCode_PreviewKeyDown);
            
            #line default
            #line hidden
            
            #line 328 "..\..\..\00_Control\ItsPop.xaml"
            this.textCode.TextChanged += new System.Windows.Controls.TextChangedEventHandler(this.textCode_TextChanged);
            
            #line default
            #line hidden
            
            #line 329 "..\..\..\00_Control\ItsPop.xaml"
            this.textCode.GotFocus += new System.Windows.RoutedEventHandler(this.textCode_GotFocus);
            
            #line default
            #line hidden
            
            #line 330 "..\..\..\00_Control\ItsPop.xaml"
            this.textCode.LostFocus += new System.Windows.RoutedEventHandler(this.textCode_LostFocus);
            
            #line default
            #line hidden
            return;
            case 18:
            this.borderName = ((System.Windows.Controls.Border)(target));
            return;
            case 19:
            this.textName = ((System.Windows.Controls.TextBlock)(target));
            return;
            }
            this._contentLoaded = true;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        void System.Windows.Markup.IStyleConnector.Connect(int connectionId, object target) {
            System.Windows.EventSetter eventSetter;
            switch (connectionId)
            {
            case 1:
            eventSetter = new System.Windows.EventSetter();
            eventSetter.Event = System.Windows.UIElement.PreviewMouseDownEvent;
            
            #line 14 "..\..\..\00_Control\ItsPop.xaml"
            eventSetter.Handler = new System.Windows.Input.MouseButtonEventHandler(this.KEY_PreviewMouseDown);
            
            #line default
            #line hidden
            ((System.Windows.Style)(target)).Setters.Add(eventSetter);
            break;
            case 2:
            eventSetter = new System.Windows.EventSetter();
            eventSetter.Event = System.Windows.UIElement.PreviewMouseDownEvent;
            
            #line 33 "..\..\..\00_Control\ItsPop.xaml"
            eventSetter.Handler = new System.Windows.Input.MouseButtonEventHandler(this.KEY_PreviewMouseDown);
            
            #line default
            #line hidden
            ((System.Windows.Style)(target)).Setters.Add(eventSetter);
            break;
            case 3:
            eventSetter = new System.Windows.EventSetter();
            eventSetter.Event = System.Windows.UIElement.PreviewMouseDownEvent;
            
            #line 52 "..\..\..\00_Control\ItsPop.xaml"
            eventSetter.Handler = new System.Windows.Input.MouseButtonEventHandler(this.KEY_PreviewMouseDown);
            
            #line default
            #line hidden
            ((System.Windows.Style)(target)).Setters.Add(eventSetter);
            break;
            case 4:
            eventSetter = new System.Windows.EventSetter();
            eventSetter.Event = System.Windows.UIElement.PreviewMouseDownEvent;
            
            #line 71 "..\..\..\00_Control\ItsPop.xaml"
            eventSetter.Handler = new System.Windows.Input.MouseButtonEventHandler(this.KEY_PreviewMouseDown);
            
            #line default
            #line hidden
            ((System.Windows.Style)(target)).Setters.Add(eventSetter);
            break;
            }
        }
    }
}

