#pragma checksum "..\..\LoginWindow.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "7AD1C3B5673476869C175CCB91AB0D9B4AC7AD3F"
//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Forms.Integration;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace ITSLOGIN {
    
    
    /// <summary>
    /// LoginWindow
    /// </summary>
    public partial class LoginWindow : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 74 "..\..\LoginWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DockPanel TITLE;
        
        #line default
        #line hidden
        
        
        #line 75 "..\..\LoginWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Canvas ICON_CLOSE;
        
        #line default
        #line hidden
        
        
        #line 81 "..\..\LoginWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Canvas ICON_MIN;
        
        #line default
        #line hidden
        
        
        #line 95 "..\..\LoginWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DockPanel LOGIN;
        
        #line default
        #line hidden
        
        
        #line 98 "..\..\LoginWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox LOGINID;
        
        #line default
        #line hidden
        
        
        #line 107 "..\..\LoginWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.PasswordBox LOGINPASS;
        
        #line default
        #line hidden
        
        
        #line 117 "..\..\LoginWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border LOGIN_BUTTON;
        
        #line default
        #line hidden
        
        
        #line 123 "..\..\LoginWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Media.SolidColorBrush borderBackground;
        
        #line default
        #line hidden
        
        
        #line 126 "..\..\LoginWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock textBlock;
        
        #line default
        #line hidden
        
        
        #line 135 "..\..\LoginWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Media.SolidColorBrush textForeground;
        
        #line default
        #line hidden
        
        
        #line 143 "..\..\LoginWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox SAVE_ID;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/ITSLOGIN;component/loginwindow.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\LoginWindow.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.TITLE = ((System.Windows.Controls.DockPanel)(target));
            return;
            case 2:
            this.ICON_CLOSE = ((System.Windows.Controls.Canvas)(target));
            
            #line 77 "..\..\LoginWindow.xaml"
            this.ICON_CLOSE.MouseDown += new System.Windows.Input.MouseButtonEventHandler(this.ICON_CLOSE_MouseDown);
            
            #line default
            #line hidden
            return;
            case 3:
            this.ICON_MIN = ((System.Windows.Controls.Canvas)(target));
            
            #line 83 "..\..\LoginWindow.xaml"
            this.ICON_MIN.MouseDown += new System.Windows.Input.MouseButtonEventHandler(this.ICON_MIN_MouseDown);
            
            #line default
            #line hidden
            return;
            case 4:
            
            #line 86 "..\..\LoginWindow.xaml"
            ((System.Windows.Controls.UserControl)(target)).MouseLeftButtonDown += new System.Windows.Input.MouseButtonEventHandler(this.TITLE_MouseLeftButtonDown);
            
            #line default
            #line hidden
            return;
            case 5:
            this.LOGIN = ((System.Windows.Controls.DockPanel)(target));
            return;
            case 6:
            this.LOGINID = ((System.Windows.Controls.TextBox)(target));
            
            #line 101 "..\..\LoginWindow.xaml"
            this.LOGINID.KeyDown += new System.Windows.Input.KeyEventHandler(this.LOGINPASS_KeyDown);
            
            #line default
            #line hidden
            return;
            case 7:
            this.LOGINPASS = ((System.Windows.Controls.PasswordBox)(target));
            
            #line 110 "..\..\LoginWindow.xaml"
            this.LOGINPASS.KeyDown += new System.Windows.Input.KeyEventHandler(this.LOGINPASS_KeyDown);
            
            #line default
            #line hidden
            return;
            case 8:
            this.LOGIN_BUTTON = ((System.Windows.Controls.Border)(target));
            
            #line 119 "..\..\LoginWindow.xaml"
            this.LOGIN_BUTTON.MouseEnter += new System.Windows.Input.MouseEventHandler(this.LOGIN_BUTTON_MouseEnter);
            
            #line default
            #line hidden
            
            #line 120 "..\..\LoginWindow.xaml"
            this.LOGIN_BUTTON.MouseLeave += new System.Windows.Input.MouseEventHandler(this.LOGIN_BUTTON_MouseLeave);
            
            #line default
            #line hidden
            
            #line 121 "..\..\LoginWindow.xaml"
            this.LOGIN_BUTTON.MouseDown += new System.Windows.Input.MouseButtonEventHandler(this.LOGIN_BUTTON_MouseDown);
            
            #line default
            #line hidden
            return;
            case 9:
            this.borderBackground = ((System.Windows.Media.SolidColorBrush)(target));
            return;
            case 10:
            this.textBlock = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 11:
            this.textForeground = ((System.Windows.Media.SolidColorBrush)(target));
            return;
            case 12:
            this.SAVE_ID = ((System.Windows.Controls.CheckBox)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

