#pragma checksum "..\..\MainWindow.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "6685F00DD88A01D4B1ACAE40B39B8677A5474BA8"
//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

using ITSLIB;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;
using TMLMAIN;


namespace TMLMAIN {
    
    
    /// <summary>
    /// MainWindow
    /// </summary>
    public partial class MainWindow : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 129 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DockPanel DOCK_MAIN;
        
        #line default
        #line hidden
        
        
        #line 132 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DockPanel LEFT_MENU;
        
        #line default
        #line hidden
        
        
        #line 135 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Canvas ICON_HIDE;
        
        #line default
        #line hidden
        
        
        #line 143 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Canvas ICON_CONFIG;
        
        #line default
        #line hidden
        
        
        #line 160 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.StackPanel PANEL_MENU;
        
        #line default
        #line hidden
        
        
        #line 161 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.UserControl MENU0;
        
        #line default
        #line hidden
        
        
        #line 162 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.UserControl MENU1;
        
        #line default
        #line hidden
        
        
        #line 163 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.UserControl MENU2;
        
        #line default
        #line hidden
        
        
        #line 164 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.UserControl MENU3;
        
        #line default
        #line hidden
        
        
        #line 165 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.UserControl MENU4;
        
        #line default
        #line hidden
        
        
        #line 166 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.UserControl MENU5;
        
        #line default
        #line hidden
        
        
        #line 167 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.UserControl MENU6;
        
        #line default
        #line hidden
        
        
        #line 168 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.UserControl MENU7;
        
        #line default
        #line hidden
        
        
        #line 169 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.UserControl MENU8;
        
        #line default
        #line hidden
        
        
        #line 170 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.UserControl MENU9;
        
        #line default
        #line hidden
        
        
        #line 176 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DockPanel DOCK_TITLE;
        
        #line default
        #line hidden
        
        
        #line 177 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Canvas ICON_MENU;
        
        #line default
        #line hidden
        
        
        #line 189 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Canvas ICON_CLOSE;
        
        #line default
        #line hidden
        
        
        #line 195 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Canvas ICON_MIN;
        
        #line default
        #line hidden
        
        
        #line 202 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label LABEL_TITLE;
        
        #line default
        #line hidden
        
        
        #line 207 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label LABEL_TITLE2;
        
        #line default
        #line hidden
        
        
        #line 217 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox COMBO_PRINT;
        
        #line default
        #line hidden
        
        
        #line 242 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DockPanel PANEL_CONFIG;
        
        #line default
        #line hidden
        
        
        #line 244 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal ITSLIB.Pass CONFIG_PASS;
        
        #line default
        #line hidden
        
        
        #line 248 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button PASS_CHECK;
        
        #line default
        #line hidden
        
        
        #line 251 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.UserControl CONFIG_LINE;
        
        #line default
        #line hidden
        
        
        #line 252 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal ITSLIB.WrapContent PANEL_OPTION;
        
        #line default
        #line hidden
        
        
        #line 253 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal ITSLIB.Combo COMBO_COMPANYCD;
        
        #line default
        #line hidden
        
        
        #line 254 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal ITSLIB.Combo COMBO_FACTORYCD;
        
        #line default
        #line hidden
        
        
        #line 255 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal ITSLIB.Combo COMBO_TMLCD;
        
        #line default
        #line hidden
        
        
        #line 257 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal ITSLIB.Combo COMBO_SCALEPORT;
        
        #line default
        #line hidden
        
        
        #line 258 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal ITSLIB.Combo COMBO_PLCPORT;
        
        #line default
        #line hidden
        
        
        #line 262 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Canvas ConfigIcon;
        
        #line default
        #line hidden
        
        
        #line 276 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Canvas ConfigClose;
        
        #line default
        #line hidden
        
        
        #line 284 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Canvas ConfigCommit;
        
        #line default
        #line hidden
        
        
        #line 292 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock TEXT_Config;
        
        #line default
        #line hidden
        
        
        #line 298 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DockPanel DOCK_FRAME;
        
        #line default
        #line hidden
        
        
        #line 299 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DockPanel PAGE_MAIN;
        
        #line default
        #line hidden
        
        
        #line 300 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Frame FRAME_MAIN;
        
        #line default
        #line hidden
        
        
        #line 302 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DockPanel PAGE0;
        
        #line default
        #line hidden
        
        
        #line 303 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Frame FRAME0;
        
        #line default
        #line hidden
        
        
        #line 305 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DockPanel PAGE1;
        
        #line default
        #line hidden
        
        
        #line 306 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Frame FRAME1;
        
        #line default
        #line hidden
        
        
        #line 308 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DockPanel PAGE2;
        
        #line default
        #line hidden
        
        
        #line 309 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Frame FRAME2;
        
        #line default
        #line hidden
        
        
        #line 311 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DockPanel PAGE3;
        
        #line default
        #line hidden
        
        
        #line 312 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Frame FRAME3;
        
        #line default
        #line hidden
        
        
        #line 314 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DockPanel PAGE4;
        
        #line default
        #line hidden
        
        
        #line 315 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Frame FRAME4;
        
        #line default
        #line hidden
        
        
        #line 317 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DockPanel PAGE5;
        
        #line default
        #line hidden
        
        
        #line 318 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Frame FRAME5;
        
        #line default
        #line hidden
        
        
        #line 320 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DockPanel PAGE6;
        
        #line default
        #line hidden
        
        
        #line 321 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Frame FRAME6;
        
        #line default
        #line hidden
        
        
        #line 323 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DockPanel PAGE7;
        
        #line default
        #line hidden
        
        
        #line 324 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Frame FRAME7;
        
        #line default
        #line hidden
        
        
        #line 326 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DockPanel PAGE8;
        
        #line default
        #line hidden
        
        
        #line 327 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Frame FRAME8;
        
        #line default
        #line hidden
        
        
        #line 329 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DockPanel PAGE9;
        
        #line default
        #line hidden
        
        
        #line 330 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Frame FRAME9;
        
        #line default
        #line hidden
        
        
        #line 332 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DockPanel OTHER_PAGE0;
        
        #line default
        #line hidden
        
        
        #line 333 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Frame OTHER_FRAME0;
        
        #line default
        #line hidden
        
        
        #line 335 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DockPanel OTHER_PAGE1;
        
        #line default
        #line hidden
        
        
        #line 336 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Frame OTHER_FRAME1;
        
        #line default
        #line hidden
        
        
        #line 338 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DockPanel OTHER_PAGE2;
        
        #line default
        #line hidden
        
        
        #line 339 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Frame OTHER_FRAME2;
        
        #line default
        #line hidden
        
        
        #line 341 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DockPanel OTHER_PAGE3;
        
        #line default
        #line hidden
        
        
        #line 342 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Frame OTHER_FRAME3;
        
        #line default
        #line hidden
        
        
        #line 344 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DockPanel OTHER_PAGE4;
        
        #line default
        #line hidden
        
        
        #line 345 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Frame OTHER_FRAME4;
        
        #line default
        #line hidden
        
        
        #line 347 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DockPanel OTHER_PAGE5;
        
        #line default
        #line hidden
        
        
        #line 348 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Frame OTHER_FRAME5;
        
        #line default
        #line hidden
        
        
        #line 350 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DockPanel OTHER_PAGE6;
        
        #line default
        #line hidden
        
        
        #line 351 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Frame OTHER_FRAME6;
        
        #line default
        #line hidden
        
        
        #line 353 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DockPanel OTHER_PAGE7;
        
        #line default
        #line hidden
        
        
        #line 354 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Frame OTHER_FRAME7;
        
        #line default
        #line hidden
        
        
        #line 356 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DockPanel OTHER_PAGE8;
        
        #line default
        #line hidden
        
        
        #line 357 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Frame OTHER_FRAME8;
        
        #line default
        #line hidden
        
        
        #line 359 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DockPanel OTHER_PAGE9;
        
        #line default
        #line hidden
        
        
        #line 360 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Frame OTHER_FRAME9;
        
        #line default
        #line hidden
        
        
        #line 367 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DockPanel WAIT_MSG;
        
        #line default
        #line hidden
        
        
        #line 368 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Canvas WAIT_ICON;
        
        #line default
        #line hidden
        
        
        #line 371 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Ellipse WAIT_PROCESS;
        
        #line default
        #line hidden
        
        
        #line 383 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DockPanel PANEL_MSG;
        
        #line default
        #line hidden
        
        
        #line 385 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Canvas MsgIcon;
        
        #line default
        #line hidden
        
        
        #line 393 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Canvas MsgClose;
        
        #line default
        #line hidden
        
        
        #line 401 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Canvas MsgCommit;
        
        #line default
        #line hidden
        
        
        #line 409 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock TEXT_MSG;
        
        #line default
        #line hidden
        
        
        #line 414 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Primitives.Popup POP_OTHER_MENU;
        
        #line default
        #line hidden
        
        
        #line 419 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.StackPanel PANEL_OTHER_MENU;
        
        #line default
        #line hidden
        
        
        #line 431 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.UserControl OTHER_MENU0;
        
        #line default
        #line hidden
        
        
        #line 432 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.UserControl OTHER_MENU1;
        
        #line default
        #line hidden
        
        
        #line 433 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.UserControl OTHER_MENU2;
        
        #line default
        #line hidden
        
        
        #line 434 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.UserControl OTHER_MENU3;
        
        #line default
        #line hidden
        
        
        #line 435 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.UserControl OTHER_MENU4;
        
        #line default
        #line hidden
        
        
        #line 436 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.UserControl OTHER_MENU5;
        
        #line default
        #line hidden
        
        
        #line 437 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.UserControl OTHER_MENU6;
        
        #line default
        #line hidden
        
        
        #line 438 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.UserControl OTHER_MENU7;
        
        #line default
        #line hidden
        
        
        #line 439 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.UserControl OTHER_MENU8;
        
        #line default
        #line hidden
        
        
        #line 440 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.UserControl OTHER_MENU9;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/TMLMAIN;component/mainwindow.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\MainWindow.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            
            #line 13 "..\..\MainWindow.xaml"
            ((TMLMAIN.MainWindow)(target)).Closing += new System.ComponentModel.CancelEventHandler(this.Window_Closing);
            
            #line default
            #line hidden
            return;
            case 2:
            this.DOCK_MAIN = ((System.Windows.Controls.DockPanel)(target));
            return;
            case 3:
            this.LEFT_MENU = ((System.Windows.Controls.DockPanel)(target));
            return;
            case 4:
            this.ICON_HIDE = ((System.Windows.Controls.Canvas)(target));
            
            #line 137 "..\..\MainWindow.xaml"
            this.ICON_HIDE.MouseDown += new System.Windows.Input.MouseButtonEventHandler(this.ICON_HIDE_MouseDown);
            
            #line default
            #line hidden
            return;
            case 5:
            this.ICON_CONFIG = ((System.Windows.Controls.Canvas)(target));
            
            #line 145 "..\..\MainWindow.xaml"
            this.ICON_CONFIG.MouseDown += new System.Windows.Input.MouseButtonEventHandler(this.ICON_CONFIG_MouseDown);
            
            #line default
            #line hidden
            return;
            case 6:
            this.PANEL_MENU = ((System.Windows.Controls.StackPanel)(target));
            return;
            case 7:
            this.MENU0 = ((System.Windows.Controls.UserControl)(target));
            
            #line 161 "..\..\MainWindow.xaml"
            this.MENU0.MouseUp += new System.Windows.Input.MouseButtonEventHandler(this.MENU_MouseUp);
            
            #line default
            #line hidden
            return;
            case 8:
            this.MENU1 = ((System.Windows.Controls.UserControl)(target));
            
            #line 162 "..\..\MainWindow.xaml"
            this.MENU1.MouseUp += new System.Windows.Input.MouseButtonEventHandler(this.MENU_MouseUp);
            
            #line default
            #line hidden
            return;
            case 9:
            this.MENU2 = ((System.Windows.Controls.UserControl)(target));
            
            #line 163 "..\..\MainWindow.xaml"
            this.MENU2.MouseUp += new System.Windows.Input.MouseButtonEventHandler(this.MENU_MouseUp);
            
            #line default
            #line hidden
            return;
            case 10:
            this.MENU3 = ((System.Windows.Controls.UserControl)(target));
            
            #line 164 "..\..\MainWindow.xaml"
            this.MENU3.MouseUp += new System.Windows.Input.MouseButtonEventHandler(this.MENU_MouseUp);
            
            #line default
            #line hidden
            return;
            case 11:
            this.MENU4 = ((System.Windows.Controls.UserControl)(target));
            
            #line 165 "..\..\MainWindow.xaml"
            this.MENU4.MouseUp += new System.Windows.Input.MouseButtonEventHandler(this.MENU_MouseUp);
            
            #line default
            #line hidden
            return;
            case 12:
            this.MENU5 = ((System.Windows.Controls.UserControl)(target));
            
            #line 166 "..\..\MainWindow.xaml"
            this.MENU5.MouseUp += new System.Windows.Input.MouseButtonEventHandler(this.MENU_MouseUp);
            
            #line default
            #line hidden
            return;
            case 13:
            this.MENU6 = ((System.Windows.Controls.UserControl)(target));
            
            #line 167 "..\..\MainWindow.xaml"
            this.MENU6.MouseUp += new System.Windows.Input.MouseButtonEventHandler(this.MENU_MouseUp);
            
            #line default
            #line hidden
            return;
            case 14:
            this.MENU7 = ((System.Windows.Controls.UserControl)(target));
            
            #line 168 "..\..\MainWindow.xaml"
            this.MENU7.MouseUp += new System.Windows.Input.MouseButtonEventHandler(this.MENU_MouseUp);
            
            #line default
            #line hidden
            return;
            case 15:
            this.MENU8 = ((System.Windows.Controls.UserControl)(target));
            
            #line 169 "..\..\MainWindow.xaml"
            this.MENU8.MouseUp += new System.Windows.Input.MouseButtonEventHandler(this.MENU_MouseUp);
            
            #line default
            #line hidden
            return;
            case 16:
            this.MENU9 = ((System.Windows.Controls.UserControl)(target));
            
            #line 170 "..\..\MainWindow.xaml"
            this.MENU9.MouseUp += new System.Windows.Input.MouseButtonEventHandler(this.MENU_MouseUp);
            
            #line default
            #line hidden
            return;
            case 17:
            this.DOCK_TITLE = ((System.Windows.Controls.DockPanel)(target));
            return;
            case 18:
            this.ICON_MENU = ((System.Windows.Controls.Canvas)(target));
            
            #line 179 "..\..\MainWindow.xaml"
            this.ICON_MENU.MouseDown += new System.Windows.Input.MouseButtonEventHandler(this.ICON_MENU_MouseDown);
            
            #line default
            #line hidden
            return;
            case 19:
            this.ICON_CLOSE = ((System.Windows.Controls.Canvas)(target));
            
            #line 191 "..\..\MainWindow.xaml"
            this.ICON_CLOSE.MouseDown += new System.Windows.Input.MouseButtonEventHandler(this.ICON_CLOSE_MouseDown);
            
            #line default
            #line hidden
            return;
            case 20:
            this.ICON_MIN = ((System.Windows.Controls.Canvas)(target));
            
            #line 197 "..\..\MainWindow.xaml"
            this.ICON_MIN.MouseDown += new System.Windows.Input.MouseButtonEventHandler(this.ICON_MIN_MouseDown);
            
            #line default
            #line hidden
            return;
            case 21:
            this.LABEL_TITLE = ((System.Windows.Controls.Label)(target));
            return;
            case 22:
            this.LABEL_TITLE2 = ((System.Windows.Controls.Label)(target));
            return;
            case 23:
            this.COMBO_PRINT = ((System.Windows.Controls.ComboBox)(target));
            
            #line 226 "..\..\MainWindow.xaml"
            this.COMBO_PRINT.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.COMBO_PRINT_SelectionChanged);
            
            #line default
            #line hidden
            return;
            case 24:
            this.PANEL_CONFIG = ((System.Windows.Controls.DockPanel)(target));
            return;
            case 25:
            this.CONFIG_PASS = ((ITSLIB.Pass)(target));
            
            #line 247 "..\..\MainWindow.xaml"
            this.CONFIG_PASS.KeyDown += new System.Windows.Input.KeyEventHandler(this.CONFIG_PASS_KeyDown);
            
            #line default
            #line hidden
            return;
            case 26:
            this.PASS_CHECK = ((System.Windows.Controls.Button)(target));
            
            #line 248 "..\..\MainWindow.xaml"
            this.PASS_CHECK.Click += new System.Windows.RoutedEventHandler(this.PASS_CHECK_Click);
            
            #line default
            #line hidden
            return;
            case 27:
            this.CONFIG_LINE = ((System.Windows.Controls.UserControl)(target));
            return;
            case 28:
            this.PANEL_OPTION = ((ITSLIB.WrapContent)(target));
            return;
            case 29:
            this.COMBO_COMPANYCD = ((ITSLIB.Combo)(target));
            return;
            case 30:
            this.COMBO_FACTORYCD = ((ITSLIB.Combo)(target));
            return;
            case 31:
            this.COMBO_TMLCD = ((ITSLIB.Combo)(target));
            return;
            case 32:
            this.COMBO_SCALEPORT = ((ITSLIB.Combo)(target));
            return;
            case 33:
            this.COMBO_PLCPORT = ((ITSLIB.Combo)(target));
            return;
            case 34:
            this.ConfigIcon = ((System.Windows.Controls.Canvas)(target));
            return;
            case 35:
            this.ConfigClose = ((System.Windows.Controls.Canvas)(target));
            
            #line 278 "..\..\MainWindow.xaml"
            this.ConfigClose.MouseUp += new System.Windows.Input.MouseButtonEventHandler(this.CONFIG_CLOSE_MouseUp);
            
            #line default
            #line hidden
            return;
            case 36:
            this.ConfigCommit = ((System.Windows.Controls.Canvas)(target));
            
            #line 286 "..\..\MainWindow.xaml"
            this.ConfigCommit.MouseUp += new System.Windows.Input.MouseButtonEventHandler(this.CONFIG_COMMIT_MouseUp);
            
            #line default
            #line hidden
            return;
            case 37:
            this.TEXT_Config = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 38:
            this.DOCK_FRAME = ((System.Windows.Controls.DockPanel)(target));
            return;
            case 39:
            this.PAGE_MAIN = ((System.Windows.Controls.DockPanel)(target));
            return;
            case 40:
            this.FRAME_MAIN = ((System.Windows.Controls.Frame)(target));
            return;
            case 41:
            this.PAGE0 = ((System.Windows.Controls.DockPanel)(target));
            return;
            case 42:
            this.FRAME0 = ((System.Windows.Controls.Frame)(target));
            return;
            case 43:
            this.PAGE1 = ((System.Windows.Controls.DockPanel)(target));
            return;
            case 44:
            this.FRAME1 = ((System.Windows.Controls.Frame)(target));
            return;
            case 45:
            this.PAGE2 = ((System.Windows.Controls.DockPanel)(target));
            return;
            case 46:
            this.FRAME2 = ((System.Windows.Controls.Frame)(target));
            return;
            case 47:
            this.PAGE3 = ((System.Windows.Controls.DockPanel)(target));
            return;
            case 48:
            this.FRAME3 = ((System.Windows.Controls.Frame)(target));
            return;
            case 49:
            this.PAGE4 = ((System.Windows.Controls.DockPanel)(target));
            return;
            case 50:
            this.FRAME4 = ((System.Windows.Controls.Frame)(target));
            return;
            case 51:
            this.PAGE5 = ((System.Windows.Controls.DockPanel)(target));
            return;
            case 52:
            this.FRAME5 = ((System.Windows.Controls.Frame)(target));
            return;
            case 53:
            this.PAGE6 = ((System.Windows.Controls.DockPanel)(target));
            return;
            case 54:
            this.FRAME6 = ((System.Windows.Controls.Frame)(target));
            return;
            case 55:
            this.PAGE7 = ((System.Windows.Controls.DockPanel)(target));
            return;
            case 56:
            this.FRAME7 = ((System.Windows.Controls.Frame)(target));
            return;
            case 57:
            this.PAGE8 = ((System.Windows.Controls.DockPanel)(target));
            return;
            case 58:
            this.FRAME8 = ((System.Windows.Controls.Frame)(target));
            return;
            case 59:
            this.PAGE9 = ((System.Windows.Controls.DockPanel)(target));
            return;
            case 60:
            this.FRAME9 = ((System.Windows.Controls.Frame)(target));
            return;
            case 61:
            this.OTHER_PAGE0 = ((System.Windows.Controls.DockPanel)(target));
            return;
            case 62:
            this.OTHER_FRAME0 = ((System.Windows.Controls.Frame)(target));
            return;
            case 63:
            this.OTHER_PAGE1 = ((System.Windows.Controls.DockPanel)(target));
            return;
            case 64:
            this.OTHER_FRAME1 = ((System.Windows.Controls.Frame)(target));
            return;
            case 65:
            this.OTHER_PAGE2 = ((System.Windows.Controls.DockPanel)(target));
            return;
            case 66:
            this.OTHER_FRAME2 = ((System.Windows.Controls.Frame)(target));
            return;
            case 67:
            this.OTHER_PAGE3 = ((System.Windows.Controls.DockPanel)(target));
            return;
            case 68:
            this.OTHER_FRAME3 = ((System.Windows.Controls.Frame)(target));
            return;
            case 69:
            this.OTHER_PAGE4 = ((System.Windows.Controls.DockPanel)(target));
            return;
            case 70:
            this.OTHER_FRAME4 = ((System.Windows.Controls.Frame)(target));
            return;
            case 71:
            this.OTHER_PAGE5 = ((System.Windows.Controls.DockPanel)(target));
            return;
            case 72:
            this.OTHER_FRAME5 = ((System.Windows.Controls.Frame)(target));
            return;
            case 73:
            this.OTHER_PAGE6 = ((System.Windows.Controls.DockPanel)(target));
            return;
            case 74:
            this.OTHER_FRAME6 = ((System.Windows.Controls.Frame)(target));
            return;
            case 75:
            this.OTHER_PAGE7 = ((System.Windows.Controls.DockPanel)(target));
            return;
            case 76:
            this.OTHER_FRAME7 = ((System.Windows.Controls.Frame)(target));
            return;
            case 77:
            this.OTHER_PAGE8 = ((System.Windows.Controls.DockPanel)(target));
            return;
            case 78:
            this.OTHER_FRAME8 = ((System.Windows.Controls.Frame)(target));
            return;
            case 79:
            this.OTHER_PAGE9 = ((System.Windows.Controls.DockPanel)(target));
            return;
            case 80:
            this.OTHER_FRAME9 = ((System.Windows.Controls.Frame)(target));
            return;
            case 81:
            this.WAIT_MSG = ((System.Windows.Controls.DockPanel)(target));
            return;
            case 82:
            this.WAIT_ICON = ((System.Windows.Controls.Canvas)(target));
            return;
            case 83:
            this.WAIT_PROCESS = ((System.Windows.Shapes.Ellipse)(target));
            return;
            case 84:
            this.PANEL_MSG = ((System.Windows.Controls.DockPanel)(target));
            return;
            case 85:
            this.MsgIcon = ((System.Windows.Controls.Canvas)(target));
            return;
            case 86:
            this.MsgClose = ((System.Windows.Controls.Canvas)(target));
            
            #line 395 "..\..\MainWindow.xaml"
            this.MsgClose.MouseUp += new System.Windows.Input.MouseButtonEventHandler(this.MSG_CLOSE_MouseUp);
            
            #line default
            #line hidden
            return;
            case 87:
            this.MsgCommit = ((System.Windows.Controls.Canvas)(target));
            
            #line 403 "..\..\MainWindow.xaml"
            this.MsgCommit.MouseUp += new System.Windows.Input.MouseButtonEventHandler(this.MSG_COMMIT_MouseUp);
            
            #line default
            #line hidden
            return;
            case 88:
            this.TEXT_MSG = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 89:
            this.POP_OTHER_MENU = ((System.Windows.Controls.Primitives.Popup)(target));
            return;
            case 90:
            this.PANEL_OTHER_MENU = ((System.Windows.Controls.StackPanel)(target));
            return;
            case 91:
            
            #line 420 "..\..\MainWindow.xaml"
            ((System.Windows.Controls.UserControl)(target)).MouseUp += new System.Windows.Input.MouseButtonEventHandler(this.MENU_MouseUp);
            
            #line default
            #line hidden
            return;
            case 92:
            this.OTHER_MENU0 = ((System.Windows.Controls.UserControl)(target));
            
            #line 431 "..\..\MainWindow.xaml"
            this.OTHER_MENU0.MouseUp += new System.Windows.Input.MouseButtonEventHandler(this.MENU_MouseUp);
            
            #line default
            #line hidden
            return;
            case 93:
            this.OTHER_MENU1 = ((System.Windows.Controls.UserControl)(target));
            
            #line 432 "..\..\MainWindow.xaml"
            this.OTHER_MENU1.MouseUp += new System.Windows.Input.MouseButtonEventHandler(this.MENU_MouseUp);
            
            #line default
            #line hidden
            return;
            case 94:
            this.OTHER_MENU2 = ((System.Windows.Controls.UserControl)(target));
            
            #line 433 "..\..\MainWindow.xaml"
            this.OTHER_MENU2.MouseUp += new System.Windows.Input.MouseButtonEventHandler(this.MENU_MouseUp);
            
            #line default
            #line hidden
            return;
            case 95:
            this.OTHER_MENU3 = ((System.Windows.Controls.UserControl)(target));
            
            #line 434 "..\..\MainWindow.xaml"
            this.OTHER_MENU3.MouseUp += new System.Windows.Input.MouseButtonEventHandler(this.MENU_MouseUp);
            
            #line default
            #line hidden
            return;
            case 96:
            this.OTHER_MENU4 = ((System.Windows.Controls.UserControl)(target));
            
            #line 435 "..\..\MainWindow.xaml"
            this.OTHER_MENU4.MouseUp += new System.Windows.Input.MouseButtonEventHandler(this.MENU_MouseUp);
            
            #line default
            #line hidden
            return;
            case 97:
            this.OTHER_MENU5 = ((System.Windows.Controls.UserControl)(target));
            
            #line 436 "..\..\MainWindow.xaml"
            this.OTHER_MENU5.MouseUp += new System.Windows.Input.MouseButtonEventHandler(this.MENU_MouseUp);
            
            #line default
            #line hidden
            return;
            case 98:
            this.OTHER_MENU6 = ((System.Windows.Controls.UserControl)(target));
            
            #line 437 "..\..\MainWindow.xaml"
            this.OTHER_MENU6.MouseUp += new System.Windows.Input.MouseButtonEventHandler(this.MENU_MouseUp);
            
            #line default
            #line hidden
            return;
            case 99:
            this.OTHER_MENU7 = ((System.Windows.Controls.UserControl)(target));
            
            #line 438 "..\..\MainWindow.xaml"
            this.OTHER_MENU7.MouseUp += new System.Windows.Input.MouseButtonEventHandler(this.MENU_MouseUp);
            
            #line default
            #line hidden
            return;
            case 100:
            this.OTHER_MENU8 = ((System.Windows.Controls.UserControl)(target));
            
            #line 439 "..\..\MainWindow.xaml"
            this.OTHER_MENU8.MouseUp += new System.Windows.Input.MouseButtonEventHandler(this.MENU_MouseUp);
            
            #line default
            #line hidden
            return;
            case 101:
            this.OTHER_MENU9 = ((System.Windows.Controls.UserControl)(target));
            
            #line 440 "..\..\MainWindow.xaml"
            this.OTHER_MENU9.MouseUp += new System.Windows.Input.MouseButtonEventHandler(this.MENU_MouseUp);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
    }
}

