#pragma checksum "..\..\..\00_Window\ItsQueryWin.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "93431245ABF8C47262DB3452B5C0C43D85106386"
//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

using DevExpress.Xpf.DXBinding;
using ITSLIB;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Forms.Integration;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace ITSLIB {
    
    
    /// <summary>
    /// ItsQueryWin
    /// </summary>
    public partial class ItsQueryWin : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 15 "..\..\..\00_Window\ItsQueryWin.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock CONNSTR;
        
        #line default
        #line hidden
        
        
        #line 23 "..\..\..\00_Window\ItsQueryWin.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock PROCNAME;
        
        #line default
        #line hidden
        
        
        #line 29 "..\..\..\00_Window\ItsQueryWin.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock CALLTYPE;
        
        #line default
        #line hidden
        
        
        #line 35 "..\..\..\00_Window\ItsQueryWin.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock TRANYN;
        
        #line default
        #line hidden
        
        
        #line 39 "..\..\..\00_Window\ItsQueryWin.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGrid GRID_VALUE;
        
        #line default
        #line hidden
        
        
        #line 63 "..\..\..\00_Window\ItsQueryWin.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button COPY;
        
        #line default
        #line hidden
        
        
        #line 69 "..\..\..\00_Window\ItsQueryWin.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TEXTBOX;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/ITSLIB;component/00_window/itsquerywin.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\00_Window\ItsQueryWin.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.CONNSTR = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 2:
            this.PROCNAME = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 3:
            this.CALLTYPE = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 4:
            this.TRANYN = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 5:
            this.GRID_VALUE = ((System.Windows.Controls.DataGrid)(target));
            return;
            case 6:
            this.COPY = ((System.Windows.Controls.Button)(target));
            
            #line 63 "..\..\..\00_Window\ItsQueryWin.xaml"
            this.COPY.Click += new System.Windows.RoutedEventHandler(this.COPY_Click);
            
            #line default
            #line hidden
            return;
            case 7:
            this.TEXTBOX = ((System.Windows.Controls.TextBox)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

