CREATE DEFINER = 'root'@'%'
PROCEDURE MES_SNS2.SYS0001_R01(
-- *****************************************************************************
-- Comment: 공통타입디테일관리
-- Create: 2025-03-27 이대규
-- *****************************************************************************
 IN $ACCYN VARCHAR(1), -- 회계여부
 IN $GPCD1 VARCHAR(20), -- 그룹코드
 IN $GPNM VARCHAR(100), -- 헤더명
 IN $TPCD VARCHAR(20), -- 상세코드
 IN $TPNM VARCHAR(1000), -- 상세명
 IN $SORTNO DECIMAL(20,0), -- 정렬순서
 IN $USEYN VARCHAR(1), -- 사용여부
 IN $REF01 VARCHAR(100), -- 참조01
 IN $REF02 VARCHAR(100), -- 참조02
 IN $REF03 VARCHAR(100), -- 참조03
 IN $REF04 VARCHAR(100), -- 참조04
 IN $REF05 VARCHAR(100), -- 참조05
 IN $REF06 VARCHAR(100), -- 참조06
 IN $REF07 VARCHAR(100), -- 참조07
 IN $REF08 VARCHAR(100), -- 참조08
 IN $REF09 VARCHAR(100), -- 참조09
 IN $REF10 VARCHAR(100), -- 참조10
 IN $REF11 VARCHAR(100), -- 참조11
 IN $REF12 VARCHAR(100), -- 참조12
 IN $REF13 VARCHAR(100), -- 참조13
 IN $REF14 VARCHAR(100), -- 참조14
 IN $REF15 VARCHAR(100), -- 참조15
 IN $REF16 VARCHAR(100), -- 참조16
 IN $REF17 VARCHAR(100), -- 참조17
 IN $REF18 VARCHAR(100), -- 참조18
 IN $REF19 VARCHAR(100), -- 참조19
 IN $REF20 VARCHAR(100), -- 참조20
 IN $REMARK VARCHAR(1000), -- 비고
 IN $RTIME VARCHAR(19), -- 등록시간
 IN $REMP VARCHAR(20), -- 등록자
 IN $RPRG VARCHAR(100), -- 등록프로그램
 IN $MTIME VARCHAR(19), -- 수정시간
 IN $MEMP VARCHAR(20), -- 수정자
 IN $MPRG VARCHAR(100), -- 수정프로그램
-- *****************************************************************************
 IN $CALLTYPE VARCHAR(50), IN $KEYWORD VARCHAR(1000))
PROC: BEGIN -- @CALLEMP, @CALLPRG, @CALLHOST, @CALLIP, @CALLMAC
-- SET @DEBUGLOGYN = 'Y';
-- *****************************************************************************

-- DECLARE _$V01 VARCHAR(1000);

-- ****************************************************************************
CASE $CALLTYPE
-- * ***************************************************************************
WHEN 'LIST_COMTYPEGP' THEN

  SELECT 
    COMTYPEGP.GPCD AS GPCD1, COMTYPEGP.GPNM, COMTYPEGP.SYSYN,
    COMTYPEGP.MESCOLUMN,
    COMTYPEGP.REF01NM, COMTYPEGP.REF02NM, COMTYPEGP.REF03NM, COMTYPEGP.REF04NM
    FROM COMTYPEGP
    WHERE (COMTYPEGP.GPCD LIKE CONCAT('%', $KEYWORD, '%')
       OR COMTYPEGP.GPNM LIKE CONCAT('%', $KEYWORD, '%')
       OR COMTYPEGP.MESCOLUMN LIKE CONCAT('%', $KEYWORD, '%'))
     -- AND LEFT(GPCD, 3) <> 'ACC'
--       AND CASE 
--             WHEN $ACCYN = 'Y' THEN LEFT(GPCD, 3) <> 'ACC'
--             WHEN $ACCYN = 'N' THEN LEFT(GPCD, 3) = 'ACC'
--             ELSE 1 = 1 END
--         AND SYSYN = 'Y'
      ; 

-- * ***************************************************************************
WHEN 'LIST_COMTYPE' THEN

  SELECT
    COMTYPE.GPCD AS GPCD1, COMTYPEGP.GPNM, COMTYPE.TPCD, COMTYPE.TPNM, COMTYPE.SORTNO, COMTYPE.USEYN, 
    COMTYPE.REF01, COMTYPEGP.REF01NM, COMTYPE.REF02, COMTYPEGP.REF02NM, COMTYPE.REF03, COMTYPEGP.REF03NM, 
    COMTYPE.REF04, COMTYPEGP.REF04NM, COMTYPE.REF05, COMTYPEGP.REF05NM, COMTYPE.REF06, COMTYPEGP.REF06NM,
    COMTYPE.REF07, COMTYPEGP.REF07NM, COMTYPE.REF08, COMTYPEGP.REF08NM, COMTYPE.REF09, COMTYPEGP.REF09NM,
    COMTYPE.REF10, COMTYPEGP.REF10NM, COMTYPE.REF11, COMTYPEGP.REF11NM, COMTYPE.REF12, COMTYPEGP.REF12NM,
    COMTYPE.REF13, COMTYPEGP.REF13NM, COMTYPE.REF14, COMTYPEGP.REF14NM, COMTYPE.REF15, COMTYPEGP.REF15NM,
    COMTYPE.REF16, COMTYPEGP.REF16NM, COMTYPE.REF17, COMTYPEGP.REF17NM, COMTYPE.REF18, COMTYPEGP.REF18NM, 
    COMTYPE.REF19, COMTYPEGP.REF19NM, COMTYPE.REF20, COMTYPEGP.REF20NM,
    COMTYPE.RTIME, COMTYPE.MTIME, COMTYPE.REMARK,
    CONCAT(COMTYPE.RTIME, ' ', COMTYPE.REMP) AS REGISTER, CONCAT(COMTYPE.MTIME, ' ', COMTYPE.MEMP) AS MODIFY
    FROM COMTYPE
    LEFT JOIN COMTYPEGP ON COMTYPE.GPCD = COMTYPEGP.GPCD
    WHERE COMTYPE.GPCD = $GPCD1
    ORDER BY COMTYPE.SORTNO;

-- ****************************************************************************
WHEN 'INFO_COMTYPE' THEN

  SELECT 
    COMTYPE.GPCD AS GPCD1, COMTYPEGP.GPNM, COMTYPE.TPCD, COMTYPE.TPNM, COMTYPE.SORTNO, COMTYPE.USEYN, 
    COMTYPE.REF01, COMTYPE.REF02, COMTYPE.REF03, COMTYPE.REF04, COMTYPE.REF05, 
    COMTYPE.REF06, COMTYPE.REF07, COMTYPE.REF08, COMTYPE.REF09, COMTYPE.REF10, 
    COMTYPE.REF11, COMTYPE.REF12, COMTYPE.REF13, COMTYPE.REF14, COMTYPE.REF15, 
    COMTYPE.REF16, COMTYPE.REF17, COMTYPE.REF18,COMTYPE.REF19, COMTYPE.REF20, 
    COMTYPE.RTIME, COMTYPE.MTIME, COMTYPE.REMARK
    FROM COMTYPE
    LEFT JOIN COMTYPEGP
    ON COMTYPE.GPCD = COMTYPEGP.GPCD
    WHERE COMTYPE.GPCD = $GPCD1
    AND COMTYPE.TPCD = $TPCD;

-- ****************************************************************************

WHEN 'DEL_COMTYPE' THEN

  IF $GPCD1 = '' THEN 
    CALL COMERR('공통타입이 비어있습니다.');
    LEAVE PROC;
  END IF;

  IF $TPCD = '' THEN 
    CALL COMERR('상세코드가 비어있습니다.');
    LEAVE PROC;
  END IF;

  IF (SELECT SYSYN FROM COMTYPEGP WHERE GPCD = $GPCD1) = 'Y' THEN
    CALL COMERR('시스템코드는 불가능합니다.');
    LEAVE PROC;
  END IF;

  DELETE COMTYPE 
    FROM COMTYPE
    WHERE COMTYPE.GPCD = $GPCD1
      AND COMTYPE.TPCD = $TPCD;

-- ****************************************************************************

WHEN 'UP_COMTYPE' THEN

  IF $GPCD1 = '' THEN 
    CALL COMERR('공통타입이 비어있습니다.');
    LEAVE PROC;
  END IF;

  IF $TPCD = '' THEN 
    CALL COMERR('상세코드가 비어있습니다.');
    LEAVE PROC;
  END IF;

  IF (SELECT SYSYN FROM COMTYPEGP WHERE GPCD = $GPCD1) = 'Y' THEN
    CALL COMERR('시스템코드는 불가능합니다.');
    LEAVE PROC;
  END IF;
  
  INSERT INTO COMTYPE (
    GPCD, TPCD, TPNM, SORTNO, USEYN,
    REF01, REF02, REF03, REF04, REF05,
    REF06, REF07, REF08, REF09, REF10,
    REF11, REF12, REF13, REF14, REF15,
    REF16, REF17, REF18, REF19, REF20,
    REMARK, RTIME, REMP, RPRG
    ) VALUES (
    $GPCD1, $TPCD, $TPNM, $SORTNO, $USEYN,    
    $REF01, $REF02, $REF03, $REF04, $REF05,    
    $REF06, $REF07, $REF08, $REF09, $REF10,
    $REF11, $REF12, $REF13, $REF14, $REF15,
    $REF16, $REF17, $REF18, $REF19, $REF20, 
    $REMARK, CALLTIME(), CALLEMP(), CALLPRG()
    ) ON DUPLICATE KEY UPDATE
    GPCD = $GPCD1,
    TPCD = $TPCD,
    TPNM = $TPNM,
    SORTNO = $SORTNO, 
    USEYN = $USEYN, 
    REF01 = $REF01, 
    REF02 = $REF02, 
    REF03 = $REF03, 
    REF04 = $REF04, 
    REF05 = $REF05, 
    REF06 = $REF06, 
    REF07 = $REF07, 
    REF08 = $REF08, 
    REF09 = $REF09, 
    REF10 = $REF10, 
    REF11 = $REF11, 
    REF12 = $REF12, 
    REF13 = $REF13, 
    REF14 = $REF14, 
    REF15 = $REF15, 
    REF16 = $REF16, 
    REF17 = $REF17, 
    REF18 = $REF18, 
    REF19 = $REF19, 
    REF20 = $REF20, 
    REMARK = $REMARK,
    MTIME = CALLTIME(),
    MEMP = CALLEMP(),
    MPRG = CALLPRG();

-- ****************************************************************************
WHEN 'LIST_COMTYPE_TEST' THEN

  SELECT
    COMTYPE.GPCD AS GPCD1, COMTYPEGP.GPNM, COMTYPE.TPCD, COMTYPE.TPNM, COMTYPE.SORTNO, COMTYPE.USEYN, 
    COMTYPE.REF01, COMTYPEGP.REF01NM, COMTYPE.REF02, COMTYPEGP.REF02NM, COMTYPE.REF03, COMTYPEGP.REF03NM, 
    COMTYPE.REF04, COMTYPEGP.REF04NM, COMTYPE.REF05, COMTYPEGP.REF05NM, COMTYPE.REF06, COMTYPEGP.REF06NM,
    COMTYPE.REF07, COMTYPEGP.REF07NM, COMTYPE.REF08, COMTYPEGP.REF08NM, COMTYPE.REF09, COMTYPEGP.REF09NM,
    COMTYPE.REF10, COMTYPEGP.REF10NM,
    LEFT(COMTYPE.RTIME, 10) AS RTIME, COMTYPE.MTIME, COMTYPE.REMARK,
    CONCAT(COMTYPE.RTIME, ' ', COMTYPE.REMP) AS REGISTER, CONCAT(COMTYPE.MTIME, ' ', COMTYPE.MEMP) AS MODIFY
    FROM COMTYPE
    LEFT JOIN COMTYPEGP ON COMTYPE.GPCD = COMTYPEGP.GPCD
    WHERE COMTYPE.GPCD = $GPCD1
    ORDER BY COMTYPE.SORTNO;
-- * ***************************************************************************
END CASE; END