CREATE TABLE MES_SNS2.PRDPLAN_M (
  PMONTH VARCHAR(7) NOT NULL DEFAULT '' COMMENT '계획년월',
  ITEMID INT(11) NOT NULL DEFAULT 0 COMMENT '품목코드',
  LINECD VARCHAR(100) NOT NULL DEFAULT '' COMMENT '작업장코드',
  SALFUP DECIMAL(20, 8) NOT NULL DEFAULT 0.00000000 COMMENT '단가',
  COUNT_LINE DECIMAL(20, 8) NOT NULL DEFAULT 0.00000000 COMMENT '생산라인수',
  UPH DECIMAL(20, 8) NOT NULL DEFAULT 0.00000000 COMMENT 'UPH',
  WORKHOURS DECIMAL(20, 8) NOT NULL DEFAULT 0.00000000 COMMENT '근무시간',
  SUMQTY DECIMAL(20, 8) NOT NULL DEFAULT 0.00000000 COMMENT '제품재고',
  SAFEQTY DECIMAL(20, 8) NOT NULL DEFAULT 0.00000000 COMMENT '안전재고',
  CAPAQTY DECIMAL(20, 8) NOT NULL DEFAULT 0.00000000 COMMENT '생산CAPA수량',
  ODRQTY DECIMAL(20, 8) NOT NULL DEFAULT 0.00000000 COMMENT '판매계획수량',
  PLANQTY DECIMAL(20, 8) NOT NULL DEFAULT 0.00000000 COMMENT '월생산계획수량',
  APPYN VARCHAR(1) NOT NULL DEFAULT 'N' COMMENT '확정여부',
  STOCKYN VARCHAR(1) NOT NULL DEFAULT 'N' COMMENT '재고 감안해서 생산계획 계산하는 방식',
  REMARK VARCHAR(1000) NOT NULL DEFAULT '' COMMENT '비고',
  RTIME VARCHAR(19) NOT NULL DEFAULT '' COMMENT '등록시간',
  REMP VARCHAR(20) NOT NULL DEFAULT '' COMMENT '등록자',
  RPRG VARCHAR(100) NOT NULL DEFAULT '' COMMENT '등록프로그램',
  MTIME VARCHAR(19) NOT NULL DEFAULT '' COMMENT '수정시간',
  MEMP VARCHAR(20) NOT NULL DEFAULT '' COMMENT '수정자',
  MPRG VARCHAR(100) NOT NULL DEFAULT '' COMMENT '수정프로그램',
  PRIMARY KEY (PMONTH, ITEMID)
)
ENGINE = INNODB
AVG_ROW_LENGTH = 564
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = '월생산계획'
ROW_FORMAT = DYNAMIC;