CREATE TABLE MES_SNS2.PRDPLAN_M_SALODRD (
  PMONTH VARCHAR(7) NOT NULL DEFAULT '' COMMENT '계획년월',
  SALODRKEY VARCHAR(100) NOT NULL DEFAULT '' COMMENT '수주품목키',
  ODRSEQ INT(11) NOT NULL DEFAULT 0 COMMENT '수주순번',
  CUSTCD VARCHAR(100) DEFAULT '' COMMENT '고객사',
  ITEMID INT(11) NOT NULL DEFAULT 0 COMMENT '품목코드',
  ITEMUNIT VARCHAR(100) DEFAULT '' COMMENT '수주단위 - BC:DM150',
  SALQTY DECIMAL(20, 0) DEFAULT 0 COMMENT '수주수량',
  SALFUP DECIMAL(20, 0) DEFAULT 0 COMMENT '수주단가_수주통화',
  DLVDT VARCHAR(10) DEFAULT '' COMMENT '납기일자',
  REMARK VARCHAR(1000) NOT NULL DEFAULT '' COMMENT '비고',
  RTIME VARCHAR(19) NOT NULL DEFAULT '' COMMENT '등록시간',
  REMP VARCHAR(20) NOT NULL DEFAULT '' COMMENT '등록자',
  RPRG VARCHAR(100) NOT NULL DEFAULT '' COMMENT '등록프로그램',
  MTIME VARCHAR(19) NOT NULL DEFAULT '' COMMENT '수정시간',
  MEMP VARCHAR(20) NOT NULL DEFAULT '' COMMENT '수정자',
  MPRG VARCHAR(100) NOT NULL DEFAULT '' COMMENT '수정프로그램',
  PRIMARY KEY (PMONTH, SALODRKEY, ODRSEQ)
)
ENGINE = INNODB
AVG_ROW_LENGTH = 468
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = '월생산계획-수주상세 매칭'
ROW_FORMAT = DYNAMIC;